### ISSUE TITLE
CareAware Connect Call Forwarding issue 

### ISSUE THREAD

**Issue by heyvdi** [cerner/terra-core#1002]
# Issue Description

<img width="445" alt="screen shot 2017-11-08 at 2 41 58 pm" src="https://user-images.githubusercontent.com/17009526/32573959-63613612-c495-11e7-98f8-6cd8af3c6665.png">
<img width="442" alt="screen shot 2017-11-08 at 2 41 38 pm" src="https://user-images.githubusercontent.com/17009526/32573963-65be8ea0-c495-11e7-849a-fb4a3df569c0.png">
The Terra platform doesn't provide the consistent UI design in the iOS platform (Please see the iOS screenshots above). The check box design and the margins in the form page are off from the original design. 

## Issue Type

- [ ] New Feature
- [x ] Enhancement
- [] Bug
- [ ] Other

## Expected Behavior

The original designs are attached below: 
![5c copy 78](https://user-images.githubusercontent.com/17009526/32574304-67b081ae-c496-11e7-877d-ef6c0ccad3c7.png)
![5c copy 108](https://user-images.githubusercontent.com/17009526/32574307-69d7dd9c-c496-11e7-9126-11830105f101.png)

## Environment

* Component Version:
* Browser Name and Version: iOS platform 
* Operating System and version (desktop or mobile): mobile

**Comment by JakeLaCombe** [comment]
That's a really light gray for the text color. I imagine that color will be changing most likely.

For the checkbox, that is under way in https://github.com/cerner/terra-core/issues/999.

Finally, the field is being redone in https://github.com/cerner/terra-core/issues/889

**Comment by mjhenkes** [comment]
Closing based on @JakeLaCombe feedback.
