### ISSUE TITLE
Uplift terra-time-input for theming

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1008]
# Issue Description
terra-time-input needs to be changed to allow for theming. In order to incorporate this, additional changes must be made to the component.

- Allow for the inputing of seconds
- Allow for the input of a meridiem.

These are the request mockups for the input.

<img width="366" alt="screen shot 2017-11-10 at 9 21 27 am" src="https://user-images.githubusercontent.com/2552573/32665030-96a5b552-c5f8-11e7-93c4-d090a57ba0fe.png">

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by JakeLaCombe** [comment]
# Tech Design - terra-time-input
## Summary:
terra-time-input needs to be updated in order to accomodate for the following features.

- Ensure themeability of the component
- Add support for seconds
- Add support for meridiem inputs

## Responsiveness:
Mobile and non-mobile device markups can be seen here.

<img width="366" alt="screen shot 2017-11-10 at 9 21 27 am" src="https://user-images.githubusercontent.com/2552573/32666262-7b0a5f56-c5fc-11e7-9157-0ad9d6b23d19.png">

## Accessibility
The timepicker will inherit the accesibility implementations of the input and button group accessible functionality. Essentially, that includes the standard tab focus, keyboard inputs, and space to choose a button.

For the meridiem on desktop, a hidden select box will be used to store the post merdiem and ante meridiem values, and a span will be used to display them. Focusing onto the span will force a focus onto the select box of size 2, giving the ability to match the meridiem based on the character input provided by the user.

## React Props:
The following props will be added
- **is12HourClock** - Whether the hour is a 12 or 24 hour clock.
- **postMeridiem** - Value for the post-meridiem time component.
- **anteMeridiem** - Value for the ante-meridiem time component.
- **currentTime** - The current time of the input.
- **hasSeconds** - Whether the clock should include seconds as part of it's time.

In addition, the following props will be changed as well:
- **value** - Value will now accept 12 hours with meridiems and seconds.

## Themeable styles:
Desktop Input Container
- background (color and opacity)
- border-radius (all corners)
- border (all sides)
- font-size
- line-height
- focus-animation styles
  - animation-speed
  - animation-size
  - animation-width
- focus-keyboard-styles
  - border (color, width, and style)
  - box-shadow.
  - (outline will be removed)

Semi Colon Spacer
- Paddings.

Input Labels
- font-size
- top-margin;

Input Groups
- margin-left and margin-right
- (widths of inputs will be locked in place)

Button Group
- (Themed through button group component)

## Notes / Questions 
1. How much auto parsing should we consider? Let's say they provide an input such as 09:30:80 AM. Should the time picker automatically add the seconds and meridiem inputs to the time-input, or should we base the construction of the time picker strictly on the passed in props?

2. The inputs are the same height as the button groups. How should we construct this in the terra component? Are we leaving those up to the individual terra-components to ensure those are themed correctly, or should we be adding custom styles to the time-input?

3. We have a base solution for detecting mobile devices. Should we do that for our time input, or should we still restrict it based on the size of the device?

**Comment by bjankord** [comment]
For 1. I'd say lets avoid auto parsing in regards to determining how to display a provided value, consumers should specify 12hour or 24hour display explicitly as a prop.

For 2. This gets tricky, as users may want to theme button groups separately from the button groups used in time-input or vice versa. Similar to the inputs used in this control. I'd lean towards adding custom styles to the time input so consumers can have more granular control on theming just for this component.

For 3. I'm open to either using what we came up with in the textarea PR or keeping this to be flipped based on purely on the size of the device.

For 4. I need some more clarity on around not requiring localization. This does seem concerning.

**Comment by benbcai** [comment]
For 1. The time-input currently expects the provided value prop to be in the HH:mm format. To support seconds, do we want to continue to expect the format to be either HH:mm or HH:mm:ss. I agree with Brett to reply the construction based on the is12HourClock and the meridiem props. If we allowed the provided value prop to contain AM/PM, parsing would be more complicated for other locales since it may not always be AM or PM.

For 4. Is the thought that only US uses AM/PM and all other supported locales use the 24-hour format?

My questions:
1. What is the purpose for the new currentTime prop? Does it represent the actual current time or the default time or something else? If it represents the actual current time, can we not get that internally? The existing value prop is used as the default time.

2. For the postMeridiem and anteMeridiem props, are these string values to replace AM/PM? If so, what's the reason to allow consumers to set these values, shouldn't they always be AM/PM?
Or are these boolean values to indicate that the default time is in AM or PM?

3. How would we handle if the value prop is in the 24-hour format (e.g.; 18:30) but the is12HourClock is true? Would it end up showing 6:30 PM?

**Comment by JakeLaCombe** [comment]
Yeah. That was the thought for 4. The main localization concern we had was with the meridiem, and if we require those as props, then we remove any localization concerns for this component. If we feel it's better to do the meridiem as locales inside the time input, then I'm fine with that as well.

**Comment by JakeLaCombe** [comment]
1. That was my mistake. I was thinking currentMeridiem, but that can potentially be apart of the string.

2. The postMeridiem and anteMeridiem props were designed to deal with localization. I do see that it could be better served as translations inside the component though.

3. My guess is that 6:30 PM would we what's shown, but we can talk to UX on how they would like to have that handled.

**Comment by bjankord** [comment]
Talked about seeing if we can cascade theming variables from input to time-input.

```
border-color: var(--terra-time-input-border-color, --terra-input-border-color);
```

**Comment by bjankord** [comment]
Talked about always requiring 24 hour format, and the component will format the display based on the 12hour prop being set.

**Comment by bjankord** [comment]
+1 on tech design

**Comment by benbcai** [comment]
+1 on tech design

**Comment by mjhenkes** [comment]
+1

**Comment by tm4027** [comment]
JIRA created
