### ISSUE TITLE
Terra-List crashing IE11 while inside an embedded MFC CHtmlView

### ISSUE THREAD

**Issue by dajaffe** [cerner/terra-core#1009]
# Issue Description
When interacting with a terra list control (expanding and collapsing using the carrot), a sporadic crash occurs from inside mshtml.dll, always ending in the CTreePos class, stemming from figuring out boundaries and performing hit tests.

Removing terra-list from a certain area of our app seems to have prevented crashing it. As soon as we added terra-list 1.2.0 back into the react view rendering it and clicking it to expand/collapse it several times, it crashed in mshtml.dll. 

We are updating all our terra components now to see if the crash persists.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
IE11 should not crash.

## Current Behavior
MSHTML.dll throws an unhandled exception, crashing the process it belongs to. In our case, a CHTMLView backed by IE11.

## Steps to Reproduce
1. Login to Skybox (Internal Cerner VM) 10.190.226.79, login to powerchart.exe, open the patient David Thower.
2. Navigate to PowerOrders, add a prescription to the scratchpad. Filled out details. To trigger Real Time Prescription Benefits.
3. Click Show More on an alternative that contains Coverage Alerts.
4. Start expanding and collapsing the coverage alerts, resizing the details pane, etc until a crash occurs.

We have a development branch of PowerOrders that can be checked out and compiled containing the Terra Component to reproduce it as well. Or just ping me (DJ021930).

## Environment
* Component Version:  Terra-list 1.2.0
* Browser Name and Version: Confirmed crash on IE11 Update 11.0.47, 11.0.46, 11.0.26, with index.html forcing content="IE=10", http-equiv="X-UA-Compatible"
* Operating System and version (desktop or mobile): Crashed on Windows 7x64, Windows 10x64

## Sample Callstacks
https://gist.github.cerner.com/DJ021930/8e974b8b30514be7dd32a17e89525e20
https://gist.github.cerner.com/DJ021930/fedd5425b8bfcc94d2bb2ad25135ae7c
https://gist.github.cerner.com/DJ021930/02306a5eba481527798a819dc51f4d44
https://gist.github.cerner.com/DJ021930/fd7aa84352cc456062bbca9391ce107c

**Comment by bjankord** [comment]
Hi @dajaffe, can you provide a reduced test case. We've found this to be helpful when debugging.

**Comment by dajaffe** [comment]
Initial tests with updating all the terra components we're using seem to have resolved it. We're going to test some more and see if the crash occurs again.

I'm not sure I can provide a slimmed down test scenario right now because of the tight deadline for this project. However we do have virtual machines with visual studio 2015 and the code we're running that causes this crash that we can provide to debug on.
