### ISSUE TITLE
Initialize terra-utilities package

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1010]
# Issue Description
We have the need for various components to share methods such as is mobile, and key events. To ensure that we are not duplicating code across various browsers, we should create a package that houses these

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by yuderekyu** [comment]
Should we close this in favor of https://github.com/cerner/terra-core/issues/2235?

**Comment by bjankord** [comment]
Yeah, I don't see much use for terra-utilities package other than the keycodes and since we are planning to replace our custom code with a third-party, I'd say we just close this issue.
