### ISSUE TITLE
Textarea - behavior enhancements

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1018]
# Issue Description
- add minimum width to stop resizing at a fixed point (specifically applicable for Chrome)
- fix scrolling error inside automatically resizing textarea after user has manually resized (and stopped the automatic resizing)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Introduced by
PR #982 
Merge Comments: https://github.com/cerner/terra-core/pull/982#issuecomment-344742186

**Comment by jmsv6d** [comment]
@neilpfeiffer What's the min width we'd want for this?
