### ISSUE TITLE
Textarea - adjust documentation examples

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1019]
# Issue Description
- add headers above each example 
- add/reorder examples to show 1.resizable at small size (two rows), 2.fixed-small size, 3.fixed-medium size, 4.fixed-large size, 5.fill-containter (same as current), 6.textarea-small size that becomes invalid/error when empty, 7.disabled (same as current), 8.disabled with error (same as current)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Introduced by 
PR #982 
Merge Comments: https://github.com/cerner/terra-core/pull/982#issuecomment-344742186

**Comment by sharynneazhar** [comment]
PR: https://github.com/cerner/terra-core/pull/1938/

**Comment by JakeLaCombe** [comment]
Can you clarify what you mean by fixed-small and fixed-medium. Are you looking to prevent autoresizing, or are you wanting the gripper removed as well?
