### ISSUE TITLE
Status View OCS component

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-core#1028]
# Issue Description
Create a new Status View component with OCS styling.  Will be similar to the Error View and No Data View components inside terra-clinical, but will be able to handle both of their functionality.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by kschuste** [comment]
# Tech Design for Status View
## Summary:
This is a new component that will allow for the consumer to specify which type of status view they wish to display for their use case that will flex to display the content on the containers height.

## Bidirectionality
These changes should make no changes to the existing ltr/rtl functionality.

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| buttons | node | [] | An array of actionable buttons to display. |
| isGlyphHidden | bool | false | Whether or not the status glyph should be displayed.  |
| message | string |  | The descriptive text to display.  |
| title | string |  |The status title to display.  |
| type | string | `error` | Determines the type of icon to display.  Should be one of `nodata`, `nomatchingresults`, `notauthorized`, `error`, `noservice`, or `unknown`.  |

## Example:
```jsx
// with all fields
<StatusView 
	buttons={[<Button text="OK" />, <Button text="Cancel" />]}
	isGlyphHidden={false}
	message=“No data was returned from the service.”
	title=“404”
        type="nodata"
>

// with no defaults
<<StatusView />
```

**Comment by emilyrohrbough** [comment]
Are you expecting there the children prop to be used as well for displaying content? If not, I vote we change the buttons prop to children.

**Comment by kschuste** [comment]
I don't expect to use the children prop, the name children implies that I can pass in any type of components into it and expect them to be displayed inside the status view; however, here I am only specifically wanting buttons.  Therefore, I think that it is best kept as buttons.

**Comment by mjhenkes** [comment]
@kschuste I agree with @emilyrohrbough. We've gone round and round on this topic and have come to the general consensus that the main area to drop elements should be named children most of the time. Your example would transform from:
```jsx
// with all fields
<StatusView 
	buttons={[<Button text="OK" key="1" />, <Button text="Cancel" key="2" />]}
	isGlyphHidden={false}
	message=“No data was returned from the service.”
	title=“404”
        type="nodata"
>
```
To this, which is easier to read though it does have the drawback you mentioned about not being explicit about requesting buttons, though in either case the consumer can drop in whatever they want.
```jsx
// with all fields
<StatusView 
	isGlyphHidden={false}
	message=“No data was returned from the service.”
	title=“404”
        type="nodata"
>
  <Button text="OK" key="1" />
  <Button text="Cancel" key="2" />
</StatusView>
```

**Comment by bjankord** [comment]
+1 to using children as prop to render buttons.
To align with other components we have, I'd recommend renaming the `type` prop to `variant`.
What are your thoughts on hyphenating the values for the type prop. `no-matching-results` instead of `nomatchingresults`

**Comment by emilyrohrbough** [comment]
+1 to hyphenating the type values and using the term variant

**Comment by emilyrohrbough** [comment]
Additionally, will title have a default message for each variant type?

**Comment by kschuste** [comment]
I still don't like using children that way but I will go with it.  I will update to use variant and will hyphenate them.
There are default titles for 4 of the variants, but not all of them.  I will update the description to show that

**Comment by yuderekyu** [comment]
Thoughts on condensing `forceAlignItemsTop` to `alignItemsTop`?

**Comment by emilyrohrbough** [comment]
The [terra-clinical-item-view](http://engineering.cerner.com/terra-clinical/#/site/item-view) component uses `accessoryAlignment` which takes a string of alignCenter and alignTop. Are the two alignment options center and top?

Also to follow boolean naming `isAlignedTop` may be appropriate. By the term items do you mean title, gyph, message and buttons will be top aligned?

**Comment by kschuste** [comment]
by items, I meant all the contents of the status view, I am ok with isAlignedTop to go with the same prefixing for hiding the glyph

**Comment by mjhenkes** [comment]
+1

**Comment by PaulSolDev** [comment]
Orion JIRA created
