### ISSUE TITLE
Uplift Button Component for OCS

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1038]
# Issue Description
Uplift Button component.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
# Button Tech Design 
## React Props:
### Changed
- `variant` prop [string] sets the button variant. See Question 1.
    - New options: 'default', 'utility', 'emphasis', 'de-emphasis', 'action' .
        - Note: 'action' and 'de-emphasis' are consumer specific.
    - Previous options: 'default', 'primary', 'secondary', 'link'

### Removed
- `isCompact` prop [bool]
- `size` prop [string] Options: 'tiny', 'small', 'medium', 'large', 'huge'

## Themeable Styles
- Background color
- Border color
- Border radius
- Border style
- Box shadow
- Font weight
- Padding
- Height

## Responsiveness & Accessibility
None to consider for uplift.

## Questions 
1. Designs indicate variant types of `'default'`, `'utility'`,  `'emphasis'`, `'de-emphasis'` and `'action'`. Do we want to use these types or maintain the current types of `'primary'`, and `'secondary'` in favor of `'emphasis'` and `'de-emphasis'`?

**Comment by emilyrohrbough** [comment]
With the removal of the `link` variant, the `href` prop will also be removed.

**Comment by bjankord** [comment]
+1 on tech design.

**Comment by mjhenkes** [comment]
I agree with @bjankord  about keeping the `href` prop

**Comment by jmsv6d** [comment]
We should add a `refCallback` prop for use with popup and menu.

**Comment by emilyrohrbough** [comment]
Removing `isCompact` will also remove the `isCompact` props of ButtonGroup

**Comment by emilyrohrbough** [comment]
Changing variant types from 'default', 'primary' and 'secondary' should change Button Group variants from 'default' and 'secondary' to 'emphasis' and 'neutral' based on designed themes.

**Comment by yuderekyu** [comment]
Shouldn't `font-color`, `font-family`, and `font-size` also be themeable, or are those inherited?
+1

**Comment by emilyrohrbough** [comment]
@yuderekyu  ^ These will be themeable but inherited

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by emilyrohrbough** [comment]
Interesting information I've discovered for anyone interested:

![screen shot 2017-12-01 at 10 41 37 am](https://user-images.githubusercontent.com/14099737/33496367-8bcb59a0-d68f-11e7-9393-eee29974694a.png)
    
- ^ and Firefox on Windows 10 does not give focus on click.

Additionally, Firefox does not apply :active focus styling with keyboard interactions with the SPACE key.

**Comment by calebmeyer** [comment]
Chrome (webkit, really) does some unexpected behavior with buttons when you click:
https://stackoverflow.com/questions/20340138/remove-blue-border-from-css-custom-styled-button-in-chrome

If we're going to be changing button, this might be a good thing to add.
