### ISSUE TITLE
Create enumeration for PropTypes.oneOf

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#1044]
# Issue Description
For [any package](https://github.com/cerner/terra-core/search?utf8=%E2%9C%93&q=oneOf%28&type=) that has a prop with a type of PropTypes.oneOf, an enumerations should be made available for that prop to make it easier for consumers to know the acceptable values. This also minimizes consumers from making typos when setting these props. 

An example of of a prop using enumeration is [alert type](https://github.com/cerner/terra-core/blob/master/packages/terra-alert/src/Alert.jsx#L16-L24) in the Alert component.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

**Comment by benbcai** [comment]
Packages that need updated:

- [ ] terra-spacer
- [ ] terra-heading
- [ ] terra-slide-panel
- [ ] terra-button
- [ ] terra-arrange
- [ ] terra-badge
- [ ] terra-table
- [ ] terra-text
- [ ] terra-button-group
- [ ] terra-progress-bar
- [ ] terra-image
- [ ] terra-hookshot
- [ ] terra-overlay
- [ ] terra-popup
- [ ] terra-form
- [ ] terra-responsive-element
- [ ] terra-collapsible-menu-view
- [ ] terra-collapsible-menu-view
- [ ] terra-modal-manager
- [ ] terra-menu
- [ ] terra-signature
- [ ] terra-form-textarea

**Comment by noahbenham** [comment]
When declaring the PropType, it might make more sense to use `Object.values()` instead of listing the options to improve maintainability.
For example, `type: PropTypes.oneOf(Object.values(AlertTypes))`.

**Comment by noahbenham** [comment]
Question for the team: Would it make more sense to export options directly instead of as part of `Opts`?

For example,
#### Internally
```jsx
const AlertTypes = {
  ALERT: 'alert',
  ...
};
```
would become
```jsx
export const AlertTypes = {
  ALERT: 'alert',
  ...
};
```


#### Consumers
```jsx
import Alert from 'terra-alert';

<Alert type={Alert.Opts.Types.WARNING}>
  This is a warning!
</Alert>
```
could become
```jsx
import Alert, { AlertTypes } from 'terra-alert';

<Alert type={AlertTypes.WARNING}>
  This is a warning!
</Alert>
```
This also allows consumers flexibility while still achieving our goal of typed props. For example,
```jsx
import Alert, { AlertTypes as TerraAlertTypes } from 'terra-alert';
...
```

#### Motivation
Not only does this reduce object property expansion, it also allows us internally to reuse types in subcomponents with greater ease.
For example, to implement text style types for `ItemDisplay` and `ItemDisplay.Comment`, I'd need to do something like
###### `ItemDisplay.jsx`
```jsx
import ItemComment from './ItemComment';

ItemDisplay.Comment = ItemComment;
ItemDisplay.Opts = {};
ItemDisplay.Opts.Style = TextStyles;
```

###### `ItemComment.jsx`
```jsx
import ItemDisplay from './ItemDisplay';

ItemComment.Opts = {};
ItemComment.Opts.Style = ItemDisplay.Opts.Style;
```

This creates circular dependency issues and generally feels like a bad pattern.

**Comment by mjhenkes** [comment]
I'm against exporting enumerations of props. Using a string is more concise and lowers the complexity of maintaining and creating these components. With prop type warning you will be warned if you've had a spelling mistake or pass in a non supported type.

A mistake using the enum is more likely to cause a run time exception and crash the page.

For consumers it's simply this:
```javascript
import Alert from 'terra-alert';

<Alert type="warning">
  This is a warning!
</Alert>
```

**Comment by dylan-sftwr** [comment]
@noahbenham, personally I prefer doing something like 

```js
const ButtonVariants = {
...
};

const ButtonTypes = {
...
};

export default Button;
export {  Types: ButtonTypes, Variants: ButtonVariants };
```

and in the case of something like button, where `Opts` has already been introduced, we'd leave the `Opts` export as well for passivity until the next major version update.

Thoughts?

**Comment by noahbenham** [comment]
I'd support that Dylan, although it sounds like Matt is advocating just using strings over an exported type.. Which makes sense to me.

**Comment by bjankord** [comment]
Plan to move forward with keeping prop-types as `strings` or as `numbers`. Doc examples should show strings used.

Export enums as below:

```jsx
const ButtonVariants = {
...
};

const ButtonTypes = {
...
};

export default Button;
export {  ButtonTypes, ButtonVariants };
```
