### ISSUE TITLE
[terra-props-table] Add ability to only render a subset of the props in the table

### ISSUE THREAD

**Issue by mschile** [cerner/terra-core#1049]
# Issue Description
When using react-redux and mapping state/dispatch to props, the props are considered 'internal' to the component and not meant to be set by consumers. It would be nice to have these props excluded from the props table.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Props only used by consumers are rendered in the table.

## Current Behavior
All props are rendered in the table.

**Comment by Blackop778** [comment]
Not really sure how would be best to proceed. The biggest problem is determining if a prop is internal or not. Some kind of marker could be added for each and every prop. Open to input. (@emilyrohrbough )

**Comment by bjankord** [comment]
One idea that might work for this would be to add an optional prop that could take an array. This array would be used to [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) out props from the [array of props](https://github.com/cerner/terra-core/blob/master/packages/terra-props-table/src/PropsTable.jsx#L83) displayed in the table.

**Comment by emilyrohrbough** [comment]
@bjankord +1. The thought here is how do we want to distinguish which props are filtered.

Take terra-navigation-layout for example; it has multiple props passed from the withRouter() HOC. These props need to be defined, however, consumer don't need to be exposed to them because the are internally given the props. @Blackop778 and I were discussion the appropriate way to distinguish this. An idea might be to filter on the key word(s) 'provided by' or 'internal' or 'private'?

**Comment by Blackop778** [comment]
# Tech Design for Props Table
## Summary:
Add a map to every package with a Props Table entry containing whether or not each prop is internal. Using a method from below that information will be passed to the `terra-props-table` which will sort itself to display `required` props at the top of the table and `internal` props at the bottom, with reguar props in the middle.

### Option 1
A custom `react-docgen` handler will be used by `terra-props-table` when parsing the source files to set a value on the prop as passed to `terra-props-table` stating whether or not it is internal. The only maintenance required would be to add the map to every package.

### Option 2
Export the map from every package then import the map in the corresponding `terra-site` `Index.jsx` page. Each page will have to sort itself. This option would require more maintenance but be easier to implement.

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/pull/2135
