### ISSUE TITLE
Fixing the Popup documentation for Stateless Target Elements

### ISSUE THREAD

**Issue by srana6** [cerner/terra-core#1052]
# Issue Description
Fixing the Popup documentation for Stateless Target Elements for the static function approach.
http://engineering.cerner.com/terra-core/#/site/popup

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Since we are using the static function, in the targetRef property instead of {this.getButtonNode} we should do {ClassName.getButtonNode}. Static should be accessed using the class name not by the instance.

## Current Behavior

Current scenario return the undefined when we call the static function using 'this'.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version: Google Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by dkasper-was-taken** [comment]
Closing, addressed when moved to terra-framework:
https://github.com/cerner/terra-framework/pull/130
