### ISSUE TITLE
Select Menu

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-core#1056]
# Issue Description
A new single select menu component is needed. This functionality already exists in the terra-form-select component. This logic needs to be pulled out into it's own component and updated with theming capability for the small screen size styles.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by PaulSolDev** [comment]
JIRA created

**Comment by PaulSolDev** [comment]
@bjankord would you be able to post a comment when you close issues for easier reference?

**Comment by bjankord** [comment]
Closed as not applicable.
