### ISSUE TITLE
Move terra-table sort indicator closer to the column name

### ISSUE THREAD

**Issue by danplubell** [cerner/terra-core#1069]
# Issue Description

The sort indicator floats to the right end of the terra-table column header name.  The sort indicator is closer to the next column.  It looks like the sort indicator is associated with the next column instead of the actual column.  
The sort indicator is set on the Name column but it looks like it is associated with the Address column.  
Here's an example of what it looks like.  
<img width="1231" alt="terra-table-sort-indicator-example" src="https://user-images.githubusercontent.com/2952155/33839894-07037e06-de59-11e7-9663-c6df1e31bbb7.png">

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

The proposal is to place the sort indicator at the end of the column name instead at the end of the column header cell.  This makes it obvious to which column the sort indicator is associate.

## Current Behavior

The sort indicator floats to the right of the column header cell.

## Steps to Reproduce

1. Set the sort indicator on a column header.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by jmsv6d** [comment]
@neilpfeiffer Need desired positioning of the sort indicator.

**Comment by neilpfeiffer** [comment]
## UX Design Input

Remove: `float:right;`
Add: `padding-left: 0.7142857143rem;`

Line reference: [Table.scss#L83](https://github.com/cerner/terra-core/blob/0a934ee4c86d8d9888783e09b8def1375df8686d/packages/terra-table/src/Table.scss#L83)
https://github.com/cerner/terra-core/blob/0a934ee4c86d8d9888783e09b8def1375df8686d/packages/terra-table/src/Table.scss#L83
