### ISSUE TITLE
Terra-menu text truncated & line height

### ISSUE THREAD

**Issue by noahbenham** [cerner/terra-core#1073]
# Issue Description

Terra-menu has a couple visual defects:
1. Setting `contentWidth="auto"` truncates text, as shown in the attached screenshot.
<img src="https://user-images.githubusercontent.com/6981195/33895725-c28b12b0-df26-11e7-92d3-171683241acc.PNG" width="300">

2. Blue_steel's menu options were much taller than terra-menu. We're concerned users may accidentally tap an incorrect option due to small menu heights. Is this best left to the consumer, or should this be addressed within Terra? See attached screenshot with fixed `160` width.

| Before | After |
|---|---|
| <img src="https://user-images.githubusercontent.com/6981195/33896085-91517dc8-df27-11e7-832c-ae066d9681e6.jpeg" width="200"> | <img src="https://user-images.githubusercontent.com/6981195/33896088-941c55b4-df27-11e7-9d42-652294111c7a.PNG" width="200"> |

3. Size for menu items on mobile is too small of a touch target and should look to make larger:
![imgo](https://user-images.githubusercontent.com/1355485/35744128-20ed77ba-0805-11e8-9912-23980439b212.jpg)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

1. contentWidth "auto" should flex based on text content and resize horizontally to support i18n'd text
2. Menu options should have increased line height

## Current Behavior

N/A - see description

## Steps to Reproduce
N/A

## Environment

* Component Version: **terra-menu 1.10.0**
* Browser Name and Version: **All**; Chrome 63.0.3239.84 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): **All**; macOS 10.12.6 (16G1036)

**Comment by jmsv6d** [comment]
@neilpfeiffer For this issue we need values for right margin and line height on menu items

**Comment by neilpfeiffer** [comment]
I'm working with Yudi to deterimine how menu on mobile (touch-detect + less than 1024px) should also grow line-height/touch area and we will provide needed design input.

**Comment by noahbenham** [comment]
I'm happy to contribute this back when you have design input, @neilpfeiffer. It'll block [CONNECT-10805](https://jira2.cerner.com/browse/CONNECT-10805).

**Comment by neilpfeiffer** [comment]
@noahbenham that's what I was hoping - I'll get details ready for you to start on for next week. We'll need to grab some util logic from https://github.com/cerner/terra-core/blob/03d12d40747885144937da85de640b886cf03638/packages/terra-time-input/src/TimeUtil.js#L199
and/or
https://github.com/cerner/terra-core/blob/03d12d40747885144937da85de640b886cf03638/packages/terra-form-radio/src/_RadioUtil.js#L2
The rest should be just setting min-width, and then line-height for the touch/mobile device.

**Comment by bjankord** [comment]
Talked with @neilpfeiffer, it sounds like he's reached out to you @noahbenham about a path forward on this you can implement in your app.
