### ISSUE TITLE
Spacing between header and item collection

### ISSUE THREAD

**Issue by laurunning** [cerner/terra-core#1080]
# Issue Description

When putting a header or subheader next to an item collection, there is extra space between them:
![image](https://user-images.githubusercontent.com/32143728/34016494-b548d5fc-e0e7-11e7-84da-b36002bf0187.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Shouldn't have extra spacing here. The header or subheader should just sit next to the item collection.

## Steps to Reproduce

1. Header or Subheader
2. Item Collection
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by emilyrohrbough** [comment]
Which item-collection version are you using?

**Comment by laurunning** [comment]
Hi @emilyrohrbough - it was an issue we had because we were forcing it into a list format always. We are now going to use a list with item views. I'll go ahead and close!
