### ISSUE TITLE
Spike: Look into rendering oddity in responsive element in IE11

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1083]
# Issue Description
Ran into an issue where using the responsiveElement without setting the responsiveTo prop, but using the defaultElement prop seems to cause some odd rendering.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Current Behavior
I was using JSX similar to this:

```
<div> <!-- this had display: flex; on it with MS vendor prefix -->
<ResponsiveElement
        className={tabCardClassNames}
        {...attributes}
        defaultElement={<div>test 1</div>}
medium={<div>test 2</div>}
      />
</div>
```

In IE 11, with this snippet above, on a narrow window where the `defaultElement` prop content should render and the `medium` content would not render, nothing renders on initial page load.

If I resized to larger screen where the medium breakpoint was triggered, it would render the div with test 2, and then if I resized to narrow screen where medium breakpoint was no longer active it would render div with test 1 string. 

Logging a spike to look into this, need a reduced test case to debug some more. For my use case at this time I can set `responsiveTo="window"` and this works the way I need it to.

**Comment by emilyrohrbough** [comment]
@StephenEsser is this the behavior you have been seeing within Item Collection within Kaiju but thought resulted from the responsive element?
