### ISSUE TITLE
Missing Autofocus feature in SearchField

### ISSUE THREAD

**Issue by srana6** [cerner/terra-core#1091]
# Issue Description
Currently there is no autofocus prop for the SearchField. User has to click inside the SearchField to bring the focus.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
As soon SearchField is displayed the focus should be in the input box.

## Current Behavior

N/A

**Comment by bjankord** [comment]
From talking with @scottwilmarth, it sounds like this is not something that we want to enable for all consumers due to accessibility concerns.
