### ISSUE TITLE
Update gh-pages when pushing to master

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#11]
# Issue Description
When merging branches to master, we have to manually deploy the changes. This is something that could be automated with Travis CI.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
When merging branches to master, I would like to automate deploying to gh-pages.

## Current Behavior
Need to manually deploy changes to master to gh-pages.

**Comment by Matt-Butler** [comment]
https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db#.6rlc9r8g5

**Comment by bjankord** [comment]
More info: https://docs.travis-ci.com/user/deployment/script/

**Comment by mjhenkes** [comment]
Travis-ci info specifically for gh-pages: https://docs.travis-ci.com/user/deployment/pages/
