### ISSUE TITLE
Need table with fixed headers and vertical scroll of rows

### ISSUE THREAD

**Issue by danplubell** [cerner/terra-core#1101]
# Issue Description

One of the requirements for our application is that the rows of a table will scroll and that the headers are fixed.  This is important because the headers are needed for the user to have the context of which column is which.  A good example is a set of columns that are date columns.  Without the fixed headers users have to remember which column is which. 

## Issue Type

- [x] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Here is a good example of the expected behavior:
[Fixed Headers with Vertical Scroll](https://react-table.js.org/#/story/fixed-header-w-vertical-scroll)
## Current Behavior

Table rows do not scroll independently of the table headers.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by neilpfeiffer** [comment]
Thanks @danplubell - Cerner UX (OCS effort) will very soon be providing new wholistic direction for how all tables will be handled and the included features. I am fairly confident this will include fixed headers. In the meantime, Terra is waiting for the new designs and feature requirements to be completed and we will complete or comment on this issue once we get those designs or received updates.

**Comment by dkasper-was-taken** [comment]
Addressed with #2615
