### ISSUE TITLE
Collapsible Menu Rolls Up 1 Button in IE

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-core#1105]
# Issue Description
When using IE, the collapsible menu will still roll up 1 button in IE, it is currently fixed in other browsers from [PR 1031](https://github.com/cerner/terra-core/pull/1031) but it is still happening in IE.
![image](https://user-images.githubusercontent.com/7713715/34364322-45d2c8ec-ea4a-11e7-81da-83f2c09413b3.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
When using IE, If the one and only button to be put into the ellipsis is already icon-only, do not roll up the button.

## Current Behavior

The one and only button being moved into the ellipsis button is icon-only. No space is saved.

## Environment

* Component Version: 1.7.0
* Browser Name and Version: IE/Edge 11.0.9600.18860IS
* Operating System and version (desktop or mobile): Desktop

**Comment by jmsv6d** [comment]
The collapsible menu view uses pure width calculations to determine if there is enough space to show each item. In the PR referenced we added the logic to determine if hiding the ellipsis button allows there to be enough space for all the buttons to show. An item being iconOnly does not guarantee the size of the button.  If an iconOnly button is larger than the ellipsis button (even by a partial pixel), this scenario can occur. That is the nature of this component.
