### ISSUE TITLE
[terra-button] Missing script failure

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#1108]
# Issue Description
An error occurs when running the test script (npm run test) in terra-button. It should execute the wdio script instead of the nightwatch script, which has been replaced by wdio.

```
missing script: test:nightwatch
```

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

**Comment by jmsv6d** [comment]
Looks like this fix is included in https://github.com/cerner/terra-core/pull/1070

**Comment by benbcai** [comment]
Oh I didn't realize that. Closing.
