### ISSUE TITLE
Translate the placeholders for the time-input

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1110]
# Issue Description
The placeholder should attribute for the time-input should be using i18n translated messages. Instead, it's hardcoded for hh:mm.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The placeholders should be set according to the locale they are in.

## Current Behavior
Placeholders will always display hh:mm

**Comment by emilyrohrbough** [comment]
Resolved by #1111
