### ISSUE TITLE
Various Popup documentation elements refer to the image component.

### ISSUE THREAD

**Issue by david-hibshman-cerner** [cerner/terra-core#1114]
# Issue Description
![terra-ui-popup-documentation](https://user-images.githubusercontent.com/35071124/34526152-90e4684c-f06f-11e7-826b-e68ae92f207d.png)

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The page should discuss the Popup component not the image component.

## Current Behavior
The Popup documentation currently starts by overviewing and showing Getting Started instructions for the image component instead of the Popup component.

## Steps to Reproduce
http://terra-ui.herokuapp.com/components/core/popup

## Environment
IE Browser, but likely the same for all browsers.

**Comment by dkasper-was-taken** [comment]
Closing as this is addressed by the new deployment of terra-ui.
