### ISSUE TITLE
Uplift Form Input Styles

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#1118]
# Issue Description
Uplift styles for the Form Input component.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Comment by benbcai** [comment]
# Tech Design 
## Summary:
Create a new package called terra-form-input to replace the Input component in terra-form. 

## React Props:
### New
- **isInvalid** Whether the input is invalid.
- **disabled** Whether the input is disabled.
- **onFocus** Function to trigger when user focuses on this input.

## Themeable Styles:
- Background color
- Border color
- Border radius
- Border style
- Boder width
- Box shadow
- Focus animation
- Font size
- Opacity when disabled, invalid, in focus
- Padding

**Comment by jmsv6d** [comment]
If adding `onFocus` as a first class prop we should probably add `onBlur` as well.

**Comment by emilyrohrbough** [comment]
Will font-size be inherited from base?

**Comment by JakeLaCombe** [comment]
+1

**Comment by JakeLaCombe** [comment]
terra-form-checkbox used isDisabled for it's prop instead of disabled. https://github.com/cerner/terra-core/blob/master/packages/terra-form-checkbox/src/Checkbox.jsx#L30. We should try to be consistent with all of our form packages

**Comment by benbcai** [comment]
- Included the onBlur prop.
- font-size, font-weight and color would be themeable. font-family would be inherited.
- We are already somewhat inconsistent. Checkbox and other non form components use `isDisabled`. However, terra-form-select and terra-form-textarea both use `disabled`. If we choose `isDisabled`, it would be less passive since consumers would need to change to `isDisabled` from `disabled` that they are currently using. This may not be a good enough reason to choose `disabled` over `isDisabled`. The other form components currently use the `required` prop (instead of isRequired). It seems natural to just keep the same prop name for these native attributes. Thoughts or preferences anyone?

**Comment by bjankord** [comment]
If terra-form-select and terra-form-textarea both use `disabled`, and checkbox uses `isDisabled`, we should go with `disabled` for this component, and get checkbox updated to use `disabled` before we cut the release for it.

**Comment by bjankord** [comment]
Closing in favor of tracking this on #1207
