### ISSUE TITLE
Add Translations for terra-time-picker

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1131]
# Issue Description
Right now, terra-time-picker uses mocked translations for it's files. We need to switch that over to what the translations will really be. The Jira has already been logged for it, so it's just a matter of moving the files over when they are ready.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
terra-time-picker uses real translations

## Current Behavior
terra-time-picker uses mocked translations

**Comment by emilyrohrbough** [comment]
Resolved in https://github.com/cerner/terra-core/pull/1203
