### ISSUE TITLE
Uplift Button Group Styles

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#1132]
# Issue Description
Uplift styles for the Button Group component and consume Button 2.0

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Comment by benbcai** [comment]
# Tech Design 

## React Props:
### ButtonGroup
#### New
- `isMultiSelect` Whether or not multiple buttons can be selected.

#### Removed
- `children` This prop has been removed in Button 2.0.
- `isCompact` This prop has been removed in Button 2.0.
- `size` This prop has been removed in Button 2.0.
- `variant` This prop is no longer needed since the variant will always be `Neutral`.

### ButtonGroupButton
#### Removed
- `children` This prop has been removed in Button 2.0.

#### Changed
- `text` Will be changed from optional to required. If an icon is provided, this text is hidden and set as the aria-label for accessibility.


## Themeable Styles:
No new themable styles for Button Group. All themable styles are based on Button.

## Responsiveness
See Questions section.

## Accessibility
N/A.

## Notes
- Buttons in Button Group can only either be Text or Icon. Buttons cannot be Text WITH Icon. To prevent buttons from having both text and icon, if an icon is provided, this will denote that it is icon only and the isIconOnly prop in Button will be set to true.

## Questions
- Button 2.0 introduces a few callback function props: `onBlur` `onFocus` `onKeyDown` `onKeyUp`. Would be props be useful for button group? These can't just be pass thru props. The button index would be to be returned to identify which button the event comes from, similar to the current onChange and onClick props.

- Button Group currently does not collapse the button in a drop-down menu when space is limited. Option 1: Encourage consumers to utilize the Collapsible Menu View to collapse the buttons in a drop-down menu. Option 2: Make Button Group collapsible on its own by replicating Collapsible Menu View

**Comment by jmsv6d** [comment]
1) I would rather remove the `buttons` prop and keep `children` for button group. 
2) Button Group currently uses index to denote which button is selected, we should update it to use keys instead. 
3) How do you expect `isMultiSelect` to work beside the `isSelectable` prop?
4) `onBlur` `onFocus` `onKeyDown` `onKeyUp` should all be able to just be passed down through the button group button. That's how `onClick` currently works. 
5) I would say that the collapsible menu view should be used for the collapse functionality so we don't end up with a resize observer inside a resize observer when the collapsible menu view is built with a button group in it.

**Comment by benbcai** [comment]
1. What is your reason for keeping `children` over `buttons`? Both are currently handled the same way. The only difference is the prop type.
2. If a key is not provided, should we fall back to use the button text since it is a required prop?
3. I'm going to verify with UX but it looks like button group will always be selectable. If that is really the case, then we won't need the `isSelectable` prop
4. I can just pass those down but consumers won't know which one of those buttons the event occurred on. I would need to wrap those similar to [wrapOnClick](https://github.com/cerner/terra-core/blob/master/packages/terra-button-group/src/ButtonGroup.jsx#L88) for onChange.
5. I agree.

**Comment by jmsv6d** [comment]
1) Passing ButtonGroup.Button as children makes more sense as a consumer using the component. There's only one main content area which has been our criteria for using children. No matter which one we are only supporting ButtonGroup.Button being put there. Consumers could technically put custom components in either so I don't see any drawbacks to using children and it will lead easier to read code for consumers.

2) If consumers don't provide a key then it just shouldn't work, they should be providing keys anyway since react will throw a warning if they don't provide keys for elements with siblings. 

3) I really think that a button group without selection styling is going to be needed, even if it's 

4) I'm saying that they should be props on the ButtonGroup.Button component. Unless you're actually using them in the ButtonGroup component there would be no need to wrap them. You wouldn't need to pass any additional information, they could use them just like they would with any other button.

**Comment by jmsv6d** [comment]
Also, I believe at one point we had talked about allowing consumers to flex between a controlled and uncontrolled ButtonGroup. Do we still think there's a need for that?

**Comment by kschuste** [comment]
I would expect we would use children over buttons, using children is most consistent across our components, also is easier for a user to build the ButtonGroup in React

ex:
<ButtonGroup>
  <ButtonGroup.Button>
  <ButtonGroup.Button>
<ButtonGroup>

+1 to using keys

use the additional props on the ButtonGroup.Button only

**Comment by jmsv6d** [comment]
This is the issue where we had an ask for a controlled button group: https://github.com/cerner/terra-core/issues/1042

**Comment by benbcai** [comment]
1. Makes sense. The `buttons` props will be removed and keeping the `children` prop.
2. Will use keys instead of index.
3. The `isSelectable` prop will be removed. A new `selectType` prop will be added to determine the select type: one of 'non-selectable', 'single-select' or 'multi-select'.
4. Made `onBlur` `onFocus` `onKeyDown` `onKeyUp` first class props and just pass through to Button.

I'll have to take a look at https://github.com/cerner/terra-core/issues/1042

**Comment by emilyrohrbough** [comment]
In regards to proving the selectable type of button-group, should we create a ButtonGroup and a SelectableButtonGroup which consumers are required to provide their own selection implementation? This would be consistent with changes in list and table.

@dkasper-was-taken

**Comment by benbcai** [comment]
If we split up the current ButtonGroup, we would have ButtonGroup, SelectableButtonGroup, SingleSelectButtonGroup and MultiSelectButtonGroup. I wonder if providing a SelectableButtonGroup, which allows consumers to manage the selection, would satisfy what is being asked in #1042.

**Comment by StephenEsser** [comment]
@tbiethman mentioned potentially making this a controlled component in an offline discussion. 

This approach would satisfy all conditions necessary in a single component. A controlled ButtonGroup could be single select, multi-select, and even no selections.

A controlled component also places the ButtonGroup integrity on the consumer. An uncontrolled ButtonGroup updates the selection state with no contract with the user opening opportunities for undefined application state.

If an uncontrolled ButtonGroup becomes desirable in the future it may be possible to passively add a default selection prop to be more consistent with forms.

**Comment by emilyrohrbough** [comment]
@benbcai 
> If we split up the current ButtonGroup, we would have ButtonGroup, SelectableButtonGroup, SingleSelectButtonGroup and MultiSelectButtonGroup.

With current implementation, could be have ButtonGroup and SelectableButtonGroup components? 

As @StephenEsser suggested, I wouldn't mind aligning the controlled and uncontrolled aspects/implementations of our components.

**Comment by benbcai** [comment]
I also think making the ButtonGroup a controlled component gives consumers the flexibilities they need. Although consumers can compose a button group that is non-selectable, single-select, or multi-select using a controlled ButtonGroup, does it make sense to also create an _uncontrolled_ MultiSelectButtonGroup so that consumers can use it out of the box without them having to manage the selection states? I think a multi-select button group can be a common reusable component.

**Comment by StephenEsser** [comment]
I would hold off on creating additional components until they become necessary. Maintaining two different components without knowing their necessity adds more overhead and duplicated code. I think the ButtonGroup itself could be both a controlled and uncontrolled component using a similar approach to form controls ( defaultValue / value ).

Creating an additional MultiSelectButtonGroup raises an expectation that we would have a SingleSelectButtonGroup and then we're left with 3-4 different ButtonGroup components to test and maintain.  

I think providing a single controlled ButtonGroup component is a flexible approach that satisfies all initial use cases, as consumers start to use these components we can evaluate the need for uncontrolled or additional components. 

It's easier to add functionality in the future than it is to give it up front and take it away later

**Comment by benbcai** [comment]
Fair enough. My thought of creating the MultiSelectButtonGroup came from the OCS guide for explicitly calling out the ability for multi selection. I can create a test component to show that multi selection can be achieved using the controlled ButtonGroup.

**Comment by bjankord** [comment]
+1
