### ISSUE TITLE
Icon: remove/change minimum size

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1139]
# Issue Description
Current icons used with terra-icon has a `min-height:20px;` and `min-width:16px;` applied to the SVGs which makes their sizes odd when paired with text at 1 rem (14px). 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Revisit need for icons having a minimum size, or change minimum size to be smaller (and square / same dimensions). Get new specifications from UX.

**Comment by bjankord** [comment]
SVG icons should have styles that apply width and height at `1em` so they scale with the font-size of the element they are within. Though looking at the CSS for terra-icon, it looks like we are not setting any size and leaving it to the browser to size.

**Comment by neilpfeiffer** [comment]
Found issue was created from another source - closing this issue and logging this one as replacement: https://github.com/cerner/terra-clinical/issues/259
