### ISSUE TITLE
Icon Documentation for Icons is difficult to read.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1140]
# Issue Description
https://terra-core-deployed.herokuapp.com/static/#/site/icon/static

When looking at this page, it's hard to tell example what code needs to be imported into the application. Statements like import IconHelp from 'terra-icon/lib/icon/IconHelp' have the same font as it's surrounding documentation, and isn't clear right away that it's sample code that can be used in their own applications.

What I propose is that we place all of the code inside a code block, and also bold the import classes so that it's clear what the react object is that is being used if that's possible.

```
import IconHelp from 'terra-icon/lib/icon/IconHelp';
```

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Icon Documentation of examples is more clear.

## Current Behavior
Icon Documentation doesn't highlight the code import statements in an easy to read fashion.

**Comment by bjankord** [comment]
+1, sgtm

**Comment by mukuldhariwal94** [comment]
can this be closed ?

**Comment by bjankord** [comment]
@mukuldhariwal94 Yep, we can close this. Resolved in #1292. This will go out in our next release.
