### ISSUE TITLE
Update repo readme with current status of new packages

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1146]
# Issue Description
We are missing some packages on the package status table - we should update this to be consistent with the current state of Terra:
- [ ] Collapsible Menu View
- [ ] Divider
- [ ] Dynamic 
- [ ] Grid
- [ ] Form Checkbox
- [ ] Form Radio
- [ ] Form Select
- [ ] Hookshot
- [ ] Profile Image
- [ ] Signature
- [ ] Spacer

**Comment by bjankord** [comment]
We should see if we can automate this.
