### ISSUE TITLE
Error when trying to use terra-base without locale / translations

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1149]
# Issue Description
I'm trying to set up terra-base without translations, and I'm getting an error that various translation files aren't included in lib when just importing Base.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
terra-base can be used without setting locale

## Current Behavior
Setting up terra-base without locale triggers an error that various translation files aren't included in lib when just importing Base.

## Steps to Reproduce

1. Setting up terra-base without locale
2. triggers an error that various translation files aren't included

## Environment

* Component Version: v1 and v2

**Comment by bjankord** [comment]
The logic in terra-base was intended to only call i18nLoader if a locale was set when the Base component was mounted or new props were passed to it: https://github.com/cerner/terra-core/blob/master/packages/terra-base/src/Base.jsx#L49-L59

However this line triggers i18nLoader to be executed irregardless of the function actually being called: https://github.com/cerner/terra-core/blob/master/packages/terra-base/src/Base.jsx#L3

I believe to fix the issue in terra-base running i18nLoader without a locale, we need to either dynamically load that import if the locale prop is set, or split base into 2 components. Base and BaseI18n.

Probably the quickest fix is to set up the i18n-plugin. This issue describes what's needed to set it up: https://github.com/cerner/terra-core/issues/928

However, we should get base fixed so people can use it with setting a locale.

**Comment by yuderekyu** [comment]
Wasn't this fixed?

**Comment by emilyrohrbough** [comment]
Base requires a minimum of 'en' translations at this point.

**Comment by bjankord** [comment]
Plan is to move forward with making locale a required prop.

**Comment by bjankord** [comment]
This has been resolved in terra-base@5.0.0/terra-i18n@4.0.0
