### ISSUE TITLE
Terra-popup isn't able to be used with onMouseEnter and onMouseLeave

### ISSUE THREAD

**Issue by CoryMcDonald** [cerner/terra-core#1156]
# Issue Description
When using Terra-Popup we would like to have the popup open on hover of an element however this does not work.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
We should be able to use onMouseEnter and onMouseLeave with Terra-Popup. Here's some simple code to replicate it.

## Current Behavior
Essentially what is happening is when we are using an `onMouseEnter` and an `onMouseLeave` event the Popup appears over the element that is triggering the popup and triggers an `onMouseLeave` event.

@JakeLaCombe was able to replicate this issue.

## Steps to Reproduce
```javascript
import React from 'react';
import Popup from 'terra-popup';
import Button from 'terra-button';
import IconInformation from 'terra-icon/lib/icon/IconInformation';

class InfoPopup extends React.Component {
  constructor(props) {
    super(props);
    this.handleButtonClick = this.handleButtonClick.bind(this);
    this.handleRequestClose = this.handleRequestClose.bind(this);

    this.state = { open: false };
  }

  handleButtonClick() {
    this.setState({ open: true });
  }

  handleRequestClose() {
    this.setState({ open: false });
  }

  render() {
    return (
      <div>
        <Popup
          isOpen={this.state.open}
          onRequestClose={this.handleRequestClose}
          targetRef={() => document.getElementById('test')}
        >
          <div><p>Hello</p></div>
        </Popup>

        <Button
          id="test"
          icon={<IconInformation />}
          onMouseEnter={this.handleButtonClick}
          onMouseLeave={this.handleRequestClose}
        />
      </div>
    );
  }
}

export default InfoPopup;

```

## Environment
* All desktop web browsers are impacted by this
* Component Version: Terra-Popup `0.18.0`

**Comment by dkasper-was-taken** [comment]
This is not the intended use case for terra-popup. That behavior falls inline with a tooltip, which would require a different set of requirements and behaviors. As mobile design prevents consistant usage of tooltips, they have largely been removed from design; so if UX deems it needs this functionality, a separate tooltip component built off of terra-hookshot would need to be created to handle this behavior.

The new behavior would need to include:
No prevention of scrolling
No reposition on scroll
No bounded size
No header functionality
An uncontrolled component
Potential mouse location target positioning
Potential dismissal on scroll
