### ISSUE TITLE
Explore skeleton pattern as alternative to loading spinner

### ISSUE THREAD

**Issue by mndrsn** [cerner/terra-core#116]
# Issue Description
Industry usability research suggests using interface skeletons (i.e. interface placeholders) rather than spinners to indicate loading progress.

From [Luke Wroblewski](http://www.lukew.com/)'s article [Avoid the spinner](http://www.lukew.com/ff/entry.asp?1797):

> A skeleton screen is essentially a blank version of a page into which information is gradually loaded. This creates the sense that things are happening immediately as information is incrementally displayed on the screen.<br><br>With a skeleton screen, the focus is on content being loaded not the fact that its loading and that’s real progress.

**Don't use spinners as a catch-all when loading content**:
![6d0d0a32-11d9-11e4-8fb0-64a30ea12e53](https://cloud.githubusercontent.com/assets/13057402/23804635/5bf86168-0580-11e7-8d2f-a01f4ae141a1.png)

**Provide skeletons as an alternative**:
![774978dc-11d9-11e4-997f-7c8460cfe5f2](https://cloud.githubusercontent.com/assets/13057402/23804704/a3102c84-0580-11e7-8cae-6c0f703fb180.png)

**Facebook utilizes skeletons as well**:
![6b940920-11da-11e4-9323-8de1e266c06d](https://cloud.githubusercontent.com/assets/13057402/23804745/d1d6ba1a-0580-11e7-82b2-b2c737f20dd6.png)

**As does Slack**:
![screen shot 2017-03-10 at 11 28 45 am](https://cloud.githubusercontent.com/assets/13057402/23805753/d13f5766-0584-11e7-805d-eff40c4b903f.png)

**And also PowerChart Touch**:
![img_0143](https://cloud.githubusercontent.com/assets/13057402/23806577/cf38df34-0587-11e7-8c14-a74d7c966bc0.PNG)

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Outcomes
- Skeleton UI elements and templates can be used as an alternative to the spinner.

## Current Behavior
N/A

**Comment by slor** [comment]
👍  this feature

**Comment by bjankord** [comment]
Closing until we have OCS design input
