### ISSUE TITLE
Create Example Component

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#117]
# Issue Description
Nice to have / low priority

Create an Example component. This component will have 2 tabs. The first tab will have the rendered react component. The second tab will display the code for the example. This component could also allow a user to adjust prop values.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
This component will have 2 tabs. The first tab will have the rendered react component. The second tab will display the code for the example. This component could also allow a user to adjust prop values.

## Current Behavior
N/A

**Comment by JakeLaCombe** [comment]
Perhaps we can utilize https://www.npmjs.com/package/react-uikit-codeblock to make this work?

**Comment by bjankord** [comment]
Talked about creating live editable examples. We can look at using https://github.com/FormidableLabs/react-live to do this.

**Comment by bjankord** [comment]
To be able to display the source code used in the example, we'll need to remove the `src` directory from .npmignore so we can display it on the terra-ui doc site.

**Comment by bjankord** [comment]
Looked into https://github.com/FormidableLabs/react-live. It does not support import/export syntax, it is meant to display just the code that would live inside a render method and is for trivial examples.

https://formidable.com/open-source/component-playground/ is another example which looks like it might fit our needs better but the minified version is fairly large coming in at [1.2 MB](https://github.com/FormidableLabs/component-playground/blob/master/dist/component-playground.min.js)

I'm hesitant to add such a large library to the doc site, instead I'd recommend we leave live updating of react components to kaiju. I'm open to including links to kaiju on the doc site for the various components so people can play around with them.

**Comment by bjankord** [comment]
Closing out in favor of using storybook with info addon
