### ISSUE TITLE
terra-status-view TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-core#1170]
# Issue Description

We're trying to consume the terra-status-view component, which works as expected; but all our jest tests are failing. 
Here's a screencap of the errors, it fails on our import lines:
![image](https://user-images.githubusercontent.com/7713715/35284779-46911b8e-0021-11e8-94a6-e2a22b2370d7.png)

It is failing on this line:
`variant: _propTypes2.default.oneOf(Object.values(variants))`

All research points to babel-polyfill being the culprit.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

It should not error when running jest tests.

## Steps to Reproduce

1. import terra-status-view
2. Run jest tests

## Environment

* Component Version: 1.0.1
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by tbiethman** [comment]
Object.values requires a polyfill. We recommend the use of babel-polyfill and use it internally. Are you currently using a polyfill in your application?

**Comment by PseudoFaux** [comment]
Yes, we currently use babel-polyfill. Does it need to be imported now in every file that consumes this component?

**Comment by PseudoFaux** [comment]
UPDATE:
Fixed by updating Node version locally to 8.9.4, might be a good idea to add it to the readme.

**Comment by mjhenkes** [comment]
@PseudoFaux, what version were you on?  We've documented in the .nvmrc and package.json that we use node 8.9.2

https://github.com/cerner/terra-core/blob/master/.nvmrc
https://github.com/cerner/terra-core/blob/master/package.json#L7

**Comment by PseudoFaux** [comment]
I believe I was running 6.11.1 at the time. I was just thinking it might be a good idea to mark it in the terra-status-view's readme that Node should be v. 8.9+
