### ISSUE TITLE
Update the default background color to transparent for TerraTable.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1174]
# Issue Description
Remove the #fff background color from table as the default, and instead either use none or transparent. This will allows both pass-through and theming.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Backgrounds as not generally set on components, but rather HOC that contain them. But table has from expect styles associated with selection and zebra striping of rows. So in order to accomplish both options for behavior, we should change the default.

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/pull/1758
