### ISSUE TITLE
Slow Response From terra-tabs on Desktop Safari (mobile viewport)

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1179]
# Issue Description
When attempting to navigate to another tab at a mobile viewport, in Safari versions mentioned below, load times inconsistently hang (see slow terra-tab example).

![slow-terra-tab-response-on-mobile-tab-change-iloveimg-compressed](https://user-images.githubusercontent.com/633148/35471301-21f3a544-031e-11e8-8219-2b41b798f257.gif)

In the iOS simulator, the tabs look to switch with no delay. 

![screen recording 2018-01-27 at 05 23 am](https://user-images.githubusercontent.com/633148/35471525-63de57e8-0322-11e8-92ec-ccdb1ce04734.gif)

Issue may be scoped to narrow screen desktop Safari

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
No rendering delay when switching between tabs

## Current Behavior
Switching between tabs has a slow response before content is rendered

## Steps to Reproduce

1. Clone https://github.cerner.com/HealtheLife/healthe-at-cerner.git
1. Check out PORTALDEV-40073-OCS-Tabs-Swap branch
1. Run npm install.
1. Run npm run start to launch the site on port 3000.
1. Open Safari and navigate to localhost:3000.
1. Shrink your screen width until the instance of terra-tabs on the home page renders with a context-menu for tab navigability.
1. Click the context menu to change to another tab.

## Environment

* Component Version: terra-tabs v1.0.0
* Browser Name and Version: Safari: 10.1.1 & 11.0.2 (narrow viewport)

**Comment by JakeLaCombe** [comment]
I tested this out, and it looks like this is an issue related to the setting of the box-shadow property in the content areas. Given this, we can close this.
