### ISSUE TITLE
Prevent Keyboard navigation and focus styling for disabled links.

### ISSUE THREAD

**Issue by msaikaushik1992** [cerner/terra-core#1181]
# Issue Description
Currently the global style for disabled hyper link only prevent mouse actions but still allows keyboard navigation and focus styles which is not expected. This is and extension of [this](https://github.com/cerner/terra-core/pull/1171) PR.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ x ] Bug
- [ ] Other

## Expected Behavior
Tabbing and pressing enter on the disabled link should prevent the action of going to the linked page.

## Current Behavior
Tabbing and pressing enter on the disabled link allows to go to the linked page.

## Steps to Reproduce
http://localhost:8080/#/site/base
1. Navigate to Global BaseStyles Anchor tag example section in the above link.
2. Press tab until the disabled link is in focus.
3. Press enter.

## Environment
Currently this bug is only in developer environment until [this ](https://github.com/cerner/terra-core/pull/1171#discussion-diff-163942855R65) gets merged.

**Comment by bjankord** [comment]
This StackOverflow post has some good resources on disabling links:
https://stackoverflow.com/questions/10276133/how-to-disable-html-links

**Comment by msaikaushik1992** [comment]
After talking to UX, this issue is no longer being supported.
