### ISSUE TITLE
Status View contents overflow narrow containers

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1182]
# Issue Description
The contents of Status View are currently bleeding out of it's container when it's too narrow for the contents. Worry is that if application supplies long, non-broken Domain, Error strings, or Exception codes as part of the message, they may not wrap within the view correctly as intended. (Is a discovered possible edge-case usage of the component.)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
1. `Message` and `Title` probably should add an extra css to handle word-breaks and hyphen usage unless there is a performance risk.
```
-ms-word-break: break-all;
    word-break: break-all;

/* Non standard for WebKit */
     word-break: break-word;

-webkit-hyphens: auto;
   -moz-hyphens: auto;
        hyphens: auto;
```

2. Probably should add extra breakpoint to hide the Icon when the container is less than 100px wide (or the appropriately needed space).

## Current Behavior
1. Screenshot showing current behavior of text overflow with a long unbroken "word" in both both the Title and Message
> <img width="406" alt="screen shot 2018-01-29 at 4 43 20 pm" src="https://user-images.githubusercontent.com/1355485/35538796-bafdb6ec-0514-11e8-940e-38d3d4d1c511.png">

2. Screenshot showing current behavior of icon overflow (and if word wrapping and hyphens were added to the text)
> <img width="221" alt="screen shot 2018-01-29 at 5 10 03 pm" src="https://user-images.githubusercontent.com/1355485/35539471-555b0f12-0517-11e8-8703-2d4b4962fb26.png">

## Steps to Reproduce
1. Text Overflows: Add Status View inside a parent container that has a smaller width than the length needed for a long unbroken word/s used in the title or message. 
2. Icon Overflows: Add Status View inside a parent container that has a smaller width than the icon -- 100px (not ideal and not recommended by UX but could happen). 

## Environment

* Component Version: 1.0.1
* Browser Name and Version: Chrome - Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Mac Sierra version 10.12.5

**Comment by emilyrohrbough** [comment]
Working with the browserslist config and including it into stylelint, I am seeing these warnings:

> Unexpected browser feature "word-break" is only partially supported by Android Browser 4.4.3-4.4.4

We should verify changes work as expected on Android devices.
