### ISSUE TITLE
Cannot read property 'length' of undefined for initial terra-search

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#1183]
# Issue Description

[Line 135 of SearchField.jsx](https://github.com/cerner/terra-core/blob/master/packages/terra-search-field/src/SearchField.jsx#L135) isn't able to access the length property of undefined. 

![length-error](https://user-images.githubusercontent.com/5365325/35576491-be51f9a8-05a4-11e8-9733-b0cfc77f2b9e.PNG)

If text is added, then removed, the search goes through fine. But if the search button is hit immediately, the error shows up. I believe it's because the default state is initialized from the prop defaultValue, which has a defaultProp of "undefined". I'm not super familiar with the code of SearchField so I'm not sure of the impact changing this default prop to empty string would be.

The error only seems to show up on this placeholder text example. The other examples on the page are fine.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
It should handle empty text, regardless if it was the initial run or subsequent runs

## Current Behavior
It handles empty text if and only if the search field had text in it any time before the handleSearch function is called.

## Steps to Reproduce

1. [Go to the Terra documentation for SearchField](http://engineering.cerner.com/terra-core/#/site/search-field)
2. Immediately click on the search button for the example "Search Field with placeholder text"
3. Open developer console and see error

## Environment

* Component Version: 1.19.0
* Browser Name and Version: Chrome Version 63.0.3239.132 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): desktop

**Comment by bjankord** [comment]
This has been resolved in in terra-search@2.0.0
