### ISSUE TITLE
Update Table documentation and examples

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-core#1188]
# Issue Description
Terra-table needs updated documentation and an example implementation of sorting.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
The sort option strings are provided in the documentation
There is an example on page that implements sorting

## Current Behavior
![](https://media.giphy.com/media/137TKgM3d2XQjK/giphy.gif)

**Comment by dkasper-was-taken** [comment]
Addressed with #2615
