### ISSUE TITLE
Elements within SlidePanel panel is focusable when closed

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#1192]
# Issue Description

Elements that are presented within the SlidePanel's panel are focusable when the panel is closed and offscreen. This is creating some workflow weirdness/confusion for people.

We should try to hide the panel content when the panel is closed from within the SlidePanel. This has some implications for the opening/closing animations, as we have to be careful when we show/hide the content. We could try using the ReactTransitionGroup to handle some of these things, but more investigation is needed.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

The SlidePanel should not allow panel content to be focusable when closed.

## Current Behavior

The SlidePanel allows panel content to be focusable when closed and looks weird doing it.

## Steps to Reproduce

1. Put a component with a Button in a closed SlidePanel panel.
2. Tab until you find it and watch the focus go offscreen.

## Environment

* Component Version: 1.15.0
* Browser Name and Version: All
* Operating System and version (desktop or mobile): All

**Comment by bjankord** [comment]
I ran into this with the toggle component. Here are some nightwatch tests which test this use case for toggle: https://github.com/cerner/terra-core/blob/master/packages/terra-toggle/tests/nightwatch/toggle-spec.js#L31-L49

Here are the styles used: https://github.com/cerner/terra-core/blob/master/packages/terra-toggle/src/Toggle.scss#L6-L21

If an element has `visibility: hidden;` set on it, it will remove it and its children from focus order. I think we may need to use ReactTransitionGroup for this component though. We'd essentially wait for the open / close animation to complete, then toggle `visibility: hidden;`

**Comment by noahbenham** [comment]
@bjankord I don't think this was fixed with `aria-hidden=true`. I'm still seeing this behavior. However, adding `visibility: hidden` around the inactive slide panel does resolve this.

**Comment by bjankord** [comment]
@noahbenham In #1228, @dkasper-was-taken added `visibility: hidden;` style to `.panel[aria-hidden='true']`: https://github.com/cerner/terra-core/pull/1228/files#diff-17fe1b653213aa7d7c3af0b153fad666

This code change has not yet been released yet though and will go out in our release on Tuesday.
