### ISSUE TITLE
New icons for Document/image handling

### ISSUE THREAD

**Issue by ven-sub** [cerner/terra-core#1197]
# Issue Description
This is a new set of icons that we need, but want to contribute it to Terra-core.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- [Link to DMicons in svg format](https://github.com/cerner/terra-core/files/1687456/DMicons.zip)

The list of icons consist
- Rotate Right
- Rotate Left
- Fit to width
- Fit to screen
- Actual size
- Annotate

## Current Behavior
"N/A"

**Comment by mjhenkes** [comment]
Are these part of https://github.com/cerner/one-cerner-style-icons and if not could we get them added there?

**Comment by neilpfeiffer** [comment]
These icons currently are not part of the one-cerner-style-icons repo, and we've created [UXREQ-9274](https://jira3.cerner.com/browse/UXREQ-9274) to have the request go through the internal process to get them created & added as a prerequisite to completing this issue for Terra.

Closing this issue for now and will reopen when the JIRA process is complete.
