### ISSUE TITLE
IconSpinner no longer working

### ISSUE THREAD

**Issue by CoryMcDonald** [cerner/terra-core#1204]
# Issue Description
You can very clearly see this issue on the LoadingOverlay
http://engineering.cerner.com/terra-core/#/tests/loading-overlay-tests/default

There are no tests for the `isSpin` prop.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
It should spin.

## Current Behavior
It does not spin. 

## Steps to Reproduce
1. Open your web browser.

## Environment

* Component Version: 1.18.0
* Browser Name and Version: Chrome 63.0, Firefox Developer Edition, Safari  11.0.3
* Operating System and version (desktop or mobile): OSX

**Comment by mjhenkes** [comment]
isAnimated needs to be set to true.
http://engineering.cerner.com/terra-core/#/site/overlay
http://engineering.cerner.com/terra-core/#/tests/loading-overlay-tests/animated

**Comment by mjhenkes** [comment]
It seem kinda weird that we default that to false.
