### ISSUE TITLE
Tabs webdriver tests timeout

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1216]
# Issue Description
Tabs seems to be frequently timeout out during wdio tests. Need to look into this and figure out a fix for the timeout issue.

**Comment by emilyrohrbough** [comment]
Is there any consistencies on where they are timing out?

**Comment by bjankord** [comment]
No consistencies, but talking with you and @JakeLaCombe, it sounds like we've found the [LOC causing the issue](https://github.com/cerner/terra-core/blob/master/packages/terra-tabs/tests/wdio/tabs-spec.js#L18).

Need to update `Terra.should.matchScreenshot({ viewports });` to `Terra.should.matchScreenshot();`

Jake has this fix in his react 16 PR.
