### ISSUE TITLE
Enhance slide panel to hide off screen content when closed

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1225]
# Issue Description
Set hidden styles on the slide panel to prevent tab focus from component off of the screen.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
When the value for isOpen is set to false, the content inside the slide panel should not be focusable, so hidden styles should be applied to the whole panel.

**Comment by bjankord** [comment]
Duplicate issue: https://github.com/cerner/terra-core/issues/1192

**Comment by bjankord** [comment]
Resolved in #1228
