### ISSUE TITLE
Scrolling allowed behind modals in iOS

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#1227]
# Issue Description
Scrolling is supposed to be disabled behind modal windows. Scrolling is disabled in most browsers; however, iOS allows this on our example site: https://terra-ui.herokuapp.com/components/core/modal

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Scrolling should be disabled behind modals.

## Current Behavior
Scrolling is happening behind the modal windows.

## Steps to Reproduce

1. On an iOS device, go to: https://terra-ui.herokuapp.com/components/core/modal
2. Invoke a modal window
3. Swipe up/down to scroll
4. Note that scrolling is happening behind the modal window

## Environment

Happens on iOS devices on any component that uses modals.

**Comment by bjankord** [comment]
Duplicate issue: https://github.com/cerner/terra-core/issues/799
