### ISSUE TITLE
Locale Switching in Terra Site is behaving inconsistently

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1236]
# Issue Description
Locale switching in Terra site appears to be having issues. It seems to be rendering one locale back as opposed to rendering the selected locale, and sometimes the locale doesn't even display the messages.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Locale shows the messages and formats correlated to the selected locale

## Current Behavior
Locale appears to be displaying messages and formats of the previously selected locale.

**Comment by jmsv6d** [comment]
I wonder if this is actually a bug with the recent changes made to collapsible menu view.

**Comment by JakeLaCombe** [comment]
The collapsible menu view isn't the defect. The defect here is this line. https://github.com/cerner/terra-core/blob/master/packages/terra-base/src/Base.jsx#L62
