### ISSUE TITLE
theming plugin generates incomplete set of themable variables

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1238]
# Issue Description
When running `npm start`, it appears the theming plugin is generating an incomplete set of themable variables in `packages/terra-site/themeable-variables.json`

My thought is this could be a result of use switching to a CSS custom property syntax that doesn't provide fallback values. Its odd that it is just now showing up.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
`packages/terra-site/themeable-variables.json` contains full set of themable variables in terra-core

## Current Behavior
`packages/terra-site/themeable-variables.json` contains only themable variables for ButtonGroupButton

## Steps to Reproduce

1. Run clean install on master branch
2. Run npm start
3. View `packages/terra-site/themeable-variables.json` 

## Environment

* Component Version: terra-core-site: 2.0.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): N/a

**Comment by emilyrohrbough** [comment]
I also noticed issues with the themeable-variables plugin while coding terra-button and discovered it correlated to the ThreadLoader. So I logged this issue: https://github.com/cerner/terra-core/issues/1106. Do you think there is a correlation?

**Comment by bjankord** [comment]
Ah, I forgot we had that issue logged. Yeah, we should test and see if thats what is causing it.

**Comment by emilyrohrbough** [comment]
Moved Issue to https://github.com/cerner/terra-dev-site/issues/54.
