### ISSUE TITLE
[Radio, Checkbox, Time Input]: Document the need to mock window.matchMedia for jest tests

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-core#1243]
# Issue Description

After consuming terra-form-radio and terra-form-checkbox, our jest tests started to fail with this error:
```
TypeError: window.matchMedia is not a function
      at Object.isConsideredMobileDevice (node_modules/terra-form-radio/lib/_RadioUtil.js:8:17)
      at Radio (node_modules/terra-form-radio/lib/Radio.js:140:131)
```
The file is here: [_RadioUtil.js](https://github.com/cerner/terra-core/blob/master/packages/terra-form-radio/src/_RadioUtil.js#L3).

The same issue exists with CheckboxUtil as well.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [X] Other

## Expected Behavior

Our jest tests should not fail when consuming terra-form-radio/terra-form-checkbox

## Steps to Reproduce

1. Consume radio/checkbox
2. Run jest test on a component that uses radio/checkbox

## Environment

* Component Version: terra-form-radio (2.0.0), terra-form-checkbox (2.0.0)
* Browser Name and Version: All
* Operating System and version (desktop or mobile): All

**Comment by PseudoFaux** [comment]
After a slight bit of investigation and discussion with @yuderekyu, we have found that there is a way to get around the issue by mocking out window.matchMedia like so:
```
window.matchMedia = () => ({ matches: true });
```
like you have in your [jestsetup.js](https://github.com/cerner/terra-core/blob/master/jestsetup.js#L22) file. 

Is this something that we, as a consumer, should be doing on our end?

**Comment by bjankord** [comment]
Yes, we'd recommend updating your `jestsetup.js` file to mock `window.matchMedia` with the code @yuderekyu provided.

**Comment by PseudoFaux** [comment]
Is it possible to add that recommendation to the documentation of those components? It would surely be helpful for other consumers to know that you _must_ mock window.matchMedia for jest tests not to fail.

**Comment by bjankord** [comment]
@PseudoFaux Would you be up for sending a PR?

**Comment by prachigotkhindikar1** [comment]
@PseudoFaux / @bjankord, checking to see if a PR has already been made to update the doc.  If not, I would be happy to make one. Thanks!

**Comment by bjankord** [comment]
@prachigotkhindikar1 Feel free to send over a PR!

**Comment by prachigotkhindikar1** [comment]
@bjankord, Please review https://github.com/cerner/terra-core/pull/2532

**Comment by bjankord** [comment]
Looks good, just need to update the changelog files.
