### ISSUE TITLE
Update react-router to v4

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#125]
# Issue Description
React-router 4.0.0 stable was recently released. Currently we are using v3.0.2. We should evaluate work needed to get us on v4

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Site is updated to use react-router v4.

## Current Behavior
Site uses react-router v3.

**Comment by emilyrohrbough** [comment]
[React Router v4 Unofficial Migration Guide](https://codeburst.io/react-router-v4-unofficial-migration-guide-5a370b8905a)
