### ISSUE TITLE
Misleading Documentation on Button Variants

### ISSUE THREAD

**Issue by dylan-sftwr** [cerner/terra-core#1251]
# Issue Description

Currently, on the [doc site page for Button](http://engineering.cerner.com/terra-core/#/site/button), there exists a `Variant` subsection below the props table that displays the different types of button variants.

#### Valid Button Variants:
* `ButtonVariants.NEUTRAL`
* `ButtonVariants.EMPHASIS`
* `ButtonVariants['DE-EMPHASIS']`
* `ButtonVariants.ACTION`
* `ButtonVariants.UTILITY`

In the visuals, however, there are **six** different visuals for possible button `variant`s. I propose we remove the outlined visual below as it can be misleading to consumers making them think that there is a non-existent sixth variant type.
![image](https://user-images.githubusercontent.com/17390173/36208890-db0eee9a-115f-11e8-9059-ec974c30011f.png)
**Note:** The outlined visual is really only a `Button` instance marked as `variant={ButtonVariants.ACTION}` and provided the `isIconOnly` prop.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior

I would expect only the valid `ButtonVariants.X` variants (detailed above) to be displayed under the `Variants` examples section on the site.
## Current Behavior

N/A

**Comment by bjankord** [comment]
I'm open to a PR to resolve this.

**Comment by dylan-sftwr** [comment]
@bjankord – I'll pick it up later today if no one has by then

**Comment by emilyrohrbough** [comment]
@dylan-sftwr I agree, the documentation is a bit misleading. That is my bad! When I was working on the button uplift, the icon-only for the action variant had a different styling, so I did this to verify they were build correctly.
