### ISSUE TITLE
Use Terra-Site v2.0.0

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1254]
# Issue Description
Uplift to use terra-site v2.0.0. With this change, terra-clinical-site will no longer be needed and will move to be a private package.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
This is blocked by:
- [ ] https://github.com/cerner/terra-site/issues/22

**Comment by emilyrohrbough** [comment]
This PR is now blocked by:
- #1264 Tag Component
- #1279 Avatar Component 
- #1304 Form Field Component
- #1270 Section Header Component
- #1286 Action Header Component

**Comment by bjankord** [comment]
While we are still waiting for action header PR, I think we can go ahead and get a PR out for this work now @emilyrohrbough
