### ISSUE TITLE
Remove PropsTable Scripts

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1256]
# Issue Description
Once terra-ui.com is uplifted to use terra-site v2.0.0 this removes the need to create add and create the props-table markdown files for each component.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by emilyrohrbough** [comment]
Blocked by:
- [ ] https://github.com/cerner/terra-ui.com/issues/57

**Comment by bjankord** [comment]
This has been released in today's release.
