### ISSUE TITLE
Enhance i18n-plugin for Terra-site v2.0.0

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1258]
# Issue Description
The terra-site v2.0.0 breaks the assumed translation directory structure of the terra-i18n plugin. This need to be addressed to work in the following scenarios:
- Find translations in a repo
- Find translations in a mono-repo
- Find translations in a repo pulling in repos

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [x] Bug
- [ ] Other

## Current Behavior
This breaks the expected pattern and results in no aggregated translations.

**Comment by bjankord** [comment]
Resolved in #1327
