### ISSUE TITLE
Remove Props-table Bin Executable

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1259]
# Issue Description
Once terra-ui.com is uplifted to use terra-site v2.0.0 this removes the need to create add and create the props-table markdown files for each component. Thus, the prop-table markdown script can be removed from the package.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
Blocked by:
- [ ] https://github.com/cerner/terra-ui.com/issues/57

**Comment by Blackop778** [comment]
In #1301 it was decided that the script will be kept in incase someone else was using it
