### ISSUE TITLE
[spike] Explore ways to enable live-reload of components in non-prodcution environment

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1260]
# Issue Description
We switched our example code from referencing src files in https://github.com/cerner/terra-core/pull/165 to resolve https://github.com/cerner/terra-core/issues/98 

The benefit of this was it allowed us to test the examples in the same format a consumer would use them, (CJS module), which is good. With the change though, we lost the ability to live reload. This makes developing more cumbersome, (need to compile code manually to see changes), and its proven confusing to new contributors.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Document and explore options to keep testing the commonJS distributed code, while enabling live reload of ES6+ code in the local development environment.

**Comment by bjankord** [comment]
# Possible option

Using `webpack -p` will automatically invoke setting `process.env.NODE_ENV="'production'"`. We can use the absence of this to detect that we are in a development environment. Webpack also includes a [resolve matcher for a package.json's main field](https://webpack.js.org/configuration/resolve/#resolve-mainfields). It uses this to determine which "main" fields to resolve. By default, `resolve.mainFields` is equal to `["browser", "module", "main"]`.
If a package.json includes a browser or module key, webpack will resolve that instead of the main key.
For example. With the following import code:

```js
import Button from 'terra-button';
```

And the following properties in the terra-button package.json

```js
{
  ...
  main: 'lib/Button.js',
  module: 'src/Button.jsx',
  ...
}
```

This will resolve to the file in the `module` property. The `module` property takes precedence here because it comes before `main` in webpack's default `resolve.mainFields`.

For our case of wanting to test the commonJS distributed code, while enabling live reload of ES6+ code in the local development environment, I think we can use a combination of these.

In our PR deployments and code that is run in tests / CI, we run webpack with the `-p` flag. For local development, we run wepack without the `-p` flag.

Using that we can add a check like:

```js
mainFields: process.env.NODE_ENV === 'production' ? [ 'browser', 'module', 'main'] : ['terraSrc', 'browser', 'module', 'main'],
```
This would use the default array webpack uses to resolve mainFields in production, and if we are running our webpack config in non-production, we'd add a custom entry which would resolve a custom property added to our package.json's `terraSrc`.

This requires adding the following to all package.json files

```js
{
  ...
  main: 'lib/Button.js',
  "terraSrc": 'src/Button.jsx',
  ...
}

**Comment by bjankord** [comment]
# Possible Option
Another possible solution I'm looking into is using [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver)
It looks like you can set [babel-env](https://babeljs.io/docs/usage/babelrc/#env-option) similar to webpack so we could use the module resolver only in a development env. Example of development and production configs for babel: https://gist.github.com/rmoorman/94eeed830942758e218d92f15ce58d88


Here's an example of what this might look like for the `.babelrc` file.
```js
{
  "presets": ["es2015", "react"],
  "plugins": ["transform-object-assign", "transform-object-rest-spread"],
  "env": {
    "development": {
      "plugins": [
        ["module-resolver", {
          "alias": {
            "terra-button": "./packages/terra-button/src/Button.jsx",
          }
        }]
      ]
    }
  }
}
```
We would need an entry for every terra package.

**Comment by emilyrohrbough** [comment]
An option would be to offload webpack aliasing to the terra-dev-site. Here we could simply iterate through a repositories 'packages' if the directory exists and add an alias for each component(s). Then, we could add a process env to our test scripts to indicate when want to reference `src` vs `lib`.

**Comment by bjankord** [comment]
terra-dev-site provides live-reload. If need to explore additional live-reloading, we can come back and revisit this issue.
