### ISSUE TITLE
Create new private subcomponent for Utility Close icon button 

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1261]
# Issue Description
Create a new private subcomponent for Utility Button for a Close button to be re-used in Popup, Menu, Select, Dialog, etc., components that needs the Close "X" icon built in, so that a it can be included more simply and avoid needing to provide themeable icons for each implementation. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The way the Utility Button currently does with a X icon already provided as the content and i18n with the word "Close" as the title/aria details. (will require standard translations to be included with button)

**Comment by bjankord** [comment]
Talked through this in our recent leadership sync. Planned to leave the code as is to allow for flexible theming if needed in regards to the close icons in various components.
