### ISSUE TITLE
Tag Component

### ISSUE THREAD

**Issue by paku-sruti** [cerner/terra-core#1264]
# Issue Description
Create a new Tag component with OCS theming.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by paku-sruti** [comment]
# Technical Design: `terra-tag`

## Summary:
This is a new component that allows the consumer to display a tag.

## Expected behavior:
Should be able to give the component an icon and a text.

## Responsiveness:
The content within the tag does not change. The width of the tag is dictated by the length of the content.

## I18N / Bi-directionality:
These changes should make no changes to the existing ltr/rtl functionality.

## Interaction States
Unselected, Selected, Hover and Keyboard focus will be available for this tag.

## React Props:
| Props | Type | Default | Description |
| ----------- | ----- | --------- | --------------------------------------------------------- |
| `href` | string | undefined | Sets the href for the label of the tag. |
| `icon` | element | undefined | The icon to render. |
| `text` | string | undefined |  Sets the text of the tag. |
| `isClose` | bool | false | Whether or not the Tag should have a close icon. |

## Themeable Styles:
* Background color
* Border style
* Border color
* Font size
* Font weight
* Font Family
* Padding
* Height

**Comment by ChaseSinclair** [comment]
Can you rename 'isClose' to 'isClosed'?

**Comment by paku-sruti** [comment]
@ChaseSinclair Updated it.

**Comment by ChaseSinclair** [comment]
From looking at the callouts, it appears that 'text' should be a required prop.

**Comment by paku-sruti** [comment]
Added a column 'Required' .

**Comment by ChaseSinclair** [comment]
+1

**Comment by ChaseSinclair** [comment]
Actually, would 'isClosable' be a more appropriate name since the prop is really indicating if you can click the X on the tag?

**Comment by bjankord** [comment]
@paku-sruti For the close prop, let's call it `onClose`. This aligns with how we've handled this use case in the [action header](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-action-header/src/ActionHeader.jsx#L25-L29). The `onClose` prop should take a callback function for when the close button is clicked. If this is set, the close icon will display.

**Comment by dm123455** [comment]
1. The close button I think needs to be themable. Please double check with Chris.
2. Would the text inside the tag wrap or it needs to show the entire text passed in? Does there need to be some truncation rules?
3. Add accessibility for tags, when we tab it needs to first access the icon and the text part and on  tabbing second it needs to focus on the close icon(if present).

**Comment by paku-sruti** [comment]
@dm123455  According to the [callouts](zpl.io/2Ewmqke) it says the tag will adjust width to fit the content. 

Do we want the icon to be clickable too or just the text needs to be clickable?

**Comment by paku-sruti** [comment]
@neilpfeiffer Do we want the Close icon in the tag component to be themable?

**Comment by dylan-sftwr** [comment]
+1 on @dm123455 's comment about the close icon needing to be themeable.

**Comment by dylan-sftwr** [comment]
@paku-sruti I believe that the configurable (non-closing) icon is supposed to remain centered vertically when text **wraps**, as it doesn't truncate, according to the callouts

**Comment by dm123455** [comment]
I would think the icon and the text together needs to be clickable.

**Comment by dm123455** [comment]
Also @paku-sruti this [example](https://github.com/cerner/terra-core/blob/master/packages/terra-dialog/src/Dialog.jsx#L42) might help with the onClose implementation part.

**Comment by dylan-sftwr** [comment]
@paku-sruti I know in standard html, we have a `tabindex` option to control tabbing order, and react has [its own concept of this](https://reactjs.org/docs/dom-elements.html), but I don't know how this is handled when a component specifying either of these properties is placed in the context of a page with other components that may or may not have the same props specified. This might require a little bit of a spike to figure out. I would suggest googling / looking through terra for examples.

**Comment by samvaity** [comment]
For the theme-able property `font-family`, I think we should confirm this as I remember on the buttons story Emily had mentioned to me that we do not want to be setting `fonts` on component level and they should rather be inherited from `terra-base`.

**Comment by dylan-sftwr** [comment]
I might set the default value of the `text` prop as `''`, not undefined.

**Comment by dylan-sftwr** [comment]
@samvaity @paku-sruti so I heard from @neilpfeiffer yesterday, `font-family` is **NOT** something that's supposed to be controllable at this level, UX designers have been throwing it on callouts due to an ambiguity in dev's vs designer's ideas of what's themeable. `font-family` should always be set to inherit!

**Comment by paku-sruti** [comment]
@bjankord Updated the onClose to a call back function.

**Comment by paku-sruti** [comment]
@dylan-sftwr and @samvaity Removed the font family from themable variables.

**Comment by paku-sruti** [comment]
@dm123455 Added the accessibility.

**Comment by dylan-sftwr** [comment]
@dm123455 i'm wondering if we should have an `aria-label` or something similar for the text for our friends with screen readers?

**Comment by samvaity** [comment]
Also, is there a use-case in which we have any other `border-style` ?

**Comment by dylan-sftwr** [comment]
@samvaity it's mentioned in the callouts

**Comment by samvaity** [comment]
@dylan-sftwr that way even `font-family` is mentioned....

**Comment by neilpfeiffer** [comment]
Add `box-shadow` as themeable variable, needed for focus style for terra default theme (page is missing and need to provide)

**Comment by paku-sruti** [comment]
Updated the text in accessibility, added box shadow in themable variables,  added a prop to set the theme of the tag, added close icon to be themable.

**Comment by dylan-sftwr** [comment]
After a conversation with Neil, I think we're going to want this to support bidirectional functionality, i.e. the close icon would be able to be on the left and the configurable icon on the right in a rtl locale

**Comment by dm123455** [comment]
@paku-sruti light and normal theme not dark for the theme prop.

**Comment by samvaity** [comment]
Also, Since this component is very similar to button component-ish. 

When considering theme-ing and since we have the background color to be theme-able, shouldn't the color of the text also be theme-able?

**Comment by paku-sruti** [comment]
@samvaity In the callouts the font-color/text-color is mentioned under the Styles:Controlled.

**Comment by dm123455** [comment]
+1

**Comment by dylan-sftwr** [comment]
nit: change the text in the `Default` column of the props table for string types from the backtick to a `'`.

**Comment by dylan-sftwr** [comment]
@dm123455 , with `light` and `normal`, for the `theme` prop, are you describing the tag, or the context in which they'd be getting used? `normal` to me sounds like you're describing the tag appearance, rather than the context in which it would be getting used. 

@paku-sruti **If** that's the case, I think the `Default` value of the `theme` prop would be `normal`, not `light`.

@paku-sruti & @dm123455, if I'm able to be confused about this, I'm sure others might too... rather than `('light' || 'normal')`, could we do something like `( ( 'default' || 'normal') || 'inverse')` ? I think doing so better describes the appearance of the tags without the ambiguity.

**Comment by dylan-sftwr** [comment]
@dm123455 I know we're only doing the darker appearance of the tags for right now, but have we thought about how the configurable icon should be passed? Meaning, is it up to the user to ensure that their usage of the `theme` prop and their supplied `icon` prop appear appropriately together? Or is there some sort of styling to the `icon` that we'll have to do under the hood as a part of this component?

**Comment by paku-sruti** [comment]
@dylan-sftwr As we spoke offline updated the theme to accept `normal` value.

**Comment by JakeLaCombe** [comment]
+1

**Comment by dylan-sftwr** [comment]
+1

**Comment by ChaseSinclair** [comment]
+1

**Comment by bjankord** [comment]
+1 on tech design

**Comment by PaulSolDev** [comment]
JIRA created
