### ISSUE TITLE
Decide on 'no-multi-assign' eslint rule

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1265]
# Issue Description
Currently in our .eslintrc file we have turned off 

```
"no-multi-assign": "off" // TODO: Decide if we want to turn this on. It was turned on in eslint-config-airbnb-base v14.1.0
```

There is an inline TODO comment that should be addressed at some point.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by mjhenkes** [comment]
https://eslint.org/docs/rules/no-multi-assign

**Comment by bjankord** [comment]
Reached agreement in war room turn this rule on and delete the code that turns it off.
