### ISSUE TITLE
Slide Panel Tab Order

### ISSUE THREAD

**Issue by noahbenham** [cerner/terra-core#1272]
# Issue Description
We're accessibility testing our application and realized Slide Panel tab order is inconsistent. Our design tabs down the right side before the left. This probably only affects `panelPosition="end"`.

Should these DOM elements be rendered in opposite order if `panelPosition` is `end`?

![screen shot 2018-02-21 at 10 33 33 am](https://user-images.githubusercontent.com/6981195/36492722-6e204664-16f3-11e8-9a07-1180cd7b3732.png)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

When tab is pressed, tab order should proceed down the left panel before transferring to the right.

## Current Behavior

The tab key follows down the right side before the left.

## Steps to Reproduce

```jsx
<SlidePanel
  mainContent={this.renderItemView()}
  panelContent={this.renderDetailView()}
  panelBehavior="squish"
  panelPosition="end"
  panelSize="large"
  isOpen={this.props.slidePanelState === SlidePanelStateTypes.DETAIL_LIST}
  fill
/>
```

## Environment

* Component Version: `1.16.0`
* Browser Name and Version: Chrome `64.0.3282.167`
* Operating System and version (desktop or mobile): **Any**; macOS `10.12.6 (16G1212)`

**Comment by mjhenkes** [comment]
@noahbenham could you attend our office ours next week @4:00 to discuss this issue? We will need to see the behavior on your app to diagnose.

**Comment by noahbenham** [comment]
@bjankord since this was closed, was it resolved?

**Comment by mjhenkes** [comment]
There have been no comments since march first, and I can't remember if we diagnosed the issue in office hours. Are you still seeing the issue?

**Comment by noahbenham** [comment]
Yeah, I discussed with @dkasper-was-taken since I didn't see you. This is easily reproducible by tabbing through a slide panel with position end. Elements on the right will first be selected, followed by the left which is counterintuitive.
