### ISSUE TITLE
LoadingOverlay Spinner Should Be Bidi

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1274]
# Issue Description
The LoadingOverlay icon should be bidirectional. We should add `isBidi` to the [loading spinner]( https://github.com/cerner/terra-core/blob/master/packages/terra-overlay/src/LoadingOverlay.jsx#L67).

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by alecrowen** [comment]
Needs more design input. @mmalaker will follow up.

**Comment by mmalaker** [comment]
Did some research on this. The spinner should not change direction in RTL. Per the [material.io](https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-rtl-mirroring-guidelines) guidelines: "While the linear representation of time is mirrored in RTL, the circular direction of time is not. Clocks still turn clockwise for RTL languages. A clock icon or a circular refresh or _progress indicator with an arrow pointing clockwise_ should not be mirrored."
