### ISSUE TITLE
PopupContent does not clone a close indicator onto a non-automatic sized child.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1278]
# Issue Description
There is no indicator as to when a popup presenting with header disabled and not using automatic sizing, that it needs to present it's own close button. Either a flag or the requestClose function should be cloned onto the child content.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
When the user chooses to disable the popup header, and is not using automatic sizing, there is no way to indicator to the component that it needs to inject a close button when it's fullscreen.

**Comment by saedar** [comment]
Assuming I am understanding this change, we need to add the onRequestClose function to this clone block: https://github.com/cerner/terra-core/blob/master/packages/terra-popup/src/_PopupContent.jsx#L134..L143.

**Comment by dkasper-was-taken** [comment]
Since the popup is a controlled component the consumer already has access to their own onRequestClose function and might already be passing it to their content for their own on clicks, so more likely this would be another boolean passed down to the content if the component is bound on both sides and the isHeaderDisabled prop is set to true regardless if they are using auto sizing. Not really sure what the best name for the prop would be.

**Comment by saedar** [comment]
Is that something a consumer would set or something we would calculate based on the other props provided?

**Comment by dkasper-was-taken** [comment]
If the consumer set the isHeaderDisabledProp on the Popup, and the _PopupContent's internal logic calculates isFullScreen, we'd clone a prop onto the child content along the lines of isFullScreen or closeButtonRequired, etc.
