### ISSUE TITLE
[terra-toggle] Use latest react-animate-height

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1281]
# Issue Description
The toggle component uses the react-animate-height dependency. This dependency has been updated to [support React 16](https://github.com/Stanko/react-animate-height/issues/28), however its peer dependencies does not indicate this. [This issue](https://github.com/Stanko/react-animate-height/issues/40) has been logged to open up the peer dependencies to accept React 15 || 16. Once this is issue is resolved we should update to use the latest version. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Current Behavior
It appears we are using an 3rd party dependency that does to support React 16.

**Comment by bjankord** [comment]
It looks like our use of `^0.9.5` for react-animate-height only pulls in the latest  patch version under the `0.9` release. I think this is odd npm behavior related to the major version being 0. Looks like to get the latest minor release under a major release using 0 as the major version number, we need to set the dependency version to `^0`

**Comment by bjankord** [comment]
Released in terra-toggle@2.2.0

**Comment by emilyrohrbough** [comment]
Technically this will not resloved the error we are see until https://github.com/Stanko/react-animate-height/pull/43 is merged and released.
