### ISSUE TITLE
[time-input] Bad Translations

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1283]
# Issue Description
The french translations are still in english. See https://github.com/cerner/terra-core/blob/62bd1ee6da469c1c3fffcebcc41324aee24d2943/packages/terra-time-input/translations/fr-FR.json.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
To add to it, it looks like we have a new translation as well? https://github.com/cerner/terra-core/blob/62bd1ee6da469c1c3fffcebcc41324aee24d2943/packages/terra-time-input/translations/nl.json

**Comment by emilyrohrbough** [comment]
Looking at the [fr.json](https://github.com/cerner/terra-core/blob/62bd1ee6da469c1c3fffcebcc41324aee24d2943/packages/terra-time-input/translations/fr.json) file, only half of the translations are in french, other rest are in english.

**Comment by benbcai** [comment]
In the [fr.json](https://github.com/cerner/terra-core/blob/master/packages/terra-time-input/translations/fr.json) file, `minutes` in French is actually the same as in English.

**Comment by emilyrohrbough** [comment]
@benbcai no kidding! I would not have thought that.

**Comment by saedar** [comment]
It looks like the incorrect translation files got pulled in. If you check the internal issue with the translation team, you can see the correct values.

**Comment by saedar** [comment]
Spoke with @bjankord: We are going to copy the translations from the language-specific files to the locality-specific files. In the event that this results in an awkward translation, we can request new ones at that time.
