### ISSUE TITLE
Scrollbar on Chrome (Windows machine) is covering up modal content

### ISSUE THREAD

**Issue by AnthonyRoss** [cerner/terra-core#1290]
# Issue Description
The scrollbar on Chrome browsers on Windows 10 computers are covering up some of the Modal content.
![screen shot 2018-02-26 at 10 43 08 am](https://user-images.githubusercontent.com/8669582/36682895-dde17616-1ae1-11e8-85cd-297f1c702732.png)

This is not the case when using IE:
![screen shot 2018-02-26 at 10 43 44 am](https://user-images.githubusercontent.com/8669582/36682929-f0fac7c0-1ae1-11e8-8e8c-af17bd264cc2.png)

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The scrollbar shouldn't cover up anything that is listed in the content of the modal

## Current Behavior
Currently, the scrollbar is covering up a few pixels of the actual modal content instead of adding space to the other side in Chrome only (Windows machines only).

## Steps to Reproduce
1. Create a Modal that is scrollable with action buttons at the bottom.
2. Open the Modal in Chrome on a PC and shrink the browser window.

## Environment
* Component Version: terra-moda": 1.19.0
* Browser Name and Version: Chrome 63.0.3239.132 
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by bjankord** [comment]
I wonder if this may be an issue to how the `box-sizing` style is set on the element with the scrollbar, it may be set to `border-box`. We may want to test switching this to `content-box`.

**Comment by saedar** [comment]
@bjankord Maybe. I checked the [scrollable modal](http://engineering.cerner.com/terra-core/#/tests/modal-tests/scrollable-true) in my VM and it appears to be working fine.

Note: Need to try in Win10. My VM is Win7 running up-to-date Chrome.

**Comment by bjankord** [comment]
@Nino55N Does the scollbar render the same when you have a mouse hooked up to your computer versus when you don't have a mouse plugged into your computer. We've seen odd rendering of scrollbars with that before, not sure if it is what its triggering the issue here.

**Comment by Nino55N** [comment]
@bjankord We tired without a mouse as well but still no luck :/

**Comment by Nino55N** [comment]
Also @bjankord I should have put how we are using the modal.
We are using several different components inside which may cause the issue:
```
<Modal>
  <Card>
    <Card.Body>

    </Card.Body>
    <Arrange>
    -- buttons go here
    </Arrange>
  </Card>
</Modal>
```

**Comment by bjankord** [comment]
Ah, we just released [terra-dialog](https://www.npmjs.com/package/terra-dialog). I'd recommend using this component nested inside of modal rather then the card component. You can see an example of nesting the dialog in the modal [here](https://github.com/cerner/terra-core/blob/master/packages/terra-site/src/examples/modal/DefaultWithDialog.jsx). This example is rendered in the doc site [here](http://engineering.cerner.com/terra-core/#/site/modal). If you scroll down that page and then click on the button to open the modal under the Default Modal w/ Dialog section, you'll see the example.

**Comment by Nino55N** [comment]
@bjankord We can certainly try, is the terra-dialog component recommended over the card component? Or is the card component going to be deprecated?

**Comment by saedar** [comment]
The Card is fine. It is just that the Dialog is designed to specifically be consumed inside a modal to provide header, body, and footer. Card is generally consumed in popovers or as its own thing.

**Comment by AnthonyRoss** [comment]
@bjankord I was able to replicate this on my mac when I have a mouse plugged in. So I think you are correct with that estimation, do you know of a remedy with this?

**Comment by BenBoersma** [comment]
I could not recreate the issue with Terra-Abstract-Model since Terra-Modal is now deprecated. 

Because of this I am closing the issue. I suggest uplifting to Terra-Abstract-Model. If the issue persists please open a new issue.
