### ISSUE TITLE
Replace Nightwatch Tests with Webdriver.io Tests

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1302]
# Issue Description
Remove the existing nightwatch tests and replace them with webdriver.io tests. This has been done for some components but these need to happen for the remaining components:

Checked off means done or claimed

- [x] terra-content-container
- [x] terra-demographics-banner
- [x] terra-divider
- [x] terra-dynamic-grid
- [x] terra-form-checkbox
- [x] terra-form-field
- [x] terra-form-textarea
- [x] terra-form-select
- [x] terra-heading
- ~terra-hookshot~ Migrated to terra-framework https://github.com/cerner/terra-framework/pull/128
- [x] terra-icon
- [x] terra-image
- [x] terra-profile-image
- [x] terra-progress-bar
- [x] terra-props-table
- ~terra-slide-panel~ Migrated to terra-framework https://github.com/cerner/terra-framework/pull/131
- [x] terra-spacer
- [x] terra-status
- [x] terra-text
- [x] terra-toggle
- [x] terra-grid
- [x] terra-list
- [x] terra-responsive-element
- [x] terra-signature
- [x] terra-slide-group
- [x] terra-table
- [x] terra-toggle-button
- [x] terra-abstract-modal
- [x] terra-date-picker
- [x] terra-menu
- [x] terra-search-field

## Remaining Components
- [x] terra-data-time-picker
- [x] terra-embedded-content-consumer

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by emilyrohrbough** [comment]
Be sure to specify terra-defined viewports in the test setup: see https://github.com/cerner/terra-core/issues/1444

**Comment by msaikaushik1992** [comment]
picking up terra-status for replacing nightwatch with wdio tests.

**Comment by bjankord** [comment]
picking up content container tests

**Comment by bjankord** [comment]
picking up the demographics banner tests

**Comment by bjankord** [comment]
picking up the dynamic grid

**Comment by bjankord** [comment]
picking up the form field

**Comment by Blackop778** [comment]
I'll grab content container

**Comment by bjankord** [comment]
@Blackop778 There is a PR out for content container: https://github.com/cerner/terra-core/pull/1468
terra-heading or terra-text would be another good one to pick up instead.

**Comment by Blackop778** [comment]
I'll grab props table. terra-heading and terra-text don't actually test anything with nightwatch.

**Comment by emilyrohrbough** [comment]
@Blackop778 The nightwatch tests fir terra-heading and terra-text aren't great, but that is because these components only apply css, which we don't want to test for as these values change with browsers and browser versions. So, the urls are hit to ensure the page loaded with the content, however we do want screenshots of these examples to ensure they render as expected visually.

**Comment by msaikaushik1992** [comment]
picking up responsive element.

**Comment by msaikaushik1992** [comment]
picking up terra-profile-image.

**Comment by msaikaushik1992** [comment]
picking up form-field

**Comment by JakeLaCombe** [comment]
Picking up time-input

**Comment by saedar** [comment]
Picking up icon.

**Comment by StephenEsser** [comment]
terra-form-select was uplifted with: https://github.com/cerner/terra-core/pull/1501

**Comment by Blackop778** [comment]
Picking up toggle button

**Comment by msaikaushik1992** [comment]
picking up data-grid

**Comment by tomleewu** [comment]
picking up list

**Comment by JakeLaCombe** [comment]
Picking up terra-grid

**Comment by Blackop778** [comment]
Picking up slide group

**Comment by emilyrohrbough** [comment]
@StephenEsser Has updated responsive element to wdio tests in his PR #1547

**Comment by msaikaushik1992** [comment]
picking up terra-search

**Comment by tomleewu** [comment]
picking up terra-abstract-modal

**Comment by emilyrohrbough** [comment]
Picked up terra-menu

**Comment by msaikaushik1992** [comment]
Note: terra-search-field  is going to be used in future in another new component (filter-view) based on feedback from UX. This blocks on how to go about search-fields accessibility issues of web driver tests.

**Comment by tomleewu** [comment]
picking up terra-date-picker

**Comment by Blackop778** [comment]
Picking up terra-search-field

**Comment by JakeLaCombe** [comment]
Picking up textarea

**Comment by JakeLaCombe** [comment]
I'll go ahead and remove the markdown tests as part of textarea since it's small

**Comment by saedar** [comment]
I'll grab terra-embedded-content-consumer

**Comment by JakeLaCombe** [comment]
I'll take date-time-picker

**Comment by bjankord** [comment]
This has now been resolved. Thanks to everyone who helped contribute on this issue!
