### ISSUE TITLE
Utility to expose standardized breakpoints

### ISSUE THREAD

**Issue by JoeJennings** [cerner/terra-core#1309]
# Issue Description
It would be good to have a utility that provides access to the defined breakpoints.  Today this file seems to define them: https://github.com/cerner/terra-core/blob/master/packages/terra-responsive-element/src/breakpoints.scss

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
A utility could be imported to provide access to the enumerated standardized breakpoints.

## Current Behavior
Doesn't exist to my knowledge outside the terra-responsive-element

## Use Case
In the React Chart summary a user selects on a components section subheader (Conditions -> Nursing subheader or an Allergies -> View More row) to access the profile view of the component.  At larger breakpoints (browser, iPad) the profile opens leveraging the slide-panel-manager and displays the Master and Detail view of the profile/view_more view.  At smaller breakpoints (iPhone) the profile view opens and the detail view should not open as it would display over the master side of the slide panel.  Leveraging a response-element in this scenario feels like adding a lot of un-needed overhead.  A utility that provides access to the standardize breakpoints seems reasonable.

**Comment by bjankord** [comment]
Resolved in #2018
