### ISSUE TITLE
[time-input] Remove Unsupported Translation Files

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1311]
# Issue Description
At this point we only support these i18n languages: `['ar', 'en', 'en-US', 'en-GB', 'es', 'es-US', 'es-ES', 'de', 'fi-FI', 'fr', 'fr-FR', 'pt', 'pt-BR']`

In the time-input component, it seems a couple unsupported translation files were added. These should be removed until these locales are supported:
- [nl](https://github.com/cerner/terra-core/blob/62bd1ee6da469c1c3fffcebcc41324aee24d2943/packages/terra-time-input/translations/nl.json)
- [sv](https://github.com/cerner/terra-core/blob/62bd1ee6da469c1c3fffcebcc41324aee24d2943/packages/terra-time-input/translations/sv.json)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by bjankord** [comment]
We've recently added nl and nl-BE locales and will be adding sv in the near future.

**Comment by yuderekyu** [comment]
This a non-issue then?
