### ISSUE TITLE
terra-spacer support for shorthand properties

### ISSUE THREAD

**Issue by dylan-sftwr** [cerner/terra-core#1314]
# Issue Description

I would like to see the functionality for supplying margin and padding shorthand as props.

I'd like to get others' thoughts on this, as if this is something that people see value in, I'd be happy to make the contribution myself.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Rather than having to do something like
```jsx
<Spacer marginTop="small" marginRight="medium" marginBottom="small" marginLeft="medium">
 {/* children */}
</Spacer>
```
I would like the API to similarly mirror the normal `margin` and `padding` CSS API where this is still valid, any of the following could be used to achieve an equivalent outcome
```jsx
<Spacer margin="small medium small medium">
 {/* children */}
</Spacer>

<Spacer margin="small medium small">
 {/* children */}
</Spacer>

<Spacer margin="small medium">
 {/* children */}
</Spacer>
```
or, in the case that all four dimensions are supposed to have the `"small"` margin, 
```jsx
<Spacer margin="small">
 {/* children */}
</Spacer>
```

## Current Behavior

See example above.

**Comment by dylan-sftwr** [comment]
# Technical Design: `terra-spacer` Shorthand Properties Enhancement

## Summary:
Uplift the `terra-spacer` component to recognize margin & padding shorthand property entry.

e.g.
```jsx
<Spacer margin="small small">{/* children */}</Spacer>
```

## React Props:
### New
| Props     | Type   | Default | Description                                                                                                                                                                        |
| --------- | ------ | ------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `margin`  | string | `none`  | 1, 2, 3, or 4 of the existing spacing property variables (small, medium, etc.) matching the [standard](https://developer.mozilla.org/en-US/docs/Web/CSS/margin) shorthand format.  |
| `padding` | string | `none`  | 1, 2, 3, or 4 of the existing spacing property variables (small, medium, etc.) matching the [standard](https://developer.mozilla.org/en-US/docs/Web/CSS/padding) shorthand format. |


## Questions
### Conflicting Prop Prececence
I'd be interested in hearing how people would want the internals of the component to behave when supplying both a shorthand, and individual directional `margin` or `padding` prop. I.e., how the component should behave when something like the following is provided.
```jsx
<Spacer marginTop="small" margin="large" /* which would result in a conflicting marginTop="large" rule */>{/* children */}</Spacer>
```

#### Current Thoughts
* I'm planning on implementing a [custom validator](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes) for typechecking both `margin` and `padding`, that will be responsible for checking that 
  1. The correct number of space-deleminted substrings (1-4) are provided.
  2. Each of the aforementioned substrings are one of the [recognized spacing prop variables](https://github.com/cerner/terra-core/blob/master/packages/terra-spacer/src/Spacer.jsx#L8).
  * As part of this custom validator, I can perform the check that a situation in the example above throws an error, or, I can let the situation occur, and throw a warning to the user informing them that they are improperly trying to set `margin` or `padding`, while defining one of the two values (`margin` or `marginTop`) a higher precedence for application `Spacer`.
* Unless anyone has a reason not to, I'm planning on mapping any values passed via `margin` or `padding` to the [existing class rules](https://github.com/cerner/terra-core/blob/master/packages/terra-spacer/src/Spacer.jsx#L93-L100), to avoid creating additional css rule permutations for each of the possible shorthand properties (1 substring, 2 substrings, etc.).

**Comment by dylan-sftwr** [comment]
@bjankord @JakeLaCombe @ryanthemanuel @mjhenkes,

What are your thoughts on the things labeled above under the **Questions** subsection?

**Comment by dylan-sftwr** [comment]
@bjankord @JakeLaCombe @ryanthemanuel @mjhenkes 

bump

**Comment by bjankord** [comment]
@dylan-sftwr I like the custom validator idea. I agree with perform a check in that a situation in the example above and throw an error instead of allowing it to happen. I like the idea of mapping any values passed via margin or padding to the existing class rules.

+1 on tech design.
