### ISSUE TITLE
New Locale NL_BE  to support dutch in belgium

### ISSUE THREAD

**Issue by muruvetri** [cerner/terra-core#1317]
# Issue Description
terra-i18n need support NL or NL_BE for support dutch in beligum

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Support NL or NL_BE as part of this change

## Current Behavior
it supports " 'de' 'es' 'en' 'en-US' 'en-GB', 'fi-FI', 'fr', 'pt' " Based the documentations provided.

This is needed as we looking support this region for new client from this area.

# nl and nl-BE translations added to the following repos:
- [x] terra-core
- [x] terra-framework
- [x] terra-toolkit
- [x] terra-consumer
- [x] terra-clinical

**Comment by jessicaoveys** [comment]
@alecrowen  or @PaulSolDev  can you all comment on whether or not you can deliver this in q2 of 2018?

**Comment by emilyrohrbough** [comment]
@muruvetri @jessicaoveys 
Terra supports [these locales](https://github.com/cerner/terra-core/tree/master/packages/terra-i18n/docs#supported-locales), not just `'de' 'es' 'en' 'en-US' 'en-GB', 'fi-FI', 'fr', 'pt'`.

With the latest changes with Terra Internationalization, you will be able to specify any locale of your choice, even non-supported locales like `NL` and/or `NL_BE`. [Here is the documentation](https://github.com/cerner/terra-core/tree/master/packages/terra-i18n/docs#non-supported-locales) on how one would be able to include non-supported locales while using Terra.

**Comment by jessicaoveys** [comment]
Muru and Trisha – does this mitigate our risk?

**Comment by bjankord** [comment]
We've logged an issue team to start work on providing dutch translations for `nl` and `nl-be`. We'll update terra-core and terra-framework components once the translations are available.

**Comment by muruvetri** [comment]
@bjankord  we were planning to do this as well to mitigate the risk though. but wanted to make sure it is documented and worked on though.

**Comment by bjankord** [comment]
@muruvetri We've added `nl` and `nl-BE` translations to the repos listed above. They'll be available in our next release of those repos.

**Comment by bjankord** [comment]
nl and nl-BE translations have been added to the terra repos, (terra-core, terra-framework, terra-toolkit, terra-consumer, and terra-clinical), and published in this week's release.
