### ISSUE TITLE
Focus styles removed from list items.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1319]
# Issue Description
Browser default focus styling was removed from list items, and no focus style was introduced for the terra default theme. Not sure this was intentional.

It appears this line is the issue:
https://github.com/cerner/terra-core/blob/master/packages/terra-list/src/List.module.scss#L65

If this was intentional we are lacking the box-shadow for focus that ux has set for other components, also the code to enable and disable the focus based on keyboard entry and mouse click.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by bjankord** [comment]
@neilpfeiffer Can we use the focus styles from button and input for this?

**Comment by tbiethman** [comment]
This issue is being worked on alongside #1320 and #1321
