### ISSUE TITLE
List adding static section headers

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1320]
## Summary
- Enhance list to be able to add static section-headers as list-items into each of the existing list components (list, SelectableList, SingleSelectList, MultiSelectList).
- will be fully themeable using existing patterns
- will be similar/related to #1270 stand-alone Section Header

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Screenshot of new static section headers to add (visual details provided separately):

![image](https://user-images.githubusercontent.com/1355485/37095244-eb396990-21da-11e8-9f97-1f6722662d97.png)

----
# Tech Design `terra-list`

##### Sections-API Props:
|Prop Name	|Type	|Is Required	|Default Value	|Description|
|---------- |:------|:-------------:|:-------------:|:---------:|
|title|```string```|optional		|```""```				|The header text of each section.|
|listItems	|```node```	|optional		|```[]```				|The children list items passed to the component.|

##### Selectable-List-Index props
Children of Selectable-List can take array of ```sections```

|Prop Name	|Type	|Is Required	|Default Value	|Description|
|-----------|:-----:|:-------------:|:-------------:|:---------:|
|children	|```node```	|optional		|```[]```				|The children list items or children sections passed to the component.|
|isDivided	|```bool```	|optional		|```false```			|Whether or not the child list items should have a border color applied.|
|disableUnselectedItems|```bool```	|optional	|```false```	|Whether or not unselected items should be disabled. Helpful for enabling max row selection.|
|hasChevrons|```bool```	|optional		|```false```			|Whether or not the child list items has a disclosure indicator presented. The behavior is intended to be used with a single selection style list, as multi selection style list should not perform disclosures.|
|onChange	|```func```	|optional		|```undefined```		|A callback event that will be triggered when selection state changes.|
|selectedIndexes	|```array```	|optional|```[]```			|An array of the currectly selected indexes.|

##### Single-Select-Index Props:
New prop ```hasSections``` has been added to specify, if sections exist or not

|Prop Name	|Type	|Is Required	|Default Value	|Description|
|---------- |:------|:-------------:|:-------------:|:---------:|
|children	|```node```	|optional		|```[]```				|The children list items passed to the component.|
|isDivided	|```bool```	|optional		|```false```			|Whether or not the child list items should have a border color applied.|
|hasChevrons|```bool```	|optional		|```false```			|Whether or not the child list items has a disclosure indicator presented.|
|onChange	|```func```	|optional		|```undefined```		|A callback event that will be triggered when selection state changes.|
|hasSections|```bool```	|optional		|```false```			|Whether or not the child items should be displayed in sections with header and list of elements.|
##### Multi-Select-Index Props
New prop ```hasSections``` has been added to specify, if sections exist or not

|Prop Name	|Type	|Is Required	|Default Value	|Description|
| --------- |:-----:|:-------------:|:-------------:|:---------:|
|children	|```bool```	|optional		|```false```			|Whether or not the child list items should have a border color applied.|
| onChange	|```func```	|optional		|```undefined```		|A callback event that will be triggered when selection state changes.|
|maxSelectionCount|```number```|optional|```undefined```|The maximum number of list items that can be selected.|
|hasSections|```bool```	|optional		|```false```			|Whether or not the child items should be displayed in sections with header and list of elements.|

## Themeable Styles:
will be fully themeable using existing patterns

## Responsiveness:
Upon interaction, the state of selection needs to be updated.

## Interaction States:
Should function the same as the exisiting terra-list with ```SingleSelectList``` and ```MultiSelectList``` across the sections and remember the state across the section.

## Accessibility:
Should have the standard accessibility features like keyboard navigation and selection across multiple sections.

## i18N / Bi-directionality:
This component must be able to be rendered with its mirror-imaged equivalent for rtl locales.

#### MultiSelect Sections
```
const MultiSelectSections = () => (
  <MultiSelectList hasSections>
    <MultiSelectList.Section
      title="Header 1"
      listItems={[
        <MultiSelectList.Item isSelectable content={<p>test1</p>} key="123" />,
        <MultiSelectList.Item isSelectable content={<p>test2</p>} key="124" />,
        <MultiSelectList.Item isSelectable content={<p>test3</p>} key="125" />,
      ]}
    />
    <MultiSelectList.Section
      title="Header 2"
      listItems={[
        <MultiSelectList.Item isSelectable content={<p>test1</p>} key="126" />,
        <MultiSelectList.Item isSelectable content={<p>test2</p>} key="127" />,
        <MultiSelectList.Item isSelectable content={<p>test3</p>} key="128" />,
      ]}
    />
  </MultiSelectList>
);
```
#### Single Select Sections
```
const SingleSelectSections = () => (
  <SingleSelectList hasSections>
    <SingleSelectList.Section
      headerContent="Header 1"
      listItems={[
        <SingleSelectList.Item isSelectable content={<p>test1</p>} key="123" />,
        <SingleSelectList.Item isSelectable content={<p>test2</p>} key="124" />,
        <SingleSelectList.Item isSelectable content={<p>test3</p>} key="125" />,
      ]}
    />
    <SingleSelectList.Section
      headerContent="Header 2"
      listItems={[
        <SingleSelectList.Item isSelectable content={<p>test1</p>} key="126" />,
        <SingleSelectList.Item isSelectable content={<p>test2</p>} key="127" />,
        <SingleSelectList.Item isSelectable content={<p>test3</p>} key="128" />,
      ]}
    />
  </SingleSelectList>
);

```
## Notes: 
Section API is going to take Acordian props while developing [Issue#1321](https://github.com/cerner/terra-core/issues/1321).

Issue#1321 will address the expand collapse functionality, with accordion iconography, decorative icon, notification icon and count.

## Changes:
* ```SingleSelectList``` has a new prop ```hasSections```
* ```MultiSelectList``` has a new prop ```hasSections```
* Children for both ```SingleSelectList``` and ```MultiSelectList``` will take List of ```Section```'s

## Questions:
_(add if needed)_

**Comment by emilyrohrbough** [comment]
Can you call out the changes/additions to the props listed under the Modifications to existing API section?

**Comment by dkasper-was-taken** [comment]
Following war room discussion a larger change to incorporate sections would be preferable.

Prop Updates for SelectableLIst, ListItem, Section:
```
  /**
   * An array of the currectly selected index path arrays.
   * Example section 1 with item 2 and section 2 with item 4: [[1, 2], [2, 4]]
   */
  selectedIndexPaths: PropTypes.arrayOf(PropTypes.array),
```

Logical updates to the newPropsForItem function inside SelectableUtils.
```
const matchingIndexPaths = (index, indexPaths) => {
  const matchingPaths = [];
  for (let i = 0; i < indexPaths.length; i += 1) {
    const indexPath = indexPaths[i];
    if (indexPath[0] === index) {
      matchingPaths.push(indexPath.slice(1));
    }
  }
  return matchingPaths;
};

/**
 * Returns an object containing accessiblity and selectable properties.
 */
const newPropsForItem = (item, index, onClick, onKeyDown, hasChevrons, selectedIndexPaths, disableUnselectedItems) => {
  const matchingPaths = matchingIndexPaths(index, selectedIndexPaths);
  const isSelected = matchingPaths.length > 0;
  const newProps = { role: 'option', 'aria-selected': isSelected, selectedIndexPaths: matchingPaths };
  // Set the isSelected attribute to false for all the items except the items whose index is set to state selectedIndex
  if (isSelected !== item.isSelected) {
    newProps.isSelected = isSelected;
  }
.
.
.
```

The section would be treated like a list item, but with this additional bit of information the section would itself also call newPropsForItem for its children. This is allow for infinite subsections whenever they are needed.

**Comment by dkasper-was-taken** [comment]
Additionally the onChange would bubble from the onClick, reverse creating the true index path, functionality would be expanded to include meta data. The end result would return on object, instead of a lone index:

```
onChange(event, { indexPath, metaData });
```

**Comment by StephenEsser** [comment]
To align more with React's dom semantic nature I would consider updating the Sections `listItems` prop to utilize children instead.

```
<MultiSelectList.Section headerContent="Header 1">
  <MultiSelectList.Item isSelectable content={<p>test1</p>} key="123" />
  <MultiSelectList.Item isSelectable content={<p>test1</p>} key="123" />
</MultiSelectList.Section>
```

**Comment by bjankord** [comment]
+1 on tech design. Let's handle this in a major version bump.

**Comment by mjhenkes** [comment]
+1
