### ISSUE TITLE
Create Toggle-Section-Header Component

### ISSUE THREAD

**Issue by dylan-sftwr** [cerner/terra-core#1322]
# Issue Description

Create a new Toggle Section Header component to serve as a state wrapper around `terra-section-header` and `terra-toggle`.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

This component should essentially maintain state and coordinate interaction between the `terra-section-header` and `terra-toggle` components.

## Current Behavior

N/A

**Comment by dylan-sftwr** [comment]
# Technical Design: `terra-toggle-section-header`

## Summary

Create a new package called `terra-toggle-section-header` to provide a toggleable sub-header component to manage the display/hiding of content.

## Responsiveness

No special considerations needed for this component.

## Accessibility

* The `aria-hidden` attribute will be used to indicate the open/closed state of the toggle section header.

## I18N / Bidirectionality

* This component must be able to be rendered with its mirror-imaged equivalent for rtl locales.

## React Props

| Prop                 | Type   | Default | Required | Description                                                                                 |
| -------------------- | ------ | ------- | -------- | ------------------------------------------------------------------------------------------- |
| `children`           | node   | N/A     | true     | Content in the body of the toggle section header component that will be expanded or hidden. |
| `title`              | string | N/A     | true     | Text to be displayed in the section header.                                                 |
| `level`              | number | `2`     | false    | Sets the heading level. One of `1`, `2`, `3`, `4`, `5`, or `6`.                             |
| `onClose`            | func   | N/A     | false    | Callback function triggered when toggle-section-header is closed.                           |
| `onOpen`             | func   | N/A     | false    | Callback function triggered when toggle-section-header is opened.                           |
| `sectionHeaderAttrs` | object | `{}`    | false    | Used to set props and HTML attributes on the toggle-section-header section-header.          |
| `isAnimated`         | bool   | N/A     | false    | Sets the toggle-section-header to be animated when it is opened or closed.                  |
| `isInitiallyOpen`    | bool   | N/A     | false    | Sets the toggle-section-header initial state to open.                                       |

## Themeable Styles

* N/A (this component is simply a state-management wrapper around `terra-section-header` and `terra-toggle`)

## Examples

### Minimal
```jsx
import React from 'react';
import ToggleButton from 'terra-toggle-section-header';

<ToggleSectionHeader isAnimated title="Toggle Section Header">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</ToggleSectionHeader>
```

**Comment by ChaseSinclair** [comment]
Are there toggle-specific callouts for this component?

**Comment by dm123455** [comment]
+1

**Comment by dylan-sftwr** [comment]
@ChaseSinclair there aren't any specific callouts for this, it's just the way that we decided to break things up

**Comment by bjankord** [comment]
+1 on tech design. Let's get @mjhenkes @JakeLaCombe or @ryanthemanuel to take a look at this too.

**Comment by mjhenkes** [comment]
+1 looks good to me

**Comment by PaulSolDev** [comment]
JIRA created
