### ISSUE TITLE
Terra OverlayContainer className not showing predefined className when user also provide className

### ISSUE THREAD

**Issue by nagrawal3** [cerner/terra-core#1324]
# Issue Description

When a className is passed on OverlayContainer, only user-defined className is added to the DOM element, and predefined className present in OverlayContainer doesn't get added to the DOM element rendered.

The line [here](https://github.com/cerner/terra-core/blob/master/packages/terra-overlay/src/OverlayContainer.jsx#L27) has the issue. We are including the className present in customProps to the variable OverlayContainerClassNames but we are not removing the className prop from the object. Thus adding customProps with spread operator at the end overwrites the className with just user-defined className 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

Predefined className 'overlay-container' along with user-defined className should be added to the DOM element rendered.

## Current Behavior
If no className is provided, predefined className 'overlay-container' is added to the DOM element rendered, but when the user also provides a className, only user-defined className is added to the DOM element rendered.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version: terra-overlay@2.2.0
* Browser Name and Version: Chrome Version 64.0.3282.167
* Operating System and version (desktop or mobile): OS X El Capitan v10.11.6

**Comment by alecrowen** [comment]
@nagrawal3  would you be willing to put up a pull request for this issue?

**Comment by bjankord** [comment]
This was resolved in #1337 and the fix is available in terra-overlay@2.3.0
