### ISSUE TITLE
Tech Design : Menu Theming

### ISSUE THREAD

**Issue by paku-sruti** [cerner/terra-core#1325]
# Issue Description
Adding active state background color theming variable in [terra-menu](https://github.com/cerner/terra-core/tree/master/packages/terra-menu).

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Tech Design
```
      &:active {
        background-color: var(--terra-menu-item-active-color, #ebf6fd);
      }
```

**Comment by ChaseSinclair** [comment]
Can you be a bit more specific on this tech design? Are you only adding a theming variable into the terra-menu component? Or are you also doing the theming itself?

**Comment by dylan-sftwr** [comment]
@ChaseSinclair i think this is just meant to add the ability to theme one property, but that could be a good point to add.

**Comment by paku-sruti** [comment]
@ChaseSinclair I am just adding the theming variable to the menu item

**Comment by dylan-sftwr** [comment]
![but why](https://media.giphy.com/media/xT8qB2tWl0dA9qMaXe/giphy.gif)

**Comment by bjankord** [comment]
+1 on tech design.

**Comment by emilyrohrbough** [comment]
+1

**Comment by paku-sruti** [comment]
Not going forward with Menu changes in core due to unavailability of updated callouts. Hence closing the issue.
