### ISSUE TITLE
[terra-popup] Popup 'top' arrow is not themeable.

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-core#1335]
# Issue Description
[PopupArrow.scss:33](https://github.com/cerner/terra-core/blob/master/packages/terra-popup/src/PopupArrow.scss#L33) is not themeable, while the others (left, right, bottom) are all themeable. Adding a variable check like the others would do.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

![image](https://user-images.githubusercontent.com/7713715/37228594-cbb3e79e-23a6-11e8-9ebc-12c09109797b.png)
The arrow at the top of the popup should be themeable.

## Steps to Reproduce

1. Click on any component using a PopupArrow, the top arrow is not themeable.

## Environment

* Component Version: terra-popup@2.2.0
* Browser Name and Version: All
* Operating System and version (desktop or mobile): All

**Comment by yuderekyu** [comment]
Addressed in #1336.

**Comment by bjankord** [comment]
This has been released in terra-popup@2.3.0 cc/ @PseudoFaux
