### ISSUE TITLE
Menu: add new theme variables

### ISSUE THREAD

**Issue by ChrisMageeJenks** [cerner/terra-core#1345]
# Issue Description
In the current Menu component, certain style attributes are not themeable. Additionally, some interaction states aren't accounted for in the current component. The items to be updated are:

- Menu item Padding (made themeable)
- Menu item Margin (made themeable)
- [EDIT] Menu item disabled color (made themeable)
- Keyboard Focus State (state defined/added, and made themeable)
- Pressed State (state defined/added, and made themeable)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The Menu component should have themeable variables for all of the desired attributes.

## Current Behavior
"N/A"

**Comment by cwalten** [comment]
We are looking to have this functionality implemented as well. Beyond the things listed above, we would also like to be able to define a disabled color for the chevron also.
