### ISSUE TITLE
Add refCallback function prop and data attribute to ContentContainer

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1359]
# Issue Description
ContentContainer is a functional component and consumers would benefit from being able to get it's ref, so we should add a refCallback similar to what we've done in terra-button and terra-list.

In conjunction with this, we've received several requests for access to the inner normalizer div that provides scrolling, so I recommend adding a data attribute to that div. Something along the lines of 'data-content-container-scroll'. That way scroll listeners, adjustments to scrollTop, or selectively disabling scrolling could be done more efficiently.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
refCallback's node value could be mapped to a variable, and a simple selector could provide the scroll:
```
const scrollNode = this.containerNode.querySelector('[data-content-container-scroll]');
```

**Comment by StephenEsser** [comment]
As we uncover components that warrant a ref callback I think there would be value in making the component a real React Class to inherit the natural and more consistent `ref`. We currently have a mixed and matched ref callback API. True components can utilize `ref` and stateless functional components have added a `refCallback` into the API. 

Making the components true classes may require disabling the lint rule, similar to what was done here: https://github.com/cerner/terra-core/blob/master/packages/terra-form-input/src/Input.jsx#L2

Does anyone else have any thoughts on uplifting components to be React Classes vs adding in a `refCallback` as needed into functional components?

**Comment by emilyrohrbough** [comment]
+1 on uplifting

**Comment by dkasper-was-taken** [comment]
Before we uplift components, I think we should look at the performance. I've noticed there's a fairly significant performance impact between the two when working with the infinite scroller. The additional life cycle events and checks add up. I would think we would only want to convert components to pure react components if we were able to implement shouldComponentUpdate. As many of these components would have a too expensive of a comparison, I'm not sure it's advisable to convert them without that check to improve performance.

**Comment by StephenEsser** [comment]
I agree with running some performance testing before a decision is reached. I'm hesitant to vote for generically implementing shouldComponentUpdate unless we are certain there are no edge cases during prop comparisons.

The Button was uplifted to be a React class during the last version bump.
