### ISSUE TITLE
Remove cerner-consumer-theme from Base

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1361]
# Issue Description
This behavior should be supplied by the consumer theme, not by the base component. 
See https://github.com/cerner/terra-core/blob/master/packages/terra-base/src/_themes.scss

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by bjankord** [comment]
This has been released in terra-base@3.3.0
