### ISSUE TITLE
terra-date-picker momentjs version doesn't support es-us

### ISSUE THREAD

**Issue by brhoades** [cerner/terra-core#1364]
# Issue Description
The minimum required version of momentjs of terra-date-picker, [2.17.1](https://github.com/cerner/terra-core/blob/master/packages/terra-date-picker/package.json#L42), doesn't support the local es-US. This leads to it giving a placeholder of `DD/MM/YYYY` on dates. [Momentjs 2.19](https://gist.github.com/ichernev/5f3f4eb02761b4f765a0cccf02cec603) added support for this locale which fixes this issue. If anyone has another package with an older version of moment preferred, this bug will pop up.

![20180322102142_1f3cis](https://user-images.githubusercontent.com/4763746/37779644-e07b03d8-2dba-11e8-890e-4f71ac47d4db.png)

## Expected Behavior
![20180322102220_ywojyd](https://user-images.githubusercontent.com/4763746/37779657-eab58fe4-2dba-11e8-83f9-f302b5c76ddb.png)

## Steps to Reproduce

1. Install terra-date-picker with moment < 2.19 in a test project.
2. Set the locale for a test application to es-US.
3. Datepicker will enforce `DD/MM/YYYY` formatting.

## Environment

* Component Version:
* Browser Name and Version: locale es-US, moment <2.19

**Comment by bjankord** [comment]
This has been released in terra-date-picker@2.4.0, terra-date-time-picker@2.4.0, and terra-time-input@2.4.0
