### ISSUE TITLE
Update our EsLint plugins to their latest versions

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1371]
# Issue Description
Our EsLint plugins our outdated. This is causing issues like this (https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/214)  to remain hard to detect in the code base. To ensure we are following proper accessibility while coding, we should update our plugins.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
Once https://github.com/cerner/eslint-config-terra is released, we can remove our eslint dependencies and add the `estlint-config-terra` as a dev-dependency and then add to the package.json to use it.
```
  "eslintConfig": {
    "extends": "terra"
  },
```

**Comment by bjankord** [comment]
I'm starting work on this.

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/pull/1775

Logged: 
* https://github.com/cerner/terra-ui/issues/114
* https://github.com/cerner/terra-toolkit/issues/163
* https://github.com/cerner/terra-dev-site/issues/107
* https://github.com/cerner/generator-terra-module/issues/111
