### ISSUE TITLE
[terra-button] Inline SVGs do not align vertically in buttons

### ISSUE THREAD

**Issue by ChaseSinclair** [cerner/terra-core#1383]
# Issue Description
I noticed in every case an inline svg is used as the background for a button, the svg does not align vertically. Some current implementations work around this by adding margins to control the centering. Some components do not center the svg at all.

# Examples
## [terra-dialog](http://engineering.cerner.com/terra-core/#/site/components/site/dialog/index)
![image](https://user-images.githubusercontent.com/5703475/38051564-5067b21c-3294-11e8-9434-e5c597753976.png)

## [terra-toggle-button](http://engineering.cerner.com/terra-core/#/site/components/site/toggle-button/index)
![image](https://user-images.githubusercontent.com/5703475/38051614-728dbfa8-3294-11e8-90c3-cc1971bdcde0.png)

## terra-action-header (In development)
![image](https://user-images.githubusercontent.com/5703475/38051680-a1a8f5d2-3294-11e8-8bd2-471cc638584e.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Inline SVGs vertically align in terra-button.

## Current Behavior
Inline SVGs are not vertically centered without setting vertical margins.

**Comment by bjankord** [comment]
I'm planning to work on a fix for this.

**Comment by amichaelparker** [comment]
It looks like (at least for something like the terra-toggle-button example) there is a negative vertical alignment being applied in icon that is pushing the icon out of alignment with the text.
 
![screen shot 2019-01-15 at 2 57 26 pm](https://user-images.githubusercontent.com/13922343/51209573-28515e80-18d6-11e9-9cc6-a8dad95a5b2e.png)

**Comment by ryanthemanuel** [comment]
Likely use this css: https://gist.github.cerner.com/NP032453/ecfc050bde7f01b95385dad9a4e4408d
