### ISSUE TITLE
[Props Table] Description column doesn't line wrap <pre> Sections

### ISSUE THREAD

**Issue by Blackop778** [cerner/terra-core#1391]
# Issue Description
Preformatted sections within the Description column added with markdown aren't automatically line wrapped, unlike preformatted sections in the type column

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Preformatted sections in the props table should line wrap

## Current Behavior
Preformatted sections in the Description column don't line wrap 

## Steps to Reproduce

1. Add \```Really long lines of text\``` to the description column of a Props Table

## Environment

* Component Version: 2.2.0
* Browser Name and Version: Chrome 65
* Operating System and version (desktop or mobile): OS X Sierra

**Comment by Blackop778** [comment]
# Proposal
Add a class to `PropsTable`s then apply `white-space: pre-wrap;` to all `<code>` elements within `<pre>` elements (how `terra-markdown` handles preformatted sections of markdown) that are descendents of the `PropsTable`
```
.propsTable pre > code {
    white-space: pre-wrap;
}
```

**Comment by bjankord** [comment]
+1 on tech design

**Comment by emilyrohrbough** [comment]
+1

**Comment by mjhenkes** [comment]
+1
