### ISSUE TITLE
Update jest missing locale tests

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1393]
# Issue Description
Currently, we test that components throw an error if locale is not set on base with the following:

```
it('throws error on missing locale prop in Base', () => {
  try {
    render(<ActionHeader />);
  } catch (e) {
    expect(e.message).toContain('add locale prop to Base component');
  }
});
```

This results in the message being outputted during the tests.
We should update these test to use the following syntax.

```js
// Mock the console call
global.console = { warn: jest.fn() };

expect(render(<ActionHeader />).toThrowError();
expect(console.warn).toBeCalledWith(expect.stringContaining('add locale prop to Base component'));
```

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Jest tests follow a consistent pattern for testing missing locale with i18n components

**Comment by kyleroush** [comment]
Created a pull request for this https://github.com/cerner/terra-core/pull/1932
