### ISSUE TITLE
I18n default loaders are not transpiled

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-core#1400]
# Issue Description
The default I18n loaders are added directly to the node modules folder and escape transpilation. This causes issues in IE 10 and 11.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Passive behaviour.

## Steps to Reproduce
1. Run webpack using the old plugin but the newest version of terra i18n
2. Run the app in IE 10 or 11
3. Error

**Comment by mjhenkes** [comment]
@bjankord Makes sense. I'm working on a fix now.

**Comment by bjankord** [comment]
This has been released in terra-i18n@2.4.0
