### ISSUE TITLE
[terra-i18n] Missing intlLoaders And translationsLoaders Dependencies

### ISSUE THREAD

**Issue by joel-cohen** [cerner/terra-core#1405]
# Issue Description
The terra-i18n component is using **intlLoaders** ([link](https://github.com/cerner/terra-core/blob/43ce643b2b3129b6d29f2ee54870ceeb2b37ded6/packages/terra-i18n/src/i18nLoader.js#L2)) and **translationsLoaders** ([link](https://github.com/cerner/terra-core/blob/43ce643b2b3129b6d29f2ee54870ceeb2b37ded6/packages/terra-i18n/src/i18nLoader.js#L3)) dependencies.

As a result when building our application with webpack the extract-text-webpack-plugin is throwing the following error:

```
ERROR in ./~/terra-i18n/lib/intlLoaders.js
Module not found: Error: Can't resolve 'intlLoaders' in '/home/pophealth/workspace/referral_management/client/node_modules/terra-i18n/lib'
 @ ./~/terra-i18n/lib/intlLoaders.js 3:19-41
 @ ./~/terra-i18n/lib/i18nLoader.js
 @ ./~/terra-i18n/lib/I18n.js
 @ ./~/terra-base/lib/Base.js
 @ <our react component>
 @ ./app/index.js
 @ multi ./app/index

ERROR in ./~/terra-i18n/lib/translationsLoaders.js
Module not found: Error: Can't resolve 'translationsLoaders' in '/home/pophealth/workspace/referral_management/client/node_modules/terra-i18n/lib'
 @ ./~/terra-i18n/lib/translationsLoaders.js 3:27-57
 @ ./~/terra-i18n/lib/i18nLoader.js
 @ ./~/terra-i18n/lib/I18n.js
 @ ./~/terra-base/lib/Base.js
 @ <our react component>
 @ ./app/index.js
 @ multi ./app/index
Child extract-text-webpack-plugin:
```

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Terra should include the **intlLoaders** and **translationsLoaders** as a dependencies so that build processes do not fail when looking for **intlLoaders** and **translationsLoaders** when using the terra-i18n component.

## Current Behavior
Webpack build processes are not able to locate the **intlLoaders** and **translationsLoaders** dependencies, so they are failing.

## Steps to Reproduce
1.  Use the Terra-Popup component in a react component.
2.  Use webpack with the **extract-text-webpack-plugin** with the following loaders: **css-loader**, **postcss-loader**, and **sass-loader**.
3.  Run webpack.

## Environment
* Component Version: 2.0.0
* Browser Name and Version: Google Chrome; Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS Sierra; Version 10.12.6

**Comment by mjhenkes** [comment]
@joel-cohen could you post your webpack config?

**Comment by joel-cohen** [comment]
@mjhenkes 

```
const webpack = require('webpack');
const { resolve } = require('path');
const Autoprefixer = require('autoprefixer');
const I18nAggregatorPlugin = require('terra-i18n-plugin');
const i18nSupportedLocales = require('terra-i18n/lib/i18nSupportedLocales');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CustomProperties = require('postcss-custom-properties');

const imageLoaderOptions = {};
const entryOutput = {};

if (process.env.RAILS_ENV === 'production') {
  imageLoaderOptions.outputPath = '/images/';
  entryOutput.filename = './[name].js';
  entryOutput.path = resolve(`${__dirname}./../public/`);
} else {
  entryOutput.filename = './[name].js';
  entryOutput.path = resolve(`${__dirname}./../public/javascripts`);
}

const config = {
  node: {
    fs: 'empty',
    child_process: 'empty',
  },

  context: resolve(__dirname),

  entry: {
    'commons-bundle': ['babel-polyfill', 'jquery-ujs'],
    'app-bundle': ['./app/index'],
  },
  output: entryOutput,
  resolve: {
    extensions: ['.js', '.jsx'],
    modules: [resolve(__dirname, 'aggregated-translations'), 'node_modules'],
    alias: {
      'react-intl': resolve(__dirname, 'node_modules/react-intl'),
    },
  },

  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.RAILS_ENV || 'production'),
      },
    }),
    new webpack.NamedChunksPlugin(),
    new ExtractTextPlugin(process.env.RAILS_ENV === 'development' ? './stylesheets/[name].css' : './[name].css'),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
    }),
    new I18nAggregatorPlugin({
      baseDirectory: __dirname,
      supportedLocales: i18nSupportedLocales,
    }),
  ],

  module: {
    rules: [
      {
        test: require.resolve('react'),
        use: {
          loader: 'imports-loader',
          options: {
            shim: 'es5-shim/es5-shim',
            sham: 'es5-shim/es5-sham',
          },
        },
      },
      {
        test: /\.(jsx|js)$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.(css|scss)$/,
        use: ExtractTextPlugin.extract(
          {
            fallback: 'style-loader',
            use: [
              {
                loader: 'css-loader',
                options: {
                  sourceMap: true,
                  importLoaders: 2,
                  localIdentName: '[name]__[local]___[hash:base64:5]',
                },
              },
              {
                loader: 'postcss-loader',
                options: {
                  plugins() {
                    return [
                      Autoprefixer(
                        {
                          browsers: [
                            'ie >= 10',
                            'last 2 versions',
                            'last 2 android versions',
                            'last 2 and_chr versions',
                            'iOS >= 8',
                          ],
                        }
                      ),
                      CustomProperties({ preserve: true, warnings: false }),
                    ];
                  },
                },
              },
              {
                loader: 'sass-loader',
                options: {
                  data: '$bundled-themes: "mock";',
                },
              },
            ],
          }
        ),
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: imageLoaderOptions,
          },
        ],
      },
    ],
  },
};

module.exports = config;
```

**Comment by mjhenkes** [comment]
@joel-cohen  The installed module from npm includes `intlLoaders.js` and `translationsLoaders.js`.
I'm not sure whats wrong.
![screen shot 2018-04-05 at 10 55 28 am](https://user-images.githubusercontent.com/1588747/38377147-e5e3f888-38bf-11e8-805e-75d7bcfde22c.png)
We do have a bug with no-transpiled files, but i'm not sure this is the same issue. https://github.com/cerner/terra-core/issues/1400

**Comment by joel-cohen** [comment]
@mjhenkes 

I am not sure if this is the same type of issue, but you may need to add *intlLoaders* and * translationsLoaders* dependencies to the package.json for the terra-i18n component.  I reported a similar issue here: [link](https://github.com/cerner/terra-framework/issues/137).

**Comment by mjhenkes** [comment]
That shouldn't be a problem here. `i18nLoaders` references `intlLoaders` and `translationLoaders` relative to itself. i.e. `var _intlLoaders = require('./intlLoaders');`. So as long as it's included in the webpack package it should be found. Can you check your terra-i18n module in your node_modules folder and see if those files are present?

**Comment by joel-cohen** [comment]
@mjhenkes You can close this issue, but I am not sure why this fixed the issue.  I noticed that webpack was indicating the following warning farther up in the logging:
```
WARNING: The terra-i18n aggregate-translations setup function should be used instead of the terra-i18n-plugin. Terra-i18n-plugin will be deprecated in the future. See https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/docs/AggregateTranslations.md for usage.
```

I followed the guide and in the above link and removed the terra-i18n-plugin package and changed webpack config to not use terra-i18n-plugin as well.  Webpack built successfully, however I am not sure why that corrected the issue of not being able to resolve those dependencies with terra-i18n.

**Comment by joel-cohen** [comment]
@mjhenkes 

npm  v3.8.6

**Comment by mjhenkes** [comment]
That version is supposed to support post install, but I'd recommend you go ahead and update npm. It's up to version 5 now.

**Comment by CoryMcDonald** [comment]
I've run into the same issue.  When I run `yarn install --force` it seems to do some additional work and link packages then it works. I'm still not certain what the problem is.

**Comment by mjhenkes** [comment]
We're going to remove the post install script https://github.com/cerner/terra-core/pull/1853

**Comment by Eshwar9990** [comment]
Degrading terra-clinical-application dependency from 3.2.0 to 2.3.0 resolved the issue for me

**Comment by ayanchax** [comment]
I also get the same issue.
./node_modules/terra-i18n/lib/intlLoaders.js
Module not found: Can't resolve 'intlLoaders' in 'C:\TerraReact\clayton\node_modules\terra-i18n\lib'

Webpack.config.js
const Autoprefixer = require('autoprefixer');
const PostCSSAssetsPlugin = require('postcss-assets-webpack-plugin');
const PostCSSCustomProperties = require('postcss-custom-properties');
const path = require('path');
const rtl = require('postcss-rtl');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const webpack = require('webpack');
const merge = require('webpack-merge');
const DuplicatePackageCheckerPlugin = require('@cerner/duplicate-package-checker-webpack-plugin');
const aggregateTranslations = require('terra-aggregate-translations');
const ThemeAggregator = require('../../scripts/aggregate-themes/theme-aggregator');
const getThemeWebpackPromise = require('./getThemeWebpackPromise');

const webpackConfig = (options, env, argv) => {
    const {
        rootPath,
        resolveModules,
        staticOptions,
        aggregatedLocales,
        themeFile,
    } = options;

    const production = argv.p;
    const fileNameStategy = production ? '[name]-[chunkhash]' : '[name]';
    const chunkFilename = argv['output-chunk-filename'] || fileNameStategy;
    const filename = argv['output-filename'] || fileNameStategy;
    const outputPath = argv['output-path'] || path.join(rootPath, 'build');
    const publicPath = argv['output-public-path'] || '';

    const devConfig = {
        mode: 'development',
        entry: {
            raf: 'raf/polyfill',
            'core-js': 'core-js/stable',
            'regenerator-runtime': 'regenerator-runtime/runtime',
            ...themeFile && { theme: themeFile },
        },
        module: {
            rules: [{
                    test: /\.(jsx|js)$/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            rootMode: 'upward', // needed to correctly resolve babel's config root in mono-repos
                        },
                    },
                },
                {
                    test: /\.(scss|css)$/,
                    use: [{
                            loader: MiniCssExtractPlugin.loader,
                            options: {
                                hmr: !production, // only enable hot module reloading in development
                                sourceMap: true,
                            },
                        },
                        {
                            loader: 'css-loader',
                            options: {
                                modules: {
                                    mode: 'global',
                                    localIdentName: '[name]__[local]___[hash:base64:5]',
                                },
                                sourceMap: true,
                                importLoaders: 2,
                            },
                        },
                        {
                            loader: 'postcss-loader',
                            options: {
                                // Add unique ident to prevent the loader from searching for a postcss.config file. See: https://github.com/postcss/postcss-loader#plugins
                                ident: 'postcss',
                                sourceMap: true,
                                plugins() {
                                    return [
                                        rtl(),
                                        Autoprefixer(),
                                    ];
                                },
                            },
                        },
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: true,
                            },
                        },
                    ],
                },
                {
                    test: /\.md$/,
                    use: 'raw-loader',
                },
                {
                    test: /\.(png|svg|jpg|gif|otf|eot|ttf|svg|woff|woff2)$/,
                    use: 'file-loader',
                }
            ],
        },
        plugins: [
            new MiniCssExtractPlugin({
                filename: `${filename}.css`,
                chunkFilename: `${chunkFilename}.css`,
                ignoreOrder: true,
            }),
            new PostCSSAssetsPlugin({
                test: /\.css$/,
                log: false,
                plugins: [
                    PostCSSCustomProperties({
                        preserve: true,
                        // If we have a theme file, use the webpack promise to webpack it.  This promise will resolve to
                        // an object with themeable variables and values. This will then be used to update the end state CSS
                        // so that they are populated with values if variables aren't supported (e.g. IE10). This dance is
                        // necessary when code splitting to ensure the variables and values are applied across all code split
                        // css files
                        ...themeFile && { importFrom: [getThemeWebpackPromise(rootPath, themeFile)] },
                    }),
                ],
            }),
            new DuplicatePackageCheckerPlugin({
                showHelp: false,
                alwaysEmitErrorsFor: [
                    'react',
                    'react-dom',
                    'react-intl',
                    'react-on-rails',
                    'terra-application',
                    'terra-breakpoints',
                    'terra-disclosure-manager',
                    'terra-navigation-prompt',
                ],
            }),
            new webpack.DefinePlugin({
                CERNER_BUILD_TIMESTAMP: JSON.stringify(new Date(Date.now()).toISOString()),
                TERRA_AGGREGATED_LOCALES: JSON.stringify(aggregatedLocales),
            }),
        ],
        resolve: {
            extensions: ['.js', '.jsx'],
            modules: resolveModules,
            mainFields: ['main'],
        },
        output: {
            filename: `${filename}.js`,
            chunkFilename: `${chunkFilename}.js`,
            path: outputPath,
            publicPath,
        },
        devServer: {
            ...staticOptions,
            host: '0.0.0.0',
            publicPath,
            stats: {
                colors: true,
                children: false,
            },
        },
        devtool: 'eval-source-map',
        resolveLoader: {
            modules: [path.resolve(path.join(rootPath, 'node_modules'))],
        },
        stats: { children: false },
    };

    if (!production) {
        return devConfig;
    }

    return merge.strategy({
        devtool: 'replace',
    })(devConfig, {
        mode: 'production',
        devtool: false,
        plugins: [
            new CleanWebpackPlugin({ cleanOnceBeforeBuildPatterns: ['**/*', '!stats.json'] }),
        ],
        optimization: {
            minimizer: [
                new TerserPlugin({
                    cache: true,
                    parallel: true,
                    sourceMap: true,
                    terserOptions: {
                        compress: {
                            typeofs: false,
                        },
                    },
                }),
            ],
        },
    });
};

const defaultWebpackConfig = (env = {}, argv = {}) => {
    const { disableAggregateTranslations, disableHotReloading } = env;

    const staticOptions = {
        ...disableHotReloading && {
            hot: false,
            inline: false,
        },
    };

    const processPath = process.cwd();
    /* Get the root path of a mono-repo process call */
    const rootPath = processPath.includes('packages') ? processPath.split('packages')[0] : processPath;

    const resolveModules = ['node_modules'];

    let aggregatedLocales;
    if (!disableAggregateTranslations) {
        aggregatedLocales = aggregateTranslations({ baseDir: rootPath, ...env.aggregateOptions });
        resolveModules.unshift(path.resolve(rootPath, 'aggregated-translations'));
    }

    const themeOverride = process.env.THEME; // Flexes root theme for theme visual regression testing.
    const themeFile = ThemeAggregator.aggregate(themeOverride);

    const options = {
        rootPath,
        resolveModules,
        staticOptions,
        aggregatedLocales,
        themeFile,
    };

    return webpackConfig(options, env, argv);
};

module.exports = defaultWebpackConfig;

![def](https://user-images.githubusercontent.com/42091907/76729384-0c1dab80-677f-11ea-9c80-bbc0765e9bf5.png)

**Comment by StephenEsser** [comment]
@ayanchax 

Can you provide a link to the project? The screenshot suggests the project was generated with create react app. I'd like to double check the configurations that were added after the project was generated.

**Comment by ayanchax** [comment]
just the UI components would do. I want to start a Demo TerraUI project. 
How do I do that ?
**Steps I followed**:
  1. npx create-react-app demoTerra
  2. After Step 1 enter "cd demoTerra"
  3. After Step 2 start the development server by entering "npm start"

The server starts and shows me the landing page as well, but then when I try installing TerraUI component into the project from the tutorial:
https://engineering.cerner.com/terra-ui/getting-started/terra-ui/basic-usage 
It throws me the error when I restart the server again, the error being:
 **./node_modules/terra-i18n/lib/intlLoaders.js Module not found: Can't resolve 'intlLoaders' in 'C:\TerraReact\clayton\node_modules\terra-i18n\lib'**  

 Am I doing something wrong here ?

**Comment by shaponpal6** [comment]
I'm also facing this problem. 
Have any solution?

**Comment by emilyrohrbough** [comment]
@shaponpal6 can you provide information on when you are seeing this error?

**Comment by shaponpal6** [comment]
I'm also getting same error above. 
I have tried all the scope above.

This is my fresh installed react app.


![Screenshot_2](https://user-images.githubusercontent.com/69696790/92806850-2e198300-f3dc-11ea-852e-b7fa412a1ddd.png)

**Comment by emilyrohrbough** [comment]
I see you are using react-scripts, so this is a create-react-app project? Did you setup you project to aggregate terra's translations? https://engineering.cerner.com/terra-ui/guides/terra-ui/internationalization/aggregate-translations

This would require updates to your project's webpack configuration.

**Comment by shaponpal6** [comment]
This is my repo
https://github.com/shaponpal6/tara-ui

**Comment by SvenWritesCode** [comment]
Is there an example with webpack set up @emilyrohrbough ? I too have been trying and failing to set up webpack.

**Comment by emilyrohrbough** [comment]
@SvenWritesCode the minimal setup we have provided in documentation is this: https://engineering.cerner.com/terra-ui/dev_tools/terra-ui/webpack#extending-the-default-config
