### ISSUE TITLE
[Markdown] - Jest SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#1407]
# Issue Description

The markdown package [imports CSS](https://github.com/cerner/terra-core/blob/master/packages/terra-markdown/src/Markdown.jsx#L6) assets for matching githubs's markdown. The import causes jests testing to fail with the following error.

```
  ● Test suite failed to run

    /Users/user/terra/terra-core/packages/terra-doc-template/node_modules/terra-props-table/node_modules/terra-markdown/node_modules/github-markdown-css/github-markdown.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@font-face {
                                                                                             ^
    
    SyntaxError: Invalid or unexpected token
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runner/node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (packages/terra-doc-template/node_modules/terra-props-table/node_modules/terra-markdown/lib/Markdown.js:19:1)
      at Object.<anonymous> (packages/terra-doc-template/node_modules/terra-props-table/lib/PropsTable.js:20:22)
```

The CSS files should already be proxied in the jest config but that doesn't seem to solve the issue:
https://github.com/cerner/terra-core/blob/master/jestconfig.json
https://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

Jest tests should be unaffected from assets.

## Current Behavior

Jest tests importing a reference to a file containing terra-markdown will fail with the error shown above.

## Steps to Reproduce

1. Import terra-markdown into a component
2. Import the component into a Jest test. `import Component from '../../src/Component'`
3. Run the jest tests for the package.
4. Observe the tests fail with the error posted above.

**Comment by JakeLaCombe** [comment]
The main issue is that our Jest configuration only mocks out files that explicitly end with .css or .scss. For this component, the styles are imported like this.

    import 'github-markdown-css';

Jest doesn't know how to directly import a css file if it doesn't have an explicit extension, so it either has to be mocked like this in your package.json file (https://github.com/cerner/terra-dev-site/blob/master/package.json#L36), or terra-markdown needs to be refactored so that it pulls in the css file as opposed to the main entry point of github-markdown-css.

**Comment by JakeLaCombe** [comment]
I'm not that happy with the solution I provided, so I'm going to modify terra-markdown to import straight css to match our mocks. Essentially, this will be our import

    import 'github-markdown-css/github-markdown.css';
