### ISSUE TITLE
Strikethrough prop for Text component

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#1418]
# Issue Description
There have been some designs from UX that include strikethroughs. We weren't sure what Terra's recommendation for this is, whether to wrap the Text component with an HTML tag or to use custom CSS. Given that there are other props to style the text component, it might be a nice addition.

This could also grow for the other text-decoration properties, based on Terra's desired direction.

## Issue Type

- [X] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
There should be a way to configure strikethrough.

## Current Behavior
There is no way to configure strikethrough

**Comment by neilpfeiffer** [comment]
Closing as not needed after discussion with @dv297 - functionality provided with [terra-clinical-item-display](https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-item-display/docs) for the case that is needed.
