### ISSUE TITLE
Create Paginator Component

### ISSUE THREAD

**Issue by saedar** [cerner/terra-core#1419]
# Issue Description
We need to build a common paginator component for Terra.

## Issue Type
New Feature

## Expected Behavior
Render a paginator component from provided props, in accordance with UX designs.

**Comment by saedar** [comment]
# Tech Design

## Proposed Inputs

Forward/Back: URL, start, limit, startParam, limitParam
First/Last: Total count
Paged: Page selected

General: Variant

The basic proposed functionality is the forward/back option. This requires a base URL and the key/values associate with start and limit. I'm taking the params as props because we can't guarantee that all consumers will use start/limit for their query params.

The first/last functionality is dependent on knowing how many pages exist, which can be calculate with the limit and total count.

Listing the page numbers is also dependent on knowing how many pages exist, but additionally needs to know currently selected page to build the relative linking and selected-page-display.

The variant will allow the consumer to flex between the Search Paginator and the Progressive Paginator. The progressive paginator will additionally be dependent on selected page as a "required" prop.

## Proposed API

```
<Paginator
	baseUri={base_uri_for_pagination}
	startParam={some_start_param}
	limitParam={some_limit_param}
	start={some_start}
	limit={some_limit}
	page={selected_page} // Optional
	totalCount={totalCount} // Optional
	// onPageChange is intended to support optional Ajax loading of content on pagination.
	onPageChange={callbackToLoadContentToContainer()} // Optional
	variant={‘search’ || ‘progressive’} // Hate these names. Don’t have better ones. Optional. Defaults ‘search’.
/>
```

## Proposed URL Builder Utility

```
var isPaged = (totalCount, page) => (!(typeof(totalCount) === 'undefined' || typeof(page) === 'undefined'));

var getPageCount = (limit, totalCount) => (Math.ceil(totalCount / limit));

// May redesign into a more complex function to account for more situations and be a little more readable.
// Ex: Setting previous to undefined if previous would result in a negative page.
var urlBuilder = (baseUrl, startParam, limitParam, start, limit, totalCount = undefined, page = undefined) => (
  {
    href: baseUrl,
    next: `${baseUrl}?${startParam}=${start + limit}&${limitParam}=${limit}` + (page ? `page=${page + 1}` : ''),
    previous: `${baseUrl}?${startParam}=${start - limit}&${limitParam}=${limit}` + (page ? `page=${page - 1}` : ''),
    first: totalCount ? `${baseUrl}?${startParam}=0&${limitParam}=${limit}&page=1` : undefined,
    last: totalCount ? `${baseUrl}?${startParam}=${getPageCount(limit, totalCount) - limit}&${limitParam}=${limit}&page=${getPageCount(limit, totalCount)}` : undefined,
    // The 'page' property below may be pulled out and built in the main component, or I might parse and modify as-needed.
    page: isPaged(totalCount, page) ? `${baseUrl}?${startParam}=${start}&${limitParam}=${limit}&page=${page}` : undefined,
  }
);

export default urlBuilder;
```

**Comment by JakeLaCombe** [comment]
Let's rename the page prop to currentPage so that it's more clear as to it's intent.

**Comment by JakeLaCombe** [comment]
@neilpfeiffer Some of our old pagination used show more style paginators that didn't know how many pages existed. Do we need to account for scenarios when we are unsure of how many total pages there are?

**Comment by JakeLaCombe** [comment]
How about themability variables? We have posted them on several tech designs.

**Comment by JakeLaCombe** [comment]
Also, should we do these as two different paginators instead of using a prop to switch between the two?

**Comment by saedar** [comment]
> @neilpfeiffer Some of our old pagination used show more style paginators that didn't know how many pages existed. Do we need to account for scenarios when we are unsure of how many total pages there are?

The various components (like page numbers) are listed as conditional at the top of the basic implementation. I took this to mean that the component should flex based on what information is provided.

> Also, should we do these as two different paginators instead of using a prop to switch between the two?

Is there a technical/UX/whatever reason you think that splitting them into separate top-level components is better than just providing a variant that achieves basically the same thing?

**Comment by JakeLaCombe** [comment]
If props or other aspects change for the API on one paginator but not on the other, it's easier to adjust for. Otherwise, we could end up having a large paginator component that has a large set of props for which only half are used at a given time.

**Comment by saedar** [comment]
Is that a realistic possibility, though? Sure, the design could change, but that is true for literally all of our components. Having said that, I know the updates to button caused a bunch of headaches for everyone involved.

@bjankord: Thoughts?

**Comment by saedar** [comment]
The above tech design is out-of-date per discussion last week. Rather than providing a mechanism to build and manage URLs in-component, we will require the user to pass in a callback function that has the Ajax/page-reload logic on their end.

A new formal design will be forthcoming.

**Comment by bjankord** [comment]
+1 on tech design

**Comment by dylan-sftwr** [comment]
+1 on tech design

**Comment by dkasper-was-taken** [comment]
+1 on tech design

**Comment by emilyrohrbough** [comment]
Get get the page number to display, will the `selectedPage`, `totalCount`, and `itemCountPerPage` need to be included? Also, will `itemCountPerPage` have a default?

**Comment by JakeLaCombe** [comment]
I say for now that we make all those props required. As for default itemCountPerPage, I think different teams across Cerner had different values for that, so I wouldn't default that for now.

**Comment by saedar** [comment]
They shouldn't be required because the design accounts for showing fewer UI elements (just next/previous) when page number isn't known.

I could see having totalCount and itemCountPerPage required, but not 100% sold on it.

**Comment by JakeLaCombe** [comment]
Sorry. I was vague. I meant requiring them all in order to get the display. I'm fine with leaving them as optional with the descriptions you provided.

**Comment by saedar** [comment]
Going with the v2 design for my PR.

**Comment by PaulSolDev** [comment]
JIRA created
