### ISSUE TITLE
[terra-form-select] Stop event propagation on clicking a terra-form-select

### ISSUE THREAD

**Issue by madelineisabelle** [cerner/terra-core#1422]
# Issue Description
Currently, terra-form-select does not stop event propagation on click. This is giving us issues as we have a select in a selectable list item and we are triggering the selectable list item's onChange on clicking the select.  Note: we are willing to contribute this fix.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

The select box should not trigger the onChange of its container element.

## Current Behavior

Currently, terra-form-select's onClick triggers its container component's onChange/onClick.

## Steps to Reproduce
1. https://kaiju.cerner.com/projects/old-bird-Tqig-A/workspaces/floral-mecha-king-ghidorah-ibeubQ/preview

**Comment by StephenEsser** [comment]
I think the Select should allow natural event bubbling / propagation. The unique workflows where a click should not bubble should be an implementation detail of the developer. Event bubbling would be an issue in every single component placed within a parent that also has a clickable region. Buttons, Icons, Forms, etc... 

These situations are unique to different workflows and the Select itself is unaware of them, one example of a potential solution would be to catch and stop the events when a unique scenario necessitates it. 

```
<div onClick={() => console.log('Select List Item')}>
  <Select onClick={(event) => { event.stopPropagation(); }} /> // Stop the propagation 
</div>
```
That being said, the Select looks like it might not honor a users onClick so the catch may need to happen at a higher level until that is resolved.

**Comment by StephenEsser** [comment]
Closing this issue. A custom onClick can be passed into the Select from version 4.0+ allowing a consumer to stopPropagation if necessary. 

https://github.com/cerner/terra-core/pull/1501
