### ISSUE TITLE
Number Field Index accepts all alphanumeric on Safari

### ISSUE THREAD

**Issue by ChelseaRyanAnderson** [cerner/terra-core#1429]
# Issue Description

Number Field Index accepts all alphanumeric on Safari
<img width="269" alt="screen shot 2018-04-17 at 1 45 28 pm" src="https://user-images.githubusercontent.com/35141408/38889918-a4233802-4245-11e8-98f9-6d174c7a4dca.png">

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

I typed "123efg" in both fields 

In Chrome: 
![screen shot 2018-04-17 at 1 45 22 pm](https://user-images.githubusercontent.com/35141408/38889963-bc7dd2c2-4245-11e8-8667-7e69af96127f.png)

## Current Behavior
In Safari, the user is able to type any alphanumeric character.

## Steps to Reproduce
1. Opened [page](http://engineering.cerner.com/terra-core/#/site/components/site/form/number-field-index) in Chrome
2. Opened [page](http://engineering.cerner.com/terra-core/#/site/components/site/form/number-field-index) in Safari 

## Environment
* Component Version:
* Browser Name and Version: Chrome Version 64.0.3282.186 (Official Build) (64-bit) and Safari Version 11.1 (12605.1.33.1.3)
* Operating System and version (desktop or mobile): Mac OS desktop

**Comment by JakeLaCombe** [comment]
Terra form input essentially is just a wrapper for the base input that a browser provides. We won't be able to provide any built in input constraints to the form components that prevent issues like this.

We did spike out our form validations to use [react-final-form](https://github.com/final-form/react-final-form), so you could wrap the input inside a field and do validations that way. That would be the recommended way to prevent this from occuring.

**Comment by emilyrohrbough** [comment]
@JakeLaCombe Is this mentioned on the documentation of the new Number Field pR?

**Comment by alecrowen** [comment]
Can be fixed by consumers via form validation.
