### ISSUE TITLE
Enhance Card On Card for better Box Shadow

### ISSUE THREAD

**Issue by alex-bezek** [cerner/terra-core#1432]
# Issue Description
Enhance Card to allow for an alternative box shadow when on a white background (like when in another card)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The card should be flexible enough to allow for a different box shadow when nested inside another card.

## Current Behavior
Terra core has a css variable for box-shadow set to none, but themes may override this to have a box shadow. The ask is for the ability to also flex it to be different when placed inside another card. This is so that a different box shadow can be applied for a better visual affect.

##### A new Prop on Card
One possible way to do this is to just add a type/variant on the card that allows it to change some visuals based off that type. In this case it might be a `stacked` card.

##### A new Card Component
In order to prevent the existing card from having its props balloon out with different specific scenarios, a simple new `StackedCard` could be created that utilizes the existing card and overrides the box shadow.

##### Smart Card Body Approach
If the rule is that "A card inside a card has a different box shadow" then 1 possibility is to make the card put a class on it that scopes a css variable inside it to change the card box shadow. This would not work in ie though, so its probably a no go. Another way of doing something similar is via a descendent selector to look for another Card inside Card and to change the box shadow. This would work in IE but comes with alot of assumptions that would inevitably cause an edge case. If target only direct children, it wouldn't work if anyone puts a div or spacer around their inner card. If you target all descendents, someone might put a container inside their card with a none-white background, and then another card in that expecting the normal box shadow.

##### Separate the box shadow concern from the Card itself
Create a wrapper component or HOC that can be used to add a box shadow on the outer most element. This would be useful to not couple specific box shadows to card, and to allow them to be used with other components. Would only apply to the outer element of a component however. After speaking with UX a bit more about this, their guidance is that the 6 levels of box shadow wouldn't need to be applied randomly to other components, but is already encapsulated by existing components.

## Cards on Light Backgrounds
So what if a card is on the background, and a client themes their background to white. After discussing with UX, this scenario shouldn't be handled by the Card trying to be smart and flex. In this case, the client would have to theme the card box shadow appropriately.

# My Vote
I think the new prop on card makes the most sense for now. There are already no props on Card (other than children) so we aren't making it super custom. The new component seems a bit overkill and would require more refactoring of the internals to share code

### New React Prop:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| TBD | boolean | false | Sets a class that overrides the default box shadow css property with a new value and a new css custom property|

To keep it passive, the default would be false. Additionally, since terra currently doesn't have a box shadow for the card at all, I'm assuming even when true, the default value for the css custom property would still be no box shadow. Would need UX input

### Proposed Names - We don't want
* stacked - isn't right, since there isn't a card stack 
* nested - Doesn't always have to be nested
* isInsideCard - ins't right, since it is for any card used on any white background,
* isRaised - Doesn't seem right since we aren't truly changing the elevation, just changing the way the light hits it and makes a shadow
* hasBoxShadow - Tied directly to the specific style it adds, not its usage. Also normal cards can already have box shadows

### Proposed Names - That we are open to using
* isOnLightBg
* enbeddedCard
* cardStyle/variant - A bit vague and non-prescriptive on how to use it, but not tied to any particular use case and open for themes to use it differently. Default would be `baseLine`, new one would be 1raised1, and in the future it could expand for other scenarios.

**Comment by bjankord** [comment]
+1 for a new prop on card.

**Comment by alex-bezek** [comment]
naming is fun as well. `stacked` or `nested` would be useful for signifying its mainly for when you have a card in a card. Or even `isInsideCard`.
If there are additional use cases to use a different box shadow when on other white backgrounds, we might not want to couple it to being inside a card. The different box shadows UX are using are related to different elevations for visual effect, so `isRaised` could work.

**Comment by neilpfeiffer** [comment]
+1 on prop on card. 

I took a look at the visuals and since the usage of this alternate card shadow has nothing tied to specific card-inside-of-card usage, or a card-stacked-ontop-of-another-card, really is just an alternate shadow for when used on white background.

- `isStacked` isn't right, since there isn't a card stack,
- `isInsideCard` ins't right, since it is for any card used on any white background, 
- `isRaised` doesn't seem right since it would imply changing to another elevation shadow depth within the styleguide (there are different shadow depths similar to [material design](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows) and this isn't one of those depths) 

Feel like the new prop should be maybe `cardStyle` or `variant` that should take a list of string options: style1, style2, etc.

**Comment by alex-bezek** [comment]
I think `cardStyle` with `style1`,  `style2`, etc is a bit vague and doesn't really describe what its used for. It would end up being used inappropriately. The variant is another thought, but this is the only other way to use it I have heard from UX, so I'm not sure what the values would be.

what about a boolean prop not signifying that its in a card, but that its on a light background? `isOnLightBg` or something of the sort?

**Comment by emilyrohrbough** [comment]
Possibly `hasBoxShadow`?

**Comment by emilyrohrbough** [comment]
One thing to consider is when adding a box-shadow around the card, the parent div will need to add the appropriate spacing such that the box-shadow is not cut off.

**Comment by emilyrohrbough** [comment]
`enbeddedCard`?

**Comment by alex-bezek** [comment]
I think that works for the Card In Card scenario, but @neilpfeiffer was saying it should work for other situations where its just on white. I'll add it to the list at the top to keep a record of it. Thanks for helping come up with names btw!!

**Comment by neilpfeiffer** [comment]
agreed that `style1` `style2` was too vague, idea was more placeholder for a better enum list we could base on solidified concepts. (Let's keep the naming open for a bit longer until something makes sense.)

.

> not typically putting margins/padding on the outside of components

Generally the rule we've discussed it that complex containers & views _do_ margin appropriately outside of themselves, such they position themselves as intended within any full-width (& height as needed) space, including other containers, but _don't_ add padding to the inside, unless it is a special type of container that can receive "basic" content as children (pure strings, etc), thus functioning like a pseudo-view (card-body and table-cell as examples). `TLDR: any child should always be able to touch/reach the edge of it's parent if it needs to.` 

For this case of the current designs trying to be achieved (as with cards of any type) - I would assume consumer would wrap the component in a spacer or other custom layout (grid, card-collection, etc) that appropriately keeps the inner cards correctly aligned and separated from one another, and inset correctly from the outer card/page-panel.

**Comment by neilpfeiffer** [comment]
Worried on the other end that `isOnLightBg` is also too specific, since if we don't look at directly at the new design being for on-white and abstract it for other themes, is really just an alternate style. 

I'm still open to using `cardStyle` with `baseline` as default, and `raised` for new type, then list can passively grow as needed in future with `raised+1`, `raised+2` for other elevations if needed, or `flip`,`reveal`, etc. if other functional types of cards might be created.

**Comment by alex-bezek** [comment]
talked in person a bit, I think we are both fine going with a prop of `cardStyle` the default prop value being `default` to provide passivity, and the new type being `raised`.

@bjankord @emilyrohrbough do you have any additional thoughts?

**Comment by bjankord** [comment]
I'd so go with `variant` instead of `cardStyle`. `variant` matches other terra components and cardStyle could be confused with a prop to pass inline styles to in my opinion. +1 on `default` and `raised`

**Comment by alex-bezek** [comment]
if we want to go with `variant` for consistency that's fine. I think @neilpfeiffer was arguing that `variant` has an undertone of being an actual different type of component (like a utility button vs emphasis) where this is just a different style.

**Comment by alex-bezek** [comment]
@bjankord I opened a PR here https://github.com/cerner/terra-core/pull/1458 using `variant`. 
@neilpfeiffer let me know if you feel strongly about the prop being called `cardStyle` instead

**Comment by dylan-sftwr** [comment]
+1 on `variant`. As other use-cases for cards pop up, this will allow us to easily divide component/styling properties passively. Although I agree that right now, the only difference being controlled through the `variant` prop is style toggling, so `cardStyle` would make sense, I don't know if that will necessarily be the case as develop new use-cases and contexts where card can be consumed

**Comment by vaghashiyamukesh** [comment]
+1 for a new prop on card.

**Comment by PaulSolDev** [comment]
JIRA created

**Comment by bjankord** [comment]
@alex-bezek This has been released in terra-card@2.8.0

**Comment by alex-bezek** [comment]
sweet, thanks!
