### ISSUE TITLE
Improve install / build time for terra

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1434]
# Issue Description
Add `--hoist` flag to lerna bootstrap to speed up install / build times. 
Lerna offers a [feature to hoist dependencies](https://github.com/lerna/lerna/blob/master/doc/hoist.md) to the root node_modules directory. This hoist flag is specifically to help reduce the time and space requirements for numerous copies of packages in development and build environments, by "hoisting" shared dependencies up to the topmost, Lerna-project-level node_modules directory instead.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Install / build times complete faster

**Comment by bjankord** [comment]
h1. Tech Design

I'm gonna test 3 approaches:

* Use yarn + yarn workspaces
* Use lerna's built-in `hoist` feature, which to my understand, works similar to yarn's workspace feature
* Use lerna's built-in `hoist` feature and adding a package.lock.json file for the root package directory

I'm planning to reach out to the lerna team to see if they are aware of any outstanding issues with using package.lock file in the root package with lerna.

**Comment by bjankord** [comment]
I'm running into issues getting yarn + yarn workspaces to pass tests. Install process seems to work, but the tests fail out on an issue with resolving moment.js This may be due to how our resolves / aliases are set up in webpack. I'm planning to further test with `lerna --hoist` and hold off on continuing to test yarn for now

**Comment by emilyrohrbough** [comment]
With using hoist, I think it puts moment at the root-level node_modules, which means we can drop the ['moment' alias](https://github.com/cerner/terra-core/blob/master/webpack.config.js#L15) in our webpack config that indicates 'moment' is within the date-time-picker's node_modules.

**Comment by bjankord** [comment]
I reached out to lerna team about using package-lock file in our root directory. They mentioned, "As long as you ensure that all the hoisted modules remain in sync with the leaves, so that `lerna bootstrap` never attempts to install a non-matching dependency inside a leaf, a root package-lock is fine". I have a feeling we'd have to be pretty vigilant to ensure this. For now, I'm planning to move forward with just using the `--hoist` flag without adding a package-lock file in the root package.

**Comment by bjankord** [comment]
Resolved in #1431
