### ISSUE TITLE
Terra.SingleSelectableRows not working when returning a mapped list

### ISSUE THREAD

**Issue by corymcdonald** [cerner/terra-core#1439]
# Issue Description
Was wondering if anyone could help me figure out if this is a defect or not. 

When I use `<Terra.Rows>` this code works fine but when I use `<Terra.SingleSelectableRows>` it breaks. I can use `SelectableTableRows` and `MultiSelectableRows` no problem

Demo here:
https://codesandbox.io/s/nr2kjz3r5p

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Should render

## Current Behavior
Does not render

## Steps to Reproduce
https://codesandbox.io/s/nr2kjz3r5p​​​​​​​

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by dkasper-was-taken** [comment]
Addressed with #2615
