### ISSUE TITLE
wdio test needed- terra form checkbox

### ISSUE THREAD

**Issue by acomputergirl** [cerner/terra-core#1441]
# Issue Description
no webdriver.io test for terra form checkbox

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Create a webdriver.io accessibility test for the terra form checkbox

## Current Behavior
N/A

**Comment by emilyrohrbough** [comment]
This is also noted on https://github.com/cerner/terra-core/issues/1302
