### ISSUE TITLE
Extra border when using ActionFooter with Dialog

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#1461]
# Issue Description
Both terra-action-footer and terra-dialog define a top border for the footer. A lot of designs have modals that present users with a message and right-aligned buttons at the bottom of the modal, and the combination of modal -> dialog -> action-footer seems like the appropriate path for this.

As a side note, I also noticed there is terra-divider. There isn't much preventing a user from just implementing their own layout and use terra-divider as the border. But terra-divider is also a slightly lighter color. Perhaps it could be a recommended / not recommended route for defining layouts to use dividers. Just a thought for making intended usages a little more obvious.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
ActionFooter should probably not define a border. It could just be a component for laying out items without any visual artifacts of its own, as borders could be applied to the container around it. Alternatively, a prop could be used to configure if the component should have a border or be borderless.

## Current Behavior
Both terra-action-footer and terra-dialog define a top border for the footer.

**Comment by bjankord** [comment]
Let's add a prop to handle this. We're open to a PR for this @dv297

**Comment by dv297** [comment]
I assume tech designs are needed?

# Tech Design

Add a new prop to ActionFooter to remove the border

| Prop Name   | Description | Required? | Default Value? |
| ----------- | ----------- | --------- | -------------- |
| borderless  | Remove the border from the ActionFooter | No | false | 

Proposed API
```jsx
<ActionFooter
  start={<a href="/link/to/somewhere">A link</a>}
  end={
    <div>
      <Button text="Submit"/>
      <Button text="Cancel"/>
    </div>
  }
  borderless={true}
/>

// Or with shorthand
<ActionFooter
  start={<a href="/link/to/somewhere">A link</a>}
  end={
    <div>
      <Button text="Submit"/>
      <Button text="Cancel"/>
    </div>
  }
  borderless
/>
```

**Comment by dv297** [comment]
Updated tech design to use isBorderless

**Comment by bjankord** [comment]
+1 on tech design, lets add the same prop to action header.

**Comment by emilyrohrbough** [comment]
+1

**Comment by mjhenkes** [comment]
+1

**Comment by jimipasa** [comment]
+1 on adding the same prop to the action header as well

**Comment by tbiethman** [comment]
For posterity, it was decided in #1754 that the Dialog itself should be updated instead of the ActionHeader/ActionFooter individually. However, due to talks of deprecation of the Dialog altogether, I don't believe these changes are still necessary. I am closing this issue as a result; if a borderless Dialog is desired, a ContentContainer can be used instead.
