### ISSUE TITLE
terra-props-table doesn't render always correctly render 'Type' column value correctly for props

### ISSUE THREAD

**Issue by dylan-sftwr** [cerner/terra-core#1463]
# Issue Description

In the case that we're using an object  (`alphaPropsObj`) to store key-value pairs of valid prop options for prop `alpha`, and we attempt to use `PropTypes.oneOf(Object.values(alphaPropsObj)`, the resulting value for the `Type` field in the props-table generated by `terra-props-table` is `undefined`.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

I would expect the table to still be able to interpret the type of the array items and yield the following props table
![image](https://user-images.githubusercontent.com/17390173/39474785-3a22417e-4d1b-11e8-9485-77d5bc9bab66.png)

**NOTE:** This _can_ be achieved by wrapping `Object.values(...)` in a set of array brackets, and spreading the returned value into said array. Example included below.
![image](https://user-images.githubusercontent.com/17390173/39474850-7ebcebb8-4d1b-11e8-818c-7d04008fcb99.png)

## Current Behavior

Using
![image](https://user-images.githubusercontent.com/17390173/39474729-f9f17070-4d1a-11e8-8746-1cb31ca37936.png)
produces

![image](https://user-images.githubusercontent.com/17390173/39474739-08401118-4d1b-11e8-9c8d-d69a69996de1.png)

## Steps to Reproduce

1. Define an object of key-value pairs, with values you'd expect to be type-checked using `PropTypes.oneOf()`
2. Call `Object.values(<your object)` as the argument to `PropTypes.oneOf`.
3. Observe the `terra-props-table`'s `Type` field doesn't properly reflect the expected type.

## Environment

* Component Version: 2.5.0
* Browser Name and Version: Chrome (66.0.3359.139)
* Operating System and version (desktop or mobile): Desktop

**Comment by bjankord** [comment]
We're open to a PR for this @dylan-sftwr
