### ISSUE TITLE
Adding theming for SlideGroup background color

### ISSUE THREAD

**Issue by mayurikini** [cerner/terra-core#1475]
# Issue Description
We as a consumer need [background color to be themeable for Slide component](https://github.com/cerner/terra-core/blob/master/packages/terra-slide-group/src/Slide.scss#L3)

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Background color for Slide component should be themeable

## Current Behavior
Background color for Slide component is not themeable

**Comment by bjankord** [comment]
We're open to a PR for this @mayurikini

**Comment by bjankord** [comment]
@mayurikini This has been released in terra-slide-group@2.8.0

**Comment by PaulSolDev** [comment]
JIRA created
