### ISSUE TITLE
Add error prop to Fieldset

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1480]
# Issue Description
The fieldset doesn't have an error prop like it's previous component contained. We need to add one back in order to display an error message for a group of forms.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Fieldset has an error prop on it.

## Current Behavior
Fieldset does not have an error prop.

**Comment by yuderekyu** [comment]
Not desired. 

> Talked with UX and found out that adding error and isInvalid props to the fieldset component is not desired. Instead, we'll be building a new component to handle rendering checkbox or radio buttons inside of a fieldset along with displaying associated help text / error text with the field. @JakeLaCombe is working on a tech design for the new component.
