### ISSUE TITLE
[terra-action-header] Children appearing on the left end of the header

### ISSUE THREAD

**Issue by hs025828** [cerner/terra-core#1482]
# Issue Description
In the action header, children do not right align when there is no left aligned buttons or title.

In the following screenshot the button with a search icon is a child of the action header.

<img width="797" alt="toolbar_bug" src="https://user-images.githubusercontent.com/4634645/39709855-a054f774-51e0-11e8-985a-a94ffc32ec6b.png">

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
According to the action header documentation children should appear on the right end of the header.

## Current Behavior
When there is no title or left aligned buttons, then children are appearing on the left end of the header.

## Steps to Reproduce

1. Create an action header with no title or left aligned buttons and with child elements.
2. Observe that child elements are appearing on the left end instead of the right end of the header.

## Environment

* Component Version: 1.2.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by tbiethman** [comment]
We will need to move the title presence check within the flex-fill div to make this spacing consistent: https://github.com/cerner/terra-core/blob/master/packages/terra-action-header/src/_ActionHeaderContainer.jsx#L53

**Comment by hs025828** [comment]
Two other issues:
1. We are also seeing both maximize and minimize buttons appearing at the same time.  I would expect only one of them to appear depending upon the current form factor.
2. Even if you give buttons on the left and right, the child components still do not anchor to the right side unless a title is given.
