### ISSUE TITLE
Create a Radio Field and CheckBox Field component

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1484]
# Issue Description
We need to have a component that is a field that consist of multiple control components (Radio and Checkboxes). The idea is that since radio and checkboxes are all the same field essentially, they need a component that has a universal error and legend.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by JakeLaCombe** [comment]
# Tech Design

## Description

Choicefield is a fieldset composed of multiple checkboxes or radio buttons with a universal error message and legend.

For implementation, this will essentially be terra-form-field rendered as a fieldset.

## Responsiveness
This will contain the same responsive behavior and the Field and Fieldset components

## Internationalization
None is needed for this component

## Props
**legend** - Legend to display for the Field
**legendAttrs** - Attributes to attach to the legend
**isLegendHidden** - Whether the legend is hidden or not.
**isInvalid** - Whether the field is valid or invalid
**error** - Error message to display
**required** - Whether or not the field is required
**isInline** - Whether or not the field is hidden
**hideRequired** - Whether or not to hide the required indicator on the label
**help** - Help element to display with the input
**error** - Error message for when the input is invalid. This will only display if isInvalid is true.
**children** - The form control elements the ControlField Contains.

**Comment by yuderekyu** [comment]
Did you include two `error` props on accident, or had another prop in mind, like `errorIcon`?

**Comment by JakeLaCombe** [comment]
two error props were on accident. This will not contain an errorIcon. That's scheduled for removal inside our existing components

**Comment by JakeLaCombe** [comment]
We talked in Scrum today. This API is good, but we are going to instead have the components duplicate inside both the checkbox and radio packages

RadioField inside terra-form-radio
CheckboxField inside terra-form-checkbox

**Comment by PaulSolDev** [comment]
JIRA Created
