### ISSUE TITLE
[terra-action-header] Next/Previous document still shows up if either one of them is passed

### ISSUE THREAD

**Issue by lifemoveson** [cerner/terra-core#1507]
# Issue Description
 In the action header, when we pass in either next or previous document button, both the button shows up. 
In the following screenshot, it shows that both the buttons still shows up if onNext is not passed in. 

<img width="720" alt="screen shot 2018-05-14 at 10 43 43 am" src="https://user-images.githubusercontent.com/759286/40008177-525f86d6-5764-11e8-8c24-990a30ba4850.png">

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
As per the documentation, next/previous document button should not show up if either of them is supplied.  Also, it would be great if either of them is passed in it just shows up that button whose definition is passed in instead of not showing up entirely.

## Current Behavior
As of now, both the button shows up if either of the values are passed in. 

## Steps to Reproduce

1. Create an action header with no next or previous document button defined.
2. Observe that both the buttons are still appearing on the action header.

## Environment

* Component Version: 1.2.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): desktop

**Comment by tomleewu** [comment]
This may be a misunderstanding?

The documentation says that
> The previous-next button group will not display if __neither__ this or onPrevious are set.

In other words, if either `onNext` _or_ `onPrevious` is supplied, the previous-next button group will display.

**Comment by benbcai** [comment]
The [documentation](https://github.com/cerner/terra-core/blob/master/packages/terra-action-header/src/ActionHeader.jsx#L43-L47) states that the Previous-Next button group would display if only _both_ the `onPrevious` and `onNext` props are set. However, the [implementation](https://github.com/cerner/terra-core/blob/master/packages/terra-action-header/src/ActionHeader.jsx#L110) would display the Previous-Next button group if _either_ of these props are set. 

Which is correct?

- Documentation

- Implementation

- Neither - It should display the Previous button if the `onPrevious` prop is set and display the Next button if the `onNext` prop is set. They should be independent.

I think the documentation is correct. Looking for input.

**Comment by bjankord** [comment]
If neither onNext or onPrevious are passed in, render nothing
If both onNext or onPrevious are passed in, render both
If only 1 passed in render button group with appropriate button enabled and the missing action as a disabled button.
