### ISSUE TITLE
`npm install` removes dependencies from node_modules in root

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#151]
This issue can be resolved be removing the preinstall script.
https://github.com/npm/npm/issues/10379

When executing `npm install` when node_modules dependencies are present in the root directory, all of the dependencies are deleted.
![npm_install](https://cloud.githubusercontent.com/assets/8146159/24107662/5c93a0e8-0d59-11e7-8b8e-90585024988e.gif)

**Comment by bjankord** [comment]
Related https://github.com/npm/npm/issues/10379
