### ISSUE TITLE
Add ability to pass custom node to section header / toggle section header

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1520]
# Issue Description
Currently the section header and toggle section header only take strings as titles. This is to ensure the styling set on the string provides proper truncation and styling without conflicting with any custom dom passed in.

This work would be to add a new prop, `customTitle` that takes a node where no component styling is provided from section header / toggle section header. The styling would be up to the consumer providing the custom title.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Ability to set custom node content as title

**Comment by saisanthosh225** [comment]
One of the tech design for this use case would be 
![List of Responsive Elements as Title ](https://user-images.githubusercontent.com/20688408/40145743-a3c6b65a-5928-11e8-89f1-dac503c1d0b8.png)., the current implementation ToggleSection Header with a String as Title would be 
![Responsive String](https://user-images.githubusercontent.com/20688408/40145776-cc9b311e-5928-11e8-9890-6eafe6b277fe.png)

**Comment by aberge00** [comment]
+1 on this enhancement request.  I have an immediate project need to format the title section with both text and icons.

Can we get started on this ASAP?

**Comment by dm123455** [comment]
+1 we would need this too!

**Comment by bjankord** [comment]
Talked with UX about this request. At this time, UX has requested that we do not add the ability to pass custom node to section header / toggle section header as it goes against design standards.

If you need this type of behavior, please work with your UX designer on a solution.

@aberge00 @dm123455, I've met with the consumer UX designers and engineers and we've got a plan to create a custom component in our inner source repos to match the designs this functionality was requested for.

@ChaseSinclair and @celvro are familiar with the design / implementation details.
