### ISSUE TITLE
Clear button in search field doesn't appear

### ISSUE THREAD

**Issue by sujith9** [cerner/terra-core#1522]
# Issue Description
The clear button used to clear input text in terra-search-field doesn't appear. Observed in IE 10. 

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The button to clear input text should appear in the search field. Clicking the button should clear the input text.
The clear button appears in other browsers and IE 11.
![search_field_clear_button](https://user-images.githubusercontent.com/1754143/40188148-e202cd82-59be-11e8-9f6e-829e19ec971b.JPG)

## Current Behavior
The button to clear input text doesn't appear in the search field (in IE 10).

## Steps to Reproduce
1. Add terra-search-field to (any) app.
2. Render the search field in IE 10.
3. Input a search text in the search field.
4. Hover over right corner of search field and see no clear button.

## Environment
* Component Version: 2.6.0
* Browser Name and Version: IE 10
* Operating System and version (desktop or mobile): Windows 10 desktop.

**Comment by noahbenham** [comment]
We're seeing this on iOS as well. Tested on iOS 11.3 mobile Safari.

As @dkasper-was-taken mentioned, this is a result of different browsers handling the ["search" input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search) type differently. To mitigate this, Terra would essentially have to add a custom clear button on the right side of the input for browsers that don't display a native clear button.

**Comment by bb3284** [comment]
Just as an FYI, this issue was logged in CareAware Connect as a defect as there are requirements dictating the existence of a "clear" option.

**Comment by bjankord** [comment]
This PR adds a cross-browser compatible solution for clearing in the select component: https://github.com/cerner/terra-core/pull/2240

**Comment by bjankord** [comment]
We are adding a clear option to the select in this PR: https://github.com/cerner/terra-core/pull/2240
It may be worth investigating adding a cross-browser clear option to search.

**Comment by ShantiiP** [comment]
@bjankord - Is there an estimated completion date for this?
Thanks.

**Comment by StephenEsser** [comment]
There's no firm date when this will be completed, but the PR looks like it is getting pretty close.

https://github.com/cerner/terra-core/pull/2317

If you want to follow along with the PR, the changes are usually available within ~ 1 week after being merged into master.
