### ISSUE TITLE
Signature: Theming is not working for the strokes in canvas

### ISSUE THREAD

**Issue by mayurikini** [cerner/terra-core#1544]
# Issue Description
For signature component, in canvas the strokes style is made themeable [here](https://github.com/cerner/terra-core/blob/master/packages/terra-signature/src/Signature.scss#L5). But it is not working as expected. Even if we try to change the [context.strokesStyle](https://github.com/cerner/terra-core/blob/master/packages/terra-signature/src/Signature.jsx#L78) to a different color, it will still result in strokesStyle color to be the default #000.  

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
StokesStyle should be themeable.

## Current Behavior
Theming does not work for StokesStyle in signature component. 

## Steps to Reproduce

1. Try to pass a different color in Signature.scss file, instead of theming variable.

**Comment by bjankord** [comment]
cc/ @vikonava @e3ujwh
