### ISSUE TITLE
InputField: Console warning when clearing an inputField 

### ISSUE THREAD

**Issue by mayurikini** [cerner/terra-core#1556]
# Issue Description
We see the following warning on console when we clear an inputField (input with type **number**). 
<img width="620" alt="screen shot 2018-05-31 at 3 20 48 pm" src="https://user-images.githubusercontent.com/16544484/40806352-ce8616b4-64e6-11e8-9dc1-9a7871ed7e86.png">

When we clear the (**controlled**) InputField, value is undefined and looks like [because this condition](https://github.com/cerner/terra-core/blob/master/packages/terra-form-input/src/Input.jsx#L94) we are getting the above warning. Sending null will not fix the issue.
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
We should not switch from controlled to uncontrolled InputField. There should be no such warning in console.

## Current Behavior
We get the above mentioned warning in console.

## Steps to Reproduce

Use Controlled <InputField> with type number and type some numbers and then clear the InputField.

**Comment by StephenEsser** [comment]
@mayurikini  

What happens when you set the value to an empty string on clear instead of null or undefined?

**Comment by JakeLaCombe** [comment]
Here's a guide that can assist with that as well. https://reactjs.org/docs/forms.html#controlled-input-null-value

**Comment by mayurikini** [comment]
I understand that this is a native behavior and that we can handle this from our end, but we will have to update the code every place where we use InputField. Every consumer who will ever need to consume InputField will have to add an extra code. I think it will be better if Terra handles it and removes the burden from consumer. :)

**Comment by bjankord** [comment]
We discussed amongst the team and plan to keep this behavior as-is. Using an empty string in your state value is what we'd recommend for clearing the input value.

**Comment by bjankord** [comment]
We can add docs on ways to avoid this. If you are unable to avoid setting the value as `undefined`, in the value prop, you can set a condition that will use an empty string if the value is undefined `value={this.state.value || ''}`

More info about this error message can be [found here](https://stackoverflow.com/questions/47012169/a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-erro?rq=1)
