### ISSUE TITLE
terra time input console error on focus change between hour and minute

### ISSUE THREAD

**Issue by doitnowshubham** [cerner/terra-core#1570]
i am getting a console error "Unable to get property 'preventDefault' of undefined or null reference" in terra-time-input component, on changing the focus between minute and hour using the keyboard events.
			the issue is only showing up in firefox and ie10, and in chrome it is working fine.
			i have used 24 hr time, and set format as HH:MM but in firefox the meridiem value is still undefined,
			i have attached all the images of the states difference between chrome and firefox, the error images and the console ouputs of ie10 and firefox
			there is some issue with the meridiem being undefined but only in firefox and ie10.
![chrome](https://user-images.githubusercontent.com/16742373/40967235-32d8ccb4-68d0-11e8-90c1-d4cd42913eb0.JPG)
![firefox](https://user-images.githubusercontent.com/16742373/40967241-3644fa58-68d0-11e8-81b1-d7d332f722d6.JPG)
![firefox_error](https://user-images.githubusercontent.com/16742373/40967255-3cbc43aa-68d0-11e8-992a-8fad56d30587.JPG)
![focus_on_hour](https://user-images.githubusercontent.com/16742373/40967256-3ecdc272-68d0-11e8-8dd3-28604f76f232.JPG)
![focus_on_minute](https://user-images.githubusercontent.com/16742373/40967262-40ec0ef6-68d0-11e8-9fa0-1ef33f8f7b89.JPG)
![hour_focused](https://user-images.githubusercontent.com/16742373/40967266-43023ba2-68d0-11e8-881f-8583e8df1354.JPG)
![ie10_detail](https://user-images.githubusercontent.com/16742373/40967269-44cf6c5c-68d0-11e8-9cf1-e455d31b5284.JPG)
![ie10_details2](https://user-images.githubusercontent.com/16742373/40967273-49496116-68d0-11e8-92a5-ce2de2cbf0b9.JPG)
![minute_focused](https://user-images.githubusercontent.com/16742373/40967281-4c1ac934-68d0-11e8-9211-ff7fa256d128.JPG)
![ie10_error](https://user-images.githubusercontent.com/16742373/40967453-a16519d0-68d0-11e8-8198-0be55805c73b.JPG)

**Comment by emilyrohrbough** [comment]
It appears the event was not passed to the focusMinute function [here](https://github.com/cerner/terra-core/blob/master/packages/terra-time-input/src/TimeInput.jsx#L373)

**Comment by JakeLaCombe** [comment]
Looks like the other focus functions failed with this as well. Looks like Chrome is filling in the event object by default for those functions?
