### ISSUE TITLE
[terra-status-view] Status view does not re-render on resize.

### ISSUE THREAD

**Issue by hs025828** [cerner/terra-core#1578]
# Issue Description
The status view does not re-render on resize which means the status glyph and message will not appear centered vertically.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
The status view should re-render during resize, repositioning its message and glyph in the center of its parent.

## Current Behavior
The status view does not re-render during resize so its client height remains fixed.

## Steps to Reproduce

1. Create a status view.
2. Resize it's parent.
3. Observe its position is incorrect.

## Environment

* Component Version: 2.13.0
* Browser Name and Version: Chrome 66.0.3359.181
* Operating System and version (desktop or mobile): macOS 10.12.6

**Comment by Blackop778** [comment]
Something such as https://stackoverflow.com/a/19014495/5863057 could be the solution

**Comment by yuderekyu** [comment]
@hs025828 are you referring to resizing the parent component consuming status-view? or resizing the browser window?

**Comment by hs025828** [comment]
@yuderekyu Its been a while since I logged the issue so my memory is fuzzy, but I **think** it was the browser window.
