### ISSUE TITLE
Date Picker Localization Incorrect for Placeholder

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#1600]
# Issue Description

When the Date Picker is translated into other languages, the placeholder for it *does* properly flex to the right format, but the initials used are incorrect:

For French (it should be AAAA not YYYY):
![image](https://user-images.githubusercontent.com/4873279/41418601-a72f3cb0-6fb5-11e8-9e58-c1520d1d9582.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

**Comment by Blackop778** [comment]
This isn't possible using momentjs, translation requests will have to be made.

**Comment by Blackop778** [comment]
Translations have been requested

**Comment by bjankord** [comment]
@Blackop778 Can you share the link to the translation request.

**Comment by Blackop778** [comment]
https://jira.cerner.com/browse/TRANS-5281
