### ISSUE TITLE
Need a way to disable auto-correct in search field

### ISSUE THREAD

**Issue by PaulSolDev** [cerner/terra-core#1604]
# Issue Description

Need a way to disable auto-correct in search field

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

![autocorrect 1](https://user-images.githubusercontent.com/29487301/41438240-3d952f62-6fec-11e8-8a68-97f0378ec2ae.png)
![autocorrect 2](https://user-images.githubusercontent.com/29487301/41438246-41cf6610-6fec-11e8-9496-ad83c8f909e4.png)

**Comment by bjankord** [comment]
Need to set input attributes on input: https://davidwalsh.name/disable-autocorrect

**Comment by yuderekyu** [comment]
Which attributes do we want to toggle? All of them? Certain ones? A new prop(s) could control this.

**Comment by bjankord** [comment]
My preference is let people set these via the `inputAttributes` prop. Curious what others think.
