### ISSUE TITLE
Unable to npm install/uninstall in sub-package

### ISSUE THREAD

**Issue by Blackop778** [cerner/terra-core#1606]
# Issue Description
Trying to install or uninstall a package from within a terra-core sub-package will generate an incredibly lengthy error ([truncated error paste](https://pastebin.com/vFP7SpND)).

Uninstall Tested commits:
* 689d793bde9036201ce52de187f4095b000a85d8 *passed*
* a0d87a22c55aa17318a8cca60bf1c1267818024e failed
* 4041d2974f04e6ac38ae75004a66d52c35696ff0 failed
* 71bd999377cb71a535916784539550d75902edd3 (latest) failed

Install Tested commits:
* 689d793bde9036201ce52de187f4095b000a85d8 *passed*
* a0d87a22c55aa17318a8cca60bf1c1267818024e failed
* 4041d2974f04e6ac38ae75004a66d52c35696ff0 failed
* 71bd999377cb71a535916784539550d75902edd3 (latest) failed

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

#### For Uninstall
The provided command will create a folder `terra-core-2` in the current working directory, clone terra-core, and attempt to uninstall `react-datepicker` from `terra-date-picker` on master branch.

`git clone git@github.com:cerner/terra-core.git terra-core-2 && cd terra-core-2 && git checkout master && npm install && cd packages/terra-date-picker && npm uninstall react-datepicker`

#### For Install
I tested installing `terra-clinical-item-view` and `terra-button` in `terra-list` and both failed.

## Environment
* Node version: v9.4.0
* NPM version: 6.0.0
* OS: OS X Sierra 10.12.6

**Comment by emilyrohrbough** [comment]
This is related more to how mono-repos install dependencies and moves each dependency to the root  `node_modules` directory. Talked offline on how this occurs.
