### ISSUE TITLE
Progress Bar inherits line height from terra-base, increasing the effective height

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-core#1607]
# Issue Description

The `terra-progress-bar` inherits line height from `terra-base` which effectively increases the box sizing of progress bars. If a progress bar is called out to take up, say 5px height, it will end up being closer to double that. This can be fixed by placing the progress bar inside a div with line height explicitly set to 0.

## Work around

```css
.progress-bar-height-fix {
  line-height: 0;
}
```

```jsx
const progressBar = (value, max) => (
  <div className={cx('progress-bar-height-fix')}>
    <ProgressBar color="green" value={value} max={max} hasGradient />
  </div>
);
```

### Bad Behavior

<img width="1658" alt="progress-bar-bad" src="https://user-images.githubusercontent.com/34115417/41472280-9206514a-707b-11e8-9ab1-4d9754ef9adb.png">

### Good Behavior

<img width="1669" alt="progress-bar-good" src="https://user-images.githubusercontent.com/34115417/41472299-a177bdbc-707b-11e8-8200-0347900474b6.png">

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

The height of the progress bar should not be dictated by any extra spacing or line height. If the progress bar is said to be 5px tall, then it should vertically take up 5px. 

## Current Behavior

The line height inherited from terra-base adds some extra spacing around the progress bar.

## Steps to Reproduce

1. Import terra-progress-bar
2. Include the progress bar in your component's markup
3. Render the component and inspect the progress bar
4. Observe that there's extra space that increases the progress bar's box size.

## Environment

* Component Version: latest
* Browser Name and Version: Chrome, Firefox, IE
* Operating System and version (desktop or mobile):

**Comment by bjankord** [comment]
I'm able to reproduce this on the doc site. The issue stems from the `display` of the progress element being set to `inline-block`. Switching the `display` to `block` resolves the height descrepency.  I'll get a PR out for this soon.
