### ISSUE TITLE
[terra-form-field] Enhance terra-field to left-align the field label

### ISSUE THREAD

**Issue by shinepd** [cerner/terra-core#1608]
# Issue Description
Enhance terra-field to left-align the label of the field rather than above the field.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Add a prop that will enable the consumer to position the label of the field where they'd like. In the screenshot below, ideally the "Chart At:" label could be left aligned.

![Desired Outcome](https://user-images.githubusercontent.com/22062222/41485053-a1550b68-70a4-11e8-8a5a-899e69f0c84f.png)

## Current Behavior
The label is fixed above the field.

**Comment by pranav300** [comment]
@neilpfeiffer I have created a branch [issue-1608-allow-customization-to-form-field](https://github.com/cerner/terra-core/tree/issue-1608-allow-customization-to-form-field). Please have a look at it and could you provide me with the dimension required for the label when it is left aligned.
Thanks.

**Comment by pranav300** [comment]
Had an offline conversation with @neilpfeiffer.
>It is something we won't fix for any immediate term, since providing left aligned labels creates a significant reliability problem, and we haven't been able to yet best solve for how reserve the left space that is agreeable to both UX and the Terra team, and work with both inline/flexible space plus fixed reserved space.

**Comment by ryanthemanuel** [comment]
Closing per the conversation mentioned above with @neilpfeiffer
