### ISSUE TITLE
Terra-Paginator needs to sync new selectedPage value

### ISSUE THREAD

**Issue by CoryMcDonald** [cerner/terra-core#1609]
# Issue Description
Currently the Paginator does not re-sync the selectedPage props when that prop is updated. We have a search box which rebinds the information and replaces it in the table.

![screen shot 2018-06-15 at 2 33 56 pm](https://user-images.githubusercontent.com/5459225/41486217-4a03e7da-70a9-11e8-8864-79e956294448.png)

## Issue Type
- [ ] Bug

## Expected Behavior

Terra should implement a `componentWillReceiveProps ` or the new `getDerivedStateFromProps` to sync the selectedPage to the correct value

## Steps to Reproduce
1. Create a function that will change how many items are in the paginator
2. Go to the next page
3. Change the function to return less or more items, essentially filtering them
4. Component is in an incorrect state

## Environment
* Component Version: 1.4.0
* Browser Name and Version: All
* Operating System and version (desktop or mobile): All

**Comment by saedar** [comment]
To give some context on my initial design: I had intended for the `selectedPage` option to be used for setting the initial selected page and the selected page for full-page refreshes.

**Comment by JakeLaCombe** [comment]
Here is what our proposal is.

This is the same scenario as a controlled vs uncontrolled input element. We need to create a version of the paginator that completely offshoots all the state handling of the current page off to the consumer. This will take in a page, and require onChange functions to be handled by the consumer, which are activated when the page on a paginator is changed.

**Comment by CoryMcDonald** [comment]
That makes sense for giving consumers a lot of control over the paginator. However because the totalPage changed I feel like that it would make sense if the calculation did math to check if the selectedPage was more than the totalPages and then reset the selectedPage back to the passed in value. If that value is over the boundary perhaps set it back to one.
 
Here's a gist that kind of demonstrates what we're doing in our component.
https://gist.github.com/CoryMcDonald/2d6fc0e58e08ef379e2414712313158f

**Comment by JakeLaCombe** [comment]
It's very difficult to have a component that switches between controlled and uncontrolled state. Mixing the two makes it hard to keep the state of the parent and state of the component in sync with each other, especially when the component is trying to change the value based on what was passed in.
