### ISSUE TITLE
Wrap the entire react-intl api with terra-i18n?

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#161]
Should we be wrapping the entire react-intl api in terra-i18n?

Currently, I need to import parts from both terra-i18n and react-intl:
https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/examples/I18nDemo.jsx#L2

Currently to use FormattedMessage, I need to import `react-intl` and `terra-i18n`. 
```
import { FormattedMessage } from 'react-intl';

import { I18nProvider, i18nLoader } from 'terra-i18n';
```

Should terra-i18n wrap the entire react-intl library?
```
import { I18nProvider, i18nLoader, FormattedMessage } from 'terra-i18n';
```

**Comment by bjankord** [comment]
We've decided to not wrap react-intl. Since applications will most likely need i18n outside of Terra, it would be best to pull it directly in and not have consumers rely on a transitive dependency from the Terra modules.
