### ISSUE TITLE
terra-form-select content dropdown has an offset

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-core#1613]
# Issue Description
When the border size is increased the dropdown itself is being pushed 1-2 px off the position it should be, this issue was noticed during the PR for the update for the consumer theme.

looks like something is happening for hookshot to position the list box in the incorrect position when setting transform: translate3d. It being off by -1px left and -1px top.

This problem was noticed during the PR for the consumer theme for the select component.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Dropdown should not have an offset from the input box

## Current Behavior
![consumer_select_problem](https://user-images.githubusercontent.com/535099/41546982-0939b7e8-72ed-11e8-8fda-2725065c2a57.png)

## Steps to Reproduce
deployment: https://pages.github.cerner.com/terra/cerner-consumer-theme/build/update-terra-select/#/site/components/core/site/form-select/index

CC: @dylan-sftwr  @StephenEsser @neilpfeiffer

**Comment by dkasper-was-taken** [comment]
closing, issue is the result of the consumer themes styles to html.
