### ISSUE TITLE
Update dialog styling and scrollable containers.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1614]
# Issue Description
Remove inner dialog-body div, wrapper div, and inner content styling.
Consume terra-scroll.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
The terra-dialog should provide a consistent content area for scrolling and expand to fill functionality in order to allow consumers to have access to scrollable values programmatically.

**Comment by ryanthemanuel** [comment]
Closing this in lieu of #1741
