### ISSUE TITLE
Update react-datepicker styles import

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1620]
# Issue Description
Currently, we import a `.css` file from react-datepicker. We believe this is triggering some warning at webpack compile time related to node-sass. [react-datepicker distributes](https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss) a `.scss` file in its npm package under the `src` directory. We could try importing that file instead and see if it resolves the issue.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Webpack compile runs without triggering node-sass warnings around importing `.css` files

## Current Behavior
Webpack compile runs with node-sass warnings around importing `.css` files

**Comment by emilyrohrbough** [comment]
We also import `.css` styles in [terra-markdown here](https://github.com/cerner/terra-core/blob/master/packages/terra-markdown/src/Markdown.jsx#L6)

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/commit/8e361e1561701d8bd249b20d1de3b883388bc406

@emilyrohrbough I'm not sure that the terra-markdown import casues node-sass compilation warnings since we are importing .css into a .js file. I think it is only an issue with importing .css files into .scss file.
