### ISSUE TITLE
preventDefault doesn't honor the active pseudo selector in firefox

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-core#1633]
# Issue Description
preventDefault is preventing the active pseudo selector from working in firefox, this bug is not present in any other browser(tested in chrome, safari, IE11, and edge)

source: https://bugzilla.mozilla.org/show_bug.cgi?id=771241
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
the active pseudo selector is applied as expected, for example with the select component when an user is selecting an option the "pressed-color" is applied, see attached gifs.

## Current Behavior
the active pseudo properties are not being applied when there is preventDefault, for the select component it is the pressed-color.

## Steps to Reproduce
Just click on one of the select options in the select component in firefox, gif shows it in action

In Chrome where it works correctly: 
![chrome](https://user-images.githubusercontent.com/535099/41736195-d2bad3d6-7559-11e8-9012-1fa2cdd52509.gif)

In Firefox where it does not work correctly, notice how when I'm pressing down on the option the color and background-color does not change:
![firefox](https://user-images.githubusercontent.com/535099/41736252-edda8f30-7559-11e8-8aba-f3779dfbda67.gif)

**Comment by bjankord** [comment]
It looks like the root issue of this is with how Firefox is handling the :active state with `preventDefault`. It looks like CSS spec is a bit ambiguous on how to implement :active. Since this a browser-based bug I don't think this is something we'll plan to resolve in this codebase. It doesn't seem to impede functionality.
