### ISSUE TITLE
[terra-props-table] Display imported PropTypes. 

### ISSUE THREAD

**Issue by adrian-94** [cerner/terra-core#1636]
# Issue Description

`Terra-doc-template` is unable to generate `Prop Table` for the props of a component if the component is importing `PropTypes` from other components. The page crashes as the imported `PropTypes` are not being parsed.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Expected to view Prop Table of component on the component site. 

## Current Behavior

Currently, the site page crashes as `terra-doc-template` is unable to obtain `Props` from the imported `PropTypes`.

**Comment by bjankord** [comment]
This is a limitation of [react-docgen](https://github.com/reactjs/react-docgen), the underlying library we use to generate the props table documentation. There is an [open issue for this in react-docgen](https://github.com/reactjs/react-docgen/issues/33), however, it does not look likely that it will be resolved.
