### ISSUE TITLE
[terra-form-select] background shadow is showing through border color of adjacent element

### ISSUE THREAD

**Issue by nagrawal3** [cerner/terra-core#1644]
# Bug Report

## Description

In terra form select, the box shadow for the select (--terra-select-focus-box-shadow) is showing through terra select toggle border style.

## Steps to Reproduce

1. Visit to the site page present on terra-core repo
2. Navigate to form-select component
3. Focus Search variant of select to see the style issue

## Additional Context / Screenshots

Lowlight style version
<img width="513" alt="terra-form-select lowlight style" src="https://user-images.githubusercontent.com/11468095/41862651-28011194-786a-11e8-8e20-e929a6e9e572.png">

Form select from deployed site url mentioned on terra-core repo
<img width="508" alt="terra-form-select default style" src="https://user-images.githubusercontent.com/11468095/41862652-2811f91e-786a-11e8-846d-4dfbc9263ab0.png">

## Environment

* Component Name and Version: terra-form-select 4.6.0
* Browser Name and Version: Chrome 67.0.3396.87
* Node/npm Version: [e.g. Node 8/npm 5] node 8.9.4 / npm 5.4
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by StephenEsser** [comment]
@nagrawal3 

What variables are you theming on the toggle border? The box shadow on the terra-core site appears to be behaving how I would expect, but the low light theme doesn't appear the way I would expect.

@neilpfeiffer 

Do you have any thoughts or adjustments in mind regarding the box shadow overlaying the toggle border?

![image](https://user-images.githubusercontent.com/6720991/41916063-d2f0e40a-791c-11e8-9e16-2ba4d03fce7a.png)
