### ISSUE TITLE
[terra-text] Long text with large font weight does not wrap correctly on small viewports

### ISSUE THREAD

**Issue by ChaseSinclair** [cerner/terra-core#1645]
# Bug Report

## Description
On very small viewports, such as the iPhone 5/SE, when using the Text component with a fairly large font weight (400+) the text does not wrap correctly. It, instead, expands past the parent container.

## Steps to Reproduce
1. Navigate to the `Text Weights` section on the terra-text doc site: https://engineering.cerner.com/terra-core/#/components/terra-text/text
2. Right click and inspect the 400 or 700 font weight example.
3. Change the text to something long such as a URL.
4. The text will expand past the parent container instead of wrapping.

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/5703475/41862282-134399d0-7869-11e8-9194-e8540cd81ed4.png)

## Expected Behavior
The text should wrap as it does for smaller font weights.

## Environment

* Component Name and Version: terra-text/v2.13.0
* Browser Name and Version: Chrome Version 67.0.3396.87, Safari Version 11.1.1
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version: v4.1.2
* Operating System and version (desktop or mobile): macOS Sierra Version 10.12.6

**Comment by bjankord** [comment]
# Tech Design
Add a new prop named `isWordWrapped`. Defaults to false. When set to true, this would apply cross-browser word-wrapping styles.

**Comment by yuderekyu** [comment]
Are there use cases where we wouldn't want word-wrapping to occur?

**Comment by bjankord** [comment]
Yes, with the way word wrapping works in various browsers, it can break words and make them appear as other words. This is a concern around medication names.

Here is an example of where the word wrapping causes an unexpected display.
<img width="277" alt="screen shot 2018-06-27 at 9 27 05 am" src="https://user-images.githubusercontent.com/633148/41980594-77f8e1c6-79ec-11e8-9179-cc8eb507b830.png">

By making this a prop, the user will need to consider there scenario and decide if the can safely apply word-wrapping styles.

**Comment by yuderekyu** [comment]
Ahhh gotcha. In that case, could we use hyphens, or does that also have the same obsfucation concern?
