### ISSUE TITLE
Add theming variables for Collapsible Menu View

### ISSUE THREAD

**Issue by Blackop778** [cerner/terra-core#1682]
I believe we should make the padding of the menu items/expansion button themeable, the border design for the divider, and the height of the divider.

**Comment by neilpfeiffer** [comment]
4 CSS items to add themeable variables :
```
.menu-button {
    ...
    padding-left: 0.714rem;
}

.face-up-item {
    ...
    padding-left: 0.714rem;
}

 .divider {
    border-right: 1px solid #dedfe0;
    height: 2.143rem;
  }
```
And in the JSX, we will need to switch the ellipse icon from importing from the terra-icon component to including it as a css variable and inline SVG, so changing this:
https://github.com/cerner/terra-core/blob/363bd082e612940ea79b9fe7aaeea7c9944250d6/packages/terra-collapsible-menu-view/src/CollapsibleMenuView.jsx#L156
to be instead like this:
https://github.com/cerner/terra-core/blob/363bd082e612940ea79b9fe7aaeea7c9944250d6/packages/terra-action-header/src/ActionHeader.jsx#L97
with CSS like this:
https://github.com/cerner/terra-core/blob/363bd082e612940ea79b9fe7aaeea7c9944250d6/packages/terra-action-header/src/ActionHeader.scss#L23-L25
