### ISSUE TITLE
Jest tests cannot be found on Windows

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#1686]
# Bug Report

## Description
When running the Jest tests on Windows, it reports that no tests are found. 

## Steps to Reproduce
1. Run `npm run jest` in the root of the project
2. Run `npm run test` inside of a package

## Expected Behavior
Jest tests run

## Possible Solution
I believe it's just because of the testMatch Regex using Unix separators. I think a combination of Jest's `testMatch` and `roots` can fix this.

```
  testMatch: [
    '**/jest/**/(*.)(spec|test).js?(x)',
  ],
  roots: [process.cwd()],
```

... but hoping to get some confirmation on the Mac side of things to make sure things still work, both when running at the root level and when running inside of a package.

## Environment
* Operating System and version (desktop or mobile): Windows 10 Enterprise

**Comment by bjankord** [comment]
Tested the proposed config change on macOS Sierra 10.12.6.
Ran jest at the root directory and inside an individual package directory, terra-button, and both jest scripts ran successfully. Thanks for the info @dv297 I've sent out a PR to update the config.
