### ISSUE TITLE
Migrate terra-react-svg-loader into repo

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#17]
# Issue Description

We had created a webpack react-svg-loader when we initially worked on terra-icon, however we pulled it as we ran into various issues with testing it. This issue is for re-evaluating the loader and  migrating that work into terra-core.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Ability to import an SVG icon and convert it to a react component on the fly via webpack loader.

## Current Behavior
N/A

**Comment by Matt-Butler** [comment]
If we ever need to revisit this, the oss code is located here: https://github.cerner.com/terra/terra-react-svg-loader/tree/oss
