### ISSUE TITLE
More Badge Themes

### ISSUE THREAD

**Issue by Blackop778** [cerner/terra-core#1714]
# Feature Request

## Description
UX would like to be able to have multiple types of Badge. My thought is to expand our intent system to include more variables.

List of proposed variables to add to intents (may or may not change based on war room on Friday):

- [ ] border
- [ ] background-image
- [ ] position *Maybe not (Needs wrapping container with `position: relative` so likely needs new component)
- [ ] position variables (top, left, right, bottom) *Maybe not
- [ ] font weight
- [ ] margin
- [ ] float *Maybe not (Works better when a wrapped in a flexbox than floated)
- [ ] font size *Maybe not (We do have classes with various font sizes, but we'd have to edit the code to add the class to get the proper size)

**Comment by emilyrohrbough** [comment]
Can you explain what you mean by position?

**Comment by Blackop778** [comment]
The position CSS property so the position of the badge can be finely controlled with top, right, etc by making position absolute

**Comment by yuderekyu** [comment]
If we're including background-image, we should probably include the rest of the background-styles.
