### ISSUE TITLE
Button Group Wrapping Issue

### ISSUE THREAD

**Issue by ChelseaRyanAnderson** [cerner/terra-core#1716]
# Bug Report

## Description
Text within the button group is wrapping, but not centered within the button (can be seen on the demo site at 320px wide)
[Terra UI](https://engineering.cerner.com/terra-ui/#/components/terra-button-group/button-group/button-group)

## Steps to Reproduce
1. Go to [Terra UI](https://engineering.cerner.com/terra-ui/#/components/terra-button-group/button-group/button-group)
2. Used Chrome inspect to reduce width to 320 px

1. Opened test harness for Orion Patient Search
2. Got to the search field page 
3. Used Chrome inspect to reduce width to 320 px 
4. Saw the text within the button groups did not wrap as expected

## Additional Context / Screenshots

Testing harness example: 
![screen shot 2018-07-18 at 3 56 49 pm](https://user-images.githubusercontent.com/35141408/42945176-47391950-8b2d-11e8-825b-d95274afffaf.png)

Terra UI example: 
![screen shot 2018-07-18 at 4 01 26 pm](https://user-images.githubusercontent.com/35141408/42945200-55cd91d0-8b2d-11e8-817a-2fa15ce27ba7.png)

## Expected Behavior
Text should center within each button group button

## Possible Solution
It looks like the span could be an issue?

![screen shot 2018-07-19 at 8 26 50 am](https://user-images.githubusercontent.com/35141408/42945271-90005874-8b2d-11e8-92b3-c934b17c2f2d.png)

![screen shot 2018-07-19 at 8 27 43 am](https://user-images.githubusercontent.com/35141408/42945292-a45b5026-8b2d-11e8-935c-989dc9d0b303.png)

## Environment
* Component Name and Version:
* Browser Name and Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Mac OS High Sierra 10.13.4 (17E199)

**Comment by JakeLaCombe** [comment]
Got closer with the issue. It looks like one of our spans need to have display: inline-block set on it. That should get the text to center.

 Reference: https://stackoverflow.com/questions/41149747/text-align-center-not-working

**Comment by neilpfeiffer** [comment]
Correction for whomever decides to pick this up - the issue lies with the Terra-Button and not Terra-Button-Group, since button group inherits it's internal structure, layout, and spacing directly from button.
