### ISSUE TITLE
Arrange: Fit End Alignment Stretch

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#172]
Stretch behavior differs between Chrome and Safari. The fit end alignment is set to `stretch` in both examples.

**Chrome**
![screen shot 2017-03-27 at 1 08 34 pm](https://cloud.githubusercontent.com/assets/8146159/24370862/83bfc92c-12ee-11e7-8e20-c751e16caf44.png)

**Safari** (desktop and mobile)
<img width="522" alt="screen shot 2017-03-27 at 1 07 20 pm" src="https://cloud.githubusercontent.com/assets/8146159/24370827/6cb47264-12ee-11e7-83d6-fedf66bd0bfc.png">

**Comment by bjankord** [comment]
I tested this some I believe setting the fit-end element to `display: flex` and removing `height: 100%` from the child element that sets the background will fix this in Safari. 

It raises a question, should all fit and fill elements all have `display: flex` set on them?

**Comment by bjankord** [comment]
I did some quick testing in IE/Edge with setting `display: flex` on both fit and fill elements. I don't believe we'll be able to use `display: flex` on the fill element, it requires `display: block` to work as expected in all browsers. Changing the fill element to `display: flex` causes odd rendering in IE10/IE 11.

IE10 Screenshot
<img width="988" alt="screen shot 2017-04-04 at 9 09 52 pm" src="https://cloud.githubusercontent.com/assets/633148/24686756/66de47f0-197b-11e7-979a-1e60d472b3ad.png">

IE11 Screenshot
<img width="1435" alt="screen shot 2017-04-04 at 9 13 49 pm" src="https://cloud.githubusercontent.com/assets/633148/24686879/1e64057c-197c-11e7-9f32-c4f5261fa9d2.png">

Need to do some more testing but I think fitStart and fitEnd elements should be good to use `display: flex`
