### ISSUE TITLE
Word wrapping in ActionHeader Component - title incorrect in Iphone5/SE view

### ISSUE THREAD

**Issue by ag044529** [cerner/terra-core#1726]
# Bug Report

## Description
Whenever the title in the Action Header is long, it doesn't wrap correctly. I would expect it to break the entire word into the next line but seems like only a part of the word is getting broken into next line.

## Steps to Reproduce

1. Create an Action Header with a very long title
2. View this is iPhone 5s/SE view.
3. The title breaks up the words oddly.

## Additional Context / Screenshots

![member not correct](https://user-images.githubusercontent.com/41591372/43095256-d5d8d34e-8e7a-11e8-93ea-f4dfaa79d7ce.JPG)

## Expected Behavior
I would expect it to break the entire word "member" into the next line.

## Possible Solution

word-break: break-word; for the child element in the component

## Environment

* Component Name and Version: Action Header 1.8.0
* Browser Name and Version: Latest Chrome on Windows when we inspect element and view in iPhone 5 mode.
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:     "html-webpack-plugin": "^3.2.0",
* Operating System and version (desktop or mobile): Windows (Desktop)

**Comment by sharynneazhar** [comment]
I can grab this issue too 🙂
