### ISSUE TITLE
Add refCallback to SearchField Component So That It Can Be Focused

### ISSUE THREAD

**Issue by juliacalandro** [cerner/terra-core#1728]
# Feature Request

## Description
My team wants the ability to place focus on the search field upon loading our search page. Currently, we don't believe this is possible, since the refCallback prop only exists on the Input component, and doesn't get passed down as a custom prop from the SearchField component. Therefore, we would like an optional inner refCallback prop to be added to the SearchField component. This would get passed straight into the refCallback prop of the inner Input component.

## Additional Context / Screenshots
I got the SearchField component to focus correctly from the terra-dev-site locally.
![screen shot 2018-07-23 at 3 28 16 pm](https://user-images.githubusercontent.com/39311706/43101118-115849b0-8e8d-11e8-88d6-9ca8b12ad1dd.png)
I have implemented the required change and will submit a pull request.

**Comment by bjankord** [comment]
This has been released in [terra-search-field@2.22.0](https://www.npmjs.com/package/terra-search-field)
