### ISSUE TITLE
Form-Select: Need to be able to deselect

### ISSUE THREAD

**Issue by kc4181** [cerner/terra-core#1736]
The problem:
Currently with any given select field, the user can not clear out their selection.  The placeholder text is not included in the list.

<img width="156" alt="screen shot 2018-07-27 at 11 08 01 am" src="https://user-images.githubusercontent.com/41794375/43332330-ba92a900-918d-11e8-86f0-042591fd0bf9.png">
 
The enhancement:
For form selects, there are use cases where the user needs to be able to deselect the previously chosen selection (ie - clearing a filter, etc).

**Comment by StephenEsser** [comment]
@kc4181 

The placeholder text can be added into the list by the developers. This gives each solution a way to conditionally provide a clearable option.

Here is a small code example:

```
  <Select placeholder="Select a color">
    <Select.Option value="" display="-- Select --" />
    <Select.Option value="blue" display="Blue" />
    <Select.Option value="green" display="Green" />
  </Select>
```

**Comment by bjankord** [comment]
Let's add an example to the doc site highlighting this functionality.

**Comment by bjankord** [comment]
Yeah, [providing an empty string for the value works](https://codesandbox.io/s/vy861825l3).

```jsx
class PlaceholderOptionExample extends React.Component {
  constructor() {
    super();

    this.state = { value: "" };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(value) {
    this.setState({ value });
  }

  render() {
    return (
      <Select value={this.state.value} onChange={this.handleChange}>
        <Select.Option value={""} display="- Select -" />
        <Select.Option value="apple_pie" display="Apple Pie" />
        <Select.Option value="cherry" display="Cherry" />
      </Select>
    );
  }
}
```

This matches how one would do this in plain HTML.

```html
<select>
    <option selected value="">- Select -</option>
    <option value="apple_pie">Apple Pie</option>
    <option value="cherry">Cherry</option>
</select>
```

**Comment by StephenEsser** [comment]
It comes down to styling. The example I put together reverts the Select back to having no option selected and displaying the placeholder text. The empty value approach selects an option without a value. Each approach puts the Select into two different states, both visually and pragmatically.  

The first option in the cleared state displays dithered placeholder text.

![image](https://user-images.githubusercontent.com/6720991/49981100-fa19e100-ff1b-11e8-9a2e-8482f7c3b2ca.png)

The empty value approach would display with the - Select - Option selected. ( No dithered placeholder text)

![image](https://user-images.githubusercontent.com/6720991/49981229-79a7b000-ff1c-11e8-9c6e-5b1774773a82.png)

This will probably need some UX feedback on. I believe there is currently a strong push to insert a clear option into the dropdown list that displays with dithered text and will revert the Select back into an unselected state displaying dithered text.

If we follow the native select approach a user must always have an option selected. If a solution wants the ability to "unselect" an option they must do so by providing an option that equates to having nothing selected "N/A, empty string, - Select -" etc... 

cc: @nickpith @bjankord @neilpfeiffer

**Comment by benbcai** [comment]
The following are feedback from UX:

- A new `allowClear` prop will be introduced. The clear option is only applicable to the COMBOBOX, DEFAULT and SEARCH variants. It is not applicable to the MULTIPLE and TAG variants because any selected option can individually be deselected. We will document that the `allowClear` prop is not applicable to select variants that allow multiple options to be selected and deselected. 
- When the clear option is selected, the selected option will be removed and reverts the Select back into an unselected state to show the placeholder.
- The display text of the clear option will be the same as the placeholder. If the placeholder is not provided or empty, the default placeholder will be used.
- The clear option should not be displayed while searching.
