### ISSUE TITLE
Deprecate Terra Dialog

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1741]
# Feature Request
Deprecate Terra Dialog.

## Description
Terra Dialog is no longer needed, as improvements to terra-action-header, terra-action-footer, and terra-content-container have supplanted it.

This will resolve #1614 and #1461 

## OCS Requested Documentation
When Terra Dialog is removed, we need to transition the component information into an Example/Recipe section of Terra-UI docsite, so it is clear for consumers how they should construct a dialog using `terra-content-container`, `terra-action-header`, `terra-action-footer`, etc. and ways to add content including the body section, fixed alerts/notifications, and patient identification/demographic banners.

**Comment by bjankord** [comment]
Plan to deprecate via npm.
