### ISSUE TITLE
Common Interface for Date, Time and DateTime picker controls

### ISSUE THREAD

**Issue by Nahusha-MS** [cerner/terra-core#1742]
# Feature Request

## Description

We have few differences in the implementation of date, time and dateTime pickers because of which these controls cannot be used interchangeably. The differences include : 
1. Date picker accepts value from selectDate attribute but time and dateTime accept from value attribute.
2. Date picker accepts focus handler from onFocus prop but time and dateTime accept from onInputFocus.
3. Date and DateTime pickers accept values in ISO-8601 format whereas time picker accepts in hh:mm format.  
Right now, if we want to have a common component, we should create wrappers around time and dateTime controls and map the attributes to the actual control props, which makes lot of code redundant and increase the complexity of the application

**Comment by bjankord** [comment]
We recommend making a wrapper component to handle this use case.
