### ISSUE TITLE
Add ability to specify message text position for Status View component

### ISSUE THREAD

**Issue by FTC7314Git** [cerner/terra-core#1743]
# Feature Request

## Issue Description
UX designers have requested the ability to Left-Justify the *message* prop.  The existing behavior only supports Center-Justify. 

## Issue Type
Enhancement

## Expected Behavior
Ability to set the message text position to either Center-Justify or Left-Justify.

**Comment by aberge00** [comment]
Oops, I opened this issue using my other github account.

**Comment by bjankord** [comment]
@neilpfeiffer can look into this and see if it aligns with Cerner's UX standards.

**Comment by neilpfeiffer** [comment]
@aberge00, have your UX designers reach out to me internally with their designs. This does not fit with our current Terra API design for the status-view, but may be possible through theming, but will need to talk through the details more with them to see how best to solve.

**Comment by neilpfeiffer** [comment]
UX team has proposed alternate solution via email to achieve the look without modifying current API. Waiting to hear feedback on proposal and will then close out this issue if no modifications needed.
