### ISSUE TITLE
i18n documentation improvement

### ISSUE THREAD

**Issue by Singleton06** [cerner/terra-core#1751]
# Issue Description
There are a couple of observations about documentation that I have noticed while trying to understand i18n in projects that consume terra.
* I'm assuming this is true of others, but when I want to learn about how to do i18n in the project, I went to components and searched for i18n.  Oddly enough, the component is named in the documentation I 18 N (with spaces).  This made it unsearchable.  Not sure if this is intentional or not.  I also realize that the reason that I searched for this in the components is because I saw it being used as a component in the past.  Maybe people who haven't seen this would search elsewhere.  Not sure.
* terra-i18n is mostly not expected to be used for doing i18n.  That is slight confusing to me, but I understand that there are probably technical reasons for this.  However, for the terra-i18n component, it would be nice if the documentation, before any other documentation, called out that terra-base is actually the expectation of where i18n would be handled and that usually the terra-i18n component is not even necessary.  As it is right now, the consumer is expected to go through two screens worth of documentation on terra-i18n before hitting the "Getting Started" section and be informed that they're likely not to even use it.
* By looking at terra-base, it appears that there is no documentation about translation aggregations.  This seems odd since there is an expectation that we should be using terra-base for the i18n.  It appears that terra-i18n documents this.  Even a link from terra-base to terra-i18n's header for Aggregating Translations (from terra-base) would be beneficial to make it clear that it is an expectation.
* Apparently there's a terra-toolkit approach that simplifies this?  I don't see this referenced in the terra-i18n or the terra-base.  terra-i18n does, however, have a link to this page: https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/docs/AggregateTranslations.md but that page does not mention terra-toolkit either.  The getting started webpack page does mention this, but there is an assumption that I would go look at a webpack page to get i18n working.

**Comment by kolkheang** [comment]
It looks like this documentation here https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/docs/AggregateTranslations.md is outdated.  I got a warning saying that the new approach is to use `terra-toolkit` [package](https://github.com/cerner/terra-toolkit).

It would be great to include the npm package and instruction how to set up this npm in the package.json file in this README too.

**Comment by bjankord** [comment]
This is something I'd like to get resolved before the end of the year.

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-ui/pull/132 and https://github.com/cerner/terra-core/pull/2144
