### ISSUE TITLE
Update Wdio Test Timeouts

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1756]
## Description
Several of our tests use commands of syntax `waitForX(element, time_in_ms)`. Be declaring a time, we are overriding the global wdio timeout vlaue defined in our wdio configuraiton. We should drop these timeout values in favor of using the default global values.

The wdio documentation on this is misleading because it states the default timeout is 500ms, but [digging into the source code, it actually defaults the to global timeout option](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/waitForVisible.js#L52). (which must be 500ms default for webdriver). [We define it as 3000 ms here](https://github.com/cerner/terra-toolkit/blob/master/config/wdio/wdio.conf.js#L38). 

This will allow for greater flexibility in writing reusable wdio tests.

**Comment by amichaelparker** [comment]
It looks like this may have been taken care of at some point. I searched through both core and framework, and none of the 'waitFor' tests have time values applied.

**Comment by emilyrohrbough** [comment]
@amichaelparker 

There are a few places throughout:
- https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js#L43
- https://github.com/cerner/terra-framework/blob/master/packages/terra-aggregator/tests/wdio/aggregator-spec.js#L34

**Comment by amichaelparker** [comment]
Not sure how I totally missed that one in framework! I'll take care of these (and any others I happen upon).
