### ISSUE TITLE
Add click event for Terra Input 

### ISSUE THREAD

**Issue by IoanaCalin** [cerner/terra-core#1760]
# Feature Request

## Description
Add the possibility to simulate a click event on an input, independent of what the type of the input is. 

## Additional Context / Screenshots
I want to let the user choose files from the device when a certain button is clicked. So I catch the onClick event of that button, and in this function I want to simulate the input type file click event.

**Comment by bjankord** [comment]
This can be achieved using the `refCallback` on input to access the actual DOM node for the input and trigger a click on that.
