### ISSUE TITLE
ActionFooter update styles & examples

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1764]
# Feature Request

## Description
The ActionFooter was initially released with styles from a different theme and need to be updated to match the Terra default open-source theme. Also now that the terra-hyperlink component is available, would be nice to update the 3 examples to use it instead of a generic `<a>` element. 

## Styles to Update
New styles to update component to:

- [ ] Default Padding
```
    $default-padding: 0.7142857143rem;
```

- [ ] Colors
```
    background-color: var(--terra-action-footer-background-color, #f9f9f9);
    border-top: var(--terra-action-footer-border-top, 1px solid #dedfe0);
```

- [ ] Top/Bottom Padding
```
    padding-bottom: var(--terra-action-footer-padding-bottom, 0.6428571429rem);
    padding-top: var(--terra-action-footer-padding-top, 0.6428571429rem);
```
\
\
Reference: current styles
https://github.com/cerner/terra-core/blob/ea44b96eb7aa0bee6ceac028bc61b3bc80ab9ce0/packages/terra-action-footer/src/ActionFooterContainer.module.scss#L1-L17

## Examples to Update
from:  `center={<a href="/#/site/action-footer/centered">A link</a>}`
to: `center={<Hyperlink href="#">A link</Hyperlink>}`

https://github.com/cerner/terra-core/blob/ea44b96eb7aa0bee6ceac028bc61b3bc80ab9ce0/packages/terra-action-footer/src/terra-dev-site/doc/example/centered/SingleAction.jsx#L9

https://github.com/cerner/terra-core/blob/ea44b96eb7aa0bee6ceac028bc61b3bc80ab9ce0/packages/terra-action-footer/src/terra-dev-site/doc/example/standard/SingleStartAction.jsx#L9

https://github.com/cerner/terra-core/blob/ea44b96eb7aa0bee6ceac028bc61b3bc80ab9ce0/packages/terra-action-footer/src/terra-dev-site/doc/example/standard/MultipleStartEndActions.jsx#L11

\
\
## Wrapping of content issue - variable height 
Need to fix so when needed, content wraps and not blow out of container. 
![image](https://user-images.githubusercontent.com/1355485/47376079-5ba99600-d6b7-11e8-9f6c-92f6ed3cdd43.png)

**Comment by jeremyfuksa** [comment]
Working on this.

**Comment by jeremyfuksa** [comment]
In order for the buttons in the multiple start/end action component to completely fold as the container shrinks, the button needs to be `display: flex`. Is that too opinionated for other use cases?
