### ISSUE TITLE
Remove extra padding in terra-toggle

### ISSUE THREAD

**Issue by vpandura** [cerner/terra-core#1774]
# Bug Report

## Description
terra-toggle contains extra spacing in the bottom which creates a white space. 

## Additional Context / Screenshots
Extra spacing - 
![screen shot 2018-08-15 at 5 13 40 pm](https://user-images.githubusercontent.com/10600570/44173682-a5ba3e00-a0ae-11e8-8c46-030bb6618d5a.png)

## Expected Behavior
Make padding below the component optional, so that this component can be used as a list-item, with no space between each one.

## Environment

* Component Name and Version: terra-toggle v2.18.0
* Browser Name and Version: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
* Node/npm Version: Node: 8.9.2 / yarn 1.3.2
* Webpack Version: 3.12.0
* Operating System and version (desktop or mobile): OS X El Capitan version 10.11.6

**Comment by bjankord** [comment]
I'm open to a PR for adding a prop, `isPadded` with a default value set to `false`. If people want padding as it is now, they can add the prop.

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/pull/1816
