### ISSUE TITLE
Make Alert message an entire paragraph

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1822]
# Feature Request
Terra Alert is constructed from two generic divs: one for the title and the other for the message. This is hard on screen readers, as it requires one key press to read the title, and another to read the error content. To make this more accessible, we should use a paragraph to encapsulate both the title and the message.

**Comment by bjankord** [comment]
Look into using aria-label to map to alert "title" and aria-describedby to map to alert "body content".

**Comment by bjankord** [comment]
This is reproducible on VoiceOver on iOS. When interacting with Alert, it seems to just read the message content and not the alert title. Though users can move to read the title. I agree with Jake, this would be a better experience if both the title and the message are read together when first interacted with.

**Comment by yuderekyu** [comment]
OCS changed the design so the `title` is on top, and the `text` is on bottom. i'm not sure what their intent is in regards to spacing the two- they may still have to be separate elements. otherwise, a paragraph with a line break should work

https://zpl.io/V4JExlz

**Comment by StephenEsser** [comment]
This is probably out of the scope of this issue, but I think it's worth having in mind while making changes to the component. `title` falls under one of the html attributes we want to avoid using for a conflicting component property. 

Similar to the issue logged here: https://github.com/cerner/terra-core/issues/1776
