### ISSUE TITLE
[terra-avatar] Enhancements

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1831]
# Feature Request
* Split avatar into three variants: Person, Facility, and Multiple (name pending). 
* Make other changes that will be listed in the tech design below.

**Comment by yuderekyu** [comment]
# Avatar Tech Design
`terra-avatar` will be split into three sub-packages: `user`, `location`, and `multi-user` (names pending) and be exported similar to [this](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/ApplicationUtility.js). They shall share themeable variables and common utils for determining color.
## Enhancements
### Color Support
* Support 10 color variants.
* Add color prop
	* Defaults to `auto`. Consumers can override this by passing `neutral` for a theme specific base color, or  one of 10 color variants: `one`, `two,`, `three`, `four`, `five`, `six`, `seven`, `eight`, `nine`, `ten`.
* Create shared color utils, utilized when `color="auto"`. This will hash the `alt` prop to determine  a color from the color variants. [Sample hash function.](https://werxltd.com/wp/2010/05/13/javascript-implementation-of-javas-string-hashcode-method/) 

### Other
* `alt` prop shall be required.
* Extract box-shadow to an `:after` selector. Addresses https://github.com/cerner/terra-core/issues/1845.
*  Support single initials for a user avatar.
* Spread custom props onto inner span. This allows an outer component to set `aria-hidden` on avatar.
* Make size in `em`'s - avatar shall scale based on its container's font-size.

## Removals
* Remove support for three initials from user avatar.
* Remove `ariaLabel` prop. Instead, use `alt` prop to set the `aria-label` attribute.
## Code Samples
### User
```jsx
import React from 'react';
import { User } from 'terra-avatar/lib/Avatar';

const AvatarUser = () => (
  <User alt="John Doe" initials="JD" />
);

export default AvatarUser;
```
### Facility
```jsx
import React from 'react';
import { Location } from 'terra-avatar/lib/Avatar';

const AvatarLocation = () => (
  <Location alt="Cerneeeer" />
);

export default AvatarLocation;
```
### MultiUser
```jsx
import React from 'react';
import { MultiUser } from 'terra-avatar/lib/Avatar';

const AvatarMultiUser = () => (
  <MultiUser alt="Squad" />
);

export default AvatarMultiUser;
```


## User Props

| Prop Name | Type | Is Required | Default Value | Description |
|-|-|-|-|-|
|alt | string | **required** | none | The text content that specifies the alternative text for the image. Also sets the `aria-label` for accessibility.
| color |PropTypes.oneOf([, 'auto', 'neutral', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']) | optional | 'auto' | Sets the background color. Defaults to 'auto'.
| image |string | optional | none | The image to display. |
| initials |string | optional | none | One or Two letters to display. |

## Facility Props

| Prop Name | Type | Is Required | Default Value | Description |
|-|-|-|-|-|
|alt | string | **required** | none | The text content that specifies the alternative text for the image. Also sets the `aria-label` for accessibility. |
| color |PropTypes.oneOf([, 'auto', 'neutral', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']) | optional | 'auto' | Sets the background color. Defaults to 'auto'.
| image |string | optional | none | The image to display. If no image is provided, fallback to facility icon. |

## MultiUser Props

| Prop Name | Type | Is Required | Default Value | Description |
|-|-|-|-|-|
|alt | string | **required** | none | The text content that specifies the alternative text for the image. Also sets the `aria-label` for accessibility.
| color |PropTypes.oneOf([, 'auto', 'neutral', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']) | optional | 'auto' | Sets the background color. Defaults to 'auto'.

**Comment by yuderekyu** [comment]
Updated to `avatar`. Added `isDesceased` prop to `avatar`.

**Comment by bjankord** [comment]
+1 on tech design.

> We need to determine if alt and the string we should hash could be separate.

I lean towards use `alt` unless a hash is provided via some prop. Not too concerned with the name of this prop.

**Comment by yuderekyu** [comment]
## Update 
* add first class `isAriaHidden` prop instead of spreading custom props on inner span. This will put the onus on consumers to know when to toggle this for accessibility 
* add `hashCode` prop. If provided, the hash function will use `hashCode` instead of `alt`

**Comment by mjhenkes** [comment]
+1 Make sure is deceased takes precedence Ofer any other color settings.

**Comment by benbcai** [comment]
1. Would MultiUser also need an `image` prop?
2. If no image is provided for Avatar, would it have a fallback icon like it does for Location?

**Comment by yuderekyu** [comment]
@benbcai 
1. MultiUser will only render an icon
2. Yes, the existing icon fallback logic will be applied to Avatar

**Comment by benbcai** [comment]
+1 on tech design.

**Comment by yuderekyu** [comment]
Update - making `isAriaHidden` default to false

**Comment by yuderekyu** [comment]
Anyone have an opinion on refactoring the `MultiUser` variant to `SharedUser`?

**Comment by bjankord** [comment]
shareduser sounds better to me compared to multiuser

**Comment by yuderekyu** [comment]
I have also changed `Location` to `Facility`, because location is a reserved word in js

**Comment by yuderekyu** [comment]
Changed `height` and `width` props to `size`. When avatar is resized, the initials will also scale correctly. 

https://github.com/cerner/terra-core/pull/2061#discussion_r235048195
