### ISSUE TITLE
Terra Hyperlink update icons from css to jsx

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1832]
# Feature Request
Enhance hyperlink to update variant icons (external, audio, video, image, document) from css to jsx

## Description
Update the Terra-Hyperlink component to switch from themeable icons provided by CSS to imported terra-icon component and inline content with JSX. This will allow the icons to be able to take the current-color of the text for all states (hover, active, visited, inactive, etc.).

## Other Items to Include:
- Determine if space between text and icon needs to be themeable
- Additional theming color value visited+focus state.
- The underline-hidden version needs to add additional text color theme values for all states (e.g. so when re-theming and basic hyperlink shows visited-state as purple, the underline-hidden version stays its own unique color and doesn't show as purple when visited).

**Comment by bjankord** [comment]
Planning to hold off on this change until around the end of Q2/beginning of Q3 to minimize major version bumps in the Terra UI ecosystem.

**Comment by nramamurth** [comment]
@neilpfeiffer 

What do we expect the color of visited+focus state to be in all the themes?

**Comment by neilpfeiffer** [comment]
This will mainly be a tech-only update (swap the icons and add additional theming variables).

\
Work needed is for:
- https://github.com/cerner/terra-core/pull/2666#discussion_r334440023: new variable for space between icon 

- https://github.com/cerner/terra-core/pull/2666#discussion_r334434956: all theme colors remain same are current, need to add theme variables for these states 
[ ] visited and focus (color),
[ ] underline-hidden and normal (color),
[ ] underline-hidden and hover (color),
[ ] underline-hidden and focus (color),
[ ] underline-hidden and visited (color),
[ ] underline-hidden and visited and focus (color),
(default theme has 1 WCAG color change: noted here)
(clinical-theme: [https://zpl.io/bew3P5D](https://zpl.io/bew3P5D) )

\
\
 Removing MVP label as this will be update to internal construction and not a major version.
