### ISSUE TITLE
[terra-action-header] Change button variants

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1835]
# Feature Request
Set buttons to `utility` variant, instead of `neutral`. https://app.zeplin.io/project/59b1bfeae515657fa8268300/screen/5a83150e74b47303abae22ef

**Comment by bjankord** [comment]
Planning to hold off on this change until around the end of Q2/beginning of Q3 to minimize major version bumps in the Terra UI ecosystem.

**Comment by ShettyAkarsh** [comment]
@bjankord should this be a MVB? as we will be mostly updating the button variants consumed internally.

**Comment by bjankord** [comment]
@ShettyAkarsh I'm going to defer to @ryanthemanuel on that call if this should be an MVB.

**Comment by ryanthemanuel** [comment]
@ShettyAkarsh if we aren't changing APIs, I'd say this is not a MVB.  Removing the label.

**Comment by nramamurth** [comment]
@neilpfeiffer I'd like to know your thoughts on the issues mentioned here  ⬇️

* [Themeable SVGs provided by CSS](https://github.com/cerner/terra-core/blob/master/packages/terra-action-header/src/ActionHeader.module.scss#L19-L41) could be removed and `terra-icon` could be used instead.

| Header Button | Terra Icon |
| ------------- | ------------- |
| Back  | IconLeft  |
| Previous  | IconUp |
| Next  | IconDown  |
| Maximize  | IconMaximize  |
| Minimize  | IconMinimize  |
| Close  | IconClose  |

Lmk if they match up. 

* ['Previous' and 'Next' buttons in the header constitute a button group](https://github.com/cerner/terra-core/blob/772f423487f80f766f01b6ad0f692519b0f097b3/packages/terra-action-header/src/ActionHeader.jsx#L127-L155); `terra-button-group` however [currently **always** renders 'neutral' variant buttons](https://github.com/cerner/terra-core/blob/master/packages/terra-button-group/src/ButtonGroupButton.jsx#L113). If we want 'Previous' and 'Next' (utility) buttons to be part of a button group, then this will mean that 
    * 'ButtonGroupButton' needs to be updated to receive a prop called `variant` and further propagate it to `terra-button`.
    * [ButtonGroupButton styles](https://github.com/cerner/terra-core/blob/772f423487f80f766f01b6ad0f692519b0f097b3/packages/terra-button-group/src/ButtonGroup.module.scss#L8-L66) need to be revisited again as they do not respect other variant styles _(if any)_. 

From a UX perspective, is there a reason why `terra-button-group` does not currently support different variants? I believe that these updates to `terra-button-group` will also help standardise the styles for the face-up items within the collapsible menu view _(if any)_. 

* [Toggle button in collapsible menu view](https://github.com/cerner/terra-framework/blob/9fcea5284e7c4b7621b3675249f8d0dadd47e064/packages/terra-collapsible-menu-view/src/CollapsibleMenuView.jsx#L151-L158) needs to be updated to allow consumers to switch between 'neutral' and 'utility' variants. 

* The current internal layout needs to be updated to reflect _any_ new spacing (padding/margin) constraints. Will the values be added on zeplin?

**Comment by neilpfeiffer** [comment]
> 'Previous' and 'Next' buttons in the header constitute a button group; terra-button-group however currently always renders 'neutral' variant buttons. If we want 'Previous' and 'Next' (utility) buttons to be part of a button group, then this will mean...

UX has intentionally not created variants for the button-group at this time. I'll post an update on how to handle changing this item, most likely making them independent buttons and handling visual grouping by exterior spacing.

\
.
> 'Previous', 'Next', 'Maximize', 'Minimize' are on the right in the design callouts but they are on the left in the current implementation. Which is the correct direction?

Action-header and other headers will be undergoing future re-work and the callouts/image you referenced most likely will be updated. Ignore those details as they do not apply for this issue. No current buttons should be adjusted or moved for this change.

**Comment by nramamurth** [comment]
@neilpfeiffer 

> UX has intentionally not created variants for the button-group at this time. An update on how to handle changing this item will be provided, most likely making them independent buttons and handling visual grouping by exterior spacing.

Then, I presume that that will mean - Collapsible Menu View also needs to undergo a change because it uses button group?

Also, do the [other points here](https://github.com/cerner/terra-core/issues/1835#issuecomment-541518155) sound good?

**Comment by neilpfeiffer** [comment]
@nramamurth Answers to all your questions:


> Then, I presume that that will mean - Collapsible Menu View also needs to undergo a change because it uses button group?

No -- for Collapsible Menu, only change is to add a new prop to switch _just_ the face-up collapsed `.menu-button` style from default to utility, no other changes to the internal Item(buttons), ItemGroup(button-groups), or Toggle(checkboxes), only change this button: 
<img width="41" alt="Screen Shot 2019-10-18 at 9 29 02 AM" src="https://user-images.githubusercontent.com/1355485/67102830-c639c880-f189-11e9-87a8-e70049533681.png">

----


> Themeable SVGs provided by CSS could be removed and terra-icon could be used instead.

No - consumer theme still needs independent icons - so can't remove as themeable svgs.

> 'Previous' and 'Next' buttons in the header constitute a button group; [...]

Switch the current previous/next button-group to individual/separate utility-style buttons, after you have a PR, I'll adjust the spacing to make sure there is still a visual connection/separation if all buttons are turned on.

> From a UX perspective, is there a reason why terra-button-group does not currently support different variants? [...]

UX intentionally does not want button group to have other styles currently, only neutral/default, the only option we might add in the future is a ghost-button style, but that is not currently requested or planned.

> Toggle button in collapsible menu view needs to be updated to allow consumers to switch between 'neutral' and 'utility' variants.

Yes - same comment as above - add prop to collapsible menu to change the style of the `.menu-button` to be able to change to utility style.

> The current internal layout needs to be updated to reflect any new spacing (padding/margin) constraints. Will the values be added on zeplin?

Yes - already posted - you can use the Clinical theme details for understanding how it should change: https://zpl.io/V1ZZOd4  

> 'Previous', 'Next', 'Maximize', 'Minimize' are on the right in the design callouts but they are on the left in the current implementation. Which is the correct direction?

None of the buttons change location to solve for this issue. Future MVB rework of action-header will adjust API and position of those button actions.
