### ISSUE TITLE
Make Terra Paginator more accessible

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1837]
# Bug Report

## Description
Terra Paginator needs more enhancements in order for it to be fully accessible:

For every page, it should say “Goto Page #”
For the current page it should say “Current Page, Page #”
First, Previous, next and last stay the same
These rule apply for both paginates

https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe

**Comment by neilpfeiffer** [comment]
Re-opening - requesting new translations for for "Go to Page #" and "Current Page, Page #" and will close when added.

**Comment by neilpfeiffer** [comment]
Converted to new issue and including need for translations #2527
