### ISSUE TITLE
Terra Table doesn't explicitly say what rows are selectable on a screen reader.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1839]
# Bug Report

## Description
Screen readers read selected table rows just fine. Selectable rows however are missed by the screen reader. We need to add the approrpriate labels and rows to prevent this.

**Comment by bjankord** [comment]
Noticed a related issue with VoiceOver on mobile when viewing https://engineering.cerner.com/terra-core/#/tests/terra-table/table/table/table-with-highlighted-rows

The status of a row being highlighted is not communicated to VO.

**Comment by bjankord** [comment]
Related info: 
* https://stackoverflow.com/questions/7554317/aria-selected-attribute-for-row-selection-in-a-grid
* http://adrianroselli.com/2017/11/hey-its-still-ok-to-use-tables.html
It sounds like we should explore the concept of aria-grid for tables that support row selection.

**Comment by bjankord** [comment]
One idea that came to mind on this was, when a table row is selected, update an aria-live region with the wording, "Row selected". At the same time append that text to the table cells in the row that is selected as visually-hidden text. What this should enable is that when a row is selected, the screen reader will announce "Row selected". If the user navigates through table cells in a row that is selected, it should read the table cell content followed by "Row selected" due to the appended visually-hidden text.

**Comment by bjankord** [comment]
I think we'll want to reconsider how we markup selectable tables. This task seems to be more complicated than originally anticipated.

I think we'll want to look at role="grid" based tables and the associated markup when a table needs selection interaction.

More info: 
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role
* https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/grid/dataGrids.html
* https://www.powermapper.com/tests/screen-readers/tables/table-role-grid/
* http://davidmacd.com/test/grid.html

**Comment by JakeLaCombe** [comment]
So while researching how to resolve this issue, there is an issue to note with JAWS.

JAWS has the concept of table mode, which allows for users to interact with a table by using the arrow keys. By hold ctrl+atl or other defined keys, a user is able to then navigate through the various cells by simply using the arrow keys. However, table mode does not allow for a user to interact with the table using space, enter, or other various keys while in this mode. This means that a user would use table mode to select a cell, leave table mode, then press space or enter to select the said row.

**Comment by bjankord** [comment]
Resolved with https://github.com/cerner/terra-core/pull/2331

**Comment by bjankord** [comment]
We've reverted the accessibility changes that resolved this due to it causing issues with various consumers. 
Reopened with the revert: https://github.com/cerner/terra-core/pull/2412

**Comment by bjankord** [comment]
In recent leadership discussions, we've talked about deprecating the row selection ability in terra-table. We would be replacing this functionality with a new component to handle similar display and provide an accessible row selection status update.

**Comment by ryanthemanuel** [comment]
Closing this with respect to Brett's comment
