### ISSUE TITLE
[terra-form-fieldset] Remove default test example

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1843]
# Bug Report
There is a [form-fieldset test example](https://engineering.cerner.com/terra-core/#/tests/terra-form-fieldset/form-fieldset/default-fieldset) that isn't tested in the [spec](https://github.com/cerner/terra-core/blob/master/packages/terra-form-fieldset/tests/wdio/fieldset-spec.js#L6). We can remove this.

**Comment by bjankord** [comment]
@AlexBrizi For this, just need to delete this file: https://github.com/cerner/terra-core/blob/master/packages/terra-form-fieldset/src/terra-dev-site/test/form-fieldset/DefaultFieldset.test.jsx
