### ISSUE TITLE
OCS Color Variables Instead of Hard Coded Hex Color Values

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-core#1852]
# Feature Request

In order to help bridge the gap between UX and IP, reduce user input error, and increase readability, I'm proposing using OCS color variables instead of hard coded hex values for colors in component implementations.

## Description

In the following [gist](https://gist.github.com/dev-cprice/68015e36542b96b1b463ede7f0538511), I have listed all of the [OCS terra-opensource-theme](https://zpl.io/bAOdZ66) colors as sass variables. We can consume this in all components and replace all hardcoded colors with their variable equivalents.

The colors can live either in `packages/terra-mixins` or under a new package `packages/terra-colors` or `packages/terra-ocs-colors`.

**Comment by mjhenkes** [comment]
Hi @dev-cprice, 
When we put together theming we discussed doing something like this but determined that it simplified and limited color usage beyond what we're comfortable with. 

The terra opensource theme uses more colors than are defined in this list and they're used correctly. States like focus, hover, active, and disable will all modify the color pallet listed here. We could continue to add colors to this list but then naming these additional colors becomes an issue. Hex values provide a unique name and an unlimited color palette.

Additionally if we added this aliased list of colors, developers outside of terra would definitely reuse the colors for a wide range of uses. While on the surface this seems like a good thing (yay reuse and one place to alter the theme!) It could definitely lead to problems, it's not granular enough. Any changes to these aliased colors would have wide reaching and unknowable impact. Color contrast ratios could break in random ways and the best way for a component to isolate itself from these changes would be to use the hex color directly.

**Comment by bjankord** [comment]
I talked with UX about this and they had a good proposal to avoid the concerns @mjhenkes listed above. One could make [a snippet package](https://code.visualstudio.com/docs/editor/userdefinedsnippets) for the colors for code editors. This would offer similar benefits to a scss variable file as users could type the color keywords UX uses in their editor without the concerns a global scss variable file introduces. If we can get a list of OCS colors, I'd be open to working on a snippet package for them for VS Code.
