### ISSUE TITLE
Hold and scroll through options doesn't work in Select box in IE 11 and IE 10

### ISSUE THREAD

**Issue by arifakram05** [cerner/terra-core#1863]
# Bug Report
Scroll bar doesn't work let a user scroll through select options in select field.
## Description

I am using this component - https://github.com/cerner/terra-core/blob/728a5106f1e3fb113b3956cefeca996468b0ffb8/packages/terra-form-field/src/Field.jsx - This works fine in Chrome, however it doesn't work as expected with IE 11 and IE 10 browsers. Also, this doesn't work inside Powerchart.

Scrolling through select field with options with a mouse with a wheel lets a user scroll through select options. However, when trying to hold the scroll bar and drag it down makes the select options disappear. I am attaching a video recording of this.
## Steps to Reproduce

1. Open an application that has **field** react component.
2. Have many select options in it.
3. Click to open the select field.
4. Try to scroll down by holding the scroll bar

## Additional Context / Screenshots

[Terra Form Field Issue.pptx](https://github.com/cerner/terra-core/files/2380022/Terra.Form.Field.Issue.pptx)

## Expected Behavior

User should be able to click and hold the scroll bar on select field and navigate through all the select options.
## Possible Solution

NA
## Environment

* Component Name and Version: Terra Form Select - https://terra-ui.herokuapp.com/#/components/terra-form-select/form-select/select
* Browser Name and Version: IE 10 and IE 11
* Node/npm Version: [e.g. Node 8/npm 5]  Node 8 and npm 6
* Webpack Version: 3
* Operating System and version (desktop or mobile): Windows 10

**Comment by StephenEsser** [comment]
@supreethmr  Why was this issue closed?

**Comment by supreethmr** [comment]
> @supreethmr Why was this issue closed?

Oops sorry my bad. I might have clicked on close and comment instead of comment.

**Comment by supreethmr** [comment]
this Issue can be resolved by resetting the focus back into dropdown like below :
`handleBlur(event) {
  // Fix - code changes
    if (this.dropdown && (this.dropdown === document.activeElement && 
        this.dropdown.contains(document.activeElement))) {
           this.focus();
           return;
    }
  // Fix - code changes

    this.closeDropdown();

    if (this.props.onBlur) {
      this.props.onBlur(event);
    }
  }`

Since IE was firing blur event on click of scroll bar of drop down, Added the check dropdown.contains(activeElement) to prevent IE11 from closing the dropdown on click of scrollbar.

Dropdown will remain open since focus is reset to active element on blur event. 

Please share your thoughts on this fix.
