### ISSUE TITLE
[terra-menu] Extract header text from back button

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1864]
# Feature Request
When bounded, Menu renders header text within the back button. So, the click target is the back button + header text.  It is now expected for the click target to only encompass the back button. 

## Potential Solution
* Render back button with `fitStart`
* Render header text with `fill`

**Comment by neilpfeiffer** [comment]
Gathering multiple enhancements items for `terra-menu` into one combined issue: #1883
