### ISSUE TITLE
[terra-form-select] Combobox variant text truncation inconsistent across browsers

### ISSUE THREAD

**Issue by PolymorphedSquirrel** [cerner/terra-core#1878]
# Bug Report

## Description
text-overflow handling varies by browser within terra-form-select.

## Steps to Reproduce
1.  Launch Chrome
2.  Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-form-select/form-select/select
3.  Observe text-overflow: ellipsis style behavior for the combobox variant.
4.  Launch IE 10 or 11 (preferably 10)
5.  Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-form-select/form-select/select
6.  Observe lack of text-overflow: ellipsis style behavior for the combobox variant.
7.  Add in-line styles via devtools and observe that the style is not honored.

## Expected Behavior
Text truncation with an ellipsis in all browsers

## Environment
* Component Name and Version: terra-form-select 4.17.1
* Browser Name and Version: Chrome Version 68.0.3440.106 and Internet Explorer 11.1266.15063.0 (also in IE 10 mode)
* Node/npm Version: Node v8.9.4/npm v5.6.0
* Webpack Version: N/A
* Operating System and version (desktop or mobile):  Windows 10

**Comment by StephenEsser** [comment]
Internet Explorer does not support an ellipsis text-overflow for **inputs** unless the input is **read-only**.

The only work around I have been able to find requires using javascript to toggle the readonly state of the input on and off. 

### Logged Issue
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15550368/

### Workarounds
https://stackoverflow.com/questions/13875889/input-text-overflow-ellipsis-for-opera-and-ie-does-not-work
https://frontendtricksandmagic.wordpress.com/2015/03/07/how-to-make-text-overflow-ellipsis-work-for-inputs-in-ie/

**Comment by PolymorphedSquirrel** [comment]
Is there any chance of additional props for component which would give consumers direct access here?  This quality of life improvement with addition of onClick, onFocus, and onBlur would add a good deal of extra value for usage as a controlled component.

**Comment by StephenEsser** [comment]
The Select does support onClick, onFocus, and onBlur. Are you wanting these callbacks available on the `<input />` separate from the component itself?

**Comment by PolymorphedSquirrel** [comment]
Those aren't documented with the component, so from a consumer standpoint, this feels like it could introduce some risk for non-passive changes down the line.  I have confirmed that they do work correctly with the customProps being passed down and attach to the input.  That said, the behavior of the library is still inconsistent across supported browsers.

**Comment by StephenEsser** [comment]
Documentation for onFocus, onBlur, and onClick can be moved into a first class prop declaration so they can be listed on the documentation page if they are frequently used properties. 

Because most components support custom property spreading it's just not possible to document all valid html attributes and functions that can be spread using custom properties. The challenge is finding a balance for documenting the most appropriate attributes.

For the browser inconsistency, have you seen any inconsistent behavior other than the text truncation?

**Comment by PolymorphedSquirrel** [comment]
The only other thing noted is a placeholder text inconsistency.  When focusing into an input, the placeholder text remains until the user has typed into the field in Chrome, while IE immediately removes the placeholder upon focusing.

When focus is placed into a variant that allows multiple selections while one or more selection is populated into the Select, the placeholder text is visible in Chrome.  This will not be visible in IE.  I'm unsure which one is the intended behavior in this case, but I am assuming the Chrome behavior is the expected result.

**Comment by StephenEsser** [comment]
The behavior noted in both situations is browser native. The inputs are behaving according to the default implementation of the browser. This is a good conversation we'll need to have with UX to determine if consistency between browsers trumps the native behavior of each browser. 

If UX decides in favor of overruling browser native behavior there will likely be a significant amount of technical changes that would need to happen to normalize between browsers. 

cc: @neilpfeiffer

**Comment by bjankord** [comment]
Would like to investigate this some more. After discussing with them, we think there could be concern around data being truncated that we'd want to be sure is communicated to users.

**Comment by ShettyAkarsh** [comment]
@neilpfeiffer As both the issues are IE browser specific. so can you please review this issue and let us know whether we need to proceed with the investigation and fix it?

**Comment by ryanthemanuel** [comment]
Closed.  We'll call this a known IE variance in behavior based on @neilpfeiffer's comment
