### ISSUE TITLE
[terra-alert] Missing OCS

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1882]
## Feature Request
Notification Banners / Alerts:
- OCS requests alert to toggle between two variants: a "page level" alert and "component level" alert. Further discussion is needed.
- Custom buttons (or button-style overrides) specifically for use inside of alerts.
- Update handling of overflow (Show/Hide) per updated OCS designs.
- Revisit how to handle Advisory, Gap Checking, Outside Records.

For reference, go to the "types" section - https://zpl.io/bPdY3xm

**Comment by emilyrohrbough** [comment]
Will need to determine if this is applicable: https://github.com/cerner/terra-core/issues/2603
