### ISSUE TITLE
ButtonGroup tests route looks like its not redirecting

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#189]
### Description of Issue
When navigating to the nightwatch test urls, http://engineering.cerner.com/terra-core/#/tests, clicking on the Button Group Tests link does not redirect to the page for button group tests.

###System Configuration
#### Component Version 
ButtonGroup v0.0.0

#### Browser and Version
Chrome

### Steps to Reproduce the Issue
1. Step 1:  navigate to http://engineering.cerner.com/terra-core/#/tests
1. Step 2: Clicking on the Button Group Tests link

### Expected Outcomes
- Link redirects to the page for button group tests

**Comment by Matt-Butler** [comment]
It looks like this issue has been resolved.
