### ISSUE TITLE
Unselectable buttons in button group do not convey that they are unselectable using VO on iOS

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1895]
# Bug Report

## Description
When interacting with buttons in a button group that are not selectable, VO on iOS does not convery that button is not selectable.

## Steps to Reproduce

1. Navigate to https://engineering.cerner.com/terra-core/#/tests/terra-button-group/button-group/button-group-not-selectable
2. Move focus on to non-selectable button
3. VoiceOver will read "${textOfButton}, toggle button, not pressed, double tap to toggle setting"

## Expected Behavior
VO should not indicate that the button is a toggle button or that the user could double tab to toggle the setting.

## Possible Solution
Remove `aria-pressed` attribute when button is not selectable

## Environment

* Component Name and Version: terra-button-group
* Browser Name and Version: Mobile Safari 12 w/ VoiceOver
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): iOS w/ VoiceOver

**Comment by supreethmr** [comment]
this issue has been resolved by #2231
