### ISSUE TITLE
Use abbreviation for required asterisk on forms

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1903]
# Feature Request

## Description
When testing with VoiceOver on one of our required fields examples, I noticed the screen reader reads the asterisk that denotes the field is required as "Star". We should look into what patterns people are using to communicate required fields to screen readers. My initial thought is we should mark this up as an asterisk that is an abbreviation for "Required field"

**Comment by JakeLaCombe** [comment]
I see some here. It looks like using the required and the aria-required attributes on the individual form inputs. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Basic_form_hints
