### ISSUE TITLE
Add VisuallyHiddenText component

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#1904]
# Feature Request

## Description
To Improve Terra for accessibility, it is recommended that we add specific text to components that is visually hidden, meaning only a screen reader would be able to pick it up. This requires a unique set of styles, and what we want to get out of is having those styles copied across several components.

To make using those styles easier, I recommend we create a VisuallyHiddenText component that takes in just text, and hides it from the UI. All it would need is a single prop of text, which is a string.

**Comment by bjankord** [comment]
More info: https://accessible360.com/accessible360-blog/use-aria-label-screen-reader-text/
