### ISSUE TITLE
ResponsiveElement doesn't pass down custom props

### ISSUE THREAD

**Issue by SusmithGayam** [cerner/terra-core#1930]
# Bug Report
ResponsiveElement doesn't pass down custom props

## Description
I have Aggregator wrapped around ResponsiveElement. Aggregator sends down aggegatorDelegate prop and that is not being passed to the components in the responsiveElement since the responsive element doesn't send down custom props

## Steps to Reproduce
```
<Aggregator> #sends down aggregatorDelegate prop
   <ResponsiveElement>
       tiny={<someComponent>//this component doesn't get aggregatorDelegate prop }
   </ResponsiveElement>
</Aggregator>
```

## Expected Behavior
Responsive Element should send down customProps. So that the user doesn't have to use wrapper around responsiveElement to get the props and again pass the custom props down to responsive element.

## Possible Solution
Modify ResponsiveElement to send down customProps

**Comment by bjankord** [comment]
Talked through some options of passing props directly to children or use new context API to make props available to children.

**Comment by StephenEsser** [comment]
After discussions with the Terra team we are closing this issue.

There are concerns around cloning and overriding props on each element defined within the responsive element. The custom property pattern is intended to be applied only to a top-level component wrapper that has a defined set of PropTypes. Spreading custom properties onto unknown elements poses a risk of introducing unsupported properties and overriding existing properties.
