### ISSUE TITLE
Remove isTransparent prop from section header and toggle section header

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1933]
# Feature Request

## Description
UX has requested the removal of the `isTransparent` prop from section header and toggle section header.

**The isTransparent prop is now deprecated on section header and toggle section header.** We'll add documentation indicate that this prop is deprecated on the doc site as well.

When we ready to do a major version bump on these components, we'll remove this prop.

## @ Mentions
@neilpfeiffer @celvro

## Related Issues
Also closes #1799 (isTransparent bug with List and button in IE)

**Comment by hboege** [comment]
So for those of us using the Transparent prop, what do we use instead?  Is there a queue, board, team that will be helping teams transition through non-passive changes?

**Comment by bjankord** [comment]
@hboege I'd recommend consulting with your UX designer or the OCS team. No migration path was provided to us, only that this visual treatment for the section header and toggle section header should not be available. Pinging our UX designer to see if they can provide any insight as well. @neilpfeiffer

**Comment by neilpfeiffer** [comment]
Thanks @hboege - the project designer has already reached out to me and we will work on figuring out  options as to how to resolve for your needs. Nothing has been decided as of yet, but I will work with UX designers on solving any transitions case-by-case.

**Comment by bjankord** [comment]
Planning to hold off on this change until around the end of Q2/beginning of Q3 to minimize major version bumps in the Terra UI ecosystem.
