### ISSUE TITLE
iOS Fixed Position Modal Bug

### ISSUE THREAD

**Issue by dkschoonover** [cerner/terra-core#1935]
# Bug Report

## Description
Editable fields in fixed content (ie Modals) do not behave as expected.  iOS accounts for the keyboard by natively shifting up the view.  When quickly switching between editable fields, it's possible this shifting can get off.  See the attached image below.

## Steps to Reproduce
1.  Have an editable field on the page, in a modal
2. Select the editable field
3. Quickly deselect, then reselect the field

Note: this doesn't happen every time, and may be more prone to UIWebview and not Safari.  Programmatically blurring and refocusing the element could help reproduce the issue as well.

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/28159802/46225182-172c1400-c31e-11e8-8c35-26640d8c3d79.png)

## Expected Behavior
The modal and modal overlay do not shift up when changing focus between editable fields.

## Possible Solution
Switching to absolute positioning for the modal and modal overlay resolves the problem.  There are many documented bugs around fixed positioning and how it responds to the keyboard on iOS.  

## Environment
* Component Name and Version: N/A
* Browser Name and Version: UIWebview, iOS 11.2, iOS 11.4
* Node/npm Version: 9.2.0, 5.5.1
* Webpack Version: 4.20.0
* Operating System and version (desktop or mobile): Mobile iOS

## @ Mentions
@dkasper-was-taken, @tbiethman

**Comment by bjankord** [comment]
@dkschoonover This has been released in terra-abstract-modal@1.19.0
