### ISSUE TITLE
Export intlProvider from terra-base

### ISSUE THREAD

**Issue by corymcdonald** [cerner/terra-core#1944]
# Feature Request

## Description
Currently we export injectIntl, and a lot of the other things from react-intl. In order to completely removed the dependency on `react-intl` for consumers it would be nice to be able to `export intlProvider`. 

Introduced by: https://github.com/cerner/terra-framework/pull/293

**Comment by bjankord** [comment]
Yeah, let's export this. The desired use of intlProvider would still be through using the `<Base />` component, but to help alleviate some testing issues, I'm fine exporting this.

**Comment by bjankord** [comment]
@corymcdonald This has been released to npm in terra-base@3.24.0
