### ISSUE TITLE
[terra-notification-dialog] Variant Icon does not display in IE 11

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#1962]
# Bug Report

## Description
[terra-notification-dialog](https://engineering.cerner.com/terra-ui/#/components/terra-notification-dialog/notification-dialog/notification-dialog) renders different in IE 11 and Chrome. The variant icon doesn't show up at all in IE 11. See screenshots below.

## Steps to Reproduce
1. Open https://engineering.cerner.com/terra-ui/#/components/terra-notification-dialog/notification-dialog/notification-dialog in IE 11

## Additional Context / Screenshots
![notification-dialog-no-icon-ie11](https://user-images.githubusercontent.com/5365325/46625382-65e56500-caf9-11e8-90b5-539e76ca479b.PNG)

## Expected Behavior
Icon shows

## Environment
* Component Name and Version: terra-notification-dialog
* Browser Name and Version: Internet Explorer 11.665.16299.9
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-framework/pull/308
