### ISSUE TITLE
[terra-scroll] [terra-content-container] Investigate terra-scroll css causing scrollbar to overlap content

### ISSUE THREAD

**Issue by PolymorphedSquirrel** [cerner/terra-core#1968]
# Issue Description
Please investigate potential removal of [this css](https://github.com/cerner/terra-core/blob/master/packages/terra-scroll/src/Scroll.module.scss#L6) to prevent IE scrollbars from overlapping content.

The scrollbar in the scrollable body area of a ContentContainer overlaps content, which may hide visual indicators from the user.  This is due to [this css](https://github.com/cerner/terra-core/blob/master/packages/terra-scroll/src/Scroll.module.scss#L6) found in terra-scroll.  The behavior of the -ms-autohiding-scrollbar style is correct as per the [documentation,](https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-overflow-style#Values) but my understanding is that this was done to resolve a rather old issue during a time when IE9 was supported (from speaking with @dkasper-was-taken ).  

Other issues that my arise from this are clear communication of scrollable content to the user when not over the scrollable area.  Consider clicking a button on a navigation bar as the header, which changes the content displayed inside the body.  If this content happens to align correctly, such that there is nothing cut off, the scrollbar will not appear unless the user hovers over the scrollable area.  This could result in the user navigating to content via header, reading the content, and not knowing that there was information that they were not shown unless they mouse over the area.

Could this be investigated to see if usage of the -ms-autohiding-scrollbar is still necessary?  It is not well respected by flex

## Additional Context / Screenshots
Behavior in IE:
![image](https://user-images.githubusercontent.com/43280824/46879118-bebf4100-ce0a-11e8-9a56-6ccc09b183ff.png)

Behavior in Chrome:
![image](https://user-images.githubusercontent.com/43280824/46879532-ed89e700-ce0b-11e8-8f25-996bef6ff421.png)

Style Disabled in IE (mimics Chrome behavior):
![image](https://user-images.githubusercontent.com/43280824/46879644-2de96500-ce0c-11e8-978d-2d3c16f28448.png)

**Comment by Matthematic** [comment]
Has there been any decision from the result of the spike for this? This has been affecting me as well, due to the computed value for width: '100%' being different with this autohiding scrollbar in IE compared to chrome. It would be nice if all browsers behaved the same with respect to the overflowed content being squished vs overlayed.
