### ISSUE TITLE
Investigate Button programmatic focus styling

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#1969]
# Bug Report

## Description
Buttons use custom focus styling, and when they are programmatically focused the default implementation leaves them focused, but without focus highlight.  I'm unsure what the expectation should be, this may need UX input.

## Steps to Reproduce
1. Use node.focus()
2. Observe button has no focus highlight.

**Comment by ravikiran6565** [comment]
Hi Dave,

Actually we debugged component in different browsers(chrome, safari, firefox and IE 10 & 11) and we checked for the tabIndex value, once modal-manager closed we expect focus should retain to triggered button but expect behaviour is working fine in chrome and all other browsers are losing it's focus.

Analysis what we have done.
Ex: In chrome after closing modal-manager tabIndex value is  > 0( which means focus was internally get selected to triggered button and browser will highlight the button).

Ex: Other browsers(safari, firefox, IE 10 and 11) after closing modal-manager tabIndex value is -1(which means focus was not selected to any elements in component and browser fail to highlight button)

We have done this analysis from our end but we are not sure what is internal functionality of modal-manager. With our analysis we gave this inputs if we are wrong please correct us.

Thanks,
Ravikiran V

**Comment by dkasper-was-taken** [comment]
To move some of the offline discussion here:
Chrome buttons behave differently, it leaves focus on the button when it's clicked.  Modal uses a focus-trap, which uses tabbable.  These save the currently active target, and restore it on release. Navigating by keyboard behaves consistently, as all browser leave focus on the button, but clicking will result in odd behavior.

A possible solution would be the programmatically set focus to the button in the onClick before an action occurs.  I don't know if this a change that can be provided broadly, as it may result in unintended behavior with other controls, but it could possibly work in a limited capacity.

**Comment by bjankord** [comment]
Right now, [we set `outline: none`](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.module.scss#L54-L58) on `:focus` and `:active`, then [programmatically apply custom focus styles on keydown](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.jsx#L139-L142), and then we [remove our custom focus styles on blur](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.jsx#L118-L120). 

I've been curious about inversing that logic. Instead, we apply our custom focus styles with `:focus` and in our onClick handler, we check the `event.type` to filter if the custom focus styles get nuked.

This should allow us to use our custom focus styles when focus is set programatically and via keyboard usage, and then we can use the `event.type` to filter our touchEvents / mouseClicks and use those event.types to hide the focus styles.

**Comment by ravikiran6565** [comment]
When can we picked up this in our component? @bjankord Manually we have to set focus in our component you meant?
