### ISSUE TITLE
Show Hide minor fixes

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1977]
## Resolve outstanding items from #1956 

- apply correct color fill for icon svg for hover: [#1956comment](https://github.com/cerner/terra-core/pull/1956#pullrequestreview-165288650), focus: [#1956comment](https://github.com/cerner/terra-core/pull/1956#pullrequestreview-165288793), and disabled state [#1956comment](https://github.com/cerner/terra-core/pull/1956#pullrequestreview-165289099)
- correct icon with multi-line wrapping, should be vertically centered (most likely need to change display to inline-block) 
- minor button sizing changes for when text wraps (need to reduce value for line-height `1.429` to and increase padding to `0.21428rem  0`, to keep touch-friendly size)
- adding new test for long button text w/wrapping label
- fix test for showing the states (normal,hover,focus,active,disabled)

\
also was discussed:
- possibly update variable names for `--terra-show-hide-button-icon` to `--terra-show-hide-button-background-image` to follow newly proposed linting rules.

**Comment by bjankord** [comment]
> fix test for showing the states (normal,hover,focus,active,disabled)

Currently, there is no API to disable the show hide component. Does this functionality need to be added to the component API or can we remove the disabled state from the button?

**Comment by bjankord** [comment]
Talked with Jennifer Wurth about this. Design standard says no disabled button for this component.
