### ISSUE TITLE
Look into drying up the npm-scripts used in each package

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#20]
# Issue Description
There are duplicate npm-scripts used across all terra-core packages. @ryanthemanuel had some ideas on ways we could reduce this duplication. Some options to look into are having all the scripts point to a .js file in the root directory for each script and using shelljs to run tasks. Another option is to investigate https://www.npmjs.com/package/npm-run to run tasks.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Duplicate npm-scripts are reduced

## Current Behavior
Duplicate npm-scripts are in every package.json

**Comment by bjankord** [comment]
link-parent-bin could help with some cleanup: https://www.npmjs.com/package/link-parent-bin

**Comment by bjankord** [comment]
We could fork react-scripts and explore adapting it to our use-cases

**Comment by emilyrohrbough** [comment]
Creating a 'terra-scripts' package or something similar with

```js
"bin": {
    "terra-scripts": "./bin/teraa-scripts.js"
  },
```

in the package.json will create a symlink to `terra-scripts.js` in the `node_modules/.bin directory` on npm install. 

This project, [kyt-coe/cli](https://github.com/NYTimes/kyt/tree/master/packages/kyt-core/cli), is a simple example of how we could dry up our scripts will still providing arguments for the scripts that need it.

**Comment by bjankord** [comment]
Closing this out, I no longer think this is something we need to prioritize.
