### ISSUE TITLE
Decouple Functional and Custom Property WebDriver Tests

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#2006]
## Issue
WebDriver tests contain both functional test steps and custom property theme tests within the same spec file. When tests are shared across libraries, specifically theming libraries, it is not possible to skip tests that are applying a mock theme. This introduces a risk of generating unnecessary and inaccurate screenshots.

Tests that contain both functional steps and custom property alteration steps generate a screenshot that includes a mock theme and inaccurately represents the component during that step.

## Proposal
Decouple functional and custom property WebDriver tests by separating them into different files and moving the custom property tests into a unique directory. This enables explicit control over which set of tests consumers want to run and makes each spec file's intention more clear.

Functional Tests: 
```
/wdio/test-name.spec
```

WDIO Tests:
```
        ↓ Directory
/wdio/theme/test-name.spec
```

## Caveats 
Custom Property tests may need to recreate their own set of functional steps when required to present the targeted custom properties. 

## Component Checklist
- [ ] terra-abstract-modal
- [x] [terra-action-footer](https://github.com/cerner/terra-core/pull/2021)
- [ ] terra-action-header
- [ ] terra-alert
- [ ] terra-arrange
- [ ] terra-avatar
- [ ] terra-badge
- [x] [terra-base](https://github.com/cerner/terra-core/pull/2009)
- [ ] terra-button
- [ ] terra-button-group
- [ ] terra-card
- [ ] terra-collapsible-menu-view
- [ ] terra-content-container
- [ ] terra-date-picker
- [ ] terra-date-time-picker
- [ ] terra-demographics-banner
- [ ] terra-dialog
- [ ] terra-divider
- [ ] terra-doc-template
- [ ] terra-dynamic-grid
- [ ] terra-embedded-content-consumer
- [ ] terra-form-checkbox
- [ ] terra-form-field
- [ ] terra-form-fieldset
- [ ] terra-form-input
- [ ] terra-form-radio
- [ ] terra-form-select
- [ ] terra-form-textarea
- [ ] terra-grid
- [ ] terra-heading
- [ ] terra-hyperlink
- [ ] terra-i18n
- [ ] terra-icon
- [ ] terra-image
- [ ] terra-legacy-theme
- [ ] terra-list
- [ ] terra-markdown
- [ ] terra-menu
- [ ] terra-mixins
- [ ] terra-overlay
- [ ] terra-paginator
- [ ] terra-profile-image
- [ ] terra-progress-bar
- [ ] terra-props-table
- [ ] terra-responsive-element
- [ ] terra-scroll
- [ ] terra-search-field
- [ ] terra-section-header
- [ ] terra-show-hide
- [ ] terra-signature
- [ ] terra-slide-group
- [ ] terra-spacer
- [ ] terra-status
- [ ] terra-status-view
- [ ] terra-table
- [ ] terra-tabs
- [ ] terra-tag
- [ ] terra-text
- [ ] terra-time-input
- [ ] terra-toggle
- [ ] terra-toggle-button
- [ ] terra-toggle-section-header
- [ ] terra-visually-hidden-text

**Comment by emilyrohrbough** [comment]
+1 

Would the use of pageObjects alleviate the caveat of rewriting functional steps? http://webdriver.io/guide/testrunner/pageobjects.html

**Comment by mjhenkes** [comment]
![](https://media.giphy.com/media/xSM46ernAUN3y/giphy.gif)

**Comment by bjankord** [comment]
+1 on the proposal.

**Comment by bjankord** [comment]
Is this issue still needed?

**Comment by StephenEsser** [comment]
It would be worth discussing whether or not we want to continue with these changes. I think there is some value in separating out theme tests from functional tests, but with the changes in toolkit many of the previous issues are mitigated.

This may be a case of "The juice isn't worth the squeeze" -- Anon

That said, there is one test that might require a directory change. It's somewhat of a special case, but because of how the signature component reads the styles they must be set before drawing. As far as I can tell the only way to skip this test is to move it into another directory.

https://github.com/cerner/terra-core/blob/master/packages/terra-signature/tests/wdio/signature-spec.js#L26-L37
