### ISSUE TITLE
Create terra-breakpoints package to house responsive utilities/values

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#2018]
# Feature Request

Today, terra-responsive-element contains all consumable APIs related to breakpoints. Consumers are importing stylesheets from that package to reuse our breakpoint values. However, it'd make more sense to create a separate package for breakpoint-related logic and utilities that ResponsiveElement and other packages can consume directly.

## Description

A new package should be created that contains:
* This stylesheet: https://github.com/cerner/terra-core/blob/master/packages/terra-responsive-element/src/breakpoints.module.scss
* Maybe some utility functions like the one found in Layout: https://github.com/cerner/terra-framework/blob/master/packages/terra-layout/src/LayoutUtils.js#L7
* Some documentation that offers some best practices for usage

**Comment by bjankord** [comment]
Related: https://github.com/cerner/terra-core/issues/1309

**Comment by tbiethman** [comment]
I'll start working on this once I get my open PRs merged.

**Comment by bjankord** [comment]
Discussed provided mixins to set stills in a given media query breakpoint. This would allow an abstraction layer if we need to adjust the breakpoints. It's unlikely we'd change breakpoints though.
