### ISSUE TITLE
Provide a callBack to the ResponsiveElement to notify when size has changed

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-core#2019]
# Feature Request

## Description
I would like the ability to know when the ResponsiveElement has swapped between mobile and desktop(I believe a change here could be made to support this https://github.com/cerner/terra-core/blob/master/packages/terra-responsive-element/src/ResponsiveElement.jsx#L108-L110 . 

## Additional Context / Screenshots
The reason I would like this feature is because we are currently facing an issue where we have a model opened up in Mobile view but when we switch from Mobile to Desktop we want the modal to go away, so we need to know when the view has switched from mobile to desktop so we can dismiss the modal.

## @ Mentions
@bjankord

**Comment by bjankord** [comment]
We are working on a new package, [terra-breakpoints](https://github.com/cerner/terra-core/pull/2039), that will offer the ability to check various info about the active media query (breakpoint).
