### ISSUE TITLE
[terra-header] Create a more generic header

### ISSUE THREAD

**Issue by k1nger** [cerner/terra-core#2028]
# Feature Request

## Description
Currently there are two headers that I can think of; action header and clinical header that do similar work. My group has tried implementing the clinical header with the collapsible menu with some mixed results. IE issues specifically and collapsible menus collapsing with room available on them.

This more generic header would be able to accept custom styles and have children passed to it to be displayed an interacted with however the consumer would want. 

## @ Mentions
@JakeLaCombe

**Comment by JakeLaCombe** [comment]
I wouldn't recommend adding props for custom styles. I think we would want to keep the same ones we have for the clincal and action headers

**Comment by k1nger** [comment]
That's fine. I was only thinking of maybe padding not necessarily colors, borders, etc.
