### ISSUE TITLE
Missing  translation that should be supported in jest fixtures

### ISSUE THREAD

**Issue by AirWick219** [cerner/terra-core#2031]
# Bug Report

## Description
got this error 

Exception Message: ENOENT: no such file or directory, open '/Users/node_modules/terra-dev-site/node_modules/terra-i18n/tests/jest/fixtures/translations/en-US.json' 

## Steps to Reproduce
1. Call aggregateTranslations({locales: ['en', 'en-US']})

## Expected Behavior
no error when compelling 

## Possible Solution
1. Add all the supported translation in [here](https://github.com/cerner/terra-core/tree/master/packages/terra-i18n/tests/jest/fixtures/translations)
2. Update the look up script

## Environment

* Component Name and Version: terra-18n
* Browser Name and Version: Chrome
* Node/npm Version: [e.g. Node 8/npm 5] Node 8 and npm 5
* Webpack Version: 7
* Operating System and version (desktop or mobile): Desktop

## @ Mentions
@bjankord

**Comment by bjankord** [comment]
## Tech Design
Add all supported locales to `terra-i18n/tests/jest/fixtures/translations`. With the way people provide globbing for looking up translations, there is a possibility this directory is picked up. We can mitigate the issue by providing translations here. 

This seems like a less risky / impactful update compared to adjusting the translation lookup code.
