### ISSUE TITLE
Add i18n Jest Setup and Tear Down for Translation Files

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2034]
## Description
Updating the i18n jest setup to create i18n translation files before test run and then remove them after the tests. We still want to validate i18n loads translations correctly, however,  by including them via `/tests/fixtures/translations/`, these fake translations can get pulled into consumers aggregated-translations, which isn't desirable. 

## Reference 
https://github.com/cerner/terra-core/pull/2032#issuecomment-437398189

**Comment by bjankord** [comment]
Discussed changing the directory name so we don't have to setup / teardown files during test run.
