### ISSUE TITLE
[terra-list] List items are not padded.

### ISSUE THREAD

**Issue by rakshith91** [cerner/terra-core#2035]
# Bug Report

## Description
The text in the list items of the terra-list are not padded and come right till the edge and the first letter is almost getting cut out. There should be a left padding to the list items. 

## Steps to Reproduce
1. Consume any terra-list application. Screenshots are attached.

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/14154054/48359271-34186e80-e662-11e8-9909-e0b3b71489be.png)
![image](https://user-images.githubusercontent.com/14154054/48359391-7d68be00-e662-11e8-9c82-3282ca0917aa.png)

## Expected Behavior
There should be some padding ( or at least a prop to support padding the text in list items )

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by bjankord** [comment]
Add new props `isHorizontallyPadded`, `isVerticallyPadded`. cc/ @neilpfeiffer 
Want to figure out what default padding should be.

**Comment by rakshith91** [comment]
Hello, Any updates about this?

**Comment by bjankord** [comment]
No updates, we'll post a comment on this issue when there is an update.
