### ISSUE TITLE
[action-header] Ability to align the title to center in the action-header.

### ISSUE THREAD

**Issue by rakshith91** [cerner/terra-core#2036]
# Feature Request
## Description
It'll be good to have the ability to align the title to center in the action header to avoid custom styling in applications. 

## Additional Context / Screenshots
This looks cleaner compared to 
![image](https://user-images.githubusercontent.com/14154054/48360830-ab9bcd00-e665-11e8-80c7-9f2c574ed226.png)
this.
![image](https://user-images.githubusercontent.com/14154054/48360809-9fb00b00-e665-11e8-9dc6-67ebe3633165.png)

**Comment by mjhenkes** [comment]
Centering titles in headers with variable width accessory areas to the left and right generally means you get a title centered within it's own container but not centered within the header itself. To avoid these issues, we recommend the usage of left aligned headers and discourage consumers from attempting to force the header to be centered with custom styles.
