### ISSUE TITLE
terra-table selected rows accessibility

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#205]
Selectable table rows are not keyboard accessible.

**Comment by bjankord** [comment]
On #214 it was mentioned, "We might also need to add an aria attribute so screen readers can determine if a row is selected."

I believe adding `aria-selected="true"` to the selectable table row element, `<tr>`, is how we want to convey this to screen-readers. We'll want to toggle that to `aria-selected="false"` when the row is unselected.

More info:
* https://www.w3.org/TR/wai-aria/states_and_properties#aria-selected
* http://www.ssbbartgroup.com/blog/how-not-to-misuse-aria-states-properties-and-roles/

**Comment by Matt-Butler** [comment]
I started this branch which is adding aria-selected to the table row. Voice-over is not reading the selected state. I'll continue to look into the issue.

https://github.com/cerner/terra-core/tree/accessibility-attributes
