### ISSUE TITLE
Update Node to use LTS, update engine requirement in package.json

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-core#2052]
# Feature Request

### It is proposed that instead of locking down to a specific Node version in the `.nvmrc`, we should be pointing to use the LTS.

As of [nvm v0.33.6](https://github.com/creationix/nvm/issues/1680#issuecomment-350184827) nvm supports the use of [lts/* for long term support](https://github.com/creationix/nvm#long-term-support) in the `.nvmrc` config file.

> You can reference LTS versions in aliases and .nvmrc files with the notation lts/* for the latest LTS

This way we don't have to worry about manually updating the Node version and we will always target LTS Node.

```
# .nvmrc
lts/*
```

### It is proposed to update the engine requirement to use both Node v8.x and v10.x. 

The new [Node LTS version is 10.x](https://github.com/nodejs/Release#release-schedule) which causes issues with Terra since it's still on 8.x (now in maintenance). 

```json
# package.json
"engines": {
  "node": "^8 || ^10"
}
```

## Additional Context / Screenshots

<img width="661" alt="screen shot 2018-11-13 at 3 02 42 pm" src="https://user-images.githubusercontent.com/34115417/48443318-5db2c200-e756-11e8-865e-2fe4d470e04d.png">
<img width="955" alt="screen shot 2018-11-13 at 3 05 16 pm" src="https://user-images.githubusercontent.com/34115417/48443325-63100c80-e756-11e8-878a-8e00d5dccbba.png">

**Comment by bjankord** [comment]
This update sounds good to me, we'll want to update the engine key in our package.json files across various projects we've defined that key.

cc/ @ryanthemanuel @mjhenkes

**Comment by bjankord** [comment]
I like this idea but a concern I have is that `lts/*` is not explicit enough, you may end up with `8.x` or `10.x`, for now you'll get 10.x, but you can imagine at some point, you'll get `12.x` likely without being aware that your project is starting to use a new lts version. 

I do like the idea of loosening the range on engines, we can update it to `"node" : ">=8.9.2"`.

Would this resolve the issue you're running into @dev-cprice?

**Comment by dev-cprice** [comment]
@bjankord I believe that will solve the engine problem, at least. `yarn` will error out based on the engine reqs, but `npm` won't.

As for the `.nvmrc`.. I know that this is a component library and it shouldn't push too many opinions onto its consumers, but I feel like requiring users to at least be on the LTS node isn't too much of an ask. It's not the EDGE version, but rather the currently supported version.

**Comment by mjhenkes** [comment]
the .nvmrc only affects building this project itself and doesn't push any opinions on consumers.

**Comment by bjankord** [comment]
`"node" : ">=8.9.2"` should match node 8.9.2 or above, so node 9.x, node 10.x would be valid. Does yarn not handle node engine ranges specified this way?

**Comment by dev-cprice** [comment]
How about instead of `lts/*`, we lock it down to 8.x at least? If we do `lts/carbon` it will pull in all minor & patch versions of 8.x carbon

**Comment by bjankord** [comment]
`lts/carbon` sounds fine to me. Does setting `^8.9.2` in the .nvmrc file do the same thing? That caret syntax may be an npm only thing that nvm doesn't parse.
