### ISSUE TITLE
[alert] Update Doc Page Examples

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2053]
# Feature Request

## Description
Update doc page examples to use the terra-doc-template to render the example's source.

#### Current View
![screen shot 2018-11-13 at 3 49 20 pm](https://user-images.githubusercontent.com/14099737/48445244-b6d12480-e75b-11e8-8083-84f5bb99bd2e.png)

#### Expected View
![screen shot 2018-11-13 at 3 49 08 pm](https://user-images.githubusercontent.com/14099737/48445251-bb95d880-e75b-11e8-875d-bc83741b6b18.png)

**Comment by bjankord** [comment]
We should update status view as well.
