### ISSUE TITLE
Required ARIA parent role not present: listbox 

### ISSUE THREAD

**Issue by subramanyaprasad** [cerner/terra-core#2065]
# Bug Report

## Description

@juliacalandro once reported this as a bug, looks like this accessibility issue still persists with the terra-list. [Here](https://github.com/cerner/terra-clinical/issues/364) is the link for the issue that @juliacalandro has logged.
I have updated our project terra-list version to use the latest version which is 2.30.0. If we use any version above 2.6.0 we get the below accessibility error.

"description": "Ensures elements with an ARIA role that require parent roles are contained by them",
"help": "Certain ARIA roles must be contained by particular parents",
"helpUrl": "https://dequeuniversity.com/rules/axe/2.6/aria-required-parent?application=axeAPI",
"id": "aria-required-parent",
..................
"nodes": [
{
"all": [],
"any": [
{
"data": [
"listbox"
],
"id": "aria-required-parent",
"impact": "critical",
"message": "Required ARIA parent role not present: listbox",
"relatedNodes": []
}
],
"failureSummary": "Fix any of the following:\n Required ARIA parent role not present: listbox"

## Steps to Reproduce

1. Install the aXe extension for Chrome.
2. Run a project using terra-list so that it can be opened and inspected in the browser.
3. Inspect the page and navigate to where the List component is being used.
4. Verify that ul tag does not have a role set but its child li tag s do.
5. Navigate to the aXe tab and run an inspection on the page.
6. Verify that an accessibility error is thrown with a description matching the error description above.
7. Add role="listbox" as an attribute to each offending <ul> component and run the aXe inspection 
  again.
8. Verify that the accessibility issue doesn't exist anymore.
 
## Expected Behavior

I expect the accessibility issue mentioned above to no longer be thrown by the terra-list component.

## Possible Solution

Add missing role="listbox" attribute to <ul> within terra-list component.
## Environment

* Component Name and Version: terra-list 2.30.0
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by bjankord** [comment]
We are currently [refactoring the list component](https://github.com/cerner/terra-core/pull/2044) to be a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) where the app developer will be responsible for managing the selection state of lists. With this, the `<List />` componet will render a `<ul>` without any aria attributes by default. 

If you add selectable list items within the `<List>` component [we will be recommending adding tha aria-role="listbox"](https://github.com/cerner/terra-core/pull/2044/files#diff-eedb9f3d45c2b31b203abcad428df71b) to the `<List>` component. With moving the component to a controlled component, we'll no longer know if the list is selectable, only if the list items are selectable, so the developers will need to add this attribute themselves to the `<List>` component.

We hope the doc helps clarify this, but we are also relying on the aXe error you mentioned to help notify developers if they make a selectable list but forget to add the attribute. We also recommend all UI being built with terra components be run through wdio tests using our [aXe service](https://github.com/cerner/terra-toolkit/blob/master/docs/AxeService.md) so accessibility issues that can be programmatically identified are caught and corrected before the code is shipped to production.

**Comment by subramanyaprasad** [comment]
@bjankord adding the role to the selectable List solved my issue. Yea doc will definitely help developers to solve this issue or else it will be really difficult to figure this out because I think we don't add aria-role explicitly for any other terra-components, so thank you for providing those links.
