### ISSUE TITLE
[terra-list] Correct flex styles introduced to list.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#2099]
# Bug Report
Correct usage of flex on list.

## Description
Flex styles were introduced on #923 to correct highlight of list item rows with content that used marigns. However flex styles were not applied to list items, so with more complication list item content, errors in sizing occurs.

## Possible Solution
This can be fixed in one of two ways:
1: Add flex: 0 0 auto; to list items.
2: Remove flex from list, add overflow: hidden; to list items.

I believe option 2 to be the correct application of the fix.

**Comment by bjankord** [comment]
My concern with overflow: hidden on list item is around it clipping focus outlines on items within it. e.g. buttons next to the edge of the list item, and clipping the focus outline on the list item. I think this can be mitigated with having the list item focus outline be an inset box-shadow and then encouraging side padding on list items.

Curious, what are the concerns you see with `flex: 0 0 auto;` ? I haven't thought through that solution much.

**Comment by dkasper-was-taken** [comment]
In the correction within #2044 there is an inner div that provides the overflow hidden. So if the list item requires an outset box shadox, it'll still function. The only scenario that you mentioned would be the button near an edge, but some padding could address that. We still have problems with margins that need to be addressed with overflow hidden in with the current case unfortunately. So I think the flex 0 0 auto will only partially address this issue.

**Comment by bjankord** [comment]
Ok, that's good to know the background on it. I'm fine with the `overflow: hidden; ` approach. I think it would be good to add a screenshot test to highlight what problems it solves so if we ever change the implementation, we can catch any regressions.
