### ISSUE TITLE
[terra-icon] v2.29.1 breaks animation of loading spinner

### ISSUE THREAD

**Issue by ChaseSinclair** [cerner/terra-core#2110]
# Bug Report

## Description
The latest version of terra-icon broke the animation for the loading spinner in terra-overlay (LoadingOverlay). The issue is not present in 2.29.0.

## Steps to Reproduce
1. Add latest version of terra-overlay (which includes terra-icon 2.29.1 as a dependency) to project.
2. Import LoadingOverlay from terra-overlay.
3. Run project server and render LoadingOverlay.
4. Loading spinner will render but will not show spin animation.

## Additional Context / Screenshots
![loading-spinner](https://user-images.githubusercontent.com/5703475/49749870-0b8a9100-fc6f-11e8-8d8a-32c547a9771e.gif)

## Expected Behavior
The spinner should actually spin.

## Possible Solution
Reverting to 2.29.0 fixes the animation in our app but breaks terra config. @bjankord mentioned a possible solution using css-in-js.

## Environment

* Component Name and Version: terra-icon 2.29.1
* Browser Name and Version: Firefox 63.0.3/Chrome 70.0.3538.110
* Node/npm Version: [e.g. Node 8/npm 5] Node v8.11.1/npm 5.6.0
* Webpack Version: 3.12.0
* Operating System and version (desktop or mobile): macOS 10.13

## @ Mentions
@bjankord @dev-cprice

**Comment by bjankord** [comment]
There seems to be some configurations around css-loader / scss-loader / node-sass that causes this regression. I think for this specific instance, wanting to have a global named CSS animation, we move the styles to a css-in-js solution and get around having to interface with the configurations / version combinations needed for the loaders.

**Comment by bjankord** [comment]
I'm seeing the icon fail to spin on [codesandbox.io](https://codesandbox.io/s/m4p3llrx59) as well. It seems the animation gets hashed at definition time even though we want it to be global, and when its used, it used the global version.
