### ISSUE TITLE
[terra-form-checkbox] The checkbox has zero width when the label is hidden.

### ISSUE THREAD

**Issue by nramamurth** [cerner/terra-core#2114]
# Issue Description
It looks like the `label` that is part of the `checkbox` element does not come with a width set when the `Checkbox` component is created with its label hidden. Due to this, an inline element that could be placed beside the checkbox needs to have extra padding/margin depending on the requirement. 

## Code Sample
```
import React from 'react';
import Spacer from 'terra-spacer';
import Checkbox from 'terra-form-checkbox/lib/Checkbox';

const CheckboxSample = () => (
  <div>
    <Spacer isInlineBlock><Checkbox labelText="Can you see me?" isLabelHidden /></Spacer>
    <span>This is Checkbox.</span>
  </div>
);

export default CheckboxSample;
```

## Additional Context / Screenshots
![screen shot 2018-12-10 at 7 23 32 pm](https://user-images.githubusercontent.com/10090859/49772005-35fd3e00-fcb1-11e8-9428-d28d835a74fe.png)

**Comment by bjankord** [comment]
@nramamurth Can we get some more info on what you are intending to do with this.

**Comment by nramamurth** [comment]
@bjankord I was trying to use Terra's [Arrange](https://github.com/cerner/terra-core/tree/master/packages/terra-arrange/docs) component with `fillStart` being the `terra-form-checkbox` that has the label hidden and `fill` being text content and it was observed that the check box with its label hidden has no width at all.
