### ISSUE TITLE
[terra-grid] Truncation and spacing issues in IE

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-core#2126]
# Bug Report
## Description
Utilizing the terra-grid component, we are seeing inconsistency between Chrome and IE around grid row spacing and truncation behavior.

## Steps to Reproduce
Use terra-grid with long text entries wrapped by terra-clinical-item-display elements.

## Additional Context / Screenshots
Chrome:
<img width="1393" alt="chrome_test" src="https://user-images.githubusercontent.com/19825717/50115774-01880580-020e-11e9-8f1e-06fc8d50d863.png">

IE:
<img width="1440" alt="ie_test" src="https://user-images.githubusercontent.com/19825717/50115778-064cb980-020e-11e9-9487-4b3e16b1a055.png">

Gist of a minimal example: https://gist.github.com/cwalten/08b481e41c59d3d57bd69f9e6dfc3e5a

## Expected Behavior
We would expect spacing and truncation to function similarly in both Chrome and IE. Our preferred view is the Chrome one.

## Possible Solution
For the spacing issue, it seems the Grid.Row thinks it needs to be bigger than it actually does to hold its children. I did some digging into line-heights on these elements, but came up with nothing substantial.

## Environment

* Component Name and Version: terra-grid@4.28.0
* Browser Name and Version: Chrome (latest) and IE10
* Node/npm Version: Node 8 NPM 5
* Webpack Version: webpack@4.27.1
* Operating System and version (desktop or mobile): Windows VM and MacOS

**Comment by cwalten** [comment]
Based on further investigation with @StephenEsser this issue has to do with the Spacer's 'isInlineBlock' prop being true. When removing that prop, IE functions as expected, wrapping and spacing more similarly to Chrome.

**Comment by JakeLaCombe** [comment]
@cwalten is there anything else you need, or are we good to close this?

**Comment by cwalten** [comment]
I was able to work around my issue by tweaking the props, so no changes are being requested by me at this time. Thanks.
