### ISSUE TITLE
CSS Custom Properties rounds values

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2128]
# Discussion
CSS custom properties will round to the hundred thousandth (5th decimal point).

### Example
Take `section-header`. 
1. We set `padding-top: 0.214285714rem` on a [icon css class](https://github.com/cerner/terra-core/blob/master/packages/terra-section-header/src/SectionHeader.module.scss#L111)
2. View section header on [terra-ui](https://engineering.cerner.com/terra-ui/#/components/terra-section-header/section-header/section-header)
3. Inspect and find the css class. The value rounds to `padding-top: 0.21429rem`
<img width="389" alt="screen shot 2018-12-18 at 2 42 31 pm" src="https://user-images.githubusercontent.com/14063284/50181965-97d22f00-02d3-11e9-838b-0f9432429f21.png">

### Non-passive
This is a problem if we add new theme variables but keep fallback values the same for passivity. There is a chance this is not passive if we use values with decimals past the hundred thousandth. Let's look at our `ocs-theme-variables` branch.
1. We made the accordion icon's width and height [themeable](https://github.com/cerner/terra-core/compare/ocs-theme-variables#diff-72b619841a4ff1c7ee64ac0888549f47R119). They keep the original value as a fallback. `0.8571428571rem`.
2. CSS custom properties rounds height and width to `0.85714rem`
3. This causes font pixels to shift *ever* so slightly
![hovered_-_long_title_accordion_section_header default](https://user-images.githubusercontent.com/14063284/50182531-2eebb680-02d5-11e9-87ae-35ff2a0124bc.png)

This is a good topic to discuss when everyone is back. We may have to cap precision to the hundred thousandth.

**Comment by ryanthemanuel** [comment]
@yuderekyu let's just keep this in mind going forward and fix places as we go.
