### ISSUE TITLE
Status view text message aligned left in Edge

### ISSUE THREAD

**Issue by yusufali2205** [cerner/terra-core#2129]
# Bug Report

## Description

Status view message is not showing in center on Edge browser. Here is the screenshot: 
<img width="805" alt="edge-status-view" src="https://user-images.githubusercontent.com/1637467/50232717-4da28980-0377-11e9-9b68-609de49e389b.png">

## Steps to Reproduce

1. Go to https://engineering.cerner.com/terra-ui/#/components/terra-status-view/status-view/status-view in MS **Edge** browser
2. Check the examples
3. You should see the message aligned improperly

## Additional Context / Screenshots

Screenshot added in the description

## Expected Behavior

The message should be in the center

## Possible Solution

Adding style `text-align: center` to the div having class StatusView-module__message__xxxx fixes it.

## Environment

* Component Name and Version: Internal Application
* Browser Name and Version: Edge
* Node/npm Version: 8.9.2
* Webpack Version: 4.27.1
* Operating System and version (desktop or mobile): Desktop Windows 10

## @ Mentions

None

**Comment by bjankord** [comment]
@amichaelparker found if we remove the CSS custom property, text-align: center; may be set already. Possibly inherited from a parent? This seems to work correctly in Edge in the CSS custom property is removed.

@neilpfeiffer Looking through the Zeplin theme boards, I didn't see an example where the text needed to an alignment other than center. Does this need to be a themable property?

**Comment by yuderekyu** [comment]
@yusufali2205 @amichaelparker @bjankord are ya'll still seeing this? I'm not able to recreate this on Edge

**Comment by yusufali2205** [comment]
I still see it. I'm on Edge Version 42.17134.1.0

**Comment by yuderekyu** [comment]
Able to recreate on 42.17134.1.0. Edge has a [CSS Properties bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11728214/) with `text-align`. The `center` fallback value fails to register - instead, edge defaults to `left`.  

To reiterate @bjankord, if there are no cases where we want non centered text, it makes sense to remove the CSS property (I vote we do this).

<img width="960" alt="status-view-edge-bug 1" src="https://user-images.githubusercontent.com/14063284/52868421-ea2fa080-3108-11e9-9d8e-8dc3f07ff1c0.png">

**Comment by neilpfeiffer** [comment]
I need to check if this is used by consumer first before approving PR - I believe it is used.
