### ISSUE TITLE
Enhance Table sections headers with nesting/collapsing functionality

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#2132]
# Feature Request

## Description
The Table component should be enhanced to support nested and collapsible subsections, similar to the functionality added to List with #1321

**Comment by jeremyfuksa** [comment]
There's a RevCycle design team interested in this enhancement and asked about estimated availability given the designated milestones.

**Comment by bjankord** [comment]
Talked with @neilpfeiffer, he has some more details on availability

**Comment by neilpfeiffer** [comment]
Will be resolved by work provided in new component: Terra-TableCellGrid (flex-table) https://github.com/cerner/terra-core/tree/terra-flex-table (PR to come later)

Nesting and expanding sections details have already been provided, removing the "Blocked: UX Input Needed" tag

**Comment by bjankord** [comment]
Discussed in our terra-lead-sync meeting a desire to move away from children based API and move to a data API for this component, something more like the API for terra-clinical-data-grid.

Some other examples of data APIs for tables:
* https://github.com/jbetancur/react-data-table-component
* https://github.com/tannerlinsley/react-table/blob/master/docs/examples.md
* https://github.com/schrodinger/fixed-data-table-2
