### ISSUE TITLE
Check boxes and Radio Buttons need to be visually aligned

### ISSUE THREAD

**Issue by HeikeK** [cerner/terra-core#2150]
# Bug Report
Radio buttons and check boxes are not visually aligned

## Description
The radio button circles have more of a (standard) left padding than the checkbox boxes, see attached screenshot below.
![checkbox text styling adjusted](https://user-images.githubusercontent.com/45692819/50832932-b13c2900-131d-11e9-8b3c-e39b05561101.png)
Can the padding be adjusted accordingly? We need this for the wellness questionnaire.

## Steps to Reproduce
Compare Radio buttons and Check Boxes in regards to left padding

## Additional Context / Screenshots
![checkbox text styling adjusted](https://user-images.githubusercontent.com/45692819/50833043-ff512c80-131d-11e9-95d5-65b5b58a6fd3.png)

## Expected Behavior
Check boxes and Radio Buttons should be visually as similar as possible

## Possible Solution
Adjust the left padding for either the radio buttons or the check boxes so the padding is the same for both 

## Environment
<n/a

## @ Mentions
n/a

**Comment by bjankord** [comment]
This is a styling change that needs to be done in the cerner-consumer-theme.

**Comment by HeikeK** [comment]
Can you give me a link to corner-consumer-theme? I am not able to find it

**Comment by JakeLaCombe** [comment]
Contact the Terra team on themes. It's internal to Cerner, so we will need to send you the details that way
