### ISSUE TITLE
Form-Select problems with duplicate values

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#2160]
# Bug Report

## Description
Even with using unique keys, terra-form-select also expects unique values for each of the select option items, and when more than one item has the same value, the variants of the form-select have reportedly unexpected behaviors. (Ideally an application should manage and pre-clean/filter a list for duplicate values, but this cannot be always guaranteed, so UI should not break, if possible). 

The issue two issues that were noticeable are:
- hovering and selecting: when hovering or selecting an option that has the same value as another/other options, they all will highlight together when hovering and all show selection when one is chosen (this UI makes sense as to why it is doing it technically, but easy for users to be confused)
- scrolling/auto-focus: when there is a very long list of options (50+) and one of the items lower in the list that is visible on-screen while scrolling, shares a value with an item that has been scrolled off above, the list will reposition in the listbox such that the first item with the same value is now at the top of the listbox (list appears to jump erratically when there is only one item that has this problem), and the mouse is pointing at a different option than before the jump. 

## Steps to Reproduce
1. Provide form-select a list of 50+ options, some of which contain duplicate values - try both first and last item in the list to show the auto-scroll issue.
2. Hover over the items in the list that have a duplicate value as another, particularly an item low in the list that is the same value as one higher in the list
3. Watch the list auto-scroll/jump so that the first item with that same value is now at the top of the listbox, but mouse now hovers over some other option since list has moved position below the mouse. 
4. Selecting an item that has a duplicate value with other items, shows all items as selected (confusing to a user if the displays are unique, but the values are the same).

## @ Mentions
@papasmile

**Comment by StephenEsser** [comment]
I don't believe it's possible for the Select to allow duplicate values. The values must be unique otherwise the selected behavior is ambiguous.

In the following example there is no way to know which option should be selected on the initial rendering. Should `Option 1` or `Option 5` be selected?
 
```
  <Select defaultValue="duplicate">
    <Select.Option value="duplicate" display="Option 1" />
    <Select.Option value="2" display="Option 2" />
    <Select.Option value="3" display="Option 3" />
    <Select.Option value="4" display="Option 4" />
    <Select.Option value="duplicate" display="Option 5" />
  </Select>
```

A controlled Select will also be presented with the same issue. The callback will return the value of the selected item. During the next render the Select cannot reliably select the appropriate option with the information available.

Here is an example using a controlled native Select. It is impossible to select `Other Zero` or `Other One`. Selected either of these will rerender with the first option matching the value selected.

```
class SelectExample extends React.Component {
  constructor() {
    super();

    this.state = { value: '1' };

    this.handleOnChange = this.handleOnChange.bind(this);
  }

  handleOnChange(event) {
    this.setState({ value: event.target.value });
  }

  render() {
    return (
      <select value={this.state.value} onChange={this.handleOnChange}>
        <option value="0">Zero</option>
        <option value="0">Other Zero</option>
        <option value="1">One</option>
        <option value="1">Other One</option>
      </select>
    );
  }
}
```

**Comment by neilpfeiffer** [comment]
cc: @papasmile

**Comment by neilpfeiffer** [comment]
I don't think we should let the terra-form-select be able to *allow* multiple options with same value (including somehow magically fix it for consumers by keeping each option unique), but we may just need to look at what the UI response is, possible modeling native select as only ever letting the first instance be shown as selected, and maybe(?) hovering each uniquely without list changing position while interacting with the list, (not directly tied to "value" for hover?).  

Definitely should be treated as only an edge case that a consumer needs to appropriately manage for correct application data/usage - but the UI we may need to update to follow similar pattern as native so response is consistent and reliable even if data is broken.

**Comment by StephenEsser** [comment]
My hesitation with making updates to the UI is that the updates would solely be made to mask an issue. If the Select contains duplicate values the current UI brings attention to those issues. An update to the UI would only help to hide issues.

**Comment by papasmile** [comment]
Thanks for that discussion, guys.  I generally agree with everything that his been mentioned.  I think our primary concern was that there ought to be ** more ** attention to that duplicate value issue.

At present when duplicate values are passed and strange things happen it is not obvious why without some debugging.  As well as what Niel mentioned, perhaps logging a console warning regarding duplicate values would alert developers early on.  Or, at a minimum call out in documentation that duplicate values are not supported.  Thanks for your consideration.

**Comment by mjhenkes** [comment]
I recommend a documentation solution. We should update the select documentation to specify that value must be unique. Consumers can manage their data to ensure that duplicate values are not passed into the select.
