### ISSUE TITLE
Avatar theme variable typo

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2166]
# Bug Report

## Description
Noticed this when wokring on the consumer theme. We have a typo in the `--terra-avatar-netural-after-box-shadow` variable. It should be `--terra-avatar-neutral-after-box-shadow`.

## Environment

* Component Name and Version: terra-avatar v2.0.0+

**Comment by bjankord** [comment]
My thoughts are we just fix the typo as a patch release but curious to hear what the other maintainers think.  cc/ @ryanthemanuel @JakeLaCombe @mjhenkes @tbiethman 

I looked through all 1241 theming variables we have in core and this is the only one that had a typo. Thinking of a way we can automate spell check on these so we don't run into this issue again.

**Comment by yuderekyu** [comment]
:(

**Comment by ryanthemanuel** [comment]
I'd say do a patch release.  Technically it's non passive, but it's a bug.  Let's go ahead and fix/release.
