### ISSUE TITLE
Cannot compile on Windows 10 device

### ISSUE THREAD

**Issue by TheFacto** [cerner/terra-core#217]
# Issue Description
Cannot compile on Windows 10 machine.

#### Synopsis
* Appears to be an issue using the `lerna` compile command.
* Specifically complaining about the use of `rm` command.
    * `terra-mixins@1.0.1 compile:clean: rm -rf lib`.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
- As a windows user, I would like to compile and consume terra-core.

## Current Behavior
Running `lerna run compile`, I see the following:

```bash
> terra-core@0.1.0 compile C:\Users\user\workspace\terra\terra-core
> lerna run compile

Lerna v2.0.0-beta.36
Independent Versioning Mode
NpmUtilities.execInDir        ("run compile", [], "C:\\Users\\user\\workspace\\terra\\terra-core\\packages\\terra-mixins")
Error: Command failed: npm run compile 
'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:clean"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! terra-mixins@1.0.1 compile:clean: `rm -rf lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the terra-mixins@1.0.1 compile:clean script 'rm -rf lib'.
```

## Steps to Reproduce

1. Run `lerna run compile` on a Windows 10 machine.

## Environment

* Operating System and version: Windows 10 Enterprise x64

**Comment by windse7en** [comment]
Hi, @TheFacto. Currently, we don't support development in windows. If you want to play with the source code in windows, you can use VM or container technique(like docker) to run Linux environment locally.

Such topic(How to support development in windows) is still under the discussion. Sorry for the inconvenient. You can keep watching this issue. We will update when we have the strategy.

**Comment by bjankord** [comment]
https://www.appveyor.com/ could help to check that builds are possible on Windows.

**Comment by Matt-Butler** [comment]
When executing `npm start`, it is failing to resolve the path for the sass-loader:
```
          File to import not found or unreadable: C:Usersmb034780terra-corepackagesterra-sitenode_modulesterra-legacy-themesrcLegacyTheme.scss.
```
https://github.com/cerner/terra-core/blob/master/packages/terra-site/webpack.config.js#L39

**Comment by Matt-Butler** [comment]
I am getting the same errors with the windows git bash terminal

**Comment by Matt-Butler** [comment]
$ npm run compile

> terra-core@0.1.0 compile C:\Users\mb034780\terra-core
> lerna run compile

Lerna v2.0.0-beta.36
Independent Versioning Mode
NpmUtilities.execInDir        ("run compile", [], "C:\\Users\\mb034780\\terra-co                                      re\\packages\\terra-toolkit")
Error: Command failed: npm run compile
'$' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                      node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! terra-toolkit@0.2.0 compile: `$(cd ..; npm bin)/babel src --out-dir lib                                       --copy-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terra-toolkit@0.2.0 compile script '$(cd ..; npm bin)/bab                                      el src --out-dir lib --copy-files'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the terra-toolkit package                                      ,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     $(cd ..; npm bin)/babel src --out-dir lib --copy-files
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs terra-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls terra-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mb034780\terra-core\packages\terra-toolkit\npm-debug.log

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by Matt-Butler** [comment]
I tried updating the package.json without the reference to the the cli tools. remove `$(cd ..; npm bin)/`
```
  "scripts": {
    "compile": "npm run compile:clean && npm run compile:build",
    "compile:clean": "rimraf lib",
    "compile:build": "babel src --out-dir lib --copy-files",
    "lint": "npm run lint:js && npm run lint:scss",
    "lint:js": "eslint --ext .js,.jsx . --ignore-path ../../.eslintignore",
    "lint:scss": "stylelint src/**/*.scss",
    "test": "npm run test:spec && npm run test:nightwatch-default",
    "test:spec": "jest --config ../../jestconfig.json",
    "test:all": "npm run test:nightwatch-default && npm run test:nightwatch-chrome && npm run test:nightwatch-firefox && npm run test:nightwatch-safari",
    "test:nightwatch-default": "SPECTRE_TEST_SUITE=terra-arrange node ./node_modules/terra-toolkit/lib/scripts/nightwatch.js",
    "test:nightwatch-chrome": "SPECTRE_TEST_SUITE=terra-arrange node ./node_modules/terra-toolkit/lib/scripts/nightwatch.js chrome",
    "test:nightwatch-firefox": "SPECTRE_TEST_SUITE=terra-arrange node ./node_modules/terra-toolkit/lib/scripts/nightwatch.js firefox",
    "test:nightwatch-safari": "SPECTRE_TEST_SUITE=terra-arrange node ./node_modules/terra-toolkit/lib/scripts/nightwatch-non-parallel.js safari",
    "test:remote": "SPECTRE_TEST_SUITE=terra-arrange REMOTE=true node ./node_modules/terra-toolkit/lib/scripts/nightwatch-process.js --config tests/nightwatch.conf.js",
    "test:remote:all": "SPECTRE_TEST_SUITE=terra-arrange REMOTE=true node ./node_modules/terra-toolkit/lib/scripts/nightwatch-process.js --config tests/nightwatch.conf.js --env chrome-tiny,chrome-small,chrome-medium,chrome-large,chrome-huge,chrome-enormous,firefox-tiny,firefox-small,firefox-medium,firefox-large,firefox-huge,firefox-enormous,ie10-tiny,ie10-small,ie10-medium,ie10-large,ie10-huge,ie10-enormous,ie11-tiny,ie11-small,ie11-medium,ie11-large,ie11-huge,ie11-enormous,edge-tiny,edge-small,edge-medium,edge-large,edge-huge,edge-enormous,safari-tiny,safari-small,safari-medium,safari-large,safari-huge,safari-enormous"
  },
```
The scripts will no longer work at the package level
```
➜  terra-arrange git:(master) ✗ npm run compile

> terra-arrange@0.3.2 compile /Users/mb034780/public_github/terra-core/packages/terra-arrange
> npm run compile:clean && npm run compile:build


> terra-arrange@0.3.2 compile:clean /Users/mb034780/public_github/terra-core/packages/terra-arrange
> rimraf lib

sh: rimraf: command not found
```

All of the root level scripts continue to work.

**Comment by bjankord** [comment]
Based on [this comment](https://github.com/lerna/lerna/issues/292#issuecomment-298370120) from one of the core lerna maintainers, I think we might be able to move away from using `$(cd ..; npm bin)/` to reference `bin` files and use `lerna exec` to access root level `bin` files. This would remove the bash code used to change directories.

> Since v2.0.0-rc.2, you can call dependency binaries from the root or leaves in `lerna exec`. So for the babel case, it's as simple as a regular npm script in your root package.json:

```json
{
  "name": "monorepo-root",
  "private": true,
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "lerna": "^2.0.0-rc.4"
  },
  "scripts": {
    "babel": "lerna exec -- babel src -d lib"
  }
}
```
