### ISSUE TITLE
Date picker does not clear date if user manually enters date and selected date is assigned with null/''(empty string)

### ISSUE THREAD

**Issue by SharathAlur** [cerner/terra-core#2177]
# Bug Report
Date picker does not clear date if user manually enters date and selected date is assigned with null/''(empty string)

## Description
Enter date manually and clear the date to reset programmatically

## Steps to Reproduce

1. Have a reset button, which will reset the date in state to null/empty
2. Enter date manually
3. Click on reset (set the selected date as null/empty

## Expected Behavior
when we reset the selected date to null/empty it should clear the date present in the control.

## Environment

* Component Name and Version: terra-date-picker
* Browser Name and Version: Chrome
* Node/npm Version: Node v10.1.0/npm v5.6.0
* Webpack Version:
* Operating System and version (desktop or mobile): Both

**Comment by ryanthemanuel** [comment]
This is issue is because the date picker is uncontrolled.  We have another issue that is similar to this (#1533) that will (likely) result in creating a controlled date picker.  Closing this and keeping that one open.
