### ISSUE TITLE
[spike] Investigate what we can do as far as form validation

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#2181]
Teams are needing more help and guidance on form validation.  I want to investigate what we can do.  This could include:

- Exporting validation functions for people to use
- Creating very specific documentation on common use cases

**Comment by bjankord** [comment]
With the release of [terra-form-validation](https://www.npmjs.com/package/terra-form-validation), we now provide more guidance on how to approach form validations with terra components.
