### ISSUE TITLE
[terra-form-checkbox] [terra-form-radio] refactor,  add default custom style, add standalone, remove mobile

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#2197]
# Enhancement Request

## Description
- Enhance radio and checkbox to have a custom default style and hide native input, transition that version down to the `terra-legacy-theme` (and terra-mpagestyle-theme if needed).
- Add prop for standalone (bool) which removes padding/margins added by default for it's most common use in forms (also needed for OCS request)
- Remove the custom functionality/detection and styling for the mobile-only variations originally part of version 1 OCS definition for consumer theme (has since been removed and no longer needed).
- Refactor both to leaner markup structure 
_(will update and add code samples)_
- Will resolve leftover items from #1779 

## Additional Context / Screenshots
_(will add standalone prop details)_

**Comment by neilpfeiffer** [comment]
related: investigate #2114

**Comment by yuderekyu** [comment]
Could we remove the native inputs entirely? That would also address cross browser alignment issues between the input and label

**Comment by neilpfeiffer** [comment]
> Could we remove the native inputs entirely? That would also address cross browser alignment issues between the input and label

No, native inputs will still be needed for orion-fusion-theme and any older themes we will need to support, even after a refactor. However, we can now update the default theme to use custom styled checkboxes and radios. Design details will need to be provided before work can begin.

Also we will need to revisit the requirements that will be needed for the standalone checkbox. Initial idea was just to remove any built-in spacing, but will most likely need to double check additional items needed for accessibility.

**Comment by neilpfeiffer** [comment]
Related new found layout bug https://github.com/cerner/terra-core/issues/2917#issuecomment-611015490
that could be solved by first item listed in this issue.
