### ISSUE TITLE
Switch Terra Form Select to using Space Bar instead of Enter for selecting a widget

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#2202]
# Feature Request

Terra Form Select is not compatible with screen readers. For a screen reader, if you hit enter on a form input, JAWS uses that to automatically exit forms mode, and sends the user to the submit button for the form. However, terra-form-select uses the enter button to make the form selection. This creates a conflict of functionality.

To resolve this issue altogether, we should refactor the terra-form-select to use a space instead of enter when making a selection

Note: This change is very non passive, from the developer stand point to the user endpoint. We will probably have to have discussions on how to best handle this behavior.

## Additional Context / Screenshots
https://support.freedomscientific.com/training/Surfs-Up/Forms.htm

On this page, look for the keywords Multiple Selection.

**Comment by JakeLaCombe** [comment]
I do understand as well that for the search, we could have values with spaces in them. I don't think there is a good win win situation for this issue, so we will have to make some heavy decisions on the functionality of this component.

**Comment by StephenEsser** [comment]
How does Jaws interact with the native Select? The native Select uses space and enter to make a selection. Does it have the same problem, or does it have browser native screen reader support?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by JakeLaCombe** [comment]
The default variant is operating without issues, and the normal search appears to be operating fine as well. However, it's mostly that multi-select that is causing issues. Since it's focused on an input field, it appears to be entering and exiting form mode when a list item is selected, making it hard to select more than one item

**Comment by JakeLaCombe** [comment]
There were several recent changes made the the select component, and most notably I think the aria-owns attribute is helping with this issue. When I am using the form component in JAWS, I'm not running into issues with forms mode. I think we are safe to close this.
