### ISSUE TITLE
[terra-form-select] - Ability to validate the searchValue in Select component

### ISSUE THREAD

**Issue by bbaraban** [cerner/terra-core#2208]
# Feature Request

## Description
My team (Orders and Plans Dev) would like to be able to verify the input the user has entered into the Select (combobox variant) before it is rendered or used to search for options.

For example, consider a field that accepts any non-negative integer values. We would like to be able to validate the new value before it's updated in state or used to search for options. For instance, we would make sure it's a valid number (not 'Bob' or 'Two'), it's non negative. We would also not allow '-' to be inputed, and would prevent decimal points from being inputed.

Currently we're achieving this with the InputField, when a numeric fields do not have existing options to pick from, but doing this validation in onChange and not updating the state when the value isn't valid.

## @ Mentions
@StephenEsser

**Comment by ryanthemanuel** [comment]
@bbaraban, is this use case for selecting numeric values?  Couple of questions.  What is the range typically?  Is it a range or just a set of numbers?

**Comment by ryanthemanuel** [comment]
If we exposed the pattern field on the underlying input and then you passed in a pattern of [0-9] would that be acceptable?

**Comment by bbaraban** [comment]
For our use case it would be positive and negative integers and decimals. So the set of allowed characters is [-][.][0-9]. This also while using the variant "combobox" so for those free-text entries we want to be able to prevent bad input from being typed in. 

From understanding of the pattern field is that it just marks the field invalid if it's not met. It doesn't actually prevent users input as they're typing.

To achieve what we would like we need a call back one could provide that determines if the search value is acceptable before it's used. So on every key stroke (before state update in _Field) it would be called with the current value passed in. We could then look at the value and decide if it's acceptable and return true. If false is returned the component just wouldn't update the state with that value effectively preventing the user from entering any non-valid input.

**Comment by ryanthemanuel** [comment]
Out of curiosity, what negative/decimal values are you selecting?  I'm loosely familiar with the orders use case and I don't remember any order details that have a set of negative/decimal numbers.

**Comment by bbaraban** [comment]
Some fields will have predefined 'options' that are loaded and those are what would be selected. In the case of numeric fields, even when there is options to select, the user can still manually enter a value. In all fields except for 'user defined fields' it will be positive. One example for decimals fields would be dose.

My concern isn't with 'selecting' pre se but the 'combobox' variant and how it allows for any value to be entered. We need the ability to validate the inputed searchValue before it's accepted/used for search.

**Comment by ryanthemanuel** [comment]
If we exposed the pattern field on the underlying input and then you passed in a pattern of [0-9.] would that be acceptable?

**Comment by bbaraban** [comment]
> From understanding of the pattern field is that it just marks the field invalid if it's not met. It doesn't actually prevent users input as they're typing.

I don't think that would work here. The user can still enter bad input. Though, would you be reading if the field is valid or not and not updating the searchValue based on the pattern?

**Comment by ryanthemanuel** [comment]
Good point @bbaraban.  We have some ideas floating around and will come up with something.  We're trying to make sure we're picking the right set of events and creating the right API.

**Comment by ryanthemanuel** [comment]
@benbcai is going to work on prototyping something out for this.  Stay tuned.
