### ISSUE TITLE
div does not respect height:100% in IE 11

### ISSUE THREAD

**Issue by SpartaSixZero** [cerner/terra-core#2219]
# Bug Report

Hi,

We are seeing a strange issue with IE 11 only.

It looks fine in Chrome and Edge but looks squished in IE 11.

After further investigation, I've tracked down the responsible element that is causing the squished height.

![image](https://user-images.githubusercontent.com/6554762/52439657-1dab7300-2aea-11e9-97d8-be98b157644f.png)

It is the div with the class "_1d5no1b"
 
I have no idea why this div doesn't seem to respect height: 100% in IE 11 but does respect height: 400px

I think the component in question is DynamicGrid. https://engineering.cerner.com/terra-ui/#/components/terra-dynamic-grid/dynamic-grid/dynamic-grid

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Expect this div to have height of 100% in IE 11

## Current Behavior
div looks squished

## Steps to Recreate
I created an example of this using repl.it here:
https://repl.it/@SpartaSixZero/List-displaying-incorrectly-in-IE-11

## Environment

* Component Version: 
* Browser Name and Version: IE 11 (Version 11.0.9600.17843)
Update Versions: 11.0.20 (KB3058515)
* Operating System and version (desktop or mobile): Windows 7 Enterprise SP1

## @ Mentions
@tbiethman

**Comment by SpartaSixZero** [comment]
What's interesting is that if I inspect the element in developer tools using Chrome, if I look at the styles section, I see that the element in question inherits from div.orion-layout in which one of the inherited styles is height: 100%.

![image](https://user-images.githubusercontent.com/6554762/52506839-d68eb200-2bbd-11e9-8d5f-ab7a6218f954.png)

If I do the same thing in IE 11, I don't see height: 100% mentioned anywhere for that same element. IE 11 developer tools also doesn't show that the element inherits from div.orion-layout.

![image](https://user-images.githubusercontent.com/6554762/52507038-69c7e780-2bbe-11e9-9344-212384167651.png)

**Comment by JakeLaCombe** [comment]
Is there a trick to getting your code to run? the link appears to be unable to generate it

**Comment by JakeLaCombe** [comment]
Looks to be working now. I'll investigate

**Comment by JakeLaCombe** [comment]
So this is a defect within IE11 itself that won't be resolved when you have auto sizing values. See 
https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/ and https://stackoverflow.com/questions/28627879/flexbox-not-filling-height-in-ie11 for more details.

In your code, one thing to note is that IE grids require explicit values for all of their columns and rows. Thus, to get what you need working, you need to set `grid-column-rows` of your grid template.

```
const template = {
  "grid-template-columns": "350px 1fr",
  "grid-template-rows": "100%",
};
```

**Comment by SpartaSixZero** [comment]
Thanks @JakeLaCombe . Appreciate the help!!! I'll give this a shot today!

**Comment by SpartaSixZero** [comment]
Verified that the solution works perfectly!
