### ISSUE TITLE
Inconsistent behavior: input field vs date field

### ISSUE THREAD

**Issue by JeanAndrsn** [cerner/terra-core#2232]
# Bug Report

## Description
If I have a text input field and a date field both required, and I tab through the fields without entering anything in them – then I get the “Required” message below the text field but not below the Date field.  For the Date field, I have to hit the Save/Submit button before the UI will give the “Required” message.

## Steps to Reproduce

1. Required: Data entry form containing both a text input field and a date field, with both set to be required before the form can be submitted
2. tab through the form, passing the text input field without entering anything in it
3. Notice that the text "Required" appears below the field as you tab out of it
4. tab through the form, passing the date field without entering anything in it
5. Notice that no text appears below the date field and there is no indication that the user should have entered a date

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/47646382/52821297-6334e680-307c-11e9-83be-acc2acb1d97c.png)
![image](https://user-images.githubusercontent.com/47646382/52821314-721b9900-307c-11e9-81ef-c15fd2bf33b7.png)

## Expected Behavior

Tabbing past a required date field should give the same behavior as tabbing past a required text field

## Environment

* Component Name and Version: Date Picker
* Browser Name and Version: Chrome
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
 Jeremy Fuksa (UX)

**Comment by lokesh-0813** [comment]
https://engineering.cerner.com/terra-ui/#/components/terra-date-picker/date-picker/date-picker-field solves the issue.

**Comment by bjankord** [comment]
Having [the date field component](https://engineering.cerner.com/terra-ui/#/components/terra-date-picker/date-picker/date-picker-field) now will allow you to implement [the solution @JakeLaCombe mentioned.](https://github.com/cerner/terra-core/issues/2232#issuecomment-464085449)
