### ISSUE TITLE
[terra-form-select] Prevent special characters from being added

### ISSUE THREAD

**Issue by shinepd-zz** [cerner/terra-core#2242]
# Feature Request

## Description
Prevent special characters from being entered into the form-select control.

## Additional Context / Screenshots
![alpha list special characters](https://user-images.githubusercontent.com/22062222/53051389-6572b880-3461-11e9-8a17-bc4a2bc34f2d.png)

**Comment by StephenEsser** [comment]
This is likely a duplicate of https://github.com/cerner/terra-core/issues/2208
