### ISSUE TITLE
[terra-form-select] Improve mobile usability for long freetext responses

### ISSUE THREAD

**Issue by shinepd-zz** [cerner/terra-core#2243]
# Feature Request

## Description
When using the form-select on mobile devices, it can become difficult to use the control when dealing with long freetext responses.

## Additional Context / Screenshots
![mobile alpha 1](https://user-images.githubusercontent.com/22062222/53052168-96ec8380-3463-11e9-979a-2cef5bbe18f8.png)
![mobile alpha 2](https://user-images.githubusercontent.com/22062222/53052170-96ec8380-3463-11e9-9779-13f424582045.png)
![mobile alpha 3](https://user-images.githubusercontent.com/22062222/53052169-96ec8380-3463-11e9-8f39-5907bd29abff.png)

**Comment by JakeLaCombe** [comment]
We'll need UX input to determine ideal size for long text items.
