### ISSUE TITLE
[terra-form-select] Script error on selecting value and moving cursor point

### ISSUE THREAD

**Issue by ravikiran6565** [cerner/terra-core#2246]
# Bug Report

## Description

Getting script error on select terra-form-select field value "Uncaught TypeError: Cannot set property 'innerText' of null"

## Steps to Reproduce

1. Select value from terra-form-select and move mouse cursor on selecting value.
2. Make sure move cursor instantly after selecting value.

## Additional Context / Screenshots

I will share video through email if it required. Can't share solution video screen in public website.
Please refer attachment for reference of error and stack flow. 
![screenshot 2019-02-26 at 2 40 09 pm](https://user-images.githubusercontent.com/39581781/53401567-10d9bb00-39d6-11e9-95ec-02155d1de74b.png)

![screenshot 2019-02-26 at 2 40 18 pm](https://user-images.githubusercontent.com/39581781/53401597-218a3100-39d6-11e9-9d8e-28a0c2cf6046.png)

## Expected Behavior

On selecting it should not throw any error.

## Possible Solution

N/A

## Environment

* Component Name and Version: blood-loss-inventory and 1.0.3
* Browser Name and Version: Cross browsers IE, Firefox, Safari and Chrome(latest version)
* Node/npm Version: Node 10.11.0/npm 6.4.1
* Webpack Version: ^4.6.0
* Operating System and version (desktop or mobile): Mac Desktop

## @ Mentions

N/A

**Comment by JakeLaCombe** [comment]
I will send a pull request to fix this. I notice when a select is completely unmounted that the timeout is still called. We will do a better safe check inside the function to make sure the component is not null before updating.
