### ISSUE TITLE
Migrate away from using dataURIs

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2247]
# Feature Request

## Description
A security concern has been brought up about the usage of data URIs in Terra UI. While there doesn't appear to be a security concern directly with our usage of data URIs, by allowing data URIs in an application, it opens the application up to vulnerabilities. Teams are interested in mitigating this concern with [Content Security Policies](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) that disallow all usage of data URIs.

### What this means for Terra UI.
If teams set up this CSP to disallow all usage of dataURIs, they would no longer see terra icons we've embedded as background-images into components as dataURIs.

Currently, we [transform SVGs into dataURIs](https://github.com/cerner/terra-core/blob/master/packages/terra-mixins/src/Mixins.scss#L575-L621) and set them as [background images](https://github.com/cerner/terra-core/blob/master/packages/terra-avatar/src/common/Avatar.module.scss#L45) for components we have which include component specific SVGs. This enables the ability to set thet background-image to a CSS custom property and swap out the background image to another image if needed.

We'll want to look at storing SVGs with the components and making them available as part of the individual component packages. These SVGs will then be used as background images but will not be dataURI'd

**Comment by bjankord** [comment]
Need to follow up with team and see if we can lock dataURI usage down to only images.

**Comment by nickpith** [comment]
Looking at https://security.stackexchange.com/questions/194909/data-image-with-csp#comment386755_194909 I'm not sure data URIs in `img` tags are a XSS threat. But we should look explicitly for any XSS attack that can prove this is an issue.

**Comment by bjankord** [comment]
Talked with @nickpith some more on this, closing as n/a. Plan to keep using dataURIs as background-images in CSS files.
