### ISSUE TITLE
Filename Too Long when you clone this repo

### ISSUE THREAD

**Issue by calebmeyer** [cerner/terra-core#2253]
# Bug Report

## Description
Cloning the repo produces an error from powershell on windows

## Steps to Reproduce
```
$ git clone https://github.com/calebmeyer/terra-core.git
Cloning into 'terra-core'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 69516 (delta 44), reused 80 (delta 29), pack-reused 69409
Receiving objects: 100% (69516/69516), 90.91 MiB | 17.70 MiB/s, done.
Resolving deltas: 100% (47364/47364), done.
error: unable to create file packages/terra-responsive-element/tests/wdio/__snapshots__/reference/en/chrome_medium/responsive-element-spec/should_render_the_default_element_at_all_viewports_if_the_parent_remains_the_same_width[default].png: Filename too long
Checking out files: 100% (3721/3721), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

## Expected Behavior
I expected no errors

## Possible Solution
If we can truncate these auto-generated file names, or come up with a new naming scheme, that would help

## Environment
* Operating System and version (desktop or mobile): Windows 10 Enterprise Version 10.0.17134

## @ Mentions
@mjhenkes

**Comment by yuderekyu** [comment]
I'm curious, does [this suggestion](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows) mitigate the issue? Seems like this is a Windows API issue, not a Terra issue.

There's a recent issue logged to git-for-windows similar to this: https://github.com/git-for-windows/git/issues/2075

**Comment by calebmeyer** [comment]
Yep, issue solved. Thanks for the help!
