### ISSUE TITLE
[Action Footer] Allow us to set the border style none

### ISSUE THREAD

**Issue by matlapuditeja** [cerner/terra-core#2256]
# Feature Request

## Description

Add a border-top-style property which sets the style of an element's top border.
Allow us to set the border 
`border= {false} `
I have to set a style for the top border to turn off the horizontal line as you can see in the screenshot. when I embedded Action Footer in a card.
The code looks like this when I added the style:
`const footerstyle = { 'border-top-style': 'none' };`

``
<ActionFooter
                  style={footerstyle}
                  end={
                    <Button
                      text="OK"
                      onClick={this.handleCloseModal}
                    />
                  }
                />
``
Please check the screenshots below how it looks with and without style.
## Additional Context / Screenshots

**without border style**
<img width="332" alt="without border style" src="https://user-images.githubusercontent.com/48136855/53748274-a4920800-3e6a-11e9-8e12-ee84a6c1e83a.png">
**with border style**
<img width="336" alt="with border style" src="https://user-images.githubusercontent.com/48136855/53748278-a65bcb80-3e6a-11e9-9485-01b4a728a868.png">

## @ Mentions

I worked with @ryanthemanuel. I am trying to figure out the solution this is unrelated.

**Comment by yuderekyu** [comment]
@matlapuditeja from the screenshots, it looks like you should use `terra-content-container` or `terra-dialog-modal` instead of `terra-card`. These two components play nicely with the `terra-action-header` and `terra-action-footer` by arranging header + content + footer without appending borders.

**Comment by matlapuditeja** [comment]
@yuderekyu there was a scenario which I have to use Dialog Instead of Dialog modal.
I have to get a modal isRelativeToContainer. As there is no such Prop in Dialog Modal I am using overlay.
So in order to get similar to that I am using card and Dialog inside overlay component.

**Comment by yuderekyu** [comment]
@matlapuditeja I think I am on the same page as you now. I recommend not using `terra-dialog` - we plan to deprecate it in the future.  Try using a `terra-content-container` in combination with `terra-action-header` and `terra-action-footer`. Pass this into a card and render this in an overlay.

**Comment by matlapuditeja** [comment]
Ok @yuderekyu  thanks will try that.

**Comment by yuderekyu** [comment]
@matlapuditeja is this still an issue?
