### ISSUE TITLE
Update danger.js devDependency to latest version

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2274]
# Issue Description
Currently we use danger `^3.7.14`

The latest stable release of danger is `7.0.15`.
https://www.npmjs.com/package/danger

Looking at the changelog for Danger, I'm not sure how easy this will be to update.
In v4, they updated Danger's runtime to work with Babel 7 so we might need to be on Babel 7 as well top update to v4.

We currently use Danger to remind contributors to update the changelog (which is a very nice feature) and then warn people that their PRs are to big if the additions/deletions are over a certain size (no one seems to pay attention to this message). 

I'm curious if we can get similar functionality from using GitHub actions. The interest in using GitHub actions instead of Danger is that it may provide a more stable tool to achieve what we're currently doing with Danger.

**Comment by emilyrohrbough** [comment]
Talked with @Blackop778 about this change. Bumping requires babel 7, which will be introduced in #2416. Nathan confirmed no other breaking changes would impact us so we will bump that version in that pr.

**Comment by Blackop778** [comment]
This was done in #2418
