### ISSUE TITLE
Investigate removal of terra-base peer dependencies from packages

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#2291]
# Feature Request

## Description

The vast majority of the Terra packages today have a peer-dependency on terra-base. This dependency serves two purposes:
1. It allows components to import the terra-base stylesheet. This stylesheet contains global styles for the html and body elements. We've been importing this stylesheet before any component-specific stylesheet to enforce the style ordering in the webpacked css output.
2. It tries to nudge the consumer into wrapping their component in terra-base, which is a requirement of most Terra components.

However, the dependency isn't free. Having this dependency in each package can trigger broad major versioning changes if terra-base needs to get bumped. This hurts the reusability of the components at an individual level and usually results in consumer projects with a large quantity of unmet peer dependency warnings during install.

If we can determine that point 1 above isn't necessary for style consistency and that 2 can be purely enforced through documentation, it would be nice to remove these terra-base peer dependencies altogether.

## @ Mentions
@bjankord

**Comment by bjankord** [comment]
Without the peerDependency, how would teams know what version of terra-base to use with their component?

With the proposal for 2. (be purely enforced through documentation), I think teams would still have unmeet peerDependencies, but now they wouldn't see warnings. 

Using a component that relies on react-intl, you need the IntlProvider which is provided via an abstraction in terra-base/terra-i18n. We've used the peerDependency to communicate this relationship between components that have translations and the IntlProvider that is used in terra-base. 

If we drop that peerDependency and use docs and or console warnings to communicate the provider / consumer releationship needed for react-intl, I think teams would still have a difficult time figuring out what specific version on terra-base has the right IntlProvider needed for use with the translations.

To me, 1. and 2. are global dependencies needed in the Terra UI ecosystem. Using npm to communicate that relationship seems like a good fit. I'm not opposed to exploring alternatives to how we have base set up today.

Having some more concrete info on the problems related to having a peerDependency on terra-base is causing, like expanding more on how it hurts the reusability of the components at an individual level or  expanding more on how it results in consumer projects with a large quantity of unmet peer dependency warnings during install, would help us find solutions for those problems.

**Comment by bjankord** [comment]
Here are the styles pulled in via terra-base.

<details>
 <summary>Summary Goes Here</summary>
  <pre><code>
html {
  background-attachment: var(--terra-base-background-attachment);
  background-color: var(--terra-base-background-color, #fff);
  background-image: var(--terra-base-background-image);
  background-position: var(--terra-base-background-position);
  background-repeat: var(--terra-base-background-repeat);
  background-size: var(--terra-base-background-size);
  // Normalize box-sizing.
  // More info: https://css-tricks.com/box-sizing/#article-header-id-6
  box-sizing: border-box;
  font-family: var(--terra-base-font-family, 'Helvetica Neue', Helvetica, Arial, sans-serif);
  font-size: var(--terra-base-font-size, 87.5%);
  height: var(--terra-base-html-height, 100%);
  margin: var(--terra-base-html-margin, 0);
  text-size-adjust: 100%;
}

body {
  color: var(--terra-base-color, #1c1f21);
  font-size: 1rem;
  height: var(--terra-base-body-height, 100%);
  line-height: var(--terra-base-line-height, 1.4285714285714286);
  margin: var(--terra-base-body-margin, 0);

  @media print {
    background-color: transparent !important;
    color: #000 !important;
  }
}

*,
*::before,
*::after {
  box-sizing: inherit;
}
  </code></pre>
</details>

I think some of these styles could be pushed down into the components. e.g. Components could define their box-sizing styles. Each component could set `box-sizing: border-box;` on itself in related children and that would remove the need for it in the base style. 

Similarly, we could push print styles down to the component level and components define their own print styles.

I find that the rest of the styles are harder to push down into the individual components. To me, these styles are ideally defined once globally at the beginning of the stylesheet. One idea I had thinking of a way to remove these from terra-base was to provide a separate stylesheet with just these styles. I view them as more or less feature complete and not needing a lot changes. I could see them being put in a CSS file we host on a CDN and add some docs on how to include it.

Something like: 
Terra UI relies on these global styles, we recommend importing once at the beginning of your app.
```
<!-- index.html -->
<link ref="stylesheet" href="https://cdnjs.com/terra-base-styles.css">
<script type="text/javascript" src="terra-dev-site-747f19a6f6d0a6fa5159.js"></script>
```

What I don't like about that idea is that today we can ensure those global styles exist. We do this by importing the base styles in every component and letting webpack dedupe the import when multiple components are used. With moving these styles out to a separate file that we tell users to include, theres no guarantee they actually include it. They could have an app that doesn't use the core base styles we've done all the testing of components with and assume to be in the CSS when an app is built.

**Comment by bjankord** [comment]
Talked with @tbiethman some more on this issue. I can get on board with the idea of removing the peerDep on terra-base and nudge the consumer into wrapping their component in terra-base, which is a requirement of most Terra components as well as including react-intl as a peerDep in packages that have translations. 

I'd like to find a solution for 1. 

> allows components to import the terra-base stylesheet. This stylesheet contains global styles for the html and body elements. We've been importing this stylesheet before any component-specific stylesheet to enforce the style ordering in the webpacked css output.

Talked with @tbiethman about making a package, terra-base-styles. that would include the current styles from terra-base. These styles are fairly static / feature complete in my mind. I don't foresee a lot of changes to them. We could treat this package like terra-base is today and have it be a dependency in every package to ensure the style order is generated as expected. But the risk of needing to major version bump this package, which could result is mismatch versions, is much much lower compared to terra-base today. 

Plan to talk some more about this in our lead sync tomorrow.

**Comment by bjankord** [comment]
Notes from lead sync:

* Plan to drop peerDependency on terra-base across packages.  We're considering this change to passive.
* Packages will still need terra-base, however, that relationship will no longer be communicated via peerDependency. 
* Documentation will be used to indicate this relationship. Components that require translations will also log warning if IntlProvider is not used.
* For the first bullet point mentioned on the issue, we'er working on the assumption that if base is imported, the global styles will be imported as well. We currently document that terra-base is needed when using terra components so if this component is missing, teams are not following the documented guidance for using terra.

**Comment by bjankord** [comment]
Put out a PR to update terra-framework: https://github.com/cerner/terra-framework/pull/557
The current PR updating terra-core will resolve removing terra-base peerDependency and normalizing the react-intl peerDepedency
