### ISSUE TITLE
[terra-form-select] - Optional search functionality

### ISSUE THREAD

**Issue by johnaudas** [cerner/terra-core#2305]
# Feature Request

## Description
For the variant="multiple",  the Select react component should be an option to turn off the default search functionality. The dropdowns in my app are small and do not need the search functionality.  In addition, on the android platform the search forces the popping up of the keyboard which often covers the dropdown.

**Comment by neilpfeiffer** [comment]
This technically would fall as a new variant -- would be a straight multi-select similar to the single-select -- and have it's own rollup design pattern (not use pills/tags) -- similar to an [example like this](https://3.bp.blogspot.com/-mg8pbAHtdYg/XDOaDK813ZI/AAAAAAAAANo/kNBjFWd_Ds4U0MH5Wqll36ph08DR93FOQCLcBGAs/s1600/bootstrap-jquery-muli-select-drop-down-list-with-the-checkbox-in-asp-dot-net.png).

UX needs to validate if this a type of multiselect Terra should support and what the rollup pattern needs to be. Further design is required before implementing.
