### ISSUE TITLE
Replace customStatusColor prop from Terra Alert

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-core#2307]
# Feature Request
Similar to: https://github.com/cerner/terra-core/issues/1999

CustomStatusColor is an untheme-able color prop and should be relplaced with a color class.

**Comment by bjankord** [comment]
Planning to hold off on this change until around the end of Q2/beginning of Q3 to minimize major version bumps in the Terra UI ecosystem.

**Comment by ryanthemanuel** [comment]
We will want to do something very similar to this: https://github.com/cerner/terra-core/pull/2211
