### ISSUE TITLE
[terra-form-select] - Add support for HTML5 validation UI

### ISSUE THREAD

**Issue by saedar** [cerner/terra-core#2308]
# Feature Request

## Description
`terra-form/select` used to support HTML5 required field validations. With the moving to `terra-form-select`, that is no longer supported.

I understand that this is a custom select box. Would it be possible to apply the `required` to the underlying `input` and surface the HTML5 validation UI?

**Comment by StephenEsser** [comment]
Terra [recommends](https://engineering.cerner.com/terra-framework/#/components/terra-form-validation/form-validation/form-validation) using [React Final Form](https://github.com/final-form/react-final-form) for validations. 

The custom Select doesn't currently have an underlying input that preserves a value so there is nothing to attach the required prop to. Adding an input would require a bit of string manipulation for selecting multiple values and layering them onto the input. 

There are a few issues with adding the required attribute onto an input and it may not have the desired effect.

The html 5 validation message would be strangely worded.

A Select should display the following message:

![image](https://user-images.githubusercontent.com/6720991/55087191-af117d00-5077-11e9-9e7a-3b03f009489a.png)

An input would display:

![image](https://user-images.githubusercontent.com/6720991/55087243-ca7c8800-5077-11e9-8d79-0ed3940fd6a6.png)

It would be good to reach out to UX and gather their perspective on this enhancement. Ideally form validations would be consistent across applications. By adding in HTML 5 validations we would be supporting two different validation approaches that look and behave differently.
