### ISSUE TITLE
ActionHeader does not render Maximize/Minimize buttons if Back button is present

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#2313]
# Bug Report

## Description
The ActionHeader has explicit logic that will prevent the Maximize and Minimize buttons from rendering if a Back button is also being rendered. This doesn't seem appropriate for most use cases. Is this a bug or an explicit design decision?

## Expected Behavior
The ActionHeader can render Back and Maximize/Minimize buttons at the same time.

## Possible Solution
We should just need to remove the backButton presence check here: https://github.com/cerner/terra-core/blame/master/packages/terra-action-header/src/ActionHeader.jsx#L101

## Environment

* Component Name and Version: terra-action-header/latest

**Comment by tbiethman** [comment]
I got a little more insight from @neilpfeiffer. The placement of the current maximize/minimize buttons is not ideal from a design standpoint. The design recommendation would be to NOT use the onMaximize/onMinimize APIs of the ActionHeader; instead, one should render their own maximize/minimize buttons as options in a CollapsibleMenuView that is rendered within the ActionHeader. 

The problem is that none of this is officially documented 😞so we should go through and document those expectations.

**Comment by yuderekyu** [comment]
Do we plan on fixing the placement of those buttons in the future, or remove the props on the next major version bump?
