### ISSUE TITLE
[terra-form-select] Text no longer fills select before truncation

### ISSUE THREAD

**Issue by prmeznar** [cerner/terra-core#2325]
# Bug Report

## Description
Text truncates far earlier in 5.12.0 than in 5.11.0, before the area of the select is taken up

## Steps to Reproduce
1. Have a select box (tested with 'search' variant, likely applicable across the board)
2. Have real long text entry
3. Observe truncation

## Additional Context / Screenshots
5.11
![image](https://user-images.githubusercontent.com/47360296/55584994-3c457900-56eb-11e9-912b-e4327a6b12fc.png)

5.12
![image](https://user-images.githubusercontent.com/47360296/55585012-49fafe80-56eb-11e9-964b-67040fd6f93c.png)

## Expected Behavior
Text does not truncate until select area is filled up.

## Possible Solution
Thinking [this change](https://github.com/cerner/terra-core/commit/553a8db6ba8641cf37211698fdfaf747904071cf#diff-a7694d0174d676146b494561fb4ffb04L133) meant that [here](https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/_Frame.jsx#L231) and perhaps elsewhere should be updated to display-content

## Environment
Chrome, Mac

## @ Mentions
@bjankord

**Comment by bjankord** [comment]
Looking at https://engineering.cerner.com/terra-core/#/components/terra-form-select/form-select/select, I believe we have a fix landed for this in master already. Should be available in our next weekly release.

**Comment by bjankord** [comment]
Resolved in #2323

**Comment by StephenEsser** [comment]
Closing. 

From the comment above the issue was resolved with #2323.
