### ISSUE TITLE
[terra-i18n-plugin] Deprecate on NPM

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2333]
# Feature Request
We list this package as deprecated on the readme, but it's not deprecated on the NPM registry.

**Comment by emilyrohrbough** [comment]
Yesterday I was reading someone's console output that was using terra-i18n-plugin and we should do one last release to update the deprecated message that is output. It currently says use `terra-i18n aggregate-translations tool` instead of terra-toolkit's aggregate translations tool

**Comment by ryanthemanuel** [comment]
@emilyrohrbough I'm not sure how possible it is to do another release of the tool since it doesn't exist anymore.  I'm going to deprecate the package though.

**Comment by ryanthemanuel** [comment]
Deprecated:

![image](https://user-images.githubusercontent.com/4873279/55962837-4b6e7e80-5c37-11e9-971c-f2d55755a935.png)
