### ISSUE TITLE
Add styles for "invalid" form inputs

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#2342]
# Feature Request

## Description

Currently, the '--terra-form-input-error-border' variable does not provide any distinction when the input is in an error state (it remains black).  Other themes, provide a distinction.  We need to come up with something similar.  It would be good to evaluate other form fields in the process (text area, etc.) to see if we're also missing this functionality.

**Comment by pranav300** [comment]
This issue seems to be resolved in this [PR](https://github.com/cerner/terra-core/pull/2670).
