### ISSUE TITLE
Update to terra-dev-site v4

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2343]
# Feature Request

## Description
terra-dev-site v4 is available. We should [update our dependency on terra-dev-site](https://github.com/cerner/terra-core/blob/master/package.json#L90) to `^4.0.0`.

**Comment by PayalSawant** [comment]
I would be willing to work on this if thats ok @bjankord

**Comment by bjankord** [comment]
Sounds good, looking forward to the PR.

**Comment by PayalSawant** [comment]
@bjankord  Question: The [PR template](https://github.com/PayalSawant/terra-core/blob/PayalSawant-Update-1/.github/PULL_REQUEST_TEMPLATE.md) says add your name to the contribution list. The [contributors list](https://github.com/PayalSawant/terra-core/blob/PayalSawant-Update-1/CONTRIBUTORS.md) however says Cerner corporation at the top followed by a list of people. I dont work for Cerner, should I still be adding my name in the list?

**Comment by bjankord** [comment]
@PayalSawant We've added a "Community" section to add you name/GitHub profile to in the [CONTRIBUTORS.md file](https://github.com/cerner/terra-core/blob/master/CONTRIBUTORS.md).

**Comment by bjankord** [comment]
Resolved with https://github.com/cerner/terra-core/pull/2352
