### ISSUE TITLE
[terra-divider] New margin is not right

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#2344]
# Bug Report

## Description
Divider used to have a margin of 0.  Now it does not.  This gives "padding" in places we were not expecting it.

## Steps to Reproduce
1. Create a page with a terra-action-header.
2. Add a terra-divider immediately after it.

Test with the old version of terra-divider (< 3.6.0).  There is no space between the divider and the content.
Test with the new version (3.6.0).  There is space between the header and the divider.
It is easy to see the space with any control that has its space filled with a color.

## Additional Context / Screenshots
We found the issue after Fix #2296 was released.
No Space (old version)
<img width="598" alt="no_space" src="https://user-images.githubusercontent.com/30238809/56310602-e8d32200-6111-11e9-9a64-77a15f1ec3a2.png">

Space (new version)
<img width="621" alt="space" src="https://user-images.githubusercontent.com/30238809/56310581-dd7ff680-6111-11e9-8357-fbb7393e3336.png">

## Expected Behavior
Given this is a minor update, margin should remain 0 when there is no text.

## Possible Solution
If the margin needs to change, it should only change when there is text.  Or allow the user to opt in.  Or make the change a major version bump, so teams have time to figure out what to do about it.

## Environment

* Component Name and Version: terra-divider 3.6.0
* Browser Name and Version: Chrome Version 72.0.3626.119  (and in our Chrome wdio tests)
* Node/npm Version: 
* Webpack Version:
* Operating System and version (desktop or mobile): desktop

**Comment by bjankord** [comment]
Looks like we missed this in our review of https://github.com/cerner/terra-core/pull/2296. I can work on getting a PR out to fix this.

**Comment by bjankord** [comment]
This has been resolved in terra-divider@3.7.0
