### ISSUE TITLE
[terra-profile-image] Allow consumers to load a default profile image

### ISSUE THREAD

**Issue by VivekChittamuri** [cerner/terra-core#2359]
# Feature Request
Is it possible for src prop of terra-profile-image be made optional. Allowing consumers to load the failed profile image if src is empty/nil?

## Description
Allow consumers to load the default image when src is blank or empty. We as a consumer have the following scenarios for our user list

1. **User exists: Image Might Exist**
     a. Image successfully loads **(Works Today)**
     b. Image fails to load **(Works Today)**

2. **User exists: Image does not exist yet** (we know this before even attempting a image load)
     a. In this scenario we want the exact same Failed Profile image(**Feature Request**)

## Additional Context / Screenshots
Today, to get this behavior we are having to pass a dummy url end point, but that increases the network traffic as it keeps trying to make the call to a non existent endpoint and keeps failing. And if we have auto refresh functionality implemented these dummy errors increase.

Also, just want to add that a terra-avatar does not really work for us here as we do not want to draw too much of a end user attention throwing in different kinds of profile images for the above scenarios. 

If further context is needed, please reach out to me on Teams.

**Comment by bjankord** [comment]
Talked about making the src prop no longer required that way you can get the fallback simply by not providing a src image.

**Comment by nramamurth** [comment]
### **Preliminary Investigation:** 

I'd believe that two things need to be done here: 

1. Make `src` optional. 

```diff
  /**
   * The source for the image which will be displayed.
   */
-  src: PropTypes.string.isRequired,
+  src: PropTypes.string,
```

2. If `src` is not supplied, then render the placeholder.

```diff
if (props.src) {
   return (<div><TerraImage placeholder={placeholderImage} {...props} /></div>);
}

return placeholderImage;
```

@bjankord Please lmk if the changes could involve a lot more than this.

**Comment by bjankord** [comment]
@nramamurth Sounds like a good approach to me. 👍
