### ISSUE TITLE
[terra-action-header] in iFrames 100% height expands header

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#2362]
# Bug Report
When displaying an action header within an iframe the header to fill the next relative container. 

## Description
When displaying an action header within an iframe it's 100% height inner values expanded the header to fill the next relative container. This 100% behavior is a hold over from the previous terra-clinical-header where the header was a fixed outer height. 

## Additional Context / Screenshots
![Screen Shot 2019-04-26 at 12 07 34 PM](https://user-images.githubusercontent.com/22619500/56827943-ce8df800-6825-11e9-9205-41c6f7f04f8a.png)

## Possible Solution
We can achieve our same standard behavior and fix the iframe bug by removing the 100% heights used within the elements of the action header container, and change the align-items to flex-start, we can also remove the alignment entries from individual elements and just use a top level align items. This will maintain the top aligned behavior of the header.
```diff
- height: 100%;
- align-items: center;
+ align-items: flex-start;
```
## Environment
* Component Name and Version: terra-action-header
* Browser Name and Version: current safari and chrome

**Comment by ThomasLiptack** [comment]
Is there a time frame for this fix?

**Comment by ryanthemanuel** [comment]
We try and fix bugs ASAP.  We have a support queue dedicated to fixing them.  Once it's fixed, we release weekly.  This one I imagine will be in our release next Tuesday or the following Tuesday.

**Comment by ThomasLiptack** [comment]
Hey guys I see this has been fixed and merged. So this will be released next tuesday? Also do you have the expected new package version?

**Comment by mjhenkes** [comment]
terra-action-header 2.13.0 was released yesterday and contains the fix.
https://www.npmjs.com/package/terra-action-header

**Comment by ThomasLiptack** [comment]
oh great thank you Matt
