### ISSUE TITLE
[terra-table] Add ability to unselect rows in Single Selectable Rows examples

### ISSUE THREAD

**Issue by jeremyfuksa** [cerner/terra-core#2363]
# Enhancement Request

## Description
In the Single Selectable Rows examples, a selected row cannot become unselected unless another row is selected. It seems that it should also be possible to unselect a row by selecting it a second time.

Is there a reason the example functions the way it does? Or should this enhancement be made?

**Comment by bjankord** [comment]
cc/ @neilpfeiffer

**Comment by dkasper-was-taken** [comment]
SingleSelectTabeRows doesn't not support deselection. A consumer of the table needs to use the SelectableTableRows to provide their own deselection behavior. Long term table selection will no longer be uncontrolled, so we maybe able to close this in either case.

**Comment by dkasper-was-taken** [comment]
Addressed with #2615
