### ISSUE TITLE
Realignment of the headers upon sorting

### ISSUE THREAD

**Issue by SushmithaBN** [cerner/terra-core#2385]
# Bug Report

## Description
When we are using sorting in [terra-table](https://engineering.cerner.com/terra-ui/#/components/terra-table/table/table) on many columns, the presence of the icon is shifting the width of the column as its an in-line span element

## Additional Context / Screenshots

Commit Date as sorted column:
![image](https://user-images.githubusercontent.com/42537313/57287547-62d54600-70d5-11e9-90f4-6ab4edfb34a7.png)
Vendor as sorted column:
![image](https://user-images.githubusercontent.com/42537313/57287519-56e98400-70d5-11e9-9caf-6a2f7cec313a.png)
Difference: 
![image](https://user-images.githubusercontent.com/42537313/57287488-420cf080-70d5-11e9-8d02-8d02cf8b3688.png)

## Expected Behavior
Table headers/column width should not change.

## Environment

* Component Name and Version: [terra-table](https://engineering.cerner.com/terra-ui/#/components/terra-table/table/table) v3.11.0
* Browser Name and Version: Chrome/IE 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Operating System and version (desktop or mobile): Windows, Mac

## @ Mentions

@dkasper-was-taken

**Comment by SushmithaBN** [comment]
@dkasper-was-taken

**Comment by SushmithaBN** [comment]
@dkasper-was-taken

**Comment by Rohanjos97** [comment]
Hey, is there any update on this issue?

**Comment by dkasper-was-taken** [comment]
Addressed with #2615
