### ISSUE TITLE
Allow for scrollable terra form input panel

### ISSUE THREAD

**Issue by chriskonopka** [cerner/terra-core#2393]
# Feature Request

## Description

Right now terra form input allows for a variable height dropdown which scrolls. However when the panel height is attempted to be modified with styling, no scroll appears in the panel to show all the selected contents. Would like a way to change the display of the panel from hidden with props in order to allow scrolling in the panel. 

## Additional Context / Screenshots

Use case:
My UX designer would like to limit the input panel AND the dropdown to 4 lines each. when more than 4 things are selected it is desired a scorll bar appears inside the input panel and selected elements can be scrolled

**Comment by neilpfeiffer** [comment]
Huh? Completely confused.

**Comment by chriskonopka** [comment]
<img width="312" alt="Screen Shot 2019-05-13 at 9 46 52 AM" src="https://user-images.githubusercontent.com/46536406/57630891-0f934580-7564-11e9-81a9-97b218e2331b.png">
This screenshot will hopefully explain it better, My UX designer would like the ability to lock the input field height to something like a maximum of 4 lines long. Once that limit is reached, they would like a scrollbar to appear inside the panel.

**Comment by bjankord** [comment]
We'd recommend having your designer reach out to OCS to see if they have designs for this. They may have a pattern to handle this use case.
