### ISSUE TITLE
Create a component to detect the network is offline

### ISSUE THREAD

**Issue by hs025828** [cerner/terra-core#2397]
# Feature Request
Provide a component to detect if the network goes offline and display a 'network offline' message.

## Description
All major browser vendors support a way to [detect if you are offline](https://caniuse.com/#feat=online-status).  It would be useful to detect the network connection status so users can be informed when their network drops.

## Additional Context / Screenshots
It has been reported that users were unable to take actions involving network requests.  The cause was because their network connection dropped.  Unfortunately, the user did not realize this and believed there was a problem with the app itself.  It would be useful to inform the user the issue is indeed their network connection so they can take action (e.g. move closer to a router).

## @ Mentions
@ryanthemanuel @StephenEsser @benbcai @neilpfeiffer

**Comment by bjankord** [comment]
This is something that we'd recommend building outside of terra. We can provide the [UI components for displaying the notification](https://engineering.cerner.com/terra-ui/#/components/terra-status-view/status-view/status-view).
