### ISSUE TITLE
[terra-list] Combination of section headers and list items cause inconsistent borders

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2401]
# Bug Report
Cosmetic issue.

## Description
When the border prop is set to `standard` or `bottom-only`, list items, with the exception of the last item and/or first item, have a `border-top` while section headers have a `border-bottom`. 

If these borders are subsequently themed for section headers and list items, the list item before a section header will be missing a border.

<img width="666" alt="Screen Shot 2019-05-17 at 1 11 26 PM" src="https://user-images.githubusercontent.com/14063284/57948239-bcdcc500-78a6-11e9-8637-2f24662eb534.png">

## Possible Solution
We'd need a way to detect if list items are within sections, then alter borders. Unfortunately list items are scoped to list, while sections and subsections are separate.

Perhaps we can move sections + subsection styles to list? Then add css rules for list items within sections or subsections. One for the first list item (`border-top: 1px solid #dedfe0);`) and one for the last list item (`border-bottom: var(--terra-list-section-header-list-item-border-bottom, none`)

The downside is `list.scss` will be enormous. Open to other ideas!

**Comment by bjankord** [comment]
Talked about adding a border to the top of section-header

**Comment by yuderekyu** [comment]
^^^ we may run into issues if section headers are stacked on top of each other. borders will overlap
