### ISSUE TITLE
Item in the List does not stay highlighted/focused after selecting, as we hover focus moves in IE

### ISSUE THREAD

**Issue by arun-odedara** [cerner/terra-core#2403]
# Issue Description

Recently we have started testing our solution in Powerchart application. We came to know about unexpected behavior of terra-list in the patient search dialog explained below. 

When trying to add a patient through search results dialog, after clicking on any patient in the list, patient does not stay highlighted. As soon as we move to other patient, focus will transfer to patient we are hovering over(Not the selected one).

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Once the item is selected from the list it should stay selected when hovering over other items. It should not lose it's focus and still be highlighted.

## Current Behavior
As of now it changes the highlighted item to the item cursor is hovering on.

## Environment

* Component Version:
* Browser Name and Version: IE 10/11
* Operating System and version (desktop or mobile): Windows - Desktop

**Comment by arun-odedara** [comment]
This issue is consistent with IE and powerchart both. We will be using the application via powerchart.
I think at this point this would be the easiest way that I can think of to reproduce the same error as I am familiar with the same workflow in our solution.

But if there is any other way to open the terra list with selectable items in IE, it might be possible.

Open IE -> go to url(s) -> Click on the Add Patient Button -> Search patient

**Comment by dkasper-was-taken** [comment]
Unable to reproduce on IE10 windows desktop using the terra-ui site.

Could you reference the version of terra-list that is being used? An example of the implementation of the list within the component?

As Terra is an open source project and is operated as such, it'd be ideal if you could refrain from referencing internal implementations of projects and logins to recreate your issue. As @bjankord requested, can you try to provide a reduced test case to reproduce this?

**Comment by dkasper-was-taken** [comment]
First guess though is that selection state isn't being updated within the HOC, so only hover and/or keyboard focus styling is remaining.

**Comment by arun-odedara** [comment]
Hi @dkasper-was-taken ,
Recently orion-demographics/ion-patient-search(which is rendering the list) updated their code to pull in latest version of terra-list and that fixed this issue. 

Thank you.
