### ISSUE TITLE
[terra-base] Missing v5 Upgrade Guide

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2423]
# Bug Report

## Description
An upgrade guide was not included in the last terra-base release. The last terra-base release removed the post-install intlLoaders so consumers using base in Jest tests are experiencing errors like: 
```
[test:jest] FAIL test/jest/chart-summary/components/ChartSummaryContainer.test.jsx
[test:jest]   ● Test suite failed to run
[test:jest] 
[test:jest]     Cannot find module 'intlLoaders' from 'intlLoaders.js'
[test:jest]       
[test:jest]       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
[test:jest]       at Object.<anonymous> (node_modules/terra-i18n/lib/intlLoaders.js:3:20)
[test:jest]
```

Because v4 created intlLoaders as a postInstall step, babel-jest could resolve the loaders, even if translations were not aggregated for Jest, then running wdio tests were find because translations are aggregated in webpack.

Consumers will need to update their jest test setup to use terra-base v5 and this should clearly be documented in an upgrade doc.

Several consumers have already had this issue.

**Comment by vakeeel** [comment]
Any timeframe of when this upgrade guide would be available?

**Comment by bjankord** [comment]
PR: https://github.com/cerner/terra-core/pull/2459
