### ISSUE TITLE
[terra-list] Enhancement - theming variable for selected state text color

### ISSUE THREAD

**Issue by jeremyfuksa** [cerner/terra-core#2430]
# Issue Description
Internal themes need the ability to change the text color of a selected list item.

**Comment by dkasper-was-taken** [comment]
As terra-list allows any content to be displayed within a list item and terra's styles are locally scoped there is no way to consistently change text coloring on selection within a list item, as we have no control of styling/structure of the child component. This is the reason for our current strategy of selection styles, were no text color is expected to change. 

If the text displayed within a list needs to be updated on selection, the component placed within the list would need it's own theme-able variable styling, and the selection state of the list would need to be passed via prop to the content to match selection styling accordingly. 

The current most common layout used within list is the terra-clinical-item-view, which itself is composed of terra-clinical-item-displays. Though other teams have built own flavors of layout with a combination of primitive tags and/or terra-text.

**Comment by jeremyfuksa** [comment]
Closing issue.
