### ISSUE TITLE
Inline SVG as background image in buttons not aligning correctly

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2448]
# Issue Description
I noticed in every case an inline svg is used as the background for a button, the svg does not align vertically. Some current implementations work around this by adding margins to control the centering. Some components do not center the svg at all.

# Examples
## [terra-dialog](http://engineering.cerner.com/terra-core/#/site/components/site/dialog/index)
![image](https://user-images.githubusercontent.com/5703475/38051564-5067b21c-3294-11e8-9434-e5c597753976.png)

## [terra-toggle-button](http://engineering.cerner.com/terra-core/#/site/components/site/toggle-button/index)
![image](https://user-images.githubusercontent.com/5703475/38051614-728dbfa8-3294-11e8-90c3-cc1971bdcde0.png)

## terra-action-header (In development)
![image](https://user-images.githubusercontent.com/5703475/38051680-a1a8f5d2-3294-11e8-8bd2-471cc638584e.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Inline SVGs vertically align in terra-button.

## Current Behavior
Inline SVGs are not vertically centered without setting vertical margins.

**Comment by bjankord** [comment]
Related: https://github.com/cerner/terra-core/issues/1383

We've tried fixing this, last time the fix we had come up with had issues in IE and so we've reverted the changes.

**Comment by bjankord** [comment]
In IE, the last fix we had was adding what appears like extra space below the icon and making the icons vertically align to the top.
<img width="1152" alt="Screen Shot 2019-06-11 at 4 47 08 PM" src="https://user-images.githubusercontent.com/633148/59310057-d507f000-8c6a-11e9-9885-ad8d5b966ad7.png">

**Comment by saket2403** [comment]
<img width="716" alt="IE CSS" src="https://user-images.githubusercontent.com/42207428/60805571-1cb46580-a19e-11e9-8d6d-b0afac642fa0.PNG">
@bjankord does it look better now?

**Comment by saket2403** [comment]
Above the changes merged in #2378 I have used styles specifically for IE to align the SVG.
**Terra-Dialog**-
@ media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
      margin-top: var(--terra-dialog-header-close-icon-margin-top, 0.07rem);
    } 
**Terra- Action Header**-
@ media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) { top: var(--terra-action-header-icon-top, 0.1429rem);
}
**Terra-ToggleButton**- 
@ media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
line-height: 1.35rem;
}
