### ISSUE TITLE
Internationalize terra-date-picker and terra-time-input

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#246]
# Issue Description
Internationalize terra-date-picker and terra-time-input

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Strings, locale, and date and time format in terra-date-picker and terra-time-input need to be internationalized to support formats in other locales. This work needs to wait until we have a strategy in place on how to get the translated strings and locale from i18nProvider. 

## Current Behavior
Strings, locale, and date and time format in terra-date-picker and terra-time-input are currently hard-coded in English and using the US date/time formats.

**Comment by benbcai** [comment]
String translations are available on https://jira.cerner.com/browse/TRANS-4222

**Comment by jmsv6d** [comment]
@benbcai We shouldn't be putting links to internal stuff on public github.

**Comment by benbcai** [comment]
@jmsv6d Oh yeah, forgot about that. It's removed.

**Comment by bjankord** [comment]
This has been released in terra-date-picker@1.5.0
