### ISSUE TITLE
[terra-overlay] Page freezes on the test pages on terra-dev-site.

### ISSUE THREAD

**Issue by avinashg1994** [cerner/terra-core#2476]
# Bug Report

## Description
Page Freezes for  "Loading Overlay" Test Page on terra-dev-site and the user is unable to navigate to anywhere on the page.

## Steps to Reproduce
1. Navigate to : https://engineering.cerner.com/terra-core/#/tests/terra-overlay/overlay
2. Click on "Loading Overlays"
3. Notice that when "Animate Loading Overlay" loads, the page freezes and the user is unable to navigate anywhere on the page.

## Additional Context / Screenshots
<img width="960" alt="AnimatedLoadingOverlay" src="https://user-images.githubusercontent.com/50138162/60100100-a44dad80-9776-11e9-9fe5-17a65640720f.png">
<img width="960" alt="DarkLoadingOverlay" src="https://user-images.githubusercontent.com/50138162/60100122-aca5e880-9776-11e9-9c0a-839220367319.png">

## Expected Behavior
When "Loading Overlay" pages are loaded, the page should not freeze and the user should be able to navigate to anywhere on the page.

## Possible Solution
There are 2 possible solutions to this:

1. Wrapping the "Loading Overlay" in an "OverlayConatiner" solves the issue. 
2. Another possible solution is to provide a Timeout (say, 5 sec) to terminate the Loading Overlay.

## Environment
* Component Name and Version: Terra Overlay
* Browser Name and Version: All Browsers
* Node/npm Version: [e.g. Node 8/npm 5]

## @ Mentions
@ShettyAkarsh @ryanthemanuel

**Comment by bjankord** [comment]
Let's move forward with an overlay-container.
