### ISSUE TITLE
Create CHANGELOG for each package

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#248]
# Issue Description
We need to be able to see what changes are going into each package release. We should create a changelog for each package so this is easy to determine.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Create a changelog for each package so this is easy to determine what changes are going into each package release.

## Current Behavior
N/A

**Comment by bjankord** [comment]
I'd like to look into use lerna's publish command with conventional-commits flag:
https://github.com/lerna/lerna/#--conventional-commits

This will auto generate CHANGELOGs for us. I've started exploring how this might look here: https://github.com/bjankord/lerna-sandbox

**Comment by bjankord** [comment]
There is another project under the [lerna org called lerna-changelog](https://github.com/lerna/lerna-changelog), though [it doesn't look like it currently works with independent mode](https://github.com/lerna/lerna-changelog/issues/26) which is what we use in this repo.

**Comment by Matt-Butler** [comment]
http://stackoverflow.com/a/16343950
This might help if we need to backfill commits on the changelog ^

```
cd packages/terra-button
git log --oneline -- .     
```

**Comment by bjankord** [comment]
This project looks interesting as well for auto-generating CHANGELOG files: https://github.com/Netflix/unleash

**Comment by bjankord** [comment]
Another interesting changelog post: http://keepachangelog.com/en/0.3.0/

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/pull/533
