### ISSUE TITLE
Upgrade to react-syntax-highlighter v11

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#2486]
# Feature Request

## Description

A breaking change was made from v10.3.2 to v10.3.3 in https://github.com/conorhastings/react-syntax-highlighter.  It was fixed to be passive, but they made the change again to v11.  We should investigate upgrading to v11.

**Comment by pranav300** [comment]
@ryanthemanuel I have investigated into v11 and pushed some changes to https://github.com/cerner/terra-core/tree/update-react-syntax-highlighter. Please have a look at it. And tell me if anything else is required to be changed.
