### ISSUE TITLE
[terra-visually-hidden-text] Focusable on iOS

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2491]
# Bug Report
The visually hidden text component is focusable on iOS VoiceOver.

## Steps to Reproduce

1. Launch VoiceOver on a mobile iOS device.
2. Navigate to visually hidden text component: https://engineering.cerner.com/terra-ui/#/components/terra-visually-hidden-text/visually-hidden-text/visually-hidden-text
3. Use swipe gesture to navigate to example. Notice that VoiceOver focuses on the `p` text and reads "Focus in this section to hear screen reader only text"
5. Swipe one more time. Focus moves to visually hidden text and VoiceOver reads "This is read by a screen reader"

![IMG_4017](https://user-images.githubusercontent.com/14063284/60455607-70520c80-9bfc-11e9-8a66-a90b8d4a0dcb.PNG)
![IMG_4018](https://user-images.githubusercontent.com/14063284/60455615-73e59380-9bfc-11e9-9b26-d61763ca2681.PNG)

## Environment

* Component Name and Version: terra-visually-hidden-text-2.9.0
* Operating System and version (desktop or mobile): iOS 12.3.1

**Comment by bjankord** [comment]
This is by design. We want screen readers to be able to read this text without it actually being visible. If you want to disable the visually-hidden-text from being read by a screen reader, you can `aria-hidden="true"` to it.

**Comment by yuderekyu** [comment]
Monday 🤦‍♂
