### ISSUE TITLE
Arrange does not allow fillContent to be truncated

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-core#250]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
When the Arrange fillContent contains an element that should have truncated text the fill div will not shrink below the implied-width of the text element, this causes the layout to break by forcing the Arrange element to be too wide. This can be fixed by adding a min-width: 0 to the fill element.

<img width="549" alt="screen shot 2017-04-20 at 1 36 06 pm" src="https://cloud.githubusercontent.com/assets/4084424/25247169/b30be226-25cf-11e7-8ea3-dd32e848982d.png">

**Comment by bjankord** [comment]
Resolved with #309, released in terra-arrange@0.2.1.
