### ISSUE TITLE
Overlay disables scrolling

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#2514]
# Bug Report

## Description
We have a test page where the view is in a OverlayContainer with an Overlay and children.  Prior to version 3.18.0, after the overlay was turned off, the view would scroll.  At the 3.18.0 version, the view would no longer scroll.

## Steps to Reproduce

Different steps than described above, but is an example of a symptom.
1. Go to terra-ui.com>Components>terra-overlay
2. Inspect the DOM, noting the top-most element's styles.
3. Click a "Trigger Container Overlay" button.
4. Notice the element changes to have a style of overflow:hidden.  It will not go away.

## Additional Context / Screenshots
In the Fix #2483, changes were made to the disableContainerChildrenFocus function such that the document's style.overflow is ALWAYS set to 'hidden'.  Previously, the document's style was only set if the overlay is NOT isRelativeToContainer.
Note: The mirror image code in enableContainerChildrenFocus only changes the style in the case the overlay is NOT isRelativeToContainer.  Meaning if the Overlay isRelativeToContainer the document is permanently left with an overflow style of hidden.

## Expected Behavior
After an overlay is stopped, the scroll behavior should return to what it was before.

## Possible Solution
Move the line to set overflow = hidden up one line, such that it is again in the ELSE block. i.e. it only executes if the overlay is NOT isRelativeToContainer.

## Environment

* Component Name and Version: terra-overlay 3.18.0
* Browser Name and Version: I was testing in chrome, but I don't think it would matter.
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): desktop Mac

## @ Mentions
@bjankord

**Comment by bjankord** [comment]
This should be resolved in [terra-overlay@3.19.0](https://www.npmjs.com/package/terra-overlay)
