### ISSUE TITLE
[terra-overlay] Unable to get overlayCount of undefined or null reference in IE10

### ISSUE THREAD

**Issue by avinashg1994** [cerner/terra-core#2529]
# Bug Report

## Description

In IE10, terra-overlay throws an exception "Unable to get overlayCount of undefined or null reference" and the page/component fails to load.
Issue only in IE10 and works fine in Chrome and IE11.
Probably introduced because of the following change: https://github.com/cerner/terra-core/pull/2483/files

## Steps to Reproduce

1. Open https://engineering.cerner.com/terra-core/#/components/terra-overlay/overlay/overlay in **IE10**.
2. Open Developer tools and notice that an error is thrown and the page is blank.

## Additional Context / Screenshots

<img width="578" alt="Ie10 console error" src="https://user-images.githubusercontent.com/50138162/61371484-67c32c80-a8b2-11e9-821d-e1e13640c655.png">

## Expected Behavior

No error should be thrown in the console and terra-overlay should load as expected like in IE11 or chrome.

## Environment

* Component Name and Version: Terra-Overlay
* Browser Name and Version: IE10
* Operating System and version (desktop or mobile): Desktop

## @ Mentions
@bjankord @ShettyAkarsh

**Comment by bjankord** [comment]
Looked into this some, it looks like [`.dataset` ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) was used to pull the data attribute value which doesn't look to be supported in IE 10. Switching to use `.getAttribute` should resolve this issue.
