### ISSUE TITLE
Table.Rows Fails When Given One Child Row

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#254]
### Description of Issue
The current version of terra-table does not allow for a table with one row to be generated and results in webpage being unrended. The Table.Rows component throws the following error when it is given one Table.Row child.  

> Uncaught TypeError: children.map is not a function 

Although most people will want more than one row in a table, the component should still render when given one row.

#### Component Version
terra-table 0.2.0

### Steps to Reproduce the Issue
The following is an example of when the error is created

  `<Table.Rows>`
       ` <Table.Row key={'row'}> <Table.Cell content={row.displays} key="cell" />
        </Table.Row> `
    `</Table.Rows>`

### Expected Outcomes
- The Table.Rows component should render when given one row or many rows.

**Comment by tbiethman** [comment]
We need to use React.Children.map(props.children, ()=>{}) to safely deal with the opaque children object.
