### ISSUE TITLE
Update SearchField examples so they are more helpful

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2542]
# Feature Request

## Description
Currently, the search field code samples display this as the code:

```
import React from 'react';
// eslint-disable-next-line import/no-extraneous-dependencies, import/no-unresolved, import/extensions
import SearchFieldExampleTemplate from 'terra-search-field/lib/terra-dev-site/doc/example/SearchFieldExampleTemplate';

const SearchFieldExample = () => (
  <SearchFieldExampleTemplate />
);

export default SearchFieldExample;
```

This doesn't offer much insight to how to actually use the SearchField component. It would be better if the code examples were more concrete so people could copy/paste them and have them be functional.

**Comment by ShettyAkarsh** [comment]
closed with #2550
