### ISSUE TITLE
[terra-form-textarea] Resize API

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2543]
# Feature Request
`terra-form-textarea` examples show that resizability is turned off when using the `size` prop. For this functionality, we are actually applying a custom stylesheet to examples: https://github.com/cerner/terra-core/blob/master/packages/terra-form-textarea/src/terra-dev-site/doc/example/FormTextareaDocCommon.module.scss

`terra-form-textarea` will always have resizability set to true, unless it is `disabled` or `size = full`. 

If we want this behavior, we should make this explicit for examples by converting this stylesheet into an inline style again. 

If we do not want this behavior, we should update the API to set `resize: none` when using the `size` or `row` props.

**Comment by saket2403** [comment]
>If we do not want this behavior, we should update the API to set resize: none when using the size or row props.

Should the user be disallowed to resize the text area when he is specifying the size or rows of the text area. Is this the behaviour that we want to provide?
cc @neilpfeiffer  @PaulSolDev .

**Comment by ShettyAkarsh** [comment]
@saket2403  By referring the examples i would say we should update the textarea source code to set resize:none whenever size prop is used and not allow the resize to happen.  in that case we can avoid the css property which we are expecting the consumer to pass when size value is other than 'full' or the textarea is disabled. 

so @neilpfeiffer  was there  any particular reason to update all our examples using the size prop to have this custom css implemented ?

**Comment by saket2403** [comment]
Can we have a new default size value as `default` instead of `small`, having same number of rows as small , so as to differentiate between the default and user-defined values of the  `size` prop. This can allow us to disable resizing for all size values except `default`. @neilpfeiffer
