### ISSUE TITLE
[terra-search-field] Select To Component List Slingshot

### ISSUE THREAD

**Issue by mstracy13** [cerner/terra-core#2553]
# Bug Report

## Description
The select to Component in Healthelife, when opening with multiple recipients, has an issue where if the list of recipients exceeds the dropdown menu, and the user has to scroll on the page, continually slingshots the menu back to the top of the list over and over again. This is especially obvious in smaller mobile devices, and can be reproduced in both iOS and Android devices. 

## Steps to Reproduce
1. Reach out to @mstracy13 for login details
2. Ensure that reply all is turned on for that organization
3. type in "as" into the select to component, see the dropdown menu appear, and try scrolling on that page. It will continually shift the focus on the page to the top

## Expected Behavior
User should be able to scroll with Select To without it shifting 

## Environment
* Component Version: 
* Browser Name and Version: Any browser
* Node/npm Version [e.g. Node 8/npm 5]:
* Webpack Version:
* Operating System and version (desktop or mobile): 

## Additional Context / Screenshots
Can't show it in screenshots, but I have video evidence of it if you want me to send it to you directly.

**Comment by lokesh-0813** [comment]
@mstracy13 Can you confirm if the values passed to `select option` in your `form-select` component are all unique? or if you could point us to your code we can take a look and see what's going on. Thank you.

**Comment by mstracy13** [comment]
I'm not the one who coded this. I'm simply logging a defect I was seeing. 

Reach out to Reena Sharma from our team, or maybe Cody Price, since I think he was the one from the Terra team that had designed the Select To Component.

**Comment by lokesh-0813** [comment]
> I'm not the one who coded this. I'm simply logging a defect I was seeing.
> 
> Reach out to Reena Sharma from our team, or maybe Cody Price, since I think he was the one from the Terra team that had designed the Select To Component.

Have reached out to Reena Sharma, awaiting response.

**Comment by lokesh-0813** [comment]
Concluding that consumer implementation is incorrect and hence closing this issue.
