### ISSUE TITLE
Is there a good way to disable auto complete functionality?

### ISSUE THREAD

**Issue by bbaraban** [cerner/terra-core#2566]
# Feature Request

## Description
I wanted to start a discussion around what is the reccomended way to prevent auto-complete functionality from occuring. In our clinical application we want to make sure previous data is not cached via the browser and able to be seen or reentered later.

I've investiaged some ways but they are not all-in-one solution.

React has a property autoComplete that can be used but the required value ("off" or "disabled") varies from browser to browser. We also have to acess to the input control to be able pass to this attribtue. Some terra components it's possible others it's not.

Another option, which I think is possible but have not tried is setting the autocomplete attribute to off via CSS.

**Comment by bjankord** [comment]
@bbaraban Do you have a list of which components you need access to the input element that don't currently provide access?
