### ISSUE TITLE
Remove devDependencies from dependencies in all Terra packages

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-core#2568]
# Bug Report

## Description
I was upgrading some projects that use `terra-base` and I noticed that `terra-i18n` includes [`terra-doc-template` as a dependency](https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/package.json#L32). It should under the package's `devDependencies` because it is part of the dev docs.

This isn't the first time I've run across this so I'm wondering if we can do a sweep thru all the packages across the terra repos and ensure we only have dependencies categorized correctly.

**Comment by StephenEsser** [comment]
@nickpith 

I think this is an important discussion. To add a little more information on the topic the doc template is a dependency of every terra package. The examples are shipped and released with the component. This requires anything included in the doc-site examples to be a hard dependency.

**Comment by nickpith** [comment]
Are there any alternatives that have been discussed that would remove that as a dependency?

**Comment by mjhenkes** [comment]
Technically since we export our docs for aggregation in terra-ui, terra-doc-template is a dependency of the package.

**Comment by bjankord** [comment]
To me, it's a question of if we want to treat docs like a first class export and support people being able to import the example files without dependency errors. We use the docs in the terra-ui site but in my mind, we're really the only people who I think should be using the doc files that we export. 

I wouldn't expect a terra consumer to import one of our doc examples and try and use it. Based on that, I'd be fine with removing the dependency on terra-doc-template from packages or moving it to a devDependency and then ensuring that terra-doc-template is a dependency in the terra-ui doc site and our theme repos to resolve the package when its referenced in the example docs in the terra-ui and theme repo projects.

**Comment by bjankord** [comment]
Talked about leaving this as-is for now and looking into seeing if we can get lerna to ignore changes to the terra-doc-template package triggering releases in other terra-core packages.
