### ISSUE TITLE
Control should go to rows even it is read only mode 

### ISSUE THREAD

**Issue by sudheervilluri** [cerner/terra-core#2569]
# Bug Report

## Description
On Readonly table, the control should go to all rows as per accessibility testing for the user to view the reconds when the scroll is enabled  

## Steps to Reproduce
Make a table to read-only then on tab navigation selection will skip the table 

## Expected Behavior
control should go to all rows in accessibility testing  

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by bjankord** [comment]
Can we get a code sample of the table you are trying to test with?

**Comment by sudheervilluri** [comment]
Please find below git hub url https://github.cerner.com/hi-malvern/dwt-app/blob/master/src/configuration/QueueDialogBoxContent.js

**Comment by sudheervilluri** [comment]
team any update we can navigate table using up and down arrows?

**Comment by dkasper-was-taken** [comment]
@sudheervilluri This seems to be more of an issue related to the scroll content in general, and not to do with the terra-table. In this case I believe the issue would be the underlying terra-scroll component within your terra-content-container.
https://github.com/cerner/terra-core/issues/2787

The terra-table v4 introduces it's own scrollable container, which may get your around the problem you are seeing in the mean time if you use it's fixed header styling.

With all containers, unless it or an element inside it gaines focus, keyboard commands will not work. This is often negated by always using body scrolling, however in the case of nested fill style components this is not so easily achieved.

Feel free let me know if we can close this issue in favor of the other broad issue to address scrolling across the application.
