### ISSUE TITLE
SearchField handleTextChange doesn't respect minimumSearchTextLength prop

### ISSUE THREAD

**Issue by sharynneazhar** [cerner/terra-core#2597]
# Bug Report

## Description
The SearchField `handleTextChange` method doesn't check for the `minimumSearchTextLength` prop being passed in. 

The [examples](https://engineering.cerner.com/terra-ui/components/terra-search-field/search-field/search-field) on the documentation does the check manually. Is this behavior intentional? Why not leverage the prop?

## Steps to Reproduce

1. Use the `minimumSearchTextLength` on any search field component with autosearch set to false

## Expected Behavior

https://github.com/cerner/terra-core/blob/55c9cd05dc7e6aa8b9f7902c89086fa478a93850/packages/terra-search-field/src/SearchField.jsx#L151-L162

## Possible Solution

We can add a check for the prop like how `handleSearch` has

https://github.com/cerner/terra-core/blob/55c9cd05dc7e6aa8b9f7902c89086fa478a93850/packages/terra-search-field/src/SearchField.jsx#L184-L185

**Comment by StephenEsser** [comment]
Hi @sharynneazhar, can you provide a code snippet we can test against? Are you using `onChange` or `onSearch`?

The SearchField's `minimumSearchTextLength` is intended to be used in conjunction with the `onSearch` property to create an uncontrolled component. The manual check in the examples is used to update the search message. `onSearch` is not invoked if the text falls below the minimum search length, `onInvalidSearch` is.

The `onChange` prop is intended to be used to create a controlled component and is expected to be called regardless of the `minimumSearchTextLength`.

**Comment by sharynneazhar** [comment]
@StephenEsser I see. We are using the `onChange` prop as a way to autosearch as the user types. Here's an example of what we have:

```
<SearchField
  minimumSearchTextLength={2}
  onChange={onSearchChange}
  query={query}
  searchDelay={500}
/>
```
where `onSearchChange` is simply:
```
onSearchChange = (event, query) => {
  this.setState({ query }, this.fetchAssets);
}
```

**Comment by sharynneazhar** [comment]
We can add the `onSearch` prop to the component to fix this. Wasn't sure if it was intended to be that way. 

Thanks for the help, though!

**Comment by ShettyAkarsh** [comment]
@sharynneazhar are we good to close this ?

**Comment by sharynneazhar** [comment]
@ShettyAkarsh Yeah, we can close this.
