### ISSUE TITLE
[terra-form-field] clicking on help and error text shows focus glow

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#2600]
# Bug Report

## Description
Adding [this accessibility](https://github.com/cerner/terra-core/commit/553a8db6ba8641cf37211698fdfaf747904071cf#diff-329b2171cca50d6f3e9df40c1bb35d87R189-R190) update possibly also introduced a ui defect where user is able to click on help-text and error-text which then shows the browser native focus glow. (Not an issue in form-fieldset, outline was already set to 0)

## Steps to Reproduce
1. Go to [.../terra-ui/components/terra-form-input/form-input/input-field](https://engineering.cerner.com/terra-ui/components/terra-form-input/form-input/input-field)
2. With mouse, click on the help-text below the form input.
3. Default browser focus glow appears.

## Additional Context / Screenshots
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1355485/63308379-011d9e00-c2b8-11e9-9fd5-98927c37322e.png)

## Expected Behavior
Focus glow does not appear for anything that is not tab/keyboard navigable (set outline:0 on `.help-text` and `.error-text`, similar to [/Fieldset.module.scss#L50](https://github.com/cerner/terra-core/blob/55c9cd05dc7e6aa8b9f7902c89086fa478a93850/packages/terra-form-fieldset/src/Fieldset.module.scss#L50))

**Comment by bjankord** [comment]
For note: the negative tab index helps JAWS read the help and error text in IE. I'll go ahead and add the outline 0 on this.
