### ISSUE TITLE
terra-core heroku master branch deployment failures

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2604]
# Issue Description
Whenever a branch is merged into master, a deployment on heroku is triggered. This has recently started to fail consistently whenever we merge a branch in to master.

Interestingly, all of our PR deployments through heroku do not fail, it is only the ones generated from merge to master that fail.

As far as I can tell, it may be related to how we are specifying [node versions](https://github.com/cerner/terra-core/blob/master/package.json#L6-L8) the project intends to use and how heroku determines what node version to use, heroku is installing node 11.15.0

This is output from the heroku build:
```
Installing binaries
engines.node (package.json):  >=8.9.2 <12
engines.npm (package.json):   unspecified (use default)
       
Resolving node version >=8.9.2 <12...
Downloading and installing node 11.15.0...
Using default npm version: 6.7.0
```
I believe there are issues with node 11, and thats the version heroku is resolving to use for this deployment.

There is also an error around multiple versions of disclosure-manager:
```

       ERROR in terra-disclosure-manager
npm ERR! terra-core@0.1.0 compile:prod: `webpack --config webpack.config.js -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR!         Multiple versions of terra-disclosure-manager found:
 Failed at the terra-core@0.1.0 compile:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
           4.17.0 ./~/terra-application/~/terra-disclosure-manager
           4.9.0 ./~/terra-disclosure-manager
       
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.AZddu/_logs/2019-08-21T14_42_40_473Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! terra-core@0.1.0 heroku-postbuild: `npm install --only=dev && npm run compile:prod`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the terra-core@0.1.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.AZddu/_logs/2019-08-21T14_42_40_489Z-debug.log
```

## Additional Context / Screenshots
This doesn't really impact much that we do, though I wanted to document it in-case anyone was interested/had time to investigate.

**Comment by bjankord** [comment]
Talked about updating engine to node >=8.9.2 <11

**Comment by emilyrohrbough** [comment]
Master branch is deployed with Travis so this can be closed.
