### ISSUE TITLE
Color classes Not Working when in the Context of Portal

### ISSUE THREAD

**Issue by jf046606** [cerner/terra-core#2605]
# Bug Report

## Description
Color scss classes are not being applied correctly to different components in our wellness applications, we first noticed this issue when we were updating our application(health trackers) to use the newer version of terra-text(version 4 and onwards).  The colors were being applied correctly locally but inside a portal the colors were not being applied correctly. We developed a workaround solution by applying the !important tag on all our color classes. 

## Additional Context / Screenshots
We believe its related to terra causing a dependency on the ordering of stylesheets In the first image is the css on a terra-text component
<img width="337" alt="Screen Shot 2019-08-21 at 1 00 25 PM" src="https://user-images.githubusercontent.com/54375404/63462192-58db1700-c428-11e9-81d4-05d0ce407d19.png">
The component is getting it's color from the inherit while in the second one I manually disable the Text.Module and the correct color gets applied 
<img width="326" alt="Screen Shot 2019-08-21 at 1 00 37 PM" src="https://user-images.githubusercontent.com/54375404/63462217-6abcba00-c428-11e9-95a4-c3017cc5e929.png">

## Environment
This can been seen in our wellness environments here http://cckc-mo.wellness.us.healtheintent.com/pages/home on most apps such as health trackers, To-do List, and screening results.  Please PM me on teams, Joseph Fortebuono, for login info..

**Comment by jf046606** [comment]
Note: this is impacting more than just terra-text if it wasn't, this is impacting any terra component that has a color set to inherit for example its not working when I try to set the color of a terra-card as well.

**Comment by mhemesath** [comment]
I'm wondering if color inherit should be used as a color class thats applied if no color class is passed in. Passing in a color class would then replace that the terra provided class applying `color:inherit`. This approach should be passive to current consumers while resolving this bug. 

The problem the current implementation creates is that it creates a dependency on the ordering of stylesheets to determine if the color class, or the terra provided class setting `color:inherit` is used.

**Comment by bjankord** [comment]
@jf046606 @mhemesath I've sent out a PR to address this, take a look and let me know if you have any thoughts on it. https://github.com/cerner/terra-core/pull/2607
