### ISSUE TITLE
[terra-status-view] Investigate CSS grid being flaky with IE

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2618]
# Feature Request
There are instances where CSS grid is not being applied to IE. Specifically, IE 11 on the selenium 3.14 grid. The result is a status view that is always aligned top.

Something is off with either our CSS styles, autoprefixer, and/or IE 11. Using this to cross check our styles is a good start: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by bjankord** [comment]
One option may be providing the -ms grid prefixes by default and see if that resolves the issue.

**Comment by yuderekyu** [comment]
There are also reported issues on Firefox. For reference, selenium 3.14 uses IE 11.0 and Firefox 62.0.3 drivers.

**Comment by bjankord** [comment]
I think it would be good to look at the generated CSS output from teams having issues and check to see that it matches what we expect.

**Comment by RHolland13** [comment]
I'm wondering if it might be easier to switch from using grids to flexbox instead of trying to make grids work in IE, since IE has better support for flexbox and this layout is one-dimensional, so it doesn't really _need_ grids.
Keeping the existing DOM structure and updating the CSS to incorporate the following seems to fix the issue for me.
```scss
.outer-view {
  display: flex;
  flex-direction: column;

  > .top-space {
    flex: 1 0 0;
  }

  > .inner-view {
    overflow: unset;
  }

  > .bottom-space {
    flex: 2 0 0;
  }
}
```

**Comment by yuderekyu** [comment]
@RHolland13  What is the rationale for `overflow: unset`?

I am cool with switching to flex for better browser support. PRs are welcome

**Comment by emilyrohrbough** [comment]
I stumbled across this article on [autoprefixer and css-grid styles](https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie) and feel it could be related to this issue. The article states:
> Autoprefixer can be used to translate modern CSS Grid syntax into IE 10 and IE 11 syntax, but this polyfill will not work in 100% of cases. This is why it is disabled by default.

**Comment by yuderekyu** [comment]
Yeah. Our grid styles do align with the IE guide linked below that article though: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by yuderekyu** [comment]
Addressed by https://github.com/cerner/terra-core/pull/2749
