### ISSUE TITLE
[terra-form-select] Placeholder remains after selections

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#2624]
# Bug Report
MultiSelect does not remove the placeholder after a selection has been made.

## Description
In the 2.25.0 of terra-form-select, MultiSelect, after selecting options and closing the select box, the placeholder would be removed.
In 2.26.0, this same workflow would result in the placeholder remaining.

## Steps to Reproduce
1.  View the terra-ui pages for Form Select.
2. Select items in the select for "Multiple".
3. Set focus elsewhere, so the select box closes.
4. Note the placeholder remains.

It did not used to do this in older versions of the control.  

## Additional Context / Screenshots
Old example:
![select 2_25](https://user-images.githubusercontent.com/30238809/64267585-45d24780-cefc-11e9-9478-d8e2d3603da2.png)

New example:
![select after 2_25](https://user-images.githubusercontent.com/30238809/64267592-48cd3800-cefc-11e9-8a1a-e58293141380.png)

## Expected Behavior
Placeholder should be removed after the options are selected and the select is "closed".

## Environment

* Component Name and Version: terra-form-select > 2.26.0
* Browser Name and Version: Safari 12
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@StephenEsser

**Comment by hboege** [comment]
Interestingly, the wdio screenprints for the multiple select have the placeholder displayed even after the control was closed in 2018.  Example [here](https://github.com/cerner/terra-core/blob/cd1180392fca1c349f3529fa852fb77a60613893/packages/terra-form-select/tests/wdio/__snapshots__/reference/en/chrome_tiny/select-spec/multiple_should_select_an_option_by_click%5Bselected-option%5D.png)

**Comment by StephenEsser** [comment]
The placeholder remains visible while the Select has focus, not whether the dropdown is open or closed

**Comment by StephenEsser** [comment]
cc: @dev-cprice

**Comment by dev-cprice** [comment]
Figured it out. Looks like I made a typo when refactoring 😬 

In the MultiSelect's [Frame](https://github.com/cerner/terra-core/blob/c8f0c72a03ab90800e6fd610e5a8e2de5e5a3d5c/packages/terra-form-select/src/multiple/Frame.jsx#L172-L175), `value` is being destructured from `this.state`, when it should be from `this.props`.

Solution:
```diff
- const { searchValue, isFocused, value } = this.state;
+ const { searchValue, isFocused } = this.state;
const {
+  disabled, display, placeholder, required, value
} = this.props;
```

**Comment by dev-cprice** [comment]
I'll get a PR out real quick to fix this
