### ISSUE TITLE
[terra-dropdown-button] - Primary action is not interactable while menu is open

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#2630]
# Bug Report

## Description

The primary action of the SplitButton is non-interactable while the menu is open.

## Steps to Reproduce

1. Click on the Split Button.
2. While the Menu is open click the primary action on the Button itself.
3. Observe the primary action is not invoked and the menu remains open

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/6720991/64455047-3268dd00-d0b2-11e9-828a-4be872c8171c.png)

Screenshot Description: 
_Clicking Reply does not invoke the primary callback and the menu remains open_

.
## Expected Behavior

Clicking the primary action while the dropdown menu is open **should** invoke the primary action callback **and close** the dropdown menu.

**Comment by nramamurth** [comment]
This is a dup of #2572.

**Comment by StephenEsser** [comment]
@nramamurth The descriptions of these two issues are slightly different. This issue specifically targets the primary action not being fired when the button is clicked.

Will the solution proposed in #2572 resolve the primary action not being invoked or will it only resolve closing the Menu when the primary action is clicked?

**Comment by nramamurth** [comment]
@StephenEsser 

As far as I know, @lokesh-0813 is working on resolving both the issues - the primary action not being invoked as well as closing the menu.

**Comment by lokesh-0813** [comment]
Had a talk about this earlier with @neilpfeiffer during weekly webEx call. Recommended behaviour was upon clicking primary button, the menu should be closed and the primary button action not be fired.

**Comment by neilpfeiffer** [comment]
Correcting previous comment @lokesh-0813:

- UX does want the primary action to be invoked/fired when pressed, even if the menu is open, and then closes the menu after pressing. 
- Focus would then be returned to the primary button (instead of the caret button as it does currently after programmatically closing the menu. 
- All other buttons and UI surrounding the split button would be covered by an overlay, does not honor clicking when the menu is open, and closes the menu if attempting to click anything around the primary button, caret button, or menu.

**Comment by lokesh-0813** [comment]
> Correcting previous comment from @lokesh-0813 and confusing wording listed above, whether the primary button _SHOULD_ or _SHOULD NOT_ be able to be pressed and be fired:
> 
> * UX **_DOES_** want the primary action **to be invoked/fired** when pressed, even if the menu is open, and then closes the menu after pressing.
> * Focus would then be returned to the primary button (instead of the caret button as it does currently after programmatically closing the menu).
> * All other buttons and UI surrounding the split button would be covered by the clear-overlay, they do not honor any clicking when the menu is open (captured by the overlay), and then closes the menu if user clicks anything around the primary button, caret button, and menu. (which means the overlay needs to be below everything else inside the split-button component, including the primary button)
> 
> 
> Hopefully this clears up the miscommunication?

 I will have the overlay implementation cover the split button. This approach should solve more than one issue. Thank you.
