### ISSUE TITLE
[terra-dropdown-button] - Mouse / Keyboard Accessibility Interactions

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#2632]
# Bug Report

## Description

UX has requested that mouse and keyboard interactions behave slightly different. Currently using a mouse to click the toggle of the SplitButton/DropdownButton will open the menu and focus/highlight the first option in the menu. 

The request is that when the menu is opened via a mouse click the first option is not focused/highlighted by default.

However, when navigating to the  SplitButton/DropdownButton via the keyboard, opening the menu with the keyboard should focus/highlight the first option in the menu.

## Steps to Reproduce

1. Navigate to the [example site](https://engineering.cerner.com/terra-core/components/terra-dropdown-button/dropdown-button/dropdown-button).
2. Click on any of the examples.
3. Observe the first menu action item is auto-focused/highlighted.

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/6720991/64456455-dc963400-d0b5-11e9-9c1c-a134695bd0b4.png)

## Expected Behavior

Clicking a DropdownButton/SplitButton should open the menu but not auto-highlight the first option.

Opening the DropdownButton/SplitButton using the keyboard should auto-highlight the first option.

**Comment by StephenEsser** [comment]
Here is an example that was referenced by UX that demonstrates the expected interactions / focus states between mouse and keyboard: https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html

**Comment by saket2403** [comment]
I have made the [changes](https://github.com/cerner/terra-core/commit/bb5cd9909189f3ffb41aa6d2722481ffa4e16a72#diff-3dfb76169e31d2dcf21b669e359679fb) for keyboard and mouse interactions but on Voice Over the focus does not goes inside the list as of now, overlay can fix this issue but we cannot have an overlay as it breaks the split button functionality.
cc @StephenEsser

**Comment by StephenEsser** [comment]
@saket2403 

Can you explain a little more what the overlay would be providing? With the hookshot implementation the focus should be controllable. The focus trap we are manually adding the the dropdown may need to flex depending on the workflow.

Using the w3 example above, is voiceover working correctly?

**Comment by saket2403** [comment]
The  VO focus moves outside the drop-down menu on the whole page that is it moves to the texts behind the menu. Having an overlay can prevent this. But it will also prevent us from clicking the primary button in the split button which is what we do not want .
cc @StephenEsser  @dkasper-was-taken

**Comment by StephenEsser** [comment]
Were you able to test the W3 example above using VoiceOver?

The terra-dropdown-button implementation is very similar to the terra-form-select. It may be worth spiking on the implementing a similar implementation to how the select resolved a similar issue. 

The Select exposes an isTouchAccessible prop that flexes the semantic implementation of the component. When isTouchAccessible is true the component is rendered inline and does not use hookshot. This keeps the dom ordering semantically in-order and is easier for screen readers to navigate. 

The caveats are that the component dropdown menu has side-effects of the layout of the ancestor components and can cause an overflow or be clipped in certain situations. 

Here is the PR that introduced the isTouchAccessible prop:

https://github.com/cerner/terra-core/pull/2658

**Comment by saket2403** [comment]
> Were you able to test the W3 example above using VoiceOver?
Yes the w3 example worked fine

**Comment by ShettyAkarsh** [comment]
@StephenEsser , as the original requirement from UX for this issue will be fixed without removing hookshot. what i was thinking we could have separate issue logged for with/without hookshot implementation for accessibility using screen reader. which would need a larger discussion.  
where we could also include the page jump issue what we found in this component when rendered inside iframe while fixing the issue #2682.  your thoughts ?

cc. @ryanthemanuel

**Comment by ryanthemanuel** [comment]
@ShettyAkarsh +1.  If we can fix this issue and then postpone and track the larger discussion, I'm all for it.
