### ISSUE TITLE
[terra-dropdown-button] - Inconsistent margin between browsers 

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#2633]
# Bug Report

## Description

The DropdownButton's margins are different between browsers.

## Steps to Reproduce

1. Open the DropdownButton [engineering page](https://engineering.cerner.com/terra-core/components/terra-dropdown-button/dropdown-button/dropdown-button) in Chrome.
2. Inspect the `<button>` tag of the first example.
3. Observe there is no margin applied.
4. Repeat steps 1-2 in Safari.
5. Observe there is a 2px default margin applied to the DropdownButton's `<button />`

## Expected Behavior

The margins should be consistent between browsers.

## Possible Solution

Override the default margin size of .button.

**Comment by nramamurth** [comment]
Fix should be similar to what was done for terra-button in https://github.com/cerner/terra-core/pull/2316.
