### ISSUE TITLE
[terra-form-select] - MultiSelect: Deselecting an option from a unfocused Select does not trigger the function passed into the "onDeselect" option

### ISSUE THREAD

**Issue by TD060293** [cerner/terra-core#2634]
# Bug Report

## Description

With the select out of focus. If you click on this "X" to deselect the option(which in-turn should be giving the select focus) the option is deselected and the select component is given focus but the update to the filter state never occurs 

## Steps to Reproduce

1. Multiselect is unfocused. (component should have option "onDeselect" with function)
2. Click "X" on select option

## Additional Context / Screenshots

![errorone](https://user-images.githubusercontent.com/55100252/64546898-2454cf80-d2f1-11e9-9fc0-eb5d60bf465b.PNG)

![errortwo](https://user-images.githubusercontent.com/55100252/64546886-1b63fe00-d2f1-11e9-8d72-2b4d9db838ac.PNG)
## Expected Behavior

When Deselecting select option from an unfocused state, "onDeselect" option triggers intended function

## Environment

* Component Name and Version: form-select 5.27.0
* Browser Name and Version: Chrome 76.0.3809
* Node/npm Version: Node 10.16.0/npm 6.9.0
* Operating System and version (desktop or mobile): windows 10 enterprise version:1809

## @ Mentions

@StephenEsser 

Link to Teams post:https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1568041553496?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1568041553496&teamName=Terra&channelName=Component%20Support&createdTime=1568041553496

**Comment by nramamurth** [comment]
@TD060293 

What do you mean by "... the filter state never occurs"? Are you saying that the `onDeselect` callback is not getting hit when you deselect an option with Select out of focus? I tested the following code and it looks the the `onDeselect` callback gets executed as expected. Let me know if I have misunderstood the problem.

```
import React, { useState } from 'react';
import Select from 'terra-form-select';

function ControlledMultiple() {
  const [value, setValue] = useState([]);

  return (
    <Select
      id="multiple"
      onChange={(option) => setValue(option)}
      placeholder="Select a color"
      value={value}
      variant="multiple"
      // eslint-disable-next-line no-console
      onDeselect={(option) => console.log(`You deselected ${option}`)}
    >
      <Select.Option value="blue" display="Blue" />
      <Select.Option value="green" display="Green" />
      <Select.Option value="purple" display="Purple" />
    </Select>
  );
}

export default ControlledMultiple;
```
---
![sample](https://user-images.githubusercontent.com/10090859/64595328-576d9080-d3cf-11e9-9427-24953cb144f6.gif)

cc / @StephenEsser

**Comment by TD060293** [comment]
This looks like it is working as intended. After doing some debuging I see what the issue is in my case.  


```
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { injectIntl, intlShape } from 'react-intl';
import MultiSelect from 'terra-form-select';
import { getComponentId, getComponentKey } from '../../utils/element_helper';
import { getActivitiesTypeFilters } from '../../utils/activities_filter_helper';

const propTypes = {
  activityTypeFilter: PropTypes.array,
  handleFilterUpdate: PropTypes.func,
  intl: intlShape.isRequired,
};

const ActivityTypeFilterComponent = (props) => {
  const { activityTypeFilter, intl, handleFilterUpdate } = props;
  const curentFilter = getActivitiesTypeFilters(activityTypeFilter, intl);
  const [selectedFilters, setFilters] = useState(activityTypeFilter);

  return (
    <MultiSelect 
		id={getComponentId('TypeFilter')} 
		variant="multiple" 
		defaultValue={curentFilter} 
		onChange={(option) => setFilters(option)} 
		value={selectedFilters} 
		onSelect={() => handleFilterUpdate(selectedFilters)} 
		onDeselect={() => handleFilterUpdate(selectedFilters)} 
	>
      <MultiSelect.Option value="MEDICATION" />
      <MultiSelect.Option value="PATIENTCARE" />
      <MultiSelect.Option value="ASSESSMENT" />
      <MultiSelect.Option value="OTHER" />
      <MultiSelect.Option value="COLLECTION" />
    </MultiSelect>
  );
};

ActivityTypeFilterComponent.propTypes = propTypes;

export default injectIntl(ActivityTypeFilterComponent);
```
The handleFilterUpdate Function is handled by the parent and looks like this:

```
  handleFilterUpdate(typeFilterChange) {
    this.setState({
      activityTypeFilter: typeFilterChange,
    });
  }
```
It seems like its working properly but the issue is that handleFilterUpdate is being hit before "onChange" is occurring. Making the "SelectedFilters" variable to be outdated when sent to the "handleFilterUpdate" function. 

This is giving it the illusion that the function is not being triggered the first time when in reality it is but the filters stayed the same giving no visual change.

**Comment by nramamurth** [comment]
@TD060293 

As far as I am aware, 'change' is handled prior to 'deselect' - we [invoke your `onChange` callback](https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/MultiSelect.jsx#L168) prior to [your `onDeselect` callback](https://github.com/cerner/terra-core/blob/8ae7d3e7ea77be7fa309a7376aa9ab142f469456/packages/terra-form-select/src/MultiSelect.jsx#L170-L172) which seems to be your desired order as well. 

--- 
I added a simple `onChange` callback to my example above to illustrate this behavior - 

![sample-1](https://user-images.githubusercontent.com/10090859/64670998-a7f2f580-d484-11e9-8dda-65ff4e582d5c.gif)

This looks like a minor implementation issue (I could be wrong) with regards to how/when your parent component's state changes, etc. I'll be happy to look into it further if you could send across your project branch to me (Naveen Kumar Ramamurthy) over Teams. 

@StephenEsser, 

Do you have any thoughts on this one?

**Comment by StephenEsser** [comment]
I agree that this appears to be an implementation issue. The onChange callback always fires before the onDeselect callback. This was tested with the following code running the latest version of Select. You might double check which version your project is using.

```jsx
import React, { useState } from 'react';
import MultiSelect from 'terra-form-select';

const ControlledExample = () => {
  const [value, setValue] = useState(['blue']);

  const onChange = (newValue) => {
    console.log('On Change');
    setValue(newValue);
  };

  const onDeselect = () => {
    console.log('On Deselect');
  };

  return (
    <MultiSelect variant="multiple" value={value} onChange={onChange} onDeselect={onDeselect}>
      <MultiSelect.Option value="blue" display="Blue" />
      <MultiSelect.Option value="green" display="Green" />
      <MultiSelect.Option value="purple" display="Purple" />
      <MultiSelect.Option value="red" display="Red" />
      <MultiSelect.Option value="violet" display="Violet" />
    </MultiSelect>
  );
};

export default ControlledExample;
```

I would look into the function you are using for onSelect and onDeselect. These callbacks only return the single value that changed, and this function is taking the exact same input for two opposite actions.

```
onSelect={() => handleFilterUpdate(selectedFilters)} 
onDeselect={() => handleFilterUpdate(selectedFilters)} 
```

Additionally setState is asynchronous by default, so you may also be seeing issues calling setState twice so closely together. Although I think this is unlikely to the the issue, but it is possible.

**Comment by StephenEsser** [comment]
Closing this issue as a result of the discussion above. This does not appear to be an issue of the component. Please feel free to reopen this issue if further investigation discovers otherwise.
