### ISSUE TITLE
[terra-form-select] Mobile keyboard issue

### ISSUE THREAD

**Issue by johnaudas** [cerner/terra-core#2643]
# Issue Description
Currently the Keyboard can cover components when it opens. This is a problem especially for the terra-form-select. I am seeking the correct way to work around this issue.

## Additional Context / Screenshots
<img width="407" alt="Screen Shot 2019-08-26 at 3 44 48 PM" src="https://user-images.githubusercontent.com/5125862/64819243-6f7e1500-d573-11e9-8186-f7acb1f9bc68.png">
<img width="404" alt="Screen Shot 2019-08-26 at 3 45 02 PM" src="https://user-images.githubusercontent.com/5125862/64819253-73aa3280-d573-11e9-8ce6-7e92d8d5cfa7.png">

Potential solution is to force the selection to scroll to the top by inserting additional white space at the bottom of the screen.  See video:
[phlebotomy_select.mov.zip](https://github.com/cerner/terra-core/files/3607370/phlebotomy_select.mov.zip)

**Comment by dev-cprice** [comment]
This seems like an application concern, not the select's: it basically boils down to your page not scrolling. The virtual keyboard overlaying the screen is expected behavior and the application needs to account for that.

**Comment by johnaudas** [comment]
We are considering fixing it by forcing whitespace into the screen and the scrolling the select to the top.
Please see the attached zip to see a video.
