### ISSUE TITLE
StatusView not updating when the variant changes

### ISSUE THREAD

**Issue by Dinesh94Singh** [cerner/terra-core#2647]
# Bug Report

## Description

**StatusView doesn't update when the variant changes.**

Reference - https://github.cerner.com/curo/nurse-medication-preparation-js/blob/NMP-424_Prepare_Details_Cancel_Button/src/nurse-medication-preparation/components/PanelContent/PanelDetailView.jsx#L182
Teams - https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1568650403050?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1568650403050&teamName=Terra&channelName=Component%20Support&createdTime=1568650403050

## Steps to Reproduce

1.  Create a component which renders two types of StatusView's.
2. When prop changes - the StatusView's prop also changes

## Additional Context / Screenshots

![StatusView_Not_Updating](https://user-images.githubusercontent.com/8749423/64979287-07824400-d87d-11e9-93c2-98d899d26af7.gif)

## Expected Behavior

expected the StatusView to be updated with new glyph.
## Possible Solution

Adding a Key have solved the issue, but since StatusView is a functional component - why was this needed?

## Environment

* Component Name and Version: StatusView - v3.16.0
* Browser Name and Version: Chrome, Firefox
* Node/npm Version: [e.g. Node 8/npm 5] Node v8.16.0
* Webpack Version: ^v4.3
* Operating System and version (desktop or mobile): Windows

## @ Mentions

@tbiethman

**Comment by yuderekyu** [comment]
That is an outdated version. Upgrade to version 4 and see if that resolves the issue.

**Comment by nramamurth** [comment]
@Dinesh94Singh Have you tested with v4 to see if this has been resolved?

**Comment by nramamurth** [comment]
@Dinesh94Singh 

Does the below example suit your scenario? I haven't had an issue using `terra-status-view@v3.16.0`. 

```
import React, { useState } from 'react';
// eslint-disable-next-line import/no-extraneous-dependencies, import/no-unresolved, import/extensions
import StatusView from 'terra-status-view/lib/StatusView';

const ToggleVariants = () => {
  const [variant, setVariant] = useState('error');

  const handleOnSelect = (event) => {
    setVariant(event.target.value);
  };

  return (
    <div>
      <StatusView variant={variant} />
      <fieldset>
        <legend>Change Variant</legend>
        <select id="statusViewVariant" name="statusViewVariant" value={variant} onChange={handleOnSelect}>
          <option value="error">Error</option>
          <option value="no-data">No Data</option>
        </select>
      </fieldset>
    </div>
  );
};

export default ToggleVariants;
```

--- 

![sample-1](https://user-images.githubusercontent.com/10090859/65306865-141bda80-dba4-11e9-98a6-0df7f654266e.gif)

If you could give us a reduced test sample, then it would be great for us to troubleshoot and I'd again recommend updating to v4 and checking if your issue is resolved.

**Comment by Dinesh94Singh** [comment]
@nramamurth - Hope this helps - 

```
class CustomView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      variant: 'error',
    };
  }

  getSnapshotBeforeUpdate(prevProps, prevState) {
    console.log(this.props);
    if (prevProps.variant != this.props.variant) {
      return 0;
    } else {
      return null;
    }
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
    console.log('snapshot is', snapshot);
    if (snapshot != null) {
      this.setState(({
        variant: 'error',
      }));
    }
  }

  render() {
    const { variant } = this.state;
    if (variant === 'error') {
      return <StatusView key="error-view" variant='error' />;
    }
    return <StatusView key="no-match-results" variant='no-matching-results' />;
  }
}

class ToggleVariants extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      variant: 'error',
    };
    this.handleOnSelect = this.handleOnSelect.bind(this);
  }

  handleOnSelect(event) {
    this.setState({
      variant: event.target.value,
    });
  }

  render() {
    return (
      <div>
        <CustomView variant={this.state.variant} />
        <fieldset>
          <legend>Change Variant</legend>
          <select id="statusViewVariant" name="statusViewVariant" value={this.state.variant} onChange={this.handleOnSelect}>
            <option value="error">Error</option>
            <option value="no-data">No Data</option>
          </select>
        </fieldset>
      </div>
    );
  }

};

```

During the componentDidUpdate - we would be making a service call to retrieve some data. Based on the status of the data - we set the state accordingly and re-render the component.

**Comment by nramamurth** [comment]
@Dinesh94Singh 

Unless I am misunderstanding the intention, shouldn't your `componentDidUpdate` look like this ⬇️? If the the new variant is _never_ updated in the code, then I'd not expect the variant switching to work. This works as expected without unique keys in v3.16.0.

```diff
componentDidUpdate(prevProps, prevState, snapshot) {
   console.log('snapshot is', snapshot);
   if (snapshot !== null) {
      // eslint-disable-next-line react/no-did-update-set-state
      this.setState(({
-         variant: 'error',
+         variant: this.props.variant,       
      }));
  }
}

```

**Comment by Dinesh94Singh** [comment]
Sorry for not being clear, in our case - we don't actually set the state of the variant from the props.

The workflow in our case would be - the component receives a prop which is a string.

If the string is empty or if the string is the same as prev props - the snapshot is null (making it not to re-render)
If the string has changed, we make a service call with this string as a unique identifier. This returns a response.

The response received will set the state as 

```
{
 isLoading: true,
 isFailed: false,
 isError: false,
 noData: true
}
```

in the render, we read the state and render the appropriate StatusView. Do you think, it will help to run the code from the repo given in description to better understand the problem?

My guess is that, could the re-render happen twice? ComponentDidMount makes a service call and sets the state - when state is set, it again tries to reload with the same prop info, which hasn't changed, making the snapshot null ??

**Comment by nramamurth** [comment]
@Dinesh94Singh 

I have a feeling that the way that you're setting the state could be an issue - maybe make sure that not more than one "type" of Status View in your state is set to `true`? If there are two values set to `true`, then I can see your issue happening and that makes sense. 

<details> <summary> Here is an updated example (put in a haphazard way) : </summary>

```
class CustomView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isError: true,
      noData: false,
    };
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
    console.log('snapshot is', snapshot);
    if (snapshot !== null) {
      // Let's assume that there was a service call made here.
      const mockSvcResponse = { variant: this.props.variant };
      if (mockSvcResponse.variant === 'error') {
        this.setState(({
          isError: true,
          noData: false,
        }));
      } else if (mockSvcResponse.variant === 'no-data') {
        this.setState(({
          noData: true,
          isError: false,
        }));
      }
    }
  }

  getSnapshotBeforeUpdate(prevProps) {
    console.log(this.props);
    if (this.props.variant && prevProps.variant !== this.props.variant) {
      return 0;
    }
    return null;
  }

  render() {
    const { isError, noData } = this.state;
    let statusView;
    if (isError) {
      statusView = (<StatusView variant="error" />);
    } else if (noData) {
      statusView = (<StatusView variant="no-matching-results" />);
    }

    return statusView;
  }
}

class ToggleVariants extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      variant: 'error',
    };
    this.handleOnSelect = this.handleOnSelect.bind(this);
  }

  handleOnSelect(event) {
    this.setState({
      variant: event.target.value,
    });
  }

  render() {
    return (
      <div>
        <CustomView variant={this.state.variant} />
        <fieldset>
          <legend>Change Variant</legend>
          <select id="statusViewVariant" name="statusViewVariant" value={this.state.variant} onChange={this.handleOnSelect}>
            <option value="error">Error</option>
            <option value="no-data">No Data</option>
          </select>
        </fieldset>
      </div>
    );
  }
}

export default ToggleVariants;
```
</details>

What issues did you run into with v4, though?

**Comment by nramamurth** [comment]
@Dinesh94Singh Has there been an update on this one? I shall go ahead and close this one for now. Please feel free to re-open it when you have a reduced test sample that helps repro this real problem.
