### ISSUE TITLE
Provide callback for keyup events on terra-form-input

### ISSUE THREAD

**Issue by zeilmannnoah** [cerner/terra-core#2656]
# Feature Request
Provide callback for keyup events on terra-form-input

## Description
For a lot of our forms, we allow the user to type in some data then press a button to submit the form. Most websites allow some keyboard shortcuts, such as pressing the enter key, to quickly submit the form. At the moment, terra does not support this without using the refCallback property, which isn't ideal. It would be nice if terrra-form-input had an onKeyUp property that would fire for events that don't change the text input, such as pressing enter.

**Comment by lokesh-0813** [comment]
One work around is to wrap terra-form-input in a form component.

@zeilmannnoah Could you give a detailed explanation where the above requested feature will be helpful?

**Comment by zeilmannnoah** [comment]
@lokesh-0813 I wanted to use this feature in a search form that has multiple inputs. With this feature, the user could type in what they want to query by and be able to press enter, or ctrl+enter, to initiate the search. Another use case is the ability to cancel the event is present in the keyup event but not in the onchange event, this allows the developer to have a more controlled input. It seems like listening for key events, such as keyup or keydown, are features that a free text input should have to provide extended features that the onchange event just cannot do.

**Comment by lokesh-0813** [comment]
@zeilmannnoah Have you tried [terra-search-field](https://engineering.cerner.com/terra-ui/components/terra-search-field/search-field/search-field) for searching?

CC @bjankord

**Comment by nramamurth** [comment]
> Most websites allow some keyboard shortcuts, such as pressing the enter key, to quickly submit the form.

@zeilmannnoah I am just throwing this out there - wouldn't form's `onSubmit` automatically handle it for you? 

General Example: https://codepen.io/gaearon/pen/VmmPgp?editors=0010
Terra Validation Example: https://engineering.cerner.com/terra-ui/components/terra-form-validation/form-validation/numeric-validation 

Where are you having to supply the `refCallback`?

**Comment by zeilmannnoah** [comment]
@nramamurth onSubmit worked for this. Thank you. You may close this issue if you feel this feature isn't desired. And with concerns to the refCallback, I was applying it to the InputField terra component, because I did not know of another way for listening for the enter key being pressed.

**Comment by nramamurth** [comment]
@zeilmannnoah I'm glad it worked out! 

I'll close this for now but please feel free to re-open it whenever the need arises.
