### ISSUE TITLE
[terra-form-input] Input Type File Not Showing Selection in Edge

### ISSUE THREAD

**Issue by saedar** [cerner/terra-core#2665]
# Bug Report

## Description
Running in MS Edge, my team is encountering an issue with `terra-form-input` with `type=file`. After interacting with the element and selecting the file...

Expectation: The file path/name is populated on field presented.
Actual: It remains blanked.

This is exclusive to Edge.

## Steps to Reproduce
1. Add `<Input type="file" />`
2. Click the element to open file select dialog.
3. Select a file.
4. See that the file name/path is not populated as expected.

## Additional Context / Screenshots
https://kaiju.cerner.com/projects/divine-spacegodzilla-ycyTiw/workspaces/silent-ebirah-vg6RLw

## Expected Behavior
The file name/path is displayed in the element.

## Possible Solution
n/a

## Environment
* Component Name and Version: `terra-form-input@1.32.0` (Also happening in Kaiju)
* Browser Name and Version: MS Edge (44.17763.1.0)
* Node/npm Version: node 8.11.3
* Webpack Version: Yarn lock is hard to read. 3.11/3.12/4.28
* Operating System and version (desktop or mobile): Windows 10

**Comment by bjankord** [comment]
Looked into this some, our thoughts is that this is a bug specifically with how Edge is handling `input type="file"`. Can you test the native input element,  `<input type="file" />` and see if it has the same problem.

**Comment by saedar** [comment]
Added a generic `input` element in the w3schools html utility and it works without issue.

<img width="1311" alt="Screen Shot 2019-09-26 at 1 41 42 PM" src="https://user-images.githubusercontent.com/3671289/65715836-7fadee00-e063-11e9-9653-91a11efff372.png">

**Comment by nramamurth** [comment]
Ah, I see the issue (I think). For whatever reason, Edge does not behave well when `defaultValue` is `undefined`. I did a quick test and changed the [default value of `defaultValue` ](https://github.com/cerner/terra-core/blob/master/packages/terra-form-input/src/Input.jsx#L74) to an empty string and it _seemed_ to fix the issue. 

Do we want to do it? I am not sure. 

cc / @bjankord
