### ISSUE TITLE
Default props for boolean props should only be true or false

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#267]
# Issue Description
Default props for boolean variables should be either true or false.

One example:
https://github.com/cerner/terra-core/blob/master/packages/terra-list/src/ListItem.jsx#L27-L30

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Any boolean default prop should be set to either true or false.

## Current Behavior
Not all boolean props are set as true or false.

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/pull/266/files#r113695096

**Comment by emilyrohrbough** [comment]
Defining an item as isSelectable has selection indication via hover highlighting/mouse indication.  
If default prop is true, all nonselectable list will need to pass isSelectable=false for each item to prevent hover highlighting/mouse pointer.
