### ISSUE TITLE
[spike][terra-demographics-banner] Remove ResponsiveElement from Demographics Banner

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#2673]
# Feature Request

## Description
The DemographicsBanner component uses the ResponsiveElement to flex between large and small layouts: https://github.com/cerner/terra-core/blob/master/packages/terra-demographics-banner/src/DemographicsBannerDisplay.jsx#L106

This implementation results in quite a bit of flickering when the component remounts, as the component renders nothing while its determining its initial width. This flickering is immediately obvious when the DemographicsBanner is integrated into our navigation frameworks and remounted on page changes.

I've also encountered scenarios where the DemographicsBanner fails to render anything at all. To be clear, this has occurred only when debugging and using breakpoints within the browser, but the fact that it can happen at all with something as sensitive as demographics gives me cause for concern.

I'd like to see if there's a way we could remove the DemographicsBanner's dependency on the ResponsiveElement. If we cannot, I'd like to see if we can update the ResponsiveElement to have fewer side-effects on components that use it.

**Comment by ShettyAkarsh** [comment]
Hi @tbiethman ,

Do you have any test case drafted for this scenario to recreate this issue ? myself tried working on the demographic examples and test between small and other breakpoints everything looks to be working fine. is this issue specific to any browser/OS ?

**Comment by StephenEsser** [comment]
As part of this spike, if we choose to keep the responsive element, we should investigate uplifting to the controlled version of the responsive element.

The uncontrolled version has been [flagged for deprecation](https://github.com/cerner/terra-core/pull/2729). This warning is printing for consumers of the demographics banner.
