### ISSUE TITLE
[Terra-Overlay] throws removeAttribute undefined error when being displayed

### ISSUE THREAD

**Issue by po016255** [cerner/terra-core#2678]
# Bug Report

## Description
It appears we get an error in the terra-overlay when displaying the overlay by setting isOpen=true.  (ie debugger kicks off a data load that shows the overlay and the error occurs before the data returns so it most likely when the overlay becomes visible, not being hidden)
When clicking yes on the script error to dismiss it, the underlying summary successfully finishes loading.

[Post on teams](https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1570037453018?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1570037453018&teamName=Terra&channelName=Component%20Support&createdTime=1570037453018)
Issue cannot be recreated in standalone chrome or ie11/10.
It only happens when running the component in an mpage.

The bug appears to be related to showing the overlay when setting isOpen=true.  [Line of code in plan-js.](https://github.cerner.com/ipoc/goals-js/blob/180edf86bf3e5c9c4ae96527f9cb3bdbc40043d3/src/goals/components/views/BaseView.jsx#L349)
[This appears to be the offending line of code in terra-overlay that throws an exception.](https://github.com/cerner/terra-core/blob/b1562abd458cb6c999fcf59e45ba4dab6eb43403/packages/terra-overlay/src/Overlay.jsx#L132)

## Steps to Reproduce
1. Load OnePlan inside an mpage. (plan-js)
2. Click tab in mpage to view goals and activity summary. 
2. Click an activity to view details. (opens slide panel with detail view)
3. Click button to modify an activity.  (view in panel changes to modify view)
3. Click apply. (triggers reload of goals content and closes slide panel)
4. Overlay displays while data is being loaded and error is thrown. (isOpen is set to true on overlay)

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/12768193/66068218-d0659100-e512-11e9-97d3-7df29bfaa72f.png)

![image](https://user-images.githubusercontent.com/12768193/66068277-ea06d880-e512-11e9-9ada-c60f9ea5234e.png)

Gif of error in solgm domain.  
![overlay_error](https://user-images.githubusercontent.com/12768193/66068843-f2abde80-e513-11e9-80fe-19f69569e9d1.gif)

## Expected Behavior
Overlay should display and then close once data is loaded, with a refreshed summary view containing the new data.

## Environment
* Component Name and Version: [Plan-js 1.2.1](https://github.cerner.com/ipoc/plan-js/blob/3daef16944bbac5aab9e8607044ce67b8e9e082d/package.json)
* Browser Name and Version: IE11 11.737.17763.0
* Operating System and version (desktop or mobile): Windows 10 1809 (OS Build 17763.737)
Powerchart: 2018.01 - solgm
Mpages: 6.12 - http://ip85wodr12a/mpage-content/solgm.ip.devcerner.net/MPAGES_6_12

**Comment by ShettyAkarsh** [comment]
closed #2679
