### ISSUE TITLE
Handling unused props in the render method

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#268]
# Issue Description

We have some components that have props not used inside the render method. We should be consistent on how we handle them.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

[Method 1: delete the props so they are not spread](https://github.com/cerner/terra-core/blob/81337a98119f2fc51c22cd0ce0a471c66400c78e/packages/terra-table/src/SingleSelectableRows.jsx#L121-L135)
```
  render() {
    const { children, ...customProps } = this.props;
    const clonedChilItems = this.clonedChildItems(children);
    if ('onClick' in customProps) {
      delete customProps.onClick;
    }
    if ('onKeyDown' in customProps) {
      delete customProps.onKeyDown;
    }
    return (
      <TableRows {...customProps}>
        {clonedChilItems}
      </TableRows>
    );
  }

}
```

[Method 2: ignore the eslint rule](https://github.com/cerner/terra-core/blob/57baaf99ebb86e32cf39e6c979932eb3311e5e47/packages/terra-responsive-element/src/ResponsiveElement.jsx#L100-L110)

```
  render() {
    /* eslint-disable no-unused-vars */
    const { defaultElement, tiny, small, medium, large, huge, responsiveTo, ...customProps } = this.props;

    return (
      <div {...customProps} ref={this.setContainer}>
        {this.props[this.state.element]}
      </div>
    );
  }
}
```

## Current Behavior

**Comment by emilyrohrbough** [comment]
Here is some interesting [discussion](https://github.com/babel/babel-eslint/issues/95) on an issue logged in the babel-eslint repo. One comment referenced to this [proposal](https://github.com/babel/babel-eslint/issues/95) which suggested the use of `_` for unused variables.

**Comment by windse7en** [comment]
It seems [eslint #7968 PR](https://github.com/eslint/eslint/pull/7968) fixes this issue. If there are unused props and `...customProps(remainder props)`, it's not considered to be unused props. As those props will affect the value in remainder props. So it won't get lint error.

**Comment by bjankord** [comment]
Let's go with option 1 but take a look at the following

Need to:
* Check what version this fix landed in eslint
* Check what airbnb config to see if it took this rule

**Comment by Matt-Butler** [comment]
https://github.com/airbnb/javascript/blob/d48083796c3a1442e44c86b050cc65a353f9bf43/packages/eslint-config-airbnb-base/CHANGELOG.md#1111--2017-03-03

**Comment by emilyrohrbough** [comment]
As this [CHANGELOG](https://github.com/airbnb/javascript/blob/d48083796c3a1442e44c86b050cc65a353f9bf43/packages/eslint-config-airbnb-base/CHANGELOG.md#1111--2017-03-03) mentioned, airbnb base 11.1.1 enables `ignoreRestSiblings` `no-unused-vars`, which removes of the `no-unused-vars` eslint error. This removes the need to delete props that should not be spread.
