### ISSUE TITLE
[terra-form-select] Variants with an input (all except single select) are causing rerenders on scroll which calls scrollIntoView

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-core#2684]
# Bug Report

## Description

Select variants with an input (all except single select) are causing rerenders on scroll which calls `Menu.scrollIntoView`. This causes scroll jumping and also prevents you from being able to properly select all items in large lists. The list will scroll immediately to the active option before an option is selected, causing the wrong option to be selected. This behavior appears after the big internal refactor (e.g. v5.25.0). While this issue is hard to replicate on desktop (generally, the active option is set via mouse hover over an option when scrolling and we don't scroll in this case), this is doubly bad on mobile. See example video [here](https://youtu.be/0-kbggVR-mg)

## Expected Behavior

No scroll jump when scrolling.

## Possible Solution

We probably don't need to call `this.scrollIntoView()` on each `componentDidUpdate()` (see [here](https://github.com/cerner/terra-core/blob/terra-form-select%405.32.0/packages/terra-form-select/src/multiple/Menu.jsx#L197)). This was likely done to guarantee that all state changes were flushed before trying to scroll to the active option.

Instead, we should just call `this.scrollIntoView()` on changes to the `active` state var (using `this.setState`'s callback arg), e.g. on key up:

```jsx
handleKeyDown(event) {
  if (event.keyCode === KeyCode.KEY_UP) {
    this.setState(
      { active: MenuUtil.findPrevious(this.state.children, this.state.active) },
      () => this.scrollIntoView()
    );
  }
  // ...
}
```

## Environment

* Component Name and Version: terra-form-select v5.32.0

**Comment by dev-cprice** [comment]
The only issue I can see happening using the above solution is that we don't properly scroll to the active option when the search criteria changes... 🤔🤔🤔

Best solution: rewrite the `Menu` to use hooks and use `React.useEffect` to `activeOption.scrollIntoView()` `iff` the `activeOption` changes.

**Comment by lokesh-0813** [comment]
@dev-cprice This issue occurs in all variants(including 'single')


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16148882/66916703-6cc28400-f039-11e9-8b84-6e1bd5d0f0c3.gif)

After selecting a option in Single Select and re-open immediately the selected item is not in focus.
