### ISSUE TITLE
[terra-button] DST Clarification Button does not take focus in Safari/Firefox

### ISSUE THREAD

**Issue by prmeznar** [cerner/terra-core#2688]
# Bug Report

## Description
In Safari and Firefox, clicking the time clarification button from a DST workflow for the terra-date-time-picker and then selecting a timezone does not return focus to the clarification button, nor does it invoke the consumer provided onBlur prop. This is particularly troublesome when that onBlur prop how the updates to the date time value get applied.

## Steps to Reproduce
1. Navigate to https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/date-time-picker in firefox or safari
2. Enter the ambiguous hour (e.g., 11/03/2019, 1:22) - modal appears, clarify your time
3. Modal disappears, click clarification button, modal reappears. Select opposite time, notice no button highlighting (terra-button 3.20.0 fixed how the button would be highlighted in chrome in this workflow, in firefox/safari it's not just that it's not highlighted, it does not even have focus)
4. If you like, run the workflow in chrome and observe the difference

## Additional Context / Screenshots
I think this is an issue with the terra-button and the fixes around programmatic focus being browser dependent, which is why I logged it here. If my assumption is wrong I apologize and this may be a terra-date-time-picker issue.
https://jira2.cerner.com/browse/ORDPLANDEV-29226 has video

## Expected Behavior
Either for the button to have focus after the modal closes (after being launched from the button), or for the provided onBlur method to be invoked.

## Possible Solution
Right now I know the date-time-picker attempts to put focus back on the button as that is where it was before the modal was launched. If that behavior isn't necessary, just invoking the onBlur method of the consumer upon the modal being dismissed would work for us... but the correct fix is probably getting focus set on the button.

## @ Mentions
@benbcai @dev-cprice  @mjhenkes

**Comment by benbcai** [comment]
The Button's [onFocus](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.jsx#L175-L183) event is called when you click on a Button in Chrome. When you then click outside of the button. The Button's [onBlur](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.jsx#L128-L134) event will also get called when you then click outside of the Button. However, in both Firefox and Safari, neither of these events are called when you click on the button and then away from it. I think that is what's causing the TZ button to behave differently in Firefox and Safari. This appears to be related to #1969 . See [comment](https://github.com/cerner/terra-core/issues/1969#issuecomment-429414465).

**Comment by mjhenkes** [comment]
This will be resolved with #1969
