### ISSUE TITLE
[terra-overlay] latest changes prevent interaction with our application

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#2699]
# Bug Report

## Description
An 'inert' attribute is added to the div with an id of 'root'.   This means users can't scroll or interact with our application.
Our application loads and displays an overlay that is not relative to container. Once the overlay is removed, the user cannot interact with our app.

## Steps to Reproduce
1.   Have a page with an Overlay that is not relative to container.
2.  Update state several times, thus causing componentDidUpdate to call disableContainerChildrenFocus.  On version 3.31.0, each call will increment the inert count, even though this spinner is already going.

## Expected Behavior
Inert should only be added for new spinners, not an existing spinner being re-rendered.

## Possible Solution
At least to get people working again, revert the changes.

## Environment

* Component Name and Version: terra-overlay 3.31.0
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by ShettyAkarsh** [comment]
#2700

**Comment by mjhenkes** [comment]
Resolved with https://github.com/cerner/terra-core/pull/2700
