### ISSUE TITLE
[terra-toggle-section-header] Transparent Background Behavior

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2701]
## Description
When using the `isTransparent` prop on the `terra-toggle-section-header`, should the grey header background be toggled when the component is focused or active?

https://share.getcloudapp.com/WnuAGyoN

## Expected Behavior
I would expect the background to remain transparent when interacting with the section header.

**Comment by neilpfeiffer** [comment]
Closing - `isTransparent` prop option is already scheduled for removal, should be marked for deprecation if not already:  

Issue to Remove and MVB: https://github.com/cerner/terra-core/issues/1933
