### ISSUE TITLE
Add ability to set the icon in the SearchField

### ISSUE THREAD

**Issue by zeilmannnoah** [cerner/terra-core#2721]
# Feature Request

## Description
When using the [Terra SearchField](https://engineering.cerner.com/terra-ui/components/terra-search-field/search-field/search-field), it can be difficult to find a way to display that a search is currently active. One of the most common ways is to use a LoadingOverlay to display that but for some teams, like ours, our clients really don't enjoy a view popping up and covering the screen for a short about of time so the LoadingOverlay can't be used. It would be nice if we could provide an icon to the SearchField to replace the current magnifying glass with something like the loading spinner icon.

## Additional Context / Screenshots
If it were possible to replace the icon. When the search fires for the SearchFIeld, a developer could add the logic to change the icon to a spinner when the request is in progress.
![captured](https://user-images.githubusercontent.com/33825428/67428434-b95f0f80-f5a3-11e9-9157-010a427fa20e.gif)

## @ Mentions
Not applicable.

**Comment by zeilmannnoah** [comment]
This could be done if there was a property similar to the inputAttributes property, but for the button attributes.

**Comment by neilpfeiffer** [comment]
This is a pattern that UX has not approved to be used as of yet. 
Work with your UX designer to adjust for an alternate set of controls or interactions for your use case.
