### ISSUE TITLE
[form-checkbox] Checked/Unchecked Indicator

### ISSUE THREAD

**Issue by andrewnottaviano** [cerner/terra-core#2736]
# Feature Request
## Description

Currently, there is a prop on the `terra-form-checkbox` called `onChange` that passes an event to the function passed to the prop. A consumer can determine the value of the component by querying `event.target.value` in the handler, but there is not a clear way to determine whether or not this is event is fired because the checkbox was checked or not checked. Additionally, there is not a clear way to query component to determine if it is currently checked or unchecked (besides querying the DOM directly with `document.getElementById` or similar api).

**Comment by ShettyAkarsh** [comment]
@andrewnottaviano have you tried using event.currentarget.Checked in your code ?

**Comment by nramamurth** [comment]
@andrewnottaviano 

> A consumer can determine the value of the component by querying event.target.value in the handler, but there is not a clear way to determine whether or not this is event is fired because the checkbox was checked or not checked.

You could use `event.currentTarget.checked` to determine if the checkbox is checked or not checked in the event handler. 

> Additionally, there is not a clear way to query component to determine if it is currently checked or unchecked (besides querying the DOM directly with document.getElementById or similar api).

Are you looking for a `refCallback` prop to attach a ref to your element?

**Comment by andrewnottaviano** [comment]
> @andrewnottaviano have you tried using event.currentarget.Checked in your code ?

Yes I did since I posted this issue and that solves my problem. Just didn't get back here to close the issue. Thanks @nramamurth and @ShettyAkarsh!
