### ISSUE TITLE
[terra-status-view] Investigate if overflow is necessary for inner container

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2737]
# Feature Request
If the status view is disclosed inside a tiny (240px height) modal, it will overflow. A scrollbar appears because we set `overflow: auto` within the inner space. 

Do we prefer a scroll bar or status view content that extends out of a <= tiny container? Another option is altering the sizes of status view content to play nicely with a tiny modal. This needs feedback from UX.

![Screen Shot 2019-11-05 at 3 49 38 PM](https://user-images.githubusercontent.com/14063284/68249209-f08de180-ffe3-11e9-95c6-5e983e5fd653.png)
https://github.com/cerner/terra-core/blob/master/packages/terra-status-view/src/StatusView.module.scss#L41

**Comment by ryanthemanuel** [comment]
Spoke with @neilpfeiffer and this is working as it should.  Likely this combination shouldn't line up.
