### ISSUE TITLE
Action Buttons in Action header are not properly aligned with fusion theme

### ISSUE THREAD

**Issue by supreethmr** [cerner/terra-core#2738]
# Bug Report
Action Buttons in Action header are misaligned in fusion theme.

## Description
Right and Left action buttons are not center aligned like title in header. this could be because of missing variable for setting padding of action buttons in action header unlike [title](https://github.com/cerner/terra-core/blob/fa60de1861435c35d1bff8d0de75cd36721b07d1/packages/terra-action-header/src/ActionHeaderContainer.module.scss#L52).

<img width="1415" alt="Screen Shot 2019-11-07 at 11 25 24 PM" src="https://user-images.githubusercontent.com/12869809/68414552-6c3f8800-01b6-11ea-94fc-11bf501ac237.png">

## Steps to Reproduce
1. Open  Action Header with Fusion Theme

## Expected Behavior
Action Buttons should be properly aligned in Action Header.

## Possible Solution
By adding Theme variable to set padding value for action buttons( left and right buttons ) .

**Comment by neilpfeiffer** [comment]
Reviewing UX needs for Theme. Generally already have the container padding plus title padding-top, which when provided correct theme values may resolve alignment issues.

**Comment by emilyrohrbough** [comment]
this was resolved and released as `terra-action-header@2.38.0`
