### ISSUE TITLE
[terra-i18n] Module not found intLoaders

### ISSUE THREAD

**Issue by kevb10** [cerner/terra-core#2756]
# Bug Report

## Description

I'm new to Terra UI and React. After copying [my code from Kaiju](https://github.cerner.com/revenue-cycle-enabling-technologies/ent-config-ui/blob/restructure/client/src/components/Create.jsx) into my project, when I run `yarn install` it gives me the following compilation error.
```js
./node_modules/terra-i18n/lib/intlLoaders.js
Module not found: Can't resolve 'intlLoaders' in '/home/km054131/Documents/React-Projects/ent-config/client/node_modules/terra-i18n/lib'
```

I've added and remove terra-i18n to no avail. I've also tried `rm -rf node_modules && yarn --force` as the others suggested but it didn't work. 

## Steps to Reproduce

1. Import code from Kaiju
2. Install needed dependecies
3. `yarn start`
4. :boom: 

## Environment

* Component Name and Version: `terra-i18n` and possibly related to `terra-form-select`
* Browser Name and Version: Chrome 78
* Node/npm Version: [e.g. Node 8/npm 5] 13.0.1/6.13.1
* Webpack Version: 
* Operating System and version (desktop or mobile): Ubuntu Desktop

**Comment by StephenEsser** [comment]
Hi @kevb10, 

Welcome to Terra and React. 

There's a couple things that need setup before diving into Terra.

The first is [terra-base](https://engineering.cerner.com/terra-ui/components/terra-base/base/base). This is the intl provider and base style each component in Terra relies on.

The second is setting up webpack. Your project was bootstraped using create-react-app so this isn't needed right now, but it will most likely be needed in the future when your application matures. Terra provides a reusable webpack configuration that we recommend consumers extend. 

Here's a few docs on getting setup with Terra. Check out the sections in this getting started page.

https://engineering.cerner.com/terra-ui/getting-started/terra-ui/what-is-terra

To help you get started here are the minimal changes you'll need to get your project up and running with Terra.

https://github.cerner.com/SE028266/ent-config-ui/commit/07a3aa4b68e690067498a52c2287cb3125efe4aa

**Comment by kevb10** [comment]
Awesome @StephenEsser. Got it to work. It was the webpack exclusion. 
Ty ty :tada:
