### ISSUE TITLE
Allow passing additional attributes to the datepicker input element

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#276]
We need to be able to add additional attributes to the input tag of the datepicker. For example, the name attribute.

**Comment by bjankord** [comment]
More info from consumer:

> The input field generated by Terra UI Date Picker dos not have a way of setting name attribute on it or does not include it as part of the input field. The name field is needed by rails as it tells rails into which param to pull in that input value into and makes it accessible to the controller.
