### ISSUE TITLE
[terra-dropdown-button] Voice Over Focus does not go inside when opening with mouse.

### ISSUE THREAD

**Issue by saket2403** [cerner/terra-core#2772]
# Bug Report

## Description
Needs investigation for page jump issue which we found out in form-select issue #2682. Since 
Terra-dropdown-button also uses terra-hookshot to render dropdown-list. we need to test terra-dropdown-button with IFrame.

**Comment by supreethmr** [comment]
> The Voice Over Focus moves around in the page before going inside the dropdown. This was introduced due to the changes in PR #2766 , where the focus was moved out of the dropdown when opening it with a mouse click.
This is due to the `Portal` in `Hookshot` which is rendered  into a DOM node that exists outside the DOM hierarchy of the parent component.

this issue has been addressed with PR : https://github.com/cerner/terra-core/pull/2766

**Comment by supreethmr** [comment]
this issue can be closed with PR : https://github.com/cerner/terra-core/pull/2766

**Comment by supreethmr** [comment]
page jump issue mentioned in issue description was not reproducible in terra-dropdown button closing this issue.
