### ISSUE TITLE
Demographic Banner - preferred name in parentheses

### ISSUE THREAD

**Issue by mikertr** [cerner/terra-core#2775]
# Issue Description
To align with other solutions, preferred name should display in parentheses instead of quote marks in the demographic banner.
 
Examples:

Today, the name in demographic banner may display as:

- Smith, Joseph "Joe"

 
Desired display:

- Smith, Joseph (Joe)

**Comment by neilpfeiffer** [comment]
### Design Instructions
This is a correct change to make based on updated Cerner Model requirements - changes to make are here:
https://github.com/cerner/terra-core/blob/2f06b944b8f030b521e9915fe822d7161fbc4e30/packages/terra-demographics-banner/src/DemographicsBanner.module.scss#L54-L57

and change to 
```
    &::before {
      content: '(';
    }

    &::after {
      content: ')';
    }
```
