### ISSUE TITLE
Button group interaction styles

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#278]
# Issue Description
Comment from UX during validation

> Add detection for mouse click vs. keyboard (tab) interaction so the default :focus outline glow can be maintained for selection/onclick/onchange when interacting via keyboard, but not applied after a user touch or click with mouse. Issue to solve will be to remove the default :focus outline by blur() or similar method but still maintaining tab position on the page.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Add detection for mouse click vs. keyboard (tab) interaction so the default :focus outline glow can be maintained for selection/onclick/onchange when interacting via keyboard, but not applied after a user touch or click with mouse.

## Current Behavior
Focus styles do not differ between mouse click vs. keyboard (tab) interaction

**Comment by emilyrohrbough** [comment]
The behavior determined here would likely carry forward for this issue regarding Selectable Lists https://github.com/cerner/terra-core/issues/529.

**Comment by bjankord** [comment]
This should be covered by https://github.com/cerner/terra-core/issues/1038
