### ISSUE TITLE
[terra-alert][fusion theme] Custom Box Shadow Overrides Prop Defined Color

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2788]
# Bug Report

## Description
In the fusion theme, the custom box-shadow color that is defined via the `customColorClass` prop is being overridden by the fusion class var `--terra-alert-custom-box-shadow` value. 

In the default style sheet, the color was not included in the custom variant's box shadow to allow the color class to be inherited: https://github.com/cerner/terra-core/blob/master/packages/terra-alert/src/Alert.module.scss#L127-L129

In the fusion theme, a color is defined for the box shadow, should it is not inheriting the custom color value.

## Steps to Reproduce

1. Go to https://engineering.cerner.com/terra-core/components/terra-alert/alert/alert
2. Look at the custom color class example
3. Change the theme to the `orion-fusion-theme`
4. See the custom color not being honored

## Additional Context / Screenshots
<img width="662" alt="Screen Shot 2019-12-26 at 8 14 50 AM" src="https://user-images.githubusercontent.com/14099737/71478964-f4eea380-27b7-11ea-86a7-a44a1b5167dd.png">

## Expected Behavior
<img width="666" alt="Screen Shot 2019-12-26 at 8 14 57 AM" src="https://user-images.githubusercontent.com/14099737/71478962-f0c28600-27b7-11ea-92c6-042923b41d44.png">

## Solution
Update the [theme var](https://github.com/cerner/terra-core/blob/master/packages/terra-alert/themes/orion-fusion-theme/orion-fusion-theme.scss#L38) to remove the color:

```diff
    --terra-alert-custom-background-color: #f4f4f4;
-  --terra-alert-custom-box-shadow: inset 2px 0 0 #9b9fa1;
+  --terra-alert-custom-box-shadow: inset 2px 0 0;
```

**Comment by emilyrohrbough** [comment]
@neilpfeiffer @jeremyfuksa Could either of you confirm the suggested solution is correct?

**Comment by jeremyfuksa** [comment]
It looks to me that the theme var could be removed completely.

**Comment by emilyrohrbough** [comment]
Closing in favor of picking up: https://github.com/cerner/terra-core/issues/1882

**Comment by emilyrohrbough** [comment]
Closing in favor of picking up: https://github.com/cerner/terra-core/issues/1882

**Comment by emilyrohrbough** [comment]
Flagging as `not an issue` as this work is moving to issue 1882 and we want to filter this closed issue from our bug-turnaround tracker.
