### ISSUE TITLE
ProfileImage sometimes clips images when resizing to fit container

### ISSUE THREAD

**Issue by cm9361** [cerner/terra-core#2798]
# Feature Request

## Description
The ProfileImage is clipping images that are resized because the object-fit CSS style is being forced to "cover".  This property is being passed to the TerraImage that is being wrapped but cannot be modified by consumers.

Example: https://jira2.cerner.com/browse/PATSEARCH-407

## Steps to Reproduce
1. Load an image that must be scaled to fit the container

## Additional Context / Screenshots
https://github.com/cerner/terra-core/blob/master/packages/terra-profile-image/src/ProfileImage.jsx#L55

## Expected Behavior
The expected behavior is that the image is scaled to fit into the container without being clipped.

## Possible Solution
Expose a prop type that allows the consumer to control the object-fit style or change the value passed to "fill" or "contain".

## @ Mentions
@ryanthemanuel

**Comment by avinashg1994** [comment]
IMO, Exposing a prop that allows the consumers to control the object-fit style is a good suggestion.
We could also default its value to "cover" so as to keep the change passive.
cc : @neilpfeiffer , @mjhenkes

**Comment by neilpfeiffer** [comment]
Exposing object-fit should be fine. 

Special note @CM046991 -- for Profile Images that are intended to be photos of People - only `cover` and `contain` would be the acceptable values. `fill` would never be acceptable by UX as is changes the original image aspect ratio and distorts the face and likeness of the image.

**Comment by neilpfeiffer** [comment]
Reclassifying as an enhancement, as photo clipping is not a bug, but intended UX behavior for standard usage (fills and centers photo). 

Any additional image sizing/styling added shown in https://jira2.cerner.com/browse/PATSEARCH-407 also not a bug of the profile-image component.
