### ISSUE TITLE
[terra-action-header] 'level' prop does not justify its purpose.

### ISSUE THREAD

**Issue by lokesh-0813** [cerner/terra-core#2801]
# Bug Report

## Description
Providing value to `level` prop does not change the appearance of the text.

## Steps to Reproduce
set level={5}(or any value).
Notice that the heading appearance does not change.

## Expected Behavior
Appropriate heading should be applied if `level` prop is provided.

## Environment
* Component Version:2.34.0 - (January 7, 2020)

## Additional Context / Screenshots
`--terra-action-header-font-size` could be causing the issue.

**Comment by emilyrohrbough** [comment]
@lokesh-0813 I think the level prop is used for accessibility with screen readers, not for altering the styles on the header

**Comment by ShettyAkarsh** [comment]
so in that we might to Update the doc for level prop as following '**Optionally sets the heading level for Screen Readers. One of 1, 2, 3, 4, 5, 6. Default level=1.**. also even for Terra-Section-Headers https://github.com/cerner/terra-core/blob/master/packages/terra-section-header/src/SectionHeader.jsx#L23-L27
