### ISSUE TITLE
Explore webpack optimizations

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#283]
# Issue Description

To enable tree-shaking in webpack, we need to add UglifyJs or bablili. We want to explore these options and better understand what considerations are involved in this decision.

The addition of tree-shaking could help us get a better idea of what our total bundle size is for consumers that use all of the terra-core components.

@windse7en listed the following concerns around adding UglifyJsPlugin or bablili:

* I'm not sure their pros and cons. We may need to create another PR to document those concerns. It helps us to track the decision and convince consumers with our final choice.

* And in [this PR](https://github.com/cerner/terra-core/issues/209), we add cheap-source-map into the webpack config. We may need to test that with minified files by UglifyJsPlugin or bablili.

* As this will be our recommendation across all consumers, we may want to compare the compression ratio to achieve the best performance.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
- [x] Update compile script https://github.com/cerner/terra-core/pull/300
    * Add `-p` flag to production compile script
    * Generate stats.json file when deploying gh-pages
- [x] Alias `moment`  and `react-dom` in webpack config https://github.com/cerner/terra-core/pull/297
- [ ] Split code into multiple bundles
   * terra-components (all of our distributed component code)
   * terra-site (the documentation site and examples)

## Current Behavior
N/A

**Comment by windse7en** [comment]
Discussion in PR: https://github.com/cerner/terra-core/pull/270#discussion_r113762844

**Comment by Matt-Butler** [comment]
Here are the initial stats without bablili or UglifyJsPlugin
```
webpack --config webpack.prod.config -p --json > stats.json
```
![initial](https://cloud.githubusercontent.com/assets/8146159/25585533/b5c4866e-2e60-11e7-87f7-858e0ef7908c.png)

**Comment by windse7en** [comment]
stat file with -p without using UglifyPlugin of bablili: https://drive.google.com/drive/u/0/folders/0Bw-81qR2Hz_bdWxHMUZ3S0VUWWM

**Comment by Matt-Butler** [comment]
**Instructions for uglifyjsPlugin:**
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

**Instructions for babili:**
https://webpack.js.org/plugins/babili-webpack-plugin/

**Comment by windse7en** [comment]
Here are the UglifyJsPlugin stats
![stats_with_uglifyjs](https://cloud.githubusercontent.com/assets/3724179/25586758/6c079c9a-2e66-11e7-9d8f-6911ad50eaa2.png)

**Comment by Matt-Butler** [comment]
Adding [babili to the .babelrc config](https://github.com/babel/babili#usage-1): https://github.com/cerner/terra-core/tree/babili-babelrc

```
cd packages/terra-site
npm run compile:prod
```

It is no longer generating the locale files.
![babili](https://cloud.githubusercontent.com/assets/8146159/25592135/35830b52-2e7d-11e7-9907-74639aed6424.png)

**Comment by Matt-Butler** [comment]
* I didn't expect props-table to be so large
* It looks like moment is being pulled in twice:
  * /node_modules/moment
  * /node_modules/terra-date-picker/node_modules/moment

We should use the resolve loader to only target moment in `/node_modules/moment`

**Comment by Matt-Butler** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/122
react-datepicker has a really, really old issue to change moment to a peerDependency.

**Comment by windse7en** [comment]
This plugin can help use to find the package with different versions. https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin 

But it doesn't work for the moment which is in the same version.

**Comment by Matt-Butler** [comment]
Executing `npm dedupe` found several duplicate packages being installed. It might be worth adding this after `npm install`

**Comment by Matt-Butler** [comment]
https://hackernoon.com/optimising-your-application-bundle-size-with-webpack-e85b00bab579

**Comment by Matt-Butler** [comment]
https://testmysite.thinkwithgoogle.com/
![screen shot 2017-05-01 at 4 55 07 pm](https://cloud.githubusercontent.com/assets/8146159/25596500/0a2d700c-2e8f-11e7-9c03-2a912028b3df.png)

![screen shot 2017-05-01 at 4 55 15 pm](https://cloud.githubusercontent.com/assets/8146159/25596499/08841670-2e8f-11e7-8a88-60364be65772.png)

**Comment by Matt-Butler** [comment]
Todo:
- [ ] Add `-p` flag to production compile scrript

**Comment by windse7en** [comment]
As in [webpack source code](https://github.com/webpack/webpack/blob/v2.4.1/bin/convert-argv.js#L441), `-p` will provide:
1. the `--optimize-minimize`, which uses `uglify-js 2.8.5` to minize js.
2. Set process.env to `production`.
3. Add `{minimize: true}` config to the loaderOptionsPlugin.

We can remove the duplicated config in `webpack.prod.config.js` after using `-p`.

**Comment by Matt-Butler** [comment]
Adding an alias from react-dom broke the nightwatch examples.

**Comment by arLevi** [comment]
Just asking: what if the tree consist same lib just with different versions ? 
( which is how I can handle the plugins and their dependencies ... by just running it vs bundling it )

I.e:
```
new-project/
└── node_modules
    ├── angular-plugin-1
    │   └── node_modeuls
    │       └── jquery-1.12
    └── angular-plugin-2
        └── node_modeuls
            └── jquery-3.2.1
```

So project `angular-plugin-1` is using a very old `jQuery` version, which has deprecated functions that no longer exists in `jquery-3.2.1`

How `--optimize-minimize` will handle this ?

**Comment by bjankord** [comment]
Three simple ways to inspect a webpack bundle:
https://medium.com/@joeclever/three-simple-ways-to-inspect-a-webpack-bundle-7f6a8fe7195d

**Comment by Matt-Butler** [comment]
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#analyzing-the-bundle-size
