### ISSUE TITLE
[terra-demographics-banner] Parenthesis in "Preferred First Name" could overlap characters on next line. 

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#2838]
# Bug Report

## Description
The parenthesis `()` added in #2793 for the "Preferred First Name" in the Demographic Banner has a potential to slightly touch or overlap characters on the next line. It is slightly more noticeable using the Fusion theme. See screenshots below.

## Additional Context / Screenshots
Default theme test example from [dev-site](https://engineering.cerner.com/terra-core/tests/terra-demographics-banner/demographics-banner/populated-demographics-banner) with updated text:
![Screen Shot 2020-02-11 at 2 36 01 PM](https://user-images.githubusercontent.com/22618655/74277163-a603bb80-4cdc-11ea-9b8e-c61b05eef982.png)

Fusion theme test example from [dev-site](https://engineering.cerner.com/terra-core/tests/terra-demographics-banner/demographics-banner/populated-demographics-banner) with updated text:
![Screen Shot 2020-02-11 at 2 35 36 PM](https://user-images.githubusercontent.com/22618655/74277202-b7e55e80-4cdc-11ea-94d2-3d359490eca5.png)

Consumer example: Note that the opening parenthesis `(` appears touching `0` below it.
<img width="365" alt="Screen Shot 2020-02-11 at 1 39 14 PM" src="https://user-images.githubusercontent.com/22618655/74272243-eca0e800-4cd3-11ea-9b96-f2baaf34b923.png">

## Possible Solution
Adjust the `line-height` or add some `padding` or `margin`.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by ShettyAkarsh** [comment]
Setting **padding-bottom: 0.2 rem** for **person-name** would fix this issue.  Need UX input on this

**Fusion theme** :- 

![image](https://user-images.githubusercontent.com/45097016/74427368-f9147480-4e7c-11ea-9c55-f9c42b04d9f3.png)

**Default theme** :-

![image](https://user-images.githubusercontent.com/45097016/74427460-27924f80-4e7d-11ea-958f-aaa19ce5d7f3.png)

@neilpfeiffer , @jeremyfuksa

**Comment by jeremyfuksa** [comment]
> Setting **padding-bottom: 0.2 rem** for **person-name** will fix this issue. anyhow Need UX input on this
This is a reasonable solution.
