### ISSUE TITLE
Alert view has no bottom border is causing visual defect

### ISSUE THREAD

**Issue by FloraChenCerner** [cerner/terra-core#2844]
# Bug Report

## Description

When we have header or alert view stacked under an alert view, there's no separator between them. 
## Steps to Reproduce

Create two stacked alert view.

or

 Add a header view under an alert view

## Additional Context / Screenshots

Two alerts stacking vertically:
![conditions_two_alerts](https://user-images.githubusercontent.com/43655107/74551019-0c285280-4f18-11ea-80e5-3412aee44118.png)

Alert with header (See chronic no recorded and allergies part):
![screenshot-1](https://user-images.githubusercontent.com/43655107/74551038-15192400-4f18-11ea-855e-bffe11a8f318.png)

## Expected Behavior

There should be a bottom border for alert view in above scenario.
## Possible Solution

This issue may occur with a variety of scenarios, as long as the component beneath alert view has same color and doesn't have a top border. We can add the alert to a list with bottom border only and no padding, but it seems hacky and brings in extra dependencies.

  The bottom border should be an option of alert view to avoid this issue.

## Environment

* Component Name and Version: terra-alert 4.20
* Browser Name and Version: Any
* Node/npm Version: [e.g. Node 8/npm 5] 
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by ShettyAkarsh** [comment]
I am not sure here whether this is an valid scenario for using alerts. @FloraChenCerner could you explain here your workflow. like why are you using the alerts this way. 

cc. @neilpfeiffer

**Comment by FloraChenCerner** [comment]
@ShettyAkarsh We are requested by SD and UX to show the alert under the header of a component when there is no chronic problem recorded in the Problem summary. Another case is when Allergies not recorded in the allergies component. If there's other alerts need to be shown we stack them under the header. Most components in our app are following this pattern to show the alert inside a component. No matter where the alert is placed, as long as there's a component that has the same color and no top border underneath it, it will have this issue, so it's not necessarily the case as how we are using the alert in our components.

**Comment by nramamurth** [comment]
@FloraChenCerner, thank you. That sounds like a legit concern to me but I'd defer this to the UX team to decide how this should be handled. 

cc / @neilpfeiffer @jeremyfuksa
