### ISSUE TITLE
[terra-table] Add overflow: hidden to cell

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#2854]
# Feature Request
Add css attribute overflow: hidden to terra-table's Cell.

## Description
In order to allow for a great number of content types, images, truncation etc, if a overflow:hidden; is added to the outer cell teams will need to set fewer custom styles when altering cell behavior from text wrapping.

## @ Mentions
@neilpfeiffer

**Comment by dkasper-was-taken** [comment]
The "container" class on the cell should also include 100% width, this allows for padding and flew nesting within cells.

**Comment by neilpfeiffer** [comment]
@dkasper-was-taken - is this where we also should add a first-class prop for cell truncation, making it easier for consumers to implement without having to add their own css class?

**Comment by dkasper-was-taken** [comment]
@neilpfeiffer  Nah, not quite that much work, this is where we just need the constraint of overflow: hidden, otherwise truncation won't work even if they setup they inner content to truncate. This fix would also address embedding other flex elements inside a cell, such as the cell grid.
