### ISSUE TITLE
[terra-paginator] Cosmetic effects of text wrapping

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#2855]
## Description

At certain dimensions the Paginator text wrapping can be aggressive. We should get UX feedback on the best way to handle this scenario.

![image](https://user-images.githubusercontent.com/6720991/74975978-8a3f9a00-53ed-11ea-9e04-8b4279a253d5.png)

## Steps to Reproduce

1. Navigate to the terra-ui Paginator [example page](https://engineering.cerner.com/terra-ui/components/terra-paginator/paginator/paginator-controlled).
2. Slowly resize the window while observing the Paginator example. 
3. Once the text wraps  observe the visual state of the component.
4. Navigating to double digit page numbers will exaggerate the effect.

## Expected Behavior

We should reach out to UX and discuss what the expected behavior should be.

**Comment by saket2403** [comment]
Removing `overflow-wrap` [here](https://github.com/cerner/terra-core/blob/master/packages/terra-paginator/src/Paginator.module.scss#L36) seems to work fine.
Your thoughts, cc @neilpfeiffer .

**Comment by ryanthemanuel** [comment]
After having discussions with @neilpfeiffer about the history of this component, we've decided that this is not a bug.  This was determined acceptable behavior when it was originally created.  I'd like to change this project into an enhancement with some UX guidance on what the proper way to fix all permutations of small screen sizes.  Possibly something similar to collapsible menu.
