### ISSUE TITLE
[terra-toggle] Update animation to ease-out

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2890]
# Feature Request
Petition to update the animation on terra-toggle from `linear` to `ease-out`. 

> Easing out is typically the best for user interface work, because the fast start gives your animations a feeling of responsiveness, while still allowing for a natural slowdown at the end.

https://developers.google.com/web/fundamentals/design-and-ux/animations/the-basics-of-easing?hl=en

**Comment by neilpfeiffer** [comment]
Fine by UX, no blocks, anyone is free to add this enhancement and submit a PR.

**Comment by manjusr** [comment]
I intend to work on this enhancement, update terra-toggle animation to ease-out and submit a PR once done.
