### ISSUE TITLE
[terra-button] Hover highlight enabled after click on mobile devices

### ISSUE THREAD

**Issue by naveenajain** [cerner/terra-core#2891]
# Bug Report

## Description
After clicking a button, the button displays as though it is hovered on mobile devices.

## Steps to Reproduce
This behavior is reproducible using the button"variant example on the [documentation page](https://engineering.cerner.com/terra-ui/components/terra-button/button/button) on mobile.
1. Click on Button with "Neutral" text on it.
2. Button remains highlighted with hover effect.

## Expected Behavior
If button is clicked on mobile device I would expect it to remove the hover effect after click.

## Environment
* Component Name and Version: terra-button
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): mobile

## @ Mentions
@StephenEsser

**Comment by RLRickard** [comment]
I wonder if this could be resolved in a similar way as https://github.com/cerner/terra-core/pull/2332 - perhaps extended to any component with a hover style.

**Comment by mjhenkes** [comment]
Before working on this wait for instructions from @neilpfeiffer
