### ISSUE TITLE
[terra-form-input] Numeric Input Behaves Incorrectly in MS Edge and IE 11

### ISSUE THREAD

**Issue by jeremyfuksa** [cerner/terra-core#2897]
# Bug Report

## Description
In Microsoft browsers, the numeric input seems to behave like a clearable text input.

## Steps to Reproduce

1. Use a numeric input.
2. Observe the behavior.

## Additional Context / Screenshots
![Screen Shot 2020-03-09 at 11 22 11 AM](https://user-images.githubusercontent.com/726351/76239909-555e8000-6200-11ea-8dd8-bf1ae07a410a.png)

## Expected Behavior
See screenshot.

## Environment

* Component Name and Version: terra-form-input v2.35.0
* Browser Name and Version: Microsoft Edge, IE 11
* Operating System and version (desktop or mobile): Windows

**Comment by ryanthemanuel** [comment]
This is native behavior to Edge.  We can't fix this unless (and until) we get a first class numeric component.
