### ISSUE TITLE
[terra-toggle-section-header] Add isOpen prop

### ISSUE THREAD

**Issue by tc043946** [cerner/terra-core#2905]
# Feature Request

## Description
Add an isOpen prop to toggle-section-header so that it can be programmatically opened and closed.

## @ Mentions
@mjhenkes recommended opening an issue.

**Comment by ShettyAkarsh** [comment]
Currently this control can be open and closed only during the click action. there is a prop [isInitiallyOpen](https://github.com/cerner/terra-core/blob/master/packages/terra-toggle-section-header/src/ToggleSectionHeader.jsx#L41).  to make this open during initial rendering.  not sure whether this issue logged was taken into account during the initial [design](https://github.com/cerner/terra-core/issues/1322) of this component tor not.  adding @neilpfeiffer  from UX to share his thoughts on this ?
