### ISSUE TITLE
[terra-form-select] Add additional documentation for isTouchAccessible 

### ISSUE THREAD

**Issue by saigorantla** [cerner/terra-core#2913]
# Bug Report
select component doesn't display dropdown when placed in card body if the variant is anything else other than default.

## Description
select component doesn't display dropdown when placed in card body if the variant is anything else other than default.

## Steps to Reproduce
* Place a select component in card body with variant other than default like search , multiselect
[code to reproduce ](https://gist.github.com/saigorantla/2317ab7f33f9f18e098c351eb38f155d)

## Additional Context / Screenshots

![Screen-Recording-2020-03-29-at-1](https://user-images.githubusercontent.com/8334184/77853219-9d8e1400-71a8-11ea-92d5-c651f2c4175d.gif)

## Expected Behavior
all select components should behave like default select

## Possible Solution
increase z-Index

## Environment
    "terra-card": "3.26.0"
    "terra-grid": "6.17.0",
    "terra-spacer": "3.26.0",

**Comment by StephenEsser** [comment]
Hi @saigorantla 

The `isTouchAccessible` prop renders the the dropdown absolutely positioned relative to the frame of the component inline with the dom elements. 

 > isTouchAccessible - Ensure accessibility on touch devices. Will render the dropdown menu in normal DOM flow with position absolute. By default, the menu renders in a portal, which is inaccessible on touch devices. Only applicable to variants that include an input (e.g. combobox, multiple, search, and tag).

This is not an issue that can be resolved with the z-index. When using the `isTouchAccessible` prop the Select cannot/should not be placed within a container that has an overflow set to hidden. If the Select must go into a container that has an overflow the isTouchAccessible prop will need to be false so the dropdown renders in a portal.

**Comment by StephenEsser** [comment]
@saigorantla I'm going to use this issue to add additional documentation for the isTouchAccessible prop for each of the variants it applies to. The documentation is intended to describe the behavior/caveats regarding inline/clipping/hidden overflow. Do you have any questions related to this issue or my previous comment above?

**Comment by saigorantla** [comment]
@StephenEsser  That works thank you, can you add what would be ideal Z-index to use for touch accessible.

**Comment by StephenEsser** [comment]
Hey @saigorantla, unfortunately this issue cannot be fixed by adjusting the z-index. When using the `isTouchAccessible` prop the dropdown will always clip if placed within a container with a hidden overflow. The terra-card has a hidden overflow:

https://github.com/cerner/terra-core/blob/master/packages/terra-card/src/Card.module.scss#L7

**Comment by saigorantla** [comment]
so if we have to use isTouchAccessible with terra-card its not possible.

Why I am in this scenario is that terra-card is the only component I am aware of to group components visually. @StephenEsser let me know if there is any other existing component to represent grouping that might solve the issue. 

If not we might have to create new component for grouping or see an alternative to overflow in terra-card.

**Comment by StephenEsser** [comment]
The issue auto-closed once the PR for the documentation updates were merged. Please feel free to make a post internally to the Terra/UX Support Microsoft Teams channel so we can get some UX feedback on the designs you're creating.
