### ISSUE TITLE
Button with Focus loses Focus style on revisiting from different window.

### ISSUE THREAD

**Issue by gerard-isdell** [cerner/terra-core#2919]
# Bug Report

## Description

When I'm using keyboard navigation to tab onto buttons in a ButtonGroup, the highlighted button loses the highlight on the right hand side of the button when in switch to and the back from another application, or another browser tab.
(This is happening in Safari and Chrome on Mac)

<img width="1044" alt="Screenshot 2020-04-06 at 14 22 50" src="https://user-images.githubusercontent.com/16339189/78650847-6362f780-78b7-11ea-92b9-5a4801dceb85.png">

I originally posted about this [on teams](https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1586179701283?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1586179701283&teamName=Terra&channelName=Component%20Support&createdTime=1586179701283)

## Steps to Reproduce

1. Open [this page](https://engineering.cerner.com/terra-core/components/terra-button-group/button-group/button-group)
2. Tab onto the Button Group example "ButtonGroup Is Block - width stretches to fill container"
3. With the first button highlighted, Cmd + tab to switch to another application and again to switch back
4. The highlight will be missing from one of the edges

## Expected Behavior
The button should retain the highlight around all 4 sides of the button

## Environment

* Component Name and Version: ButtonBroup.Button
* Browser Name and Version: Safari and Chrome on Mac
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Mac desktop

## @ Mentions

@supreethmr

**Comment by ShettyAkarsh** [comment]
I am not sure whether this is an issue. seems to be default behavior when two buttons get clubbed together because of the right  button border taking more precedence.

This is the same behavior in [html button group](https://www.w3schools.com/howto/howto_css_button_group.asp) as well.

cc. @neilpfeiffer , @StephenEsser

**Comment by supreethmr** [comment]
I was able to recreate this on dev-site. focus styles of selected button was being removed on opening new window and revisiting the dev-site. 

![button-group-focus-issue](https://user-images.githubusercontent.com/12869809/79228150-9c363a00-7e7e-11ea-871f-ebe93b698d9b.gif)

we can also on dom element `isFocused` class gets removed from selected button on changing the window but it stays on unselected button even on opening new window.

![button-group-focus-issue](https://user-images.githubusercontent.com/12869809/79226512-2335e300-7e7c-11ea-80aa-a18ee476ab7f.gif)

it looks like for unselected button `is-focused` class adds focus styles whereas for selected button focus styles were being added by class `is-selected.is-focused` which is defined [here](https://github.com/cerner/terra-core/blob/18398f46e66db2e21c7546266e801c8d8e40b3b3/packages/terra-button-group/src/ButtonGroup.module.scss#L46). Needs further investigations for the fix.
