### ISSUE TITLE
Add onRequestClose prop to Modal to ensure state is driven purely by consuming components

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#293]
### Description of Issue

The primary issue is the calling of `closePortal` here: https://github.com/cerner/terra-core/blob/master/packages/terra-modal/src/ModalContent.jsx#L54

The Modal component itself should be stateless; it has an isOpened prop that is used to open and close the modal.  However, the `closePortal` function that is provided by the Portal (and called in the linked code above) closes the Portal (and therefore Modal) without notifying the component that is rendering the Modal of that closure. This leaves the consuming component's state in a weird spot.

Instead of using `closePortal` for our escape/outside click handling, we should have an `onRequestClose` prop that we call instead that consumers must set.  With this, the Modal consumer is in complete control of the Modal state. This is similar to how the `react-modal` works: https://reactcommunity.org/react-modal/examples/on_request_close.html

```
class ModalPresenter extends React.Component {
  openModal() {
    this.setState({ isOpen: true });
  }

  closeModal() {
    this.setState({ isOpen: false });
  }

  render () {
    return (
      <div>
        <button onClick={this.openModal}>Open Modal</button>
        <Modal
          isOpened={this.state.isOpen}
          onRequestClose={this.closeModal}
        >
          <div>Stuff</div>
          <button onClick={this.closeModal}>Close Modal</button>
        </Modal>
      </div>
    )
  }
}
```

### Expected Outcomes
- The Modal and internal components are completely stateless.

**Comment by Matt-Butler** [comment]
Good catch on this @tbiethman 

Here is a demonstration of the issue:
![modalstate](https://cloud.githubusercontent.com/assets/8146159/25663348/0a24a13a-2fdd-11e7-934b-695c52c872b9.gif)

In this example, the user provides methods to handle the isOpened state.
```
  handleOpenModal() {
    this.setState({ isOpened: true });
  }

  handleCloseModal() {
    this.setState({ isOpened: false });
  }

<button onClick={this.handleOpenModal}>Open Modal</button>
<button onClick={this.handleCloseModal}>Close Modal</button>
```
When we use the open and close buttons, the behavior is as expected.
![expected](https://cloud.githubusercontent.com/assets/8146159/25663472/6953bea2-2fdd-11e7-907c-4b29b7f7ad5b.gif)


However, when using the props `closeOnEsc` and `closeOnOutsideClick`, they do not modify the isOpened state.
![incorrect_behavior](https://cloud.githubusercontent.com/assets/8146159/25663659/e3780b7a-2fdd-11e7-850f-bde29c975832.gif)

**Comment by Matt-Butler** [comment]
With the current implementation, we could require a consumer to use the onClose prop to set the state to false when closing. 
```
handleCloseModal() {
  this.setState({ isOpened: false });
}

onClose={this.handleCloseModal}
```

However, I agree with approach @tbiethman recommended.  Instead of react-portal handling esc & closeOnOutsideClick, the user should be in control of the state and what happens for those events.

**Comment by Matt-Butler** [comment]
Spoke with @tbiethman 

The first thing to try out:
1) Don't use the closePortal method here:
https://github.com/cerner/terra-core/blob/master/packages/terra-modal/src/ModalContent.jsx#L54

Instead, use an onRequestClose prop provided by the user which would update the state.

2) Add a key listener to the Modal component. When the `esc` key is pressed, call onRequest close.
Add the key listener in a componentDidMount function.
https://github.com/cerner/terra-core/blob/master/packages/terra-modal/src/Modal.jsx#L83

We would not use react-portal for the closeOnOutsideClick and closeOnEsc functionality.
