### ISSUE TITLE
[terra-action-header] Additional line-height added from foundation stylesheet

### ISSUE THREAD

**Issue by tarunkolla** [cerner/terra-core#2931]
# Bug Report

## Description

We are using Terra action header for our component to have a banner bar with Collapsable Menu view and this is being consumed by a rails server. Just the component by itself works great with no issues but when this is pulled into the server we use the `base` layout from `orion/orion-rails-layouts` that adds a foundation.css stylesheet. (This doesn't get added for `application_layout`)

This file has additional styles added which have a `line-height: 50px` added to `<h1/>` and `<h2/>` tags and `line-height: 20px` for `<h3/>`, `<h4/>`, `<h5/>` and `<h6/>`. 

The following is the layout:

*application.html.haml* 
```
= render layout: 'orion/rails/layouts/base' do
  = yield
```

*index.html.haml*
```
- content_for :title do
 Title

- content_for :webpack_style do
  = stylesheet_webpack_tag 'orion-common-bundle'
  = stylesheet_webpack_tag 'action-header-component'

- content_for :webpack_javascript do
  = javascript_webpack_tag 'orion-common-bundle'
  = javascript_webpack_tag 'action-header-component'

- content_for :root do
  = react_component('ActionHeaderComponent')
```

## Steps to Reproduce

1. Consuming a terra action header with the base layout from Orion should reproduce it.

## Additional Context / Screenshots

Screenshot of action header from the rails server:
<img width="720" alt="line-height:50px" src="https://user-images.githubusercontent.com/35357999/79690478-318b5280-8220-11ea-9cfc-a3151530ea81.png">

Screenshot of the styles:
<img width="720" alt="styles that get added" src="https://user-images.githubusercontent.com/35357999/79690467-22a4a000-8220-11ea-8522-a99a465602a6.png">

## Expected Behavior

Screenshot from terra action header dev site:
![screenshot from terra dev site](https://user-images.githubusercontent.com/35357999/79691128-71a00480-8223-11ea-89f0-2dd36ac23e96.png)

I assume we don't want to have additional style added to from the server-side to components that would make them look different.
I did notice other parts of the component having less noticeable style changes. 

## Possible Solution

We also use Terra Clinical Header in the same application but these styles are overridden as clinical header has `line-height` of its own. 

I could have this work as expected with `line-height: unset` but this may not be a good way to fix it. (As this is adding styles to any `<h1/>` tag)

Adding props `level={3}` or lower makes this less noticeable but still has a bit of height added. And this is just a way around for now and the prop is not meant for this purpose according to the dev site.

## Environment

* Component Name and Version: terra-action-header v2.42.0
* Browser Name and Version: Chrome v80
* Node/npm Version: [e.g. Node 8/npm 5] node 10.19.0, npm 6.13.4 
* Webpack Version: 3.6.0
* Operating System and version (desktop or mobile): desktop

## @ Mentions

@nramamurth @Berkyle @ATBull81

## Other
* Possibly related: https://github.com/cerner/terra-core/issues/1783
* More info: [#41](https://github.cerner.com/cerner-video/cerner-video-banner-component/issues/41) (Will have additional description added here)

**Comment by ryanthemanuel** [comment]
@tarunkolla this is more of an internal issue so closing it.  My recommendation is to use the application_layout (as base is deprecated along with terra-rails-view_models).  If you need additional assistance with this, reach out on Teams or log a JIRA to UXPLATFORM.
