### ISSUE TITLE
[terra-demographics-banner] Uplift to the controlled responsive element

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2962]
# Feature Request

## Description
Investigate uplifting the terra-demographics-banner onto the controlled responsive element or alternative. 

## Description

The uncontrolled responsive element has been [flagged for deprecation](https://github.com/cerner/terra-core/pull/2729). The terra-demographics-banner should either be uplifting onto the controlled responsive element implementation or alternatively the responsive element should be removed from the component.

**Comment by StephenEsser** [comment]
Duplicate of https://github.com/cerner/terra-core/issues/2673. These issues can probably be merged into a single issue

**Comment by ryanthemanuel** [comment]
Closing this as duplicate of #2673
