### ISSUE TITLE
[terra-table] Single selectable table header row screen reader accessibility issue

### ISSUE THREAD

**Issue by SpandanaEdara** [cerner/terra-core#2967]
# Bug Report
## Description
When focus is on terra table(single selection) header row and voice over on, header row checkbox(invisible) is supposed to be dimmed(/unselectable) but screen reader is reading "single selection, unchecked, checkbox column 1 of 3. To select this click option+control+space". This error occurs even when isDisabled prop set to true for header.

## Steps to Reproduce
1. With screen reader on, focus on header row of single selectable table example https://engineering.cerner.com/terra-ui/components/terra-table/table/guides/single-select-table
2. Use the above example and set isDisabled prop to true for headerData,
       selectAllColumn: {
              checkLabel: 'Single Selection',
              isDisabled: true,
            }

## Additional Context / Screenshots
<img width="1675" alt="1" src="https://user-images.githubusercontent.com/65313639/81867711-c5f28780-9536-11ea-9c60-b94c51d9060d.png">
<img width="1672" alt="2" src="https://user-images.githubusercontent.com/65313639/81867724-cc80ff00-9536-11ea-9b90-76cb25c54e67.png">

## Expected Behavior
Screen reader should read following or some more descriptive statement for header row. 
> "single selection, unchecked, checkbox, dimmed column 1 of 3. "

## Possible Solution
Seems like isDisabled prop is only spread to attribute that are visible.

## Environment
* Component Name and Version: Table/ terra-table 4.7.0
* Browser Name and Version: safari
* Operating System and version (desktop or mobile): Mac

**Comment by lokesh-0813** [comment]
Apparently the isDisabled property is applied to the checkbox only if it is intractable(i,e selectable). The checkbox becomes selectable only upon providing checkStyle="toggle" and providing an onCheckAction function.

We could tweak the visually hidden content fed to the screenreaders to set role="checkbox" only if the checkbox is intractable. 

@dkasper-was-taken  any thoughts?
