### ISSUE TITLE
Adding Subheaders to the Table component

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-core#298]
# Issue Description
We are in need of Subheaders being implemented into the existing Table component. This would be built into the existing Table component to separate rows of the table into sub-lists.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Needs definition

## Current Behavior
N/A

**Comment by bjankord** [comment]
Code review and UX/Functional review is complete. We want to hold off on merging this into master until #392 is ready as well.

**Comment by bjankord** [comment]
#392 has been merged down to master. I plan to release terra-table tomorrow with this update and updates from #392.

**Comment by bjankord** [comment]
This has been released in terra-table@0.5.0.
