### ISSUE TITLE
Look into making it easier for users to log issue.

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#299]
# Issue Description
Some of our consumers do not have public GitHub accounts and do not want to create them. This issue is to explore what options we have to make it easier for them to log issues. We should check out https://gitreports.com/

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Users who do not wish to create a GitHub account have a way to log issues to our repo.

## Current Behavior
Users required to have a GitHub account log issues to Github repo.

**Comment by JakeLaCombe** [comment]
I've used it on another project on Github. This is the output of using github reports. https://github.com/codeforkansascity/Neighborhood-Dashboard/issues/109

Another possibility is to create a google spreadsheet with an authenticity token, and use that when you submit the form. 

https://gist.github.com/bmcbride/62600e48274961819084

**Comment by mjhenkes** [comment]
I'm of the opinion to keep it simple and just require a public github account to log issues. They're free and if it's a consumer we know and want to facilitate, we can log the issue ourselves.
