### ISSUE TITLE
Radiobutton select functionality through space key not working.

### ISSUE THREAD

**Issue by bimbitha** [cerner/terra-core#2991]
# Bug Report

## Description
Radiobutton select functionality through space key not working.

## Steps to Reproduce
While investigating, we figured out that in the product, the functionality to select radio button with space key is not working. Not just radio button, normal buttons are also not getting selected with space key even though focus is there.

But, the behavior is different when we execute the code  in different browsers. For browsers like Internet Explorer and Microsoft Edge, the tabs and selection through space bar is happening fine. But, in Google Chrome, the radio button is not getting selected on pressing space key, also, the tab is not working fine while navigating from one radio button to another. 

So, the functionality is working fine technically on some browsers. We need to get more light on how the keyboard actions can get more compatible.

**Comment by StephenEsser** [comment]
@bimbitha I did some initial testing using the [terra-ui](https://engineering.cerner.com/terra-core/components/terra-button/button/button) documentation site. Space is working as expected to make a selection for both terra-button and terra-form-radio buttons when using Google chrome.

Can you provide a reduced test case and steps to reproduce the issue you are seeing? If possible, please use the terra-ui site or codesandbox to create an example. This ensures any issues presented are isolated away from the application implementation and our team will be able to reproduce them.

While testing, please compare/reference the expected functionality/interactions to the native input examples.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_radio
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

**Comment by yuderekyu** [comment]
> But, in Google Chrome, the radio button is not getting selected on pressing space key, also, the tab is not working fine while navigating from one radio button to another

Can you clarify this? If the radio buttons are in a group, they function as single element. This means that tabbing will move focus to another element, rather than cycling through radio buttons within a group.

https://www.w3.org/wiki/RadioButton

**Comment by ryanthemanuel** [comment]
Closing this as we believe this is working as expected. Please reach out to one of us in the teams channel or in office hours if you have further questions.
