### ISSUE TITLE
[terra-form-input] Insufficient color-contrast for placeholder

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#2992]
# Bug Report

## Description
The placeholder color in terra-form-input and terra-form-textarea is [rgba(25, 32, 35, 0.53)](https://github.com/cerner/terra-core/blob/fac7744f171f4336c980791547a61caa54878962/packages/terra-form-input/src/Input.module.scss#L26). The equivalent hex color of this is `#85898a`. This color on a white background does not meet the minimum color contrast ratio of `4.5:1`. 

The placeholder color in terra-form-select is [rgba(21, 33, 41, 0.61)](https://github.com/cerner/terra-core/blob/fac7744f171f4336c980791547a61caa54878962/packages/terra-form-select/src/shared/_Frame.module.scss#L243). The equivalent hex color of this is `#70777d` and this has a contrast ratio of `4.54 : 1` and is sufficient.

terra-form-input and terra-form-textarea should match terra-form-select to be consistent and meet the contrast ratio. What is unknown is Chrome/FF does not complain about the insufficient color contrast. IE seems to be the only browser able to truly detect the insufficient color contrast.

There are plans in the near future to get rid of placeholders. Until then, we should use a darker placeholder color to provide sufficient color contrast.

## Steps to Reproduce
1. Many online rgba to hex color converters do not take the opacity into account. 
2. Go to https://cssgenerator.org/rgba-and-hex-color-generator.html and enter the rgba values.
3. Take a screenshot of the generated color.
4. Update the screenshot to https://imagecolorpicker.com/en/.
5. The hex color of `#85898a` should be returned.
6. Go to https://dequeuniversity.com/rules/axe/3.5/color-contrast?application=axeAPI and enter `#85898a` as the foreground color and `#ffffff` as the background color.
7. Note that a contrast ratio of `3.53 : 1` does not meet the minimum ratio of `4.5:1`.

## Additional Context / Screenshots

```
1) [enormous] Onset Picker has [date granularity] [default] is accessible and is within the mismatch tolerance:
expected no accessibility violations but got:
	{
  "description": "Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds",
  "help": "Elements must have sufficient color contrast",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.5/color-contrast?application=axeAPI",
  "id": "color-contrast",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": {
            "bgColor": "#ffffff",
            "contrastRatio": 3.53,
            "expectedContrastRatio": "4.5:1",
            "fgColor": "#85898a",
            "fontSize": "11.9pt (15.86px)",
            "fontWeight": "normal",
            "messageKey": null
          },
          "id": "color-contrast",
          "impact": "serious",
          "message": "Element has insufficient color contrast of 3.53 (foreground color: #85898a, background color: #ffffff, font size: 11.9pt (15.86px), font weight: normal). Expected contrast ratio of 4.5:1",
          "relatedNodes": [
            {
              "html": "<input name=\"terra-date-test-date-input\" class=\"Input-module__form-input___2z_wq DatePicker-module__input___3vYbH\" aria-labelledby=\"test-date-input-label\" aria-label=\"Date\" type=\"text\" placeholder=\"MM/DD/YYYY\" value=\"\">",
              "target": [
                ".Input-module__form-input___2z_wq"
              ]
            }
          ]
        }
      ],
      "failureSummary": "Fix any of the following:\n  Element has insufficient color contrast of 3.53 (foreground color: #85898a, background color: #ffffff, font size: 11.9pt (15.86px), font weight: normal). Expected contrast ratio of 4.5:1",
      "html": "<input name=\"terra-date-test-date-input\" class=\"Input-module__form-input___2z_wq DatePicker-module__input___3vYbH\" aria-labelledby=\"test-date-input-label\" aria-label=\"Date\" type=\"text\" placeholder=\"MM/DD/YYYY\" value=\"\">",
      "impact": "serious",
      "none": [],
      "target": [
        ".Input-module__form-input___2z_wq"
      ]
    }
  ],
  "tags": [
    "cat.color",
    "wcag2aa",
    "wcag143"
  ]
}
```

## Environment

* Component Name and Version:
* Browser Name and Version: IE
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by benbcai** [comment]
Increasing the darkness of the placeholder color to meet the minimum contrast ratio is not recommended because doing so makes the placeholder values appear as entered text. According to https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research the use of placeholder is generally not recommended.

The long term plan is to remove placeholder values in all terra components. The short term solution to get around this error for now are either:

1. Ignore the `color-contrast` axe rule for any test showing placeholders.
```
const ignoreColorContrastRule = { 'color-contrast': { enabled: false } };
Terra.it.validatesElement({ rules: ignoreColorContrastRule });
```
2. If feasible, add an empty space to the input to hide the placeholder.
3. Do not run tests with placeholders in IE.

**Comment by neilpfeiffer** [comment]
_(02/Jun/2020) Outcome from today's UX component review:_

Darkening placeholders to pass at `4.50:1` ratio will create usability risk of a user mis-perceiving the placeholder as an actual value, paired with existing recommendations from Cerner A11Y that placeholders are not fully accessible for all assistive technology [(#2808)](https://github.com/cerner/terra-core/issues/2808#issuecomment-578585186), determination was made to MVB and remove placeholders from the various form elements. 

Before beginning -- additional UX guidance needs to be provided here for each component prior to fixing. Current audit of components that implement placeholders include:
- terra-form-input
- terra-form-text-area
- terra-form-select (and similar variants)
- terra-date-input
- terra-date-picker
- terra-time-input
- terra-search-field

cc: @jeremyfuksa

**Comment by neilpfeiffer** [comment]
Directions for alterations for:
- terra-form-input 
- terra-form-input/lib/InputField
- terra-form-textarea/
- terra-form-textarea/lib/TextareaField

---
- [ ] Remove the `placeholder` from the props table and available propTypes for all components 
- [ ] Remove the css styles and variables for the `::placeholder` and `[disabled]::placeholder`
- [ ] Will need to keep logic that if a user provides the html native placeholder attribute, that it explicitly not be added at all and props spreading will not pass it through
- [ ] Add major version Upgrade Guide that includes these comments:
_TODO_ add the language needed for the accessibility and human factors guidance switching from consumers providing placeholders to providing more detailed help text with Field compositions.
- [ ] Will need to test all other Terra components that imports the terra-form-input component directly and make sure downstream effects for their placeholders are correctly handled.

**Comment by neilpfeiffer** [comment]
Alteration directions for:
- terra-date-input
- terra-date-input/lib/DateInputField
- terra-date-picker
- terra-date-picker/lib/DatePickerField
- terra-time-input
- terra-date-time-picker

---
- [ ] The strings (the localized letter abbreviation date/time format masks, e.g. ) that are provided to the text inputs and the `placeholder` prop/html attributes need to be removed. The Date-Input component should remove "Month" as the placeholder text in the select and the text "- Select -" should be used instead to match the form-select components.
- [ ] For each of the base components (non-Field compositions), a new element that matches the styling of the help text prop in terra-form-field needs to be added, and localized letter abbreviation date/time format masks originally put in the placeholder (`MM/DD/YYYY`, `hh:mm:ss`, `Month DD, YYYY`)  is now given to the help text placement 
- [ ] For the component that do not have Field compositions (Time-Input and Date-Time-Picker) need to add Field compositions. All the Field compositions need to remove the help text of the format letter abbreviation masks in the stand-alone/imported inputs, and need to supply the text to the actual `help` prop.  Format notes: If no additional help text is provided, the help text is only the provided format mask e.g. `MM/DD/YYYY`. If additional help text is provided, the format mask should be supplied first at `(MM/DD/YYYY)` followed by a space, followed by the text given to the `help` prop.
- [ ] Remove any css styles and variables for the placeholder in the input elements (exception for Date-Input which will keep the "- Select -" placeholder in the dropdown select).
- [ ] Add major version Upgrade Guide that includes these comments:
_TODO_ add the language needed for the accessibility and human factors guidance switching from consumers providing placeholders to providing more detailed help text with Field compositions.

**Comment by neilpfeiffer** [comment]
Alteration directions for:

- terra-form-select
- terra-form-select/lib/SelectField
- terra-form-select/lib/SingleSelect
- terra-form-select/lib/SingleSelectField
- terra-form-select/lib/Combobox
- terra-form-select/lib/ComboboxField
- terra-form-select/lib/MultiSelect
- terra-form-select/lib/MultiSelectField
- terra-form-select/lib/TagSelect
- terra-form-select/lib/TagSelectField
- terra-form-select/lib/SearchSelect
- terra-form-select/lib/SearchSelectField

---
- [ ] All forms of select: remove the `placeholder` prop that allows consumers to customize the placeholder text
- [ ] All forms of select: the default text given to the component as the placeholder is `- Select -`
- [ ] `allowClear` is still allowed and available as a prop for those that already have it.
- [ ] Theming changes:
**Default theme:**
placeholder color:  _TODO:ux-check-if-needs-to-be-updated_
placeholder font-style: `italic`
disabled placeholder color: _TODO:ux-check-if-needs-to-be-updated_
**Fusion theme:**
placeholder color:  _TODO:ux-check-if-needs-to-be-updated_
placeholder font-style: `normal`
disabled placeholder color: _TODO:ux-check-if-needs-to-be-updated_
**Lowlight theme:**
placeholder color:  _TODO:ux-check-if-needs-to-be-updated_
placeholder font-style: `italic`
disabled placeholder color: _TODO:ux-check-if-needs-to-be-updated_
- [ ] Add major version Upgrade Guide that includes these comments:
_TODO_ add the language needed for the accessibility and human factors guidance switching from consumers providing placeholders to providing more detailed help text with Field compositions.

**Comment by neilpfeiffer** [comment]
Alteration directions for:

- terra-search-field

---
- [ ] API currently stays the same
- [ ] Theming changes:
**Default theme:**
placeholder color:  _TODO:ux-check-if-needs-to-be-updated_
placeholder font-style: `italic`
disabled placeholder color: _TODO:ux-check-if-needs-to-be-updated_
**Fusion theme:**
placeholder color:  _TODO:ux-check-if-needs-to-be-updated_
placeholder font-style: `normal`
disabled placeholder color: _TODO:ux-check-if-needs-to-be-updated_
**Lowlight theme:**
placeholder color:  _TODO:ux-check-if-needs-to-be-updated_
placeholder font-style: `italic`
disabled placeholder color: _TODO:ux-check-if-needs-to-be-updated_
- [ ] Add major version Upgrade Guide that includes these comments:
_TODO_ add the language needed for the accessibility and human factors guidance switching from consumers providing placeholders to providing more detailed help text with Field compositions.
