### ISSUE TITLE
Terra Arrange component's flex values are not working in IE11. 

### ISSUE THREAD

**Issue by KM050466** [cerner/terra-core#3027]
# Bug Report

## Description

I am using Terra Arrange component in my application. When I resize the window, contents inside the arrange components are not responsive in IE 11 browser for smaller viewports. I investigated further and found out that flex values of '1 1 auto' for the 'fill' prop is not working in IE11. However these values are working fine with other browsers like chrome and safari also contents inside are responsive.

Kindly look into this issue and fix asap.

## Steps to Reproduce

1.Create Arrange component with some content inside with fill prop.
<Arrange
      fill={(
          <Header
            startContent={(
                Content1
            )}
            endContent={(
                Content2
           )}
        />
 />
2. Load in ie 11. Resize the window.
3. Observe that contents(e.g Content2) inside Arrange components are not responsive

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/66681316/84172875-1f989400-aa9a-11ea-95a0-caf05659ee3f.png)
![image](https://user-images.githubusercontent.com/66681316/84172887-258e7500-aa9a-11ea-8f58-9c97db3cda2c.png)

## Expected Behavior

contents inside Arrange component with fill prop should be responsive on resizing the window in IE11.

## Possible Solution

Change fill prop's flex value such that it should be compatible for IE 11 as well.

## Environment

* Component Name and Version: 'terra-arrange' latest version
* Browser Name and Version: IE 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version: v4.41.5
* Operating System and version (desktop or mobile): Windows 10 VM. Desktop

**Comment by KM050466** [comment]
@tbiethman  I tried to remove the custom css as well but I could still see this issue.
What I feel is value being 'auto' to flex-basis isn't working in IE11. 
This is happening only in IE11, but current css works totally fine with chrome or safari.

**Comment by pranav300** [comment]
I couldn't test much on the user application as they have removed arrange from there code. And I cannot run the project locally. But from the local testing, I did not see the `clinical-header or arrange` being unresponsive in IE11.

@KM050466 I believe the issue is due to the usage of older versions of `arrange v^2.29.0` and `clinical-header v^2.11.0`. You can try with the latest versions and let us know if the issue still exists.

**Comment by KM050466** [comment]
@pranav300 I tried with latest versions as you have mentioned in earlier comment, I don't see the issue and it is responsive now. 
Thank you for your help.
