### ISSUE TITLE
Datepicker enforce formatting

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#303]
# Issue Description
When typing data into the datepicker, the component should enforce the format provided by the user. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The datepicker should enforce the format provided by the user. 

## Current Behavior
The datepicker does not enforce format for user entered data. In this example, we have placeholder text for the format of the date input field. 
![dateformatting](https://cloud.githubusercontent.com/assets/8146159/25665258/ad1ff7ea-2fe2-11e7-8840-befa413a1228.gif)

**Comment by Nick-Kroeker** [comment]
Plan needs this as well.

**Comment by bjankord** [comment]
Related: https://github.com/Hacker0x01/react-datepicker/issues/1503

**Comment by Jmacek** [comment]
I would also like some form of input enforcement. It would act similarly to the `pattern` attribute of the `TimePicker` component that only allows a correct date format (probably determined by the locale) as text entry.

**Comment by bjankord** [comment]
Example added of how to add validation to date picker in https://github.com/cerner/terra-framework/pull/442
