### ISSUE TITLE
[terra-form-select] Search variant doesn't take focus on clicking toggle button on mobile

### ISSUE THREAD

**Issue by prmeznar** [cerner/terra-core#3035]
# Bug Report

## Description
I've only tested this in the search variant, but I imagine it exists in other variants as well.

(In 6.8.0) When rendered in mobile, the toggleButton does not open the dropDown, but relies on the handleMouseDown event. This [event](https://github.com/cerner/terra-core/blob/ff8271d46fd2519bc59bd1ad7bd11a718dec326c/packages/terra-form-select/src/search/Frame.jsx#L381) is implemented with a preventDefault call, in order to stop the search input from losing focus.

However, that also stops the select control from ever taking focus in the first place, resulting in opening the dropDown while an entirely different element has focus:

![image](https://user-images.githubusercontent.com/47360296/84538452-4bdd2c00-acb7-11ea-920f-bd6d45396814.png)

This cascades into more significant issues for our application, which relies on onBlur events as indications the user has finished editing some field which we subsequently need to update (the services we call can have logic that needs to run on a per detail basis).

## Steps to Reproduce
Easiest way to see this would be to visit https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/select on a mobile device, and select a component using the drop down. For the first selection, you'll notice that the input box does not get highlighted.

![image](https://user-images.githubusercontent.com/47360296/84539472-146f7f00-acb9-11ea-9da1-8bda3c9b9f1c.png)
![image](https://user-images.githubusercontent.com/47360296/84539540-3963f200-acb9-11ea-887c-bb8fd5cdce9b.png)

You can see the difference in behavior by clicking back and forth between inputs, which will always take focus and close the other input, and then clicking back and forth between drop down arrows, which will often leave both open and not have focus.

## Additional Context / Screenshots
Probably related to #2898 and #2964 

## Expected Behavior
Clicking the drop down arrow should take focus and apply it to the component.

## Possible Solution
Adding 
`if (this.input) {
    this.input.focus();
}`
to onMouseDown before the preventDefault call (after may work as well) seems to fix this issue, as does moving that same snippet outside of the "if (this.state.isOpen)" block in handleToggleButtonMouseDown.

I imagine this would affect accessibility stuff in some way I don't understand though.

## Environment

* Component Name and Version: terra-form-select 6.8.0
* Browser Name and Version: Chrome 83.0.4103.101 (on Android)
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Mobile

**Comment by StephenEsser** [comment]
Thanks for logging this issue @prmeznar. I've done an initial investigation and it appears there are a handful of issues. 

Regarding the focus; on mobile when the arrow is clicked to open the dropdown the input is not supposed to receive focus. The dropdown menu itself is supposed to receive the focus so screen readers can appropriately announce the options in the portaled dropdown.

https://github.com/cerner/terra-core/blob/ff8271d46fd2519bc59bd1ad7bd11a718dec326c/packages/terra-form-select/src/search/Frame.jsx#L264-L276

The 10ms timeout doesn't appear to be working to set the focus, although focus() is called. I was able to get it to work by increasing the timeout to 100ms, however, I think using timeouts in general is part of the issue. 

This is what should be happening, I added a red border to emphasis what has focus when this is working correctly. Notice the input is not focused and there is no keyboard:

![image](https://user-images.githubusercontent.com/6720991/84802654-86500d00-afc6-11ea-8205-d1359887b4fc.png)

On Mobile clicking the toggle arrow should focus the dropdown, clicking the input should focus the input. 

Issues:

1. Clicking the dropdown arrow should focus the menu. It does not currently. 
2. Opening a dropdown menu should close any existing dropdown. It does not currently.

Were there any other issues you noticed that I may have missed?

**Comment by prmeznar** [comment]
No, I think that covers what I was seeing, thanks for the quick investigation.

My hope is that once focus begins being put on the menu we'll get the onBlur event that we depend on. Would it be possible for a snapshot to be put out there whenever the fix is implemented so I could give it a shot?

**Comment by saket2403** [comment]
I was able to fix the multiple dropdown opening issue by making changes similar to PR #2753 . Another issue mentioned was the focus issue, regarding that tried a few approaches : 

- Replaced the timeout by passing callback function to setState to set focus on select menu when opened via toggle button.
- Removed timeout and tried to set focus on selectMenu in componentDidUpdate

But in both the approaches the focus is not getting set on the selectMenu. The only thing that works is increasing the timeout to about 100ms, but that is not what we want.
Any inputs on the approaches @StephenEsser .
Branch link with multiple dropdown fix : [Link](https://github.com/cerner/terra-core/tree/form-select-focus).

**Comment by StephenEsser** [comment]
@saket2403 

I spent a little time looking into this issues. I agree with making the changes to use a dom ref to prevent having duplicate components on the page with the same identifier. 

Regarding the timeouts, to avoid major changes to the component I think increasing the timeout is the safest option. Ideally this component would not rely on timeouts for functionality, but it is existing behavior within the component. 

+1 to increasing the timeout to 100ms if that resolves the issue in all mobile browsers and does not introduce any negative side effects.
