### ISSUE TITLE
Icons for start and stop screen share

### ISSUE THREAD

**Issue by yusufali2205** [cerner/terra-core#3042]
# Feature Request

## Description

Need icons for start and stop screen share. 
For start screen share I'm imagining something like IconSimulation with up arrow on top. 
Ex: ![image](https://user-images.githubusercontent.com/1637467/85183412-36d14180-b251-11ea-81a7-fb687f86333c.png)

For stop screen share I'm imagining something like IconSimulation with IconCancel.

## Additional Context / Screenshots

These icons can be used in a video conferencing application.

**Comment by neilpfeiffer** [comment]
Thanks @yusufali2205 - I just sent you an email with the details of how to log a new icon request to our internal process with Cerner UX.

Closing this issue and will resolve though Cerner's normal open source icon publishing process.
