### ISSUE TITLE
[terra-tag] Missing themeable variable

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#3053]
# Bug Report

The following variables are missing:

**clinical-lowlight-theme**

--terra-tag-padding-top - packages/terra-tag/lib/Tag.module.scss (line: 26, column: 4)

**Comment by jeremyfuksa** [comment]
Base style: `padding-top: var(--terra-tag-padding-top, 0.1428571429rem);`

**Comment by lokesh-0813** [comment]
> Base style: `padding-top: var(--terra-tag-padding-top, 0.1428571429rem);`

This was addressed in the above mentioned PR and is already merged. 

There appears to be a small variation in the suggested and merged value. Let me know if it needs to be changed. 

Suggested Value : 0.1428571429rem

Merged Value      : 0.1428611429rem

**Comment by jeremyfuksa** [comment]
Those two values are negligible. Don't worry about it.

**Comment by emilyrohrbough** [comment]
Resolved in https://github.com/cerner/terra-core/pull/3088
