### ISSUE TITLE
[terra-text] Missing themeable variables

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#3054]
# Bug Report

The following themeable variables are missing:

**clinical-lowlight-theme**

--terra-text-attention-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 14, column: 4)
--terra-text-default-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 10, column: 4)
--terra-text-info-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 22, column: 4)
--terra-text-success-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 18, column: 4)

**orion-fusion-theme**

--terra-text-attention-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 14, column: 4)
--terra-text-default-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 10, column: 4)
--terra-text-info-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 22, column: 4)
--terra-text-success-color - packages/terra-text/lib/terra-dev-site/doc/example/colors.module.scss (line: 18, column: 4)

**Comment by neilpfeiffer** [comment]
For the Lowlight theme:
```
:local {
  .clinical-lowlight-theme {
    --terra-text-v2-font-stack-after-content: '\"Helvetica Neue\", Helvetica, Arial, sans-serif';

    // Used for docsite custom color examples only
    --terra-text-attention-color: #fb4c4c;
    --terra-text-default-color: #6f7477;
    --terra-text-info-color: #5a81ff;
    --terra-text-success-color: #78c346;
  }
}
```

----

For the Fusion theme:
```
:local {
  .orion-fusion-theme {
    --terra-text-v2-font-stack-after-content: 'Tahoma, Geneva, Verdana, \"Trebuchet MS\", sans-serif';

    // Used for docsite custom color examples only 
    --terra-text-attention-color: #c00;
    --terra-text-default-color: #1c1f21;
    --terra-text-info-color: #007cc3;
    --terra-text-success-color: #2e7d32;
  }
}
```

**Comment by emilyrohrbough** [comment]
Resolved in https://github.com/cerner/terra-core/pull/3107
