### ISSUE TITLE
[terra-table] Columns and rows are misaligned for selectable tables.

### ISSUE THREAD

**Issue by dkschoonover** [cerner/terra-core#3076]
# Bug Report

## Description
When rendering a selectable terra-table with version 4.10.0, the first column has additional space that results in the rest of the columns being misaligned with the table content.

## Steps to Reproduce
Bug is reproducible in the selectable terra-table example.

## Additional Context / Screenshots
<img width="1177" alt="Screen Shot 2020-07-14 at 11 40 37 AM" src="https://user-images.githubusercontent.com/28159802/87465329-10958c00-c5da-11ea-98b5-dfba3a092a49.png">

## Expected Behavior
Leftmost column does not have additional left padding.

## Possible Solution
The hidden checkbox appears to be taking up space.  May need to force the width to 0.

## Environment

* Component Name and Version: terra-table 4.10.0
* Browser Name and Version: Chrome/IE
* Node/npm Version: npm 5, node 10
* Webpack Version: 4
* Operating System and version (desktop or mobile): N/A

## @ Mentions
@dkasper-was-taken

**Comment by dkasper-was-taken** [comment]
Looks like the hidden scss wasn't quite complete. The px unit needed to be added. For HeaderCheckMarkCell.module.scss and CheckMarkCell.module.scss we should update the `.checkmark.is-hidden` selector to match this:
```
 .checkmark.is-hidden {
    background-color: transparent;
    background-image: none;
    border: 0;
    left: 50%;
    margin: -1px;
    padding: 0;
    position: absolute;
    top: 50%;
    width: 1px;
  }
```
