### ISSUE TITLE
[terra-switch] Add isBlock style prop

### ISSUE THREAD

**Issue by jeremyfuksa** [cerner/terra-core#3113]
# Enhancement Request

## Description
In the initial build, block styling for the component was missed. Adding this will help the component look right in mobile and small containers.

## Additional Context / Screenshots

![imgpsh_mobile_save](https://user-images.githubusercontent.com/726351/89453759-55b66500-d725-11ea-8151-3ad4c8a9e281.jpg)

**Comment by supreethmr** [comment]
Hi @jeremyfuksa 

Need small clarification on switch width when isBlock is true. So does switch should expand to 100% width when isBlock is set..?
<img width="1321" alt="Screen Shot 2020-08-07 at 7 51 16 PM" src="https://user-images.githubusercontent.com/12869809/89658332-0cfcd880-d8ec-11ea-8088-252c20174dfc.png">
(when label doesn't have enough text to it will expand like above by moving switch tray to corner of container)

**Comment by jeremyfuksa** [comment]
Correct.
