### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#313]
# Issue Description
Create card component.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Needs expected behavior defined

## Current Behavior
N/A

**Comment by WhiteLight1107** [comment]
# Tech Design for Card
## Summary:
The Card Component is used as container for other divs. 

PR:
TBD

## React Props:
### Card:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| padding | array or bool | true | option to pass in a single boolean to turn on/off, or an array to specify each side using css short hand https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties |
| children | node | none | Child Nodes |

## Example:
```
import React from 'react';
import Card from 'terra-card';

const CardDefault = () => (
  <div>
    <Card children={"Hello World!!"}/>
</div>
);

export default CardDefault;

```

## CSS Classes:
| Selector | Description |
|----------|------|
| .well-card | Outer Container of the Card |
| .well-card-container | Inner part of the card used to contain children prop |
| .u-pa--sm | 10px padding |
| .u-pv--sm | 10px padding vertical |
| .u-ph--sm | 10px padding horizontal |
| .u-pt--sm | 10px padding top |
| .u-pb--sm | 10px padding bottom |
| .u-pl--sm | 10px padding left |
| .u-pr--sm | 10px padding right |

**Comment by WhiteLight1107** [comment]
UX Designs: https://jira2.cerner.com/browse/PORTALDEV-35541

**Comment by mhemesath** [comment]
CSS classes aren't really needed anymore in tech designs as we localize those in modules. I will say though to remove the well prefix from them.

**Comment by dkasper-was-taken** [comment]
As far as the selectors, they needs to be update to remove the wellness name spacing.
We are no longer using the '--' selector nomenclature.
5px margins are not enforceable as a stand alone component relative, so HOC or usage of list would be needed.
I'm a little uncertain about using a bool & array type, generally multiple typed variables are discouraged.
If we are using array, we want to set a type or shape of the array contents.
The padding itself it currently under discussion if we need a component to provide such padding styles, or if a cerner standard padding should be applied.

**Comment by jmsv6d** [comment]
It looks like the UX designs also have at concept of a selectable card and a selectable list of cards that is missing from this tech design. I also propose renaming this component.
And FYI we shouldn't be putting links to internal resources on public github.

**Comment by WhiteLight1107** [comment]
@jmsv6d  @mhemesath  was under the impression that a list of cards would be another component?  For the selectable card it looked it was part of the list of cards, not just a stand alone selectable card, so I thought that would be part of that component.  Clarification for what is required for this component would be much appreciated.

**Comment by jmsv6d** [comment]
I would really expect this to be able to be utilized as a list item in our existing selectable list component, if possible. So taking that into the consideration of the design would be what I'm looking for.

**Comment by jmsv6d** [comment]
Or perhaps, would the card list be achieved by placing a list within a card?

**Comment by mhemesath** [comment]
@jmsv6d we haven't gotten any specification for selectable cards in either OCS preview or consumer specifications. I suggest we just focus on the basic card component for now until we get those finalized specs. Those enhancements should be easy to make to the component in the future or as a wrapper component.

A card list should be a grouping of cards, not a list within a card. Either way, I think its a separate component.

**Comment by WhiteLight1107** [comment]
@dkasper-was-taken could you explain in a little bit more detail how the padding should be done, the way I was thinking was the user could pass in true and then 10px padding would be applied to all sides or they could pass in a boolean array of size 2-4 to represent each side the user wanted the 10px padding on.

Length 2:
vertical, horizontal
Length 3:
top, horizontal, bottom
Length 4:
top, right, bottom, left

Thanks

**Comment by mhemesath** [comment]
We could probably simplify padding to the following 3 props

* veritcalPadding
* horizontalPadding
* padding

Its unlikely that we'll have  only vertical or horizontal padding on one side and not the other

**Comment by alex-bezek** [comment]
`I'm a little uncertain about using a bool & array type, generally, multiple typed variables are discouraged.` @dkasper-was-taken 
If we wanted to keep with the css shorthand pattern, this could easily just always take an array and the consumer could pass in an array of 1. I think using css shorthand for margin/padding helper components was brought up last week and there was some aversion to it. Perhaps a topic for the war room to remain consistent.

@mhemesath I believe we tried to steer clear from having props that if the consumer provided both would have to override each other somehow (like verticalPadding would override the overall padding attribute I assume?) as it can be unclear how they would resolve.

**Comment by mhemesath** [comment]
@alex-bezek I think the rule would be the specific padding attribute would override the generic. However, if we don't like that then the simple solution is to remove padding and jjust have horizontalPadding and verticalPadding.

**Comment by emilyrohrbough** [comment]
@alex-bezek in regards to Dave's comment:

> I'm a little uncertain about using a bool & array type, generally, multiple typed variables are discouraged. 

Could the padding prop be an array type with a default value of undefined. Then instead of checking for either an array or a boolean, if padding is provided it is automatically added. To me this seems sufficient to turn padding on or off.

**Comment by WhiteLight1107** [comment]
@mhemesath  would this appropriate in how to handle padding?
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| padding | array | [true,true] | [veritcalPaddingOn,horizontalPadding] first element provides 10px padding on top and bottom of the card if true and second element provides 10px padding on left and right of card if true

**Comment by mhemesath** [comment]
I the discussion is that people do not want an array. My vote is we just keep this simple.

```jsx
<Card padVertical padHorizontal /> 
```

**Comment by WhiteLight1107** [comment]
Updated Tech Design

# Tech Design for Card
## Summary:
The Card Component is used as a container for other divs. 

PR:
TBD

## React Props:
### Card:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
|padVertical | bool | true |Provides 10px on top and bottom |
|padHorizontal | bool | true |Provides 10px on Left and Right |
| children | node | none | Child Nodes |

## Example:
```
import React from 'react';
import Card from 'terra-card';

const CardDefault = () => (
  <div>
    <Card>Hello World!!</Card>
</div>
);

export default CardDefault;

```

**Comment by bjankord** [comment]
+1 on tech design. Per team discussions on Friday, we landed on defaulting the card to `0` padding. If users set a `padVertical` or `padHorizontal` prop, add the `10px` padding to the relating sides.

**Comment by WhiteLight1107** [comment]
@bjankord  ok I updated my tech design
