### ISSUE TITLE
Add lib to gitignore

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#316]
# Issue Description
A common pattern for npm modules is to add the lib(es5) directory to the .gitignore and add the src(es6) directory to the .npmignore. [Babel is an example of this pattern](https://github.com/babel/babel/tree/7.0/packages/babel-core) that also uses lerna. 

More information can be found in this article:
http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/
## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- [x] Update the .gitignore to no longer check in the lib directory.
- [x] We can probably remove the prepush script after this is completed.
- [x] Compile for travis CI tests
- [x] Add script which compiles before publishing https://github.com/cerner/terra-core/issues/353

## Current Behavior
`lib` directory is included in version control

**Comment by bjankord** [comment]
With all the components importing `terra-base/lib/baseStyles' we'll want to run compile before tests.

**Comment by bjankord** [comment]
We can move the prepush script into a prepublish script without much change to generate lib when packages are published.

**Comment by Matt-Butler** [comment]
I am going to update the postinstall script to compile. That way the lib directories are generated after installing our dependencies.

**Comment by Matt-Butler** [comment]
The prepublish script has different behavior depending on the version of npm a person is using.
https://docs.npmjs.com/misc/scripts

I added to the agenda to check which version of npm people are using.

**Comment by bjankord** [comment]
Let's look in using lerna for prepublish scripts, looks like they have some code for that case: https://github.com/lerna/lerna/blob/2dddce0c8f1550578b1042e65fbccc7d22844d7f/lib%2Fcommands%2Fpublish.js#L148-L152

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/tree/ignore-lib-directory
^ This branch has been updated to ignore the lib directory. 

We should also add a script similar to this: 
https://github.com/cloudflare/cf-ui/blob/master/package.json#L24

**Comment by Matt-Butler** [comment]
Blocked on this issue: https://github.com/cerner/terra-core/issues/369

**Comment by emilyrohrbough** [comment]
Issue #369 addressed in PR [#408](https://github.com/cerner/terra-core/pull/408) & [#409](https://github.com/cerner/terra-core/pull/409).

**Comment by bjankord** [comment]
I updated the checkboxes in the initial comment. 
We still need to do the following:
- [ ] Remove the prepush script
- [ ] Compile for travis CI tests

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/tree/ignore-lib-directory <- This should be up to date after the lerna publish script was added.

**Comment by bjankord** [comment]
Resolved in #414
