### ISSUE TITLE
<terra-text> - incorrect documentation ? 

### ISSUE THREAD

**Issue by RusseII** [cerner/terra-core#3164]
[The docs say ](https://engineering.cerner.com/terra-ui/components/terra-text/text/text)

> However, there are drawbacks to be aware of with this component. The styles set with this component are not themable and will be static. If this is a concern for your usage, we recommend building a custom component that handles your font styles that need to differ from the base font styles so you can control the themability of them.

Is that no longer true after https://github.com/cerner/terra-core/pull/3026 ?

**Comment by mjhenkes** [comment]
You are correct, with the addition of the javascript context, you could now set the terra text props based on the theme.
