### ISSUE TITLE
Document Approach for testing remotely

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#317]
It's not quite clear from the repo how it can be ran and tested remotely through a VM. I think we need to investigate if it's possible to have an npm script to allow for us for easy VM testing to test against IE browsers.

**Comment by windse7en** [comment]
This [config](https://github.com/cerner/terra-core/blob/master/packages/terra-site/webpack.config.js#L95) in updated webpack.config should allow the webpack-dev-server for the remote test by IP address.

- [ ] We can also add some docs on how to test remotely.

**Comment by bjankord** [comment]
Yeah, I'm able to test local dev server on iPhone / Android with IP address + port number. e.g. `http://10.123.45.67:8080` Note, you'll need to have the device your remote testing on the same wifi network as the computer your using to run the local server.

For IE testing, we'll want to document using the `host` file on Windows to setup alias for localhost.

**Comment by windse7en** [comment]
Hi, @JakeLaCombe. As we have already updated to diable host check, the remote testing should work as expected. Could you check if we can close this issue?

<img width="1029" alt="screen shot 2017-05-11 at 12 54 45 pm" src="https://cloud.githubusercontent.com/assets/3724179/25964022/164210d4-3649-11e7-823a-64ecd12376c0.png">

**Comment by JakeLaCombe** [comment]
We can close this. It's working just fine!
