### ISSUE TITLE
[terra-form-field] Remove errorIcon prop

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-core#3196]
# Feature Request

## Description

To ensure consistency between form field implementations, the error icon should not be customizable. Therefore we should remove the errorIcon Prop.

**Comment by ryanthemanuel** [comment]
I believe we can make this not an MVB by just ignoring this prop going forward and marking it as deprecated.

**Comment by ryanthemanuel** [comment]
After talking with @neilpfeiffer, there is some concern that this is a non passive change if teams were relying on the error prop and don't have the appropriate theme values for the error icon that we want to use instead.
