### ISSUE TITLE
[terra-form-input] Add maxLength and character counter 

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-core#3199]
# Feature Request

## Description
The form input Field currently has maxLength property which limits typing in input beyond the number of characters. A new property needs to be added to allow for a user to type beyond the maximum submittable characters, but allow user to go beyond and display help text that shows remaining character count.

## Additional Context / Screenshots
Similar to Legacy Orion and Legacy Terra. (Twitter 140 character max example)

![char-count-2](https://user-images.githubusercontent.com/1355485/29428025-53393d78-8351-11e7-9b08-1f67aa2fcad5.png)

## Current Behavior
Stops the user from typing beyond the maxLength. That case is fine by itself, a new case needs to allow for similar limitation for submission but allow for typing beyond limit with ability to remove characters.

**Comment by emilyrohrbough** [comment]
duplicate of https://github.com/cerner/terra-core/issues/736

**Comment by StephenEsser** [comment]
I think this issue was logged intentionally for a different package with the same functionality as 736. The issues should probably be linked, but aren't quite duplicates

**Comment by emilyrohrbough** [comment]
You're right. I retract my statement that it was a duplicate.
