### ISSUE TITLE
Heroku review apps: memory issue

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#322]
When loading the review apps, we see this page:
![screen shot 2017-05-05 at 4 41 21 pm](https://cloud.githubusercontent.com/assets/8146159/25765264/b584354c-31b1-11e7-85d6-c390a385c149.png)

This is due to the webpack-dev-server taking up too much memory.

**Comment by Matt-Butler** [comment]
We might want to create the static assets and host them on heroku to get around the memory issue.

**Comment by windse7en** [comment]
Heroku Error R14(Memory quota exceeded): https://gist.github.com/windse7en/e9685f48af1b015ff1245c68297985bc

**Comment by windse7en** [comment]
Heroku logs after updating express: https://gist.github.com/windse7en/b5b0df051286df8970a83c0f3ebfc4e3

**Comment by windse7en** [comment]
There are still some R14 errors. That dues to the webpack compile process taking too much memory.

**Comment by windse7en** [comment]
In the #326, move the build process into `heroku postbuild`. It will run for any new commit and won't have the memory issue in the build process. All the build logs information can be found in the Heroku dashboard.

**Comment by windse7en** [comment]
Close this memory issue. As we move the build process into the heroku build time, there is no memory issue in the logs.
