### ISSUE TITLE
terra-table hover styling is not adjusted for lowlight

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#3299]
# Bug Report

## Description
Run the terra-table in a lowlight application/page adding multiple rows that are selectable.
Hover over any row.  The background changes to a off-white color, making it difficult to see gray text.

The [lowlight](https://github.com/cerner/terra-core/blob/8fdfafc0583d4eb8568e09777fa8dd2365a0877b/packages/terra-table/src/clinical-lowlight-theme/Table.module.scss#L135) setting of the --terra-table-row-hover-background-image variable is identical to the [default](https://github.com/cerner/terra-core/blob/terra-visually-hidden-text%402.31.0/packages/terra-table/src/subcomponents/Row.module.scss#L113) value.

Comparing the default and lowlight values, it seems many (if not all) of the *hover-background-image values are identical between the 2 themes.  I suggest reviewing all of them when making the correction.

## Additional Context / Screenshots
<img width="1073" alt="Screen Shot 2021-01-05 at 9 32 01 AM" src="https://user-images.githubusercontent.com/30238809/103688775-f4a2ef80-4f57-11eb-8109-b20b9c7ed340.png">
The dotted line around the row was added by my debugger when trying to capture the hover state. It is not there in an actual table.  The point of the picture is the light colored background.

## Expected Behavior
Hover color should be specified for the lowlight theme.

## Possible Solution
Modify the --terra-table-row-*-hover-background-image variables in the lowlight file to be appropriate values for lowlight.

## Environment
I tested in the following. 
* Component Name and Version: terra-table 4.19.0
* Browser Name and Version:  Chrome
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Mac

## @ Mentions
@neilpfeiffer

**Comment by ryanthemanuel** [comment]
@jeremyfuksa we will need some input on this.

**Comment by jeremyfuksa** [comment]
Active/Hover color is specified as `#1e3a49`.

**Comment by saket2403** [comment]
Thanks for the color input @jeremyfuksa , Can I get some more input on which variables the color is to be applied.
