### ISSUE TITLE
List site documentation is not formatted

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#330]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
List site documentation is not formatted
![screen shot 2017-05-09 at 1 57 42 pm](https://cloud.githubusercontent.com/assets/6720991/25867630/c8b971a2-34bf-11e7-99d1-f701e0e8fa77.png)

### Steps to Reproduce the Issue
1. Navigate to http://engineering.cerner.com/terra-core/#/site/list
2. Scroll down to the React Props documentation
3. Observe the prop table is not formatted

### Expected Outcomes
- The List site documentation is properly formatted

**Comment by bjankord** [comment]
This is coming from props documentation in a markdown file: https://github.com/cerner/terra-core/blob/master/packages/terra-list/docs/README.md

Looks like we should remove that from the markdown file as it should be coming from the JSDoc comments in the src code via prop table component.
