### ISSUE TITLE
List example issues

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#331]
# Issue Description
@mmalaker found some issues with the examples: http://engineering.cerner.com/terra-core/#/site/list

* the "Single Select List with Preselected Item" example does not a have a preselected item.
* The regular "Multi Select List" example is limited to only two selections - behaving the same way as the last example: "Multi Select List With Maximum Selection of 2 Items".
* The List Test examples are not functioning and do not include all the scenarios.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- The "Single Select List with Preselected Item" example includes a preselected list item
- The regular "Multi Select List" example has no limit on selections
- The List Test examples are updated to function correctly and include all the scenarios.

### Steps to Reproduce the Issue
1. Navigate to http://engineering.cerner.com/terra-core/#/site/list
1. View the "Single Select List with Preselected Item" and "Multi Select List" examples
1. Navigate to http://engineering.cerner.com/terra-core/#/tests/list-tests and http://engineering.cerner.com/terra-core/#/tests/list-item-tests and view the examples

**Comment by emilyrohrbough** [comment]
This issue was fixed in https://github.com/cerner/terra-core/pull/325

**Comment by bjankord** [comment]
Resolved in #387
