### ISSUE TITLE
Terra Dropdown Alignment Is Not Proper With The Terra Button 

### ISSUE THREAD

**Issue by neerajson** [cerner/terra-core#3353]
# Bug Report

## Description

Terra Dowpdown is creating a misalignment when we are using it with the terra-button. Please check the attached screenshots.

## Steps to Reproduce

1. This issue is happening in the staged record component of the powerchart.

## Additional Context / Screenshots

<img width="165" alt="Screen Shot 2021-02-16 at 6 02 45 PM" src="https://user-images.githubusercontent.com/22203537/108063707-a1a57780-7081-11eb-864d-dddad43d6227.png">

## Expected Behavior

the button should be aligned properly 
<img width="178" alt="Screen Shot 2021-02-16 at 6 07 59 PM" src="https://user-images.githubusercontent.com/22203537/108063936-f77a1f80-7081-11eb-8da8-a56bb1cf90c2.png">

## Possible Solution

There is the margin issue, for the Reject button we can give margin-top:3px;
## Environment

* Component Name and Version: terra-dropdown-button(https://engineering.cerner.com/terra-ui/components/terra-dropdown-button/dropdown-button/dropdown-button)
* Browser Name and Version: IE10/11
* Node/npm Version: [e.g. Node 8/npm 5] Node 8.9.4/npm 5.6.0
* Webpack Version: ^4.35.2
* Operating System and version (desktop or mobile): Desktop.

## @ Mentions

@supreethmr

**Comment by supreethmr** [comment]
this can be re-creatable on dev-site to by adding button together with split-button / dropdown button :
safari : 
<img width="421" alt="Screen Shot 2021-02-16 at 6 49 03 PM" src="https://user-images.githubusercontent.com/12869809/108068137-b5ec7300-7087-11eb-9801-6e289c59b3d2.png">

<img width="493" alt="Screen Shot 2021-02-16 at 6 49 17 PM" src="https://user-images.githubusercontent.com/12869809/108068143-b7b63680-7087-11eb-8a04-7fb977b2f67b.png">

firefox : 
<img width="422" alt="Screen Shot 2021-02-16 at 6 50 25 PM" src="https://user-images.githubusercontent.com/12869809/108068317-edf3b600-7087-11eb-9e54-c30ba0906b9d.png">

<img width="493" alt="Screen Shot 2021-02-16 at 6 50 35 PM" src="https://user-images.githubusercontent.com/12869809/108068326-efbd7980-7087-11eb-85ac-361321d5e634.png">

not sure of what causing this misalignment on other browsers than chrome. It looks like `vertical-align` style property of terra-button causing this slight misalignment with terra-dropdown in safari and firefox.

cc: @neilpfeiffer

**Comment by neilpfeiffer** [comment]
Thanks for the investigation @supreethmr, this seems to be the same problem as https://github.com/cerner/terra-core/issues/3085#issuecomment-692716460 which was also noticeable primarily in Safari.

It isn't the vertical-align that is in button that is the problem, it is that the outer base div for dropdown-button and split-button does not also have it, and it needs to be added. 

If `vertical-align: middle;` is added here, it will resolve this issue:
https://github.com/cerner/terra-core/blob/8f55f0f558e76b28a13a38dc9883cb114183f665/packages/terra-dropdown-button/src/_DropdownButtonBase.module.scss#L6-L14

**Comment by neilpfeiffer** [comment]
Confirmed bug. UX instructions added above and ready to work.
