### ISSUE TITLE
terra-form-checkbox-line-height isn't aligning checkbox with label text 

### ISSUE THREAD

**Issue by tejasrim** [cerner/terra-core#3380]
# Bug Report

## Description
terra-form-checkbox isn't aligning checkbox with label text 
## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/79934402/109695790-f224d680-7b51-11eb-9133-3e652cf04604.png)

## Expected Behavior

Checkbox and text should be aligned

## Possible Solution

Default value of terra-form-checkbox-line-height need to be changed from 1.33 to 1

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by pranav300** [comment]
Can you provide a link, where you are using the checkbox. As I am not seeing the misalignment in the dev-site.

**Comment by pranav300** [comment]
Closing this issue, as the misalignment was due to some global styles in the consumer's project.
