### ISSUE TITLE
Prepush script that involves testing doesn't succeed with SourceTree

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#34]
# Issue Description
Prepush script that involves testing doesn't succeed with SourceTree

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Prepush script that involves testing succeeds with SourceTree

## Current Behavior
SourceTree is not able this run this script successfully. `git push` is successful from the command line but pushing from SourceTree results in the following error:

```bash
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v origin refs/heads/ResponsiveElement:refs/heads/ResponsiveElement 
Pushing to git@github.com:cerner/terra-ui.git
error: failed to push some refs to 'git@github.com:cerner/terra-ui.git'

> husky - npm run -s prepush


> husky - pre-push hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
Completed with errors, see above
```

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by StephenEsser** [comment]
I am also running into this. 

SourceTree is not able this run this script successfully. `git push` is successful from the command line but pushing from SourceTree results in the following error:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v origin refs/heads/ResponsiveElement:refs/heads/ResponsiveElement 
Pushing to git@github.com:cerner/terra-ui.git
error: failed to push some refs to 'git@github.com:cerner/terra-ui.git'

> husky - npm run -s prepush


> husky - pre-push hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
Completed with errors, see above
```

**Comment by windse7en** [comment]
The pre-push hook works for me. SourceTree version: 2.0.5.5. Use Alfred to open the SourceTree application.

It maybe SourceTree bug. It maybe the the same issue like [this comment](http://stackoverflow.com/questions/17538460/using-git-pre-commit-hooks-in-context-of-github-client/33588294#33588294).

**Comment by bjankord** [comment]
We are looking to remove the prepush script as a part of https://github.com/cerner/terra-core/issues/316

**Comment by Matt-Butler** [comment]
The prepush script has been removed https://github.com/cerner/terra-core/pull/414
