### ISSUE TITLE
Terra Grid should expect column

### ISSUE THREAD

**Issue by kapilpipaliya** [cerner/terra-core#3418]
# Feature Request
terra-grid component currently only support direction 'row'.

## Description
how to add direction="column" to the Grid.Row ?

## Additional Context / Screenshots
https://next.material-ui.com/api/grid/
material-ui has direction prop to change direction of 'flex' grid.

**Comment by neilpfeiffer** [comment]
@kapilpipaliya After reviewing material-ui's grid component, the APIs and approaches aren't really the same between the two components.  Material uses a simple `Container` > `Item` structure with their API, and all the layout details are prop driven (row, row-reverse, column, column-reverse) and very much follows flexbox styling options, where the container width on the row style, or container height on the column style is what drives the wrapping to next row/column.

Terra-grid's API however is much more formal in constructing a `Grid` > `Row` > `Column` > `Item/Children` with unique subcomponents. If needing to create a primarily vertical grid, it can be accomplished by simply putting more items vertically stacked within each column. Or Terra also offers the [Terra-Dynamic-Grid](https://engineering.cerner.com/terra-ui/components/terra-dynamic-grid/dynamic-grid/dynamic-grid) based off the principles of CSS Grid.


@kapilpipaliya - how do you propose enhancing [Terra-Grid](https://engineering.cerner.com/terra-ui/components/terra-grid/grid/grid) to accomplish similarity with Material UI?

**Comment by kapilpipaliya** [comment]
Thank you very much for your input.
I have no specific requirements for direction="column". I was working on material ui. i found it very customizable. so i just give suggestion here.
I very much like terra components. Thank you very much for such a great components.
