### ISSUE TITLE
[terra-search-field] Delayed Search is not honored while the user is typing text

### ISSUE THREAD

**Issue by rasthana** [cerner/terra-core#3430]
# Bug Report

## Description

Search field performs a search before the search delay threshold is met, while the user is still typing text.

## Steps to Reproduce

1. Navigate to [terra-ui#seach-field](https://engineering.cerner.com/terra-ui/components/terra-search-field/search-field/search-field)
2. Scroll to `Search Field Delayed` example
3. Continuously enter text for longer than 2 seconds
4. Search text label gets updated when it shouldn't.

## Expected Behavior

Search field should reset the timer if new text is entered within the search delay threshold.

## Possible Solution

The search timeout probably isn't getting cleared [here](https://github.com/cerner/terra-core/blob/main/packages/terra-search-field/src/SearchField.jsx#L159) and the initial valid inputs are possibly triggering the search instead of waiting till the user stops typing.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by tbiethman** [comment]
I agree with the proposed solution. Any search delay should be reset on changes to the input.

https://github.com/cerner/terra-core/blob/main/packages/terra-search-field/src/SearchField.jsx#L158-L160
```jsx
    if (!this.searchTimeout && !this.props.disableAutoSearch) {
      this.searchTimeout = setTimeout(this.handleSearch, this.props.searchDelay);
    }
```
to
```jsx
    if (!this.props.disableAutoSearch) {
      this.clearSearchTimeout();
      this.searchTimeout = setTimeout(this.handleSearch, this.props.searchDelay);
    }
```
