### ISSUE TITLE
[terra-profile-image] fallback image missing equal style and treatments as valid image

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#3432]
# Bug Report

## Description

When Terra-profile-image has a correct/successful image source, it does not have the same treatment applied for when it has an invalid/unsuccessful image source.  There should be parity in approach between the regular profile-image and the fallback/placeholder that is built in.

## Additional Context / Screenshots

Attaching a series of example tests, testing with a valid src image (e.g. `src={exampleProfileImage}`) on the left, next to an invalid src image (e.g. `src="invalid.jpg"`) on the right. The expected is for the fallback placeholder to be the same but with a replacement image.

1: when two images are side-by-side, both should be inline and vertically-aligned to the middle:
```
<ProfileImage width="75" height="75" alt="inline test" src={exampleProfileImage} />
<ProfileImage width="75" height="75" alt="inline test" src="invalid.jpg" />
```
![1-inline](https://user-images.githubusercontent.com/1355485/116996369-eb752580-aca0-11eb-9202-76e02ac345af.png)
\
\
\
2: When adding additional CSS Style, the fallback image doesn't also apply the style
```
<ProfileImage width="75" height="75" className={cx('test-style-border')} alt="adds css style" src={exampleProfileImage} />
<ProfileImage width="75" height="75" className={cx('test-style-border')} alt="adds css style" src="invalid.jpg" />
```
```
.test-style-border {
    border: 10px solid rgb(69, 221, 170);
    border-radius: 25px;
    box-sizing: content-box;
}
```
![2-style](https://user-images.githubusercontent.com/1355485/116996385-efa14300-aca0-11eb-8738-2995afdc04c3.png)
\
\
\
3: When Height and Width is not provided via props, the fallback image doesn't appear, should rely on a default image size
 ```
 <ProfileImage alt="no height or width provided" src={exampleProfileImage} />
 <ProfileImage alt="no height or width provided" src="invalid.jpg" />
 ```
![3-no-height-width](https://user-images.githubusercontent.com/1355485/116996486-1d868780-aca1-11eb-9f2e-6acf328508a7.png)
\
\
\
4. When Height and Width are provided by CSS and not props, the fallback image doesn't appear, should use css size
```
<ProfileImage className={cx('test-style-size')} alt="use css size instead" src={exampleProfileImage} />
<ProfileImage className={cx('test-style-size')} alt="use css size instead" src="invalid.jpg" />
```
```
.test-style-size {
    height: 100px;
    width: 40px;
}
```
![4-height-width-css](https://user-images.githubusercontent.com/1355485/116996522-2aa37680-aca1-11eb-8ca4-5519ed227a57.png)
\
\
\
5. Profile-Image implements Terra-Image, and though it's not declared, allows for the passthrough of Terra-Image props like variant, which are not applied to the fallback image
```
<ProfileImage width="75" height="75" alt="passing through terra-image props" src={exampleProfileImage} variant="thumbnail" />
<ProfileImage width="75" height="75" alt="passing through terra-image props" src="invalid.jpg" variant="thumbnail" />
<ProfileImage width="75" height="75" alt="passing through terra-image props" src={exampleProfileImage} variant="circle" />
<ProfileImage width="75" height="75" alt="passing through terra-image props" src="invalid.jpg" variant="circle" />
```
![5-image-variants](https://user-images.githubusercontent.com/1355485/116996537-3131ee00-aca1-11eb-85d3-8bf1e60aa6d4.png)
\
\
\
6. The same Fit treatment should also apply to the fallback image when set
```
<ProfileImage width="75" height="150" alt="testing fit" src={exampleProfileImage} fit="contain" />
<ProfileImage width="75" height="150" alt="testing fit" src="invalid.jpg" fit="contain" />
<ProfileImage width="150" height="75" alt="testing fit" src={exampleProfileImage} fit="scale-down" />
<ProfileImage width="150" height="75" alt="testing fit" src="invalid.jpg" fit="scale-down" />
```
![6-image-fit](https://user-images.githubusercontent.com/1355485/116996546-35f6a200-aca1-11eb-9621-004ac151ed29.png)

## @ Mentions

followup to PR #3422 and issue #3412

**Comment by veronimazur** [comment]
hi, wanted to add some info to this issue since I'm encountering a possibly related problem (the previous terra-profile-image issue didn't seem to solve my issue). 
my issue is that the placeholder image still seems to have an extra bit of space while the regular image does not, and both are created the same way. they are both given height/width of 35px (no fill for either of them). I made sure that I pulled in the latest terra-profile-image changes as well.

in this screenshot, for the placeholder, there is that small sliver at the bottom that seems to be an extra div around the image. the span containing the image is 35x35 as it should be, but the div containing the image is 35x36.6.
![image](https://user-images.githubusercontent.com/19920191/117879075-1f85b300-b26c-11eb-85c7-5800f1d37a0a.png)

in this screenshot, the image that loads in is 35x35 and has no extra space around it. 
![image](https://user-images.githubusercontent.com/19920191/117879009-0977f280-b26c-11eb-9ce0-7fef75b2a35a.png)

please let me know if you need any more info to help out!

**Comment by mjhenkes** [comment]
@Shruthila, This issue is nearly 50 days old now. I see it's marked as blocked, could you comment on why it's blocked and what we could do to unblock it?

**Comment by ShettyAkarsh** [comment]
@mjhenkes. we are currently waiting on UX inputs for third and the sixth point mentioned above by @neilpfeiffer. basically the size of the default image and how the fallback image should behave when we apply fit property. we have created this [branch](https://github.com/cerner/terra-core/compare/update-fallback-image-styles#diff-585129f3ac23a3eb83b82ce533f1e7cec08ad9a7ed11d433b96ba47a5dbf4205) with above mentioned changes. so currently neil is working on those inputs and reviewing the branch changes.
