### ISSUE TITLE
[terra-table] screen reader 

### ISSUE THREAD

**Issue by ezargar** [cerner/terra-core#3445]
# Bug Report

## Description

1. Table heading is not read as the focus is not trapped from keyboard tabs
2. Screen reader does not inform that row is clickable for the single selectable table

	
## Steps to Reproduce

1. Jaws and voice-over tool has been used for the screen reading 
2. Screen reading has been performed using the Tab key to navigate within the table

## Expected Behavior

Screen reader should read the table heading and should inform that row is clickable 
## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 10/npm 6]
* Webpack Version:
* Operating System and version (desktop or mobile): MACOS 10.15.7

**Comment by ryanthemanuel** [comment]
We reached out to @ezargar and were able to work through his issues. Closing this.
