### ISSUE TITLE
terra-form-select 'search' variant does not focus when there is a large number of options

### ISSUE THREAD

**Issue by kw070877** [cerner/terra-core#3451]
# Bug Report

## Description

When the terra-form-select 'search' variant has a large number of options (400+), the menu is not focused correctly which results in the dropdown remaining open when clicking on other fields.

## Steps to Reproduce

1. Create a search select field with 400+ options
2. Click the dropdown arrow to open the dropdown
3. Click elsewhere on the screen - the dropdown does not close because it was not focused
4. *Happens most frequently on the first opening of the dropdown

## Additional Context / Screenshots

Video:
https://user-images.githubusercontent.com/85512188/121061339-bb361080-c791-11eb-9124-dd06a25dbb71.mov

## Expected Behavior

The dropdown should still be focused even if there is a large number of options.

## Possible Solution

The menu is not yet painted to the DOM when trying to focus here https://github.com/cerner/terra-core/blob/main/packages/terra-form-select/src/shared/_FrameUtil.js#L150. In other words, that 100 ms timeout is not long enough. One solution I have noticed to fix the issue is adding a requestAnimationFrame inside the timeout, around the frame.selectMenu.focus();. 

## Environment

* Component Name and Version: terra-form-select 6.29.0
* Browser Name and Version: Chrome 91.0.4472.77 
* Node/npm Version: [e.g. Node 8/npm 5] Node 10/npm 6
* Webpack Version: Webpack v4
* Operating System and version (desktop or mobile): Mac, issue only occurs on mobile

## @ Mentions

@supreethmr

**Comment by dkasper-was-taken** [comment]
From some offline discussion, even though performance can be expected to degrade with an increasingly sized list of options, we shouldn't be left in a "broken" state.

As mentioned above the initial focus is part of the issue, but we should also make sure this cleanup method properly closes the menu in either case:
https://github.com/cerner/terra-core/blob/main/packages/terra-form-select/src/search/Frame.jsx#L217

The useLayoutEffect could be used to great effect to solve this as well. The two locations I seeing being possible are switching the Menu component to hooks, or making a sub-component written in Hooks for the UL, and provide a callback trigger within the useLayoutEffect hook, ensuring the DOM has fulling laid out before we set focus:
https://github.com/cerner/terra-core/blob/main/packages/terra-form-select/src/search/Menu.jsx#L423
