### ISSUE TITLE
[terra-core] Update WDIO Screenshots due to webpack-config-terra sass upgrade.

### ISSUE THREAD

**Issue by pranav300** [cerner/terra-core#3467]
# Feature Request

## Description

As of October 2020 [node-sass](https://www.npmjs.com/package/node-sass) is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated). The [sass](https://www.npmjs.com/package/sass) npm package is the replacement.

But the sass package has an unadjustable precision of 10 decimal points, whereas node-sass had it of 5.

So we need to update wdio snapshots as diff in snapshots will be in micro pixels.

related to: [webpack-config-terra issue#676](https://github.com/cerner/terra-toolkit/issues/676)

**Comment by mjhenkes** [comment]
Alternatively, regenerate the screenshots.
