### ISSUE TITLE
[Terra-text] - `isWordWrapped` property does not wrap long words on IE.

### ISSUE THREAD

**Issue by amanagasthya0005** [cerner/terra-core#3484]
# Bug Report![long ordername truncation](https://user-images.githubusercontent.com/51478407/131106716-0c10d04f-42ef-4c5a-b209-26b9c1703c93.png)
## Description

 While working on Internet Explorer i have been using terra-text component to wrap my information but i noticed when the resolution of the explorer is reduced the long words does not get wrapped up and text overflows while at the same resolution the same component when loaded on google chrome works fine with text not overflowing.
## Steps to Reproduce

1. Set up long texts like ("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") or ("amnsjxnweiucnweicnxeixnniwnxuwnxiqnxiqwnx") in the terra-text control with prop-type `isWordWrapped` passed.
2. Now reduce the size of the IE window.
3.  We will notice that the text overflows instead of wrapping up
4.

## Additional Context / Screenshots
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/51478407/131106915-aa6fa069-913e-45aa-a9ee-bdb558df332e.png)

MicrosoftTeams-image (3)![long ordername truncation](https://user-images.githubusercontent.com/51478407/131106716-0c10d04f-42ef-4c5a-b209-26b9c1703c93.png)

## Expected Behavior
The text should not overflow instead should come down to the next line.
## Environment

* Component Name and Version:
* Browser Name and Version: Internet Explorer 10,11, Edge
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Windows

**Comment by supreethmr** [comment]
This issue seems to be not happening on IE 11 as I was able to test the terra-text with large text as shown in screenshot shared below the text was wrapped when isWordWrapped was set.

![WhatsApp Image 2021-08-26 at 9 41 18 PM](https://user-images.githubusercontent.com/12869809/131320751-b950d7bc-096a-4920-b6e6-afad1bf83efc.jpeg)

```js
<Text id="text" isWordWrapped>
texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
</Text>
```

I even verified with other examples as well on IE 11. Text was not overflown as shown in the issue. Look at screenshot I think the view holding terra-text is not Modal view. Not sure if we need to consider to include terra-text within IFRAME to see if the overflow happens.

**Comment by pranav300** [comment]
@amanagasthya0005 May I know what width is being passed for the parent container of terra-text?

**Comment by amanagasthya0005** [comment]
@pranav300 We are seeing the issue in chrome as well now, i'll get back to you with more details on the same.

**Comment by ryanthemanuel** [comment]
@amanagasthya0005 were there more details you were going to share?
