### ISSUE TITLE
Make terra-toolkit's server-launcher Compatible Across All Repos

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#349]
The Webpack 2 Integration pull request had the issue where webpack can't find the correct devDependencies modules directory. The quick solution implemented was to to switch working directory to site and make all modules available.  This fix was in terra-toolkit's `server-launcher.js` file [here](https://github.com/cerner/terra-core/pull/270/files#diff-e1ecc7a7ac21bfa2834574ebe1915fd4R14).

Terra-toolkit is a dependency in terra-clinical, so a different solution needs to be implemented to handle both terra-core and terra-clinical devDependencies modules.

**Comment by mjhenkes** [comment]
This is currently breaking the build in the terra-clinical repo

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/pull/270/files#diff-9999c132bd53c2a36d76ea10d837dd57L14
This section of the webpack config was resolving root to `terra-site` 

Resolve.root was updated to resolve.modules in webpack 2.
https://webpack.js.org/configuration/resolve/#resolve-modules

I think adding resolve.modules should fix the issue. I'll look into it.

**Comment by Matt-Butler** [comment]
Resolved in https://github.com/cerner/terra-core/issues/356.

**Comment by bjankord** [comment]
@emilyrohrbough @mjhenkes This fix has been released in terra-toolkit@0.3.1
