### ISSUE TITLE
Button outline styles inside of modal

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#351]
# Issue Description
Buttons inside the modal do not display an outline when active. However, when the modal is full screen, the buttons do display an outline when active.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Buttons inside the modal display an outline when active.

## Current Behavior
Buttons inside the modal do not display an outline when active. However, when the modal is full screen, the buttons do display an outline when active.

## Steps to Reproduce
1. Navigate to the modal examples using safari.
2. Open the modal and tab through the focusable elements (you may need to turn on keyboard navigation for safari)

Safari: The tab key is being pressed but the button does not display as active
![safari_no_focus](https://cloud.githubusercontent.com/assets/8146159/26076877/d891c920-397f-11e7-9ee6-d2d21dc46ef0.gif)

Chrome:
![chrome_focus](https://cloud.githubusercontent.com/assets/8146159/26076921/003fc6e8-3980-11e7-84e6-9a9cccade592.gif)

## Environment

* Component Version: Button v0 and Modal v0
* Browser Name and Version: Safari
* Operating System and version (desktop or mobile): Mac OSX

**Comment by Matt-Butler** [comment]
@bjankord suggested we investigate adding outline styles instead of using the browsers default focus outline

**Comment by emilyrohrbough** [comment]
As of right now, some sort of outline style will need to be applied to selectable list items when an item contains a chevron. Because of this I think it would be a good idea to set our own outline.

**Comment by bjankord** [comment]
I lean towards using the browser's default styles for focus outlines, but in this case, it looks like there is an issue in Safari that is causing the focus outline not to render on the button element in this use case. This causes a usability / accessibility issue making it difficult to visually see which button is in focus within non-fullscreen modals.

I'd suggest we take a [page from Bootstrap](https://github.com/twbs/bootstrap/blob/dd0ce3e4b2a89f245ee608a1acc9f848cf8c833a/scss/_buttons.scss#L22-L26) and remove the outline from `<Button />` components on focus and provide our own focus outline.

**Comment by emilyrohrbough** [comment]
I took a look. It seems the css styling `bottom: auto` is disabling the tab-ability in Safari for modals of fixed size.

**Comment by neilpfeiffer** [comment]
+1 @emilyrohrbough, what we need to adjust so we can remove `bottom: auto`

**Comment by emilyrohrbough** [comment]
@neilpfeiffer and I have done some digging and have found a few things:
- the first focusably element located at the bottom left corner will not receive focus styles but other elements will
- adding `padding: 10px` to the inner content will allow the focus styles to apply

**Comment by bjankord** [comment]
# Tech Design

* Add inline styles for 15px padding to div here to push in demo content https://github.com/cerner/terra-core/blob/master/packages/terra-site/src/examples/modal/ModalIsOpened.jsx#L32

* Add inline styles for 15px padding to div here to push in demo content https://github.com/cerner/terra-core/blob/master/packages/terra-site/src/examples/modal/ModalIsFullscreen.jsx#L33

* Add inline styles for 15px padding to div here to push in demo content 
https://github.com/cerner/terra-core/blob/master/packages/terra-site/src/examples/modal/ModalCloseOnOutsideClick.jsx#L33

**Comment by emilyrohrbough** [comment]
+1
