### ISSUE TITLE
Date picker exclude or include days of week by usage of abbreviated day of week

### ISSUE THREAD

**Issue by poloka** [cerner/terra-core#3526]
# Feature Request

## Description
Would like the ability to include or exclude calendar dates based on the day of the week they fall on.  For instance, if I know that my work week is only Monday through Friday, it would be nice to specify a filter for selectable days being [Mon, Tue, Wed, Thu, Fri] or maybe my availability is only [Mon, Wed, Thu].

**Comment by benbcai** [comment]
@poloka terra-date-picker currently provides the ability to filter dates using thee [filterDate](https://engineering.cerner.com/terra-ui/components/terra-date-picker/date-picker/date-picker#date-picker-props-table) prop. 

- [Here](https://engineering.cerner.com/terra-framework/tests/terra-date-picker/date-picker/date-picker-filter-dates) is a test example showing weekdays are enabled and weekends are disabled in the calendar.
- [Here](https://github.com/cerner/terra-framework/blob/main/packages/terra-date-picker/src/terra-dev-site/test/date-picker/DatePickerFilterDates.test.jsx#L9-L23) is the associating code example showing how to use the `filterDate` prop for the above example.

I'm going to close this issue. If you have more use cases that the `filterDate` prop does not support, please reopen this issue or submit a new one.

**Comment by poloka** [comment]
Oh nice, I did not see that property. Thanks man for taking a look.￼
