### ISSUE TITLE
Don't make background page actionable when an modal is opened

### ISSUE THREAD

**Issue by TN032688** [cerner/terra-core#3528]
Accessibility 

Ensure keyboard user focus is kept within the modal or URL bar, not the page content behind the modal when the modal is opened.

https://jira2.cerner.com/browse/HNCONSUMER-11012

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by benbcai** [comment]
We will reach out to the internal team to get a better understanding of the issue.

**Comment by neilpfeiffer** [comment]
Closed to work with the consumer to investigate the issue further with their implementation
