### ISSUE TITLE
Remove individual publish scripts from packages

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#354]
### Description of Issue
Using `lerna publish` creates git tags when publishing packages. These tags are used to help determine if a package contains any new commits that should be released since the last time the package was published.

Using the individual `release:version` scripts will publish a package without making a tag for the release. This results in sync issues when trying to use `lerna publish` again. To avoid this issue, we should use `lerna publish` solely for publishing and avoid using individual publish scripts.

**Comment by Matt-Butler** [comment]
This issue has been resolved in https://github.com/cerner/terra-core/pull/358
