### ISSUE TITLE
terra-button Pressing the button with enter and space should look the same

### ISSUE THREAD

**Issue by KunigundaLauly** [cerner/terra-core#3569]
# Bug Report

## Description
Pressing the button with _enter_ and _space_ does not look the same. Currently, pressing with _space_, the background changes, while pressing with _enter_ it remains the same.

## Steps to Reproduce

1. open the following page: https://engineering.cerner.com/terra-ui/components/cerner-terra-core-docs/button/button
2. Press the _space_, while focusing on a terra button.
2. Press the _enter_, while focusing on a terra button.
3. Currently the button pressed states are different.

## Additional Context / Screenshots

![buttons](https://user-images.githubusercontent.com/47626274/148967867-033d4165-5c53-4805-ae3b-4cb9e83ac014.png)
![button-background-color](https://user-images.githubusercontent.com/47626274/148968035-d7556deb-706f-4c26-8ba8-a9c03e290a80.gif)

## Expected Behavior

The button's pressed states should look the same. (or maybe, is this a default workout?)

## Environment

* Component Name and Version: terra-button v3.60.0
* Browser Name and Version: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
* Node/npm Version: [e.g. Node 8/npm 5] -
* Webpack Version: -
* Operating System and version (desktop or mobile): Win 10

**Comment by tiborud** [comment]
We're still experiencing this issue.

**Comment by BenBoersma** [comment]
I took a look at a bunch of different approaches and native-browser handling for button states, which I will include at the bottom of this comment with an audit I did. The main take away however, is that there is not a perfectly universal and consistent standard for how buttons respond in respect with pressing return or spacebar and clicking, though there seems to be a common majority with a few outliers (e.g. Firefox on click).

With that in mind, Terra buttons are currently following the native handling pattern of the common majority of browsers, and as such I am closing this issue.

[Terra Button](https://engineering.cerner.com/terra-core/components/cerner-terra-core-docs/button/about#)
  | Click | Spacebar | Return
-- | -- | -- | --
Chrome <br /> 101.0.4951.64 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css
Firefox <br /> 100.0.1 | On release fires event <br /> While pressed does not change css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css
Safari <br /> Version 15.4 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css
IE 10 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css
MSEdge <br /> 42.17134.1098.0 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css <br /> **While pressed scrolls down** | On down fires event <br /> While pressed does not change css

[Basic Button html tag](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_button_test)
  | Click | Spacebar | Return
-- | -- | -- | --
Chrome <br /> 101.0.4951.64 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css
Firefox <br /> 100.0.1 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css
Safari <br /> Version 15.4 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css
IE 10 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css
MSEdge <br /> 42.17134.1098.0 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> While pressed does not change css

[W3 button examples that don't use button tag](https://www.w3.org/TR/wai-aria-practices-1.1/examples/button/button.html)
  | Click | Spacebar | Return
-- | -- | -- | --
Chrome <br /> 101.0.4951.64 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css
Firefox <br /> 100.0.1 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css
Safari <br /> Version 15.4 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css
IE 10 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css
MSEdge <br /> 42.17134.1098.0 | On release fires event <br /> While pressed changes css | On release fires event <br /> **While pressed does not change css** | On down fires event <br /> While pressed does not change css

[Oracle Jet Cookbook for Buttons](https://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=pushButtons&demo=pushButto) (Specifically the submenu opener button)
  | Click | Spacebar | Return
-- | -- | -- | --
Chrome <br /> 101.0.4951.64 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> **While pressed changes css**
Firefox <br /> 100.0.1 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> **While pressed changes css**
Safari <br /> Version 15.4 | On release fires event <br /> While pressed changes css | On release fires event <br /> While pressed changes css | On down fires event <br /> **While pressed changes css**
IE 10 | **Doesn't Load**
MSEdge <br /> 42.17134.1098.0 | **Doesn't Load**

**Comment by KunigundaLauly** [comment]
Thank you very mutch for the very detailed explanation. I'll foward this to my team. Thanks again :)
