### ISSUE TITLE
Collect performance metrics

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#357]
# Issue Description
In order to create performant code, we want to have performance metrics available.
We'd like to explore options for monitoring and recording performance metrics.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Have performance metrics available.

## Current Behavior
N/A

**Comment by bjankord** [comment]
Using [Google's lighthouse project](https://developers.google.com/web/tools/lighthouse/) seems to be a good way to get some performance metrics. I saw one team that had a bot that posted lighthouse scores on PRs: https://twitter.com/tuttsj/status/863155499390337031

It sounds like they may open source that in the near future.

There is a webpack plugin we could explore using as well: https://github.com/addyosmani/webpack-lighthouse-plugin

**Comment by bjankord** [comment]
I'm thinking we use a tool to keep track of bundle sizes:
https://github.com/siddharthkp/bundlesize  
https://github.com/danvk/travis-weigh-in
https://github.com/ai/size-limit 

We have new relic set up so we are capturing performance metrics there.

It would be cool if we could run the [lighthouse plugin]( https://github.com/addyosmani/webpack-lighthouse-plugin) on travis CI and then report back its output with the Danger file.

**Comment by emilyrohrbough** [comment]
@Blackop778

**Comment by Blackop778** [comment]
Yeah it could probably be worked into what I'm looking at.

**Comment by bjankord** [comment]
Performance metrics are now collected in new relic. If we want to collect additional info, we can check out the spike @Blackop778 did: https://github.com/cerner/terra-toolkit/issues/129
