### ISSUE TITLE
Jest warnings

### ISSUE THREAD

**Issue by sdadn** [cerner/terra-core#3603]
# Description

As a developer, I would like to clean up the jest warnings caused by outdated tests, so that the output is cleaner and doesn't bury any legitimate output. We'll know we're done when there are no more jest warnings.

## Steps to Reproduce

1. Run `npm run compile && npm run jest` on the main branch
2. The jest tests will output warnings

## Additional Context / Screenshots

![CleanShot 2022-03-30 at 13 14 51](https://user-images.githubusercontent.com/38024451/160903553-acf56c6d-21ff-4977-a8c4-e2861d1b3b08.png)

**Comment by chrismichalewicz** [comment]
UXPLATFORM-6602 was logged to track this internally
