### ISSUE TITLE
Add localization to demographics banner.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#363]
# Issue Description
The Demographics Banner right now does not have it's messages localized, as the component wasn't ready for it. Now that the solution for translations is coming through, we need to remove the props that take messages for labels, and replace them with translated messages.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- Props for labels have been removed, and replaced with formatted messages inside the component.

## Current Behavior
Labels for Demographics Banner are only provided in English language.

**Comment by bjankord** [comment]
Resolved in #431
