### ISSUE TITLE
terra install failure(s) because of @types/eslint v8.4.4

### ISSUE THREAD

**Issue by xenoworf** [cerner/terra-core#3638]
Right now terra-core will fail to install because [@types/eslint v8.4.4 was not correctly published](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61032). I'll update this issue once that problem goes away or if we figure out a workaround faster than that.

**Comment by xenoworf** [comment]
A couple workarounds have been posted to that linked issue.

**Comment by saket2403** [comment]
Closing this issue as it was fixed after @types/eslint @8.4.4 was re-released.
