### ISSUE TITLE
Create better docs on how to theme Terra.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#364]
# Issue Description
While the legacy theme has an example of adding a theme to your terra build, it doesn't really explain how to create a themed variable file, and how the process to get those values into the apps webpack build. Most likely, we need a page on terra-site that covers where to find the themable variables, how to setup your themed file, and how webpack should be modified to use those new variables.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The Terra documentation site provides context as to how to create a custom theme for Terra by detailing where to find the variables that are themeable, how the themed files should be structured, and how webpack should be modified.

Also for this issue, perhaps we should add the themeable markdown pages to our doucmentation. We can do it either on each components page, or perhaps make a new themeable page that houses all of the themeable variable markdown pages.

## Current Behavior
No doc exists on how to go about theming terra components.

**Comment by Matt-Butler** [comment]
+1 We need to have this for consumers.

This is also probably going to change pretty drastically soon if we start using styled components.

**Comment by bjankord** [comment]
Agreed, we need this, however let's hold off on this work until we get a css-in-js solution tested out and rolled into the framework.

**Comment by bjankord** [comment]
UX is seems to be hesitant about us documenting how to create custom themes. I believe they would prefer consumers use first class themes provided by UX / Terra. I've documented how to change themes to one of the first class ones here: https://terra-ui.herokuapp.com/getting-started#theming
