### ISSUE TITLE
terra-content-container Scroll wrapper is mandatory for children, causing the terra-overlay to be scrollable

### ISSUE THREAD

**Issue by KunigundaLauly** [cerner/terra-core#3668]
# Bug Report
Scroll wrapper is mandatory for children, causing the terra-overlay to be scrollable.

## Description

We have a terra-overlay and a scrollable view inside a terra-content-container:
`<ContentContainer header={header} footer={footer} fill>
      <>
        {loadingOverlay}
        {view}
      </>
    </ContentContainer>`
When showing the loading overlay, the user still can scroll the view, causing the overlay to scroll too.
Since we need to show the overlay inside the content-container's children, we need here a not-scrollable children option to properly show the overlay on the body of the container.

Tried using the OverlayContainer instead, but this component would make the loading overlay height match the view's height, causing the spinner not to be visible due to the view's big height. (the spinner is positioned in the middle and would not be in the visible part of the view, but its actual middle.)

## Additional Context / Screenshots

![bug](https://user-images.githubusercontent.com/47626274/194033098-af9d30cc-f779-4045-abb5-df3982cc7281.png)

## Expected Behavior

Ability to add a not wrapped in <Scroll children to the container, so we can show the overlay without the ability to scroll it away with its spinner positioned in the middle of the visible view.

## Possible Solution

Please add an extra children prop to the terra-content-container, witch is not wrapped in the Scroll component.
![terra-container-bug-fix-idea](https://user-images.githubusercontent.com/47626274/194028823-069e2f3a-14b6-462c-ab6c-bb26845c73f5.png)

## Environment

* Component Name and Version: Terra Content Container v3.36.1
* Browser Name and Version: Chrome latest
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version: - 
* Operating System and version (desktop or mobile): win10

**Comment by chrismichalewicz** [comment]
UXPLATFORM-7792 has been logged to track this internally.
