### ISSUE TITLE
Add script for lerna publish

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#369]
We are starting to use [lerna publish](https://github.com/lerna/lerna#publish) to release several packages at once. We would like to add a script that uses lerna-publish.

- [x] add script to compile, test, and lerna publish. Similar to what [cloudflare-ui does](https://github.com/cloudflare/cf-ui/blob/master/package.json#L24)
- [ ] remove existing release script: https://github.com/cerner/terra-core/tree/master/scripts/release

**Comment by bjankord** [comment]
I'm on the fence if we should add in a script to run `git pull` when we run the script to make sure the publisher has the latest changes for a branch. This is something I try to do when I publish. While I can't think of a case where you wouldn't want run `git pull` before publishing, I'm sure one exists.

**Comment by bjankord** [comment]
## Tech Design

Looking at other projects that use lerna, it looks like it is common to have the publish script run tests, compile, and lerna publish.

* https://github.com/dadviegas/melpack/blob/998d00140ffaf0ff441143f80a876e51f79d442b/package.json#L9
* https://github.com/suitstack/spacesuit/blob/7bf0fef752658517816a110e2dd5cb0dbe96b955/package.json#L9
* https://github.com/tamoore/todos-redux-lerna/blob/f9d9743ec280589e8c38c356e9f4756cec69134b/package.json#L6

I plan to add the following package, [check-installed-dependencies](https://www.npmjs.com/package/check-installed-dependencies) and add the following script to the root package.json

```json
"scripts": {
    ...
    "publish": "check-installed-dependencies && npm test && npm run compile && lerna publish",
    ...
  },
```

I'm chunking all the commands into the `publish` script as we've run into issues with the `prepublish` command running on `npm install`. More info about that can be found here: https://blog.greenkeeper.io/what-is-npm-s-prepublish-and-why-is-it-so-confusing-a948373e6be1
