### ISSUE TITLE
props-table required props displayed as optional

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#371]
The props table is displaying required props as optional.

**Comment by Matt-Butler** [comment]
We need to update to a newer version of react-docgen:
https://github.com/reactjs/react-docgen/releases/tag/v2.15.0

We are currently locked at 2.13
https://github.com/cerner/terra-core/blob/master/packages/terra-props-table/package.json#L33

**Comment by ryanthemanuel** [comment]
The props table is also showing everything as "custom".  Will this fix that issue as well?

**Comment by Matt-Butler** [comment]
Yes, updating the version will fix everything being shown as "custom" too.
