### ISSUE TITLE
Popup Component

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#374]
# Issue Description
Create a popup component capable of displaying with and without an arrow indicator.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The Terra Popup should allow the dynamic presentation of children elements aligned with a presenting target. The option for an arrow that maintains a correct attachment, regardless of flipping and pinning.

Open questions: 
- What should the prescribed set of sizes be?
- What visual design should be placed on the popup content and arrow?

## Responsiveness:
The Terra popup should be either responsive to a boundingRef container or default to the window for it's bounds and edge pinning. When both vertical and horizontal bounds are breached, a close button should be injected.  Popup dimensions are set heights and widths, from a given subset of prescribed dimensions. The popup will attempt to flip it's positioning should it's initial positioning not allow it's presentation between the bounds and the target element.

## React Props - Popup:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| boundingRef | Function | undefined | |
| children  | node  | undefined     | Required content to display as popup content.|
| classNameArrow | String | null | Class name to append to the arrow element. |
| classNameContent | String | null | Class name to append to the content element inner. |
| classNameOverlay | String | null | Class name to append to the overlay element. |
| contentAttachment | String | 'top center' | String pair of top, middle, bottom, and left, center, right. |
| contentDimensions | String | '25x 25x' | Modifier values based on a 16 x 9 base size. |
| isArrowDisplayed |Bool | false | Should an arrow be presented at the calculated attachment. |
| isHeaderDisabled |Bool | false | Should the default header be disabled for bounds breach.|
| isOpen | Bool | false | Should the popup be displayed.|
| onRequestClose | Function | undefined | Callback function when popup close conditions are met. |
| targetRef | Function | undefined | Required element ref callback to be presented. |

## React Props - _PopupContent:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| arrow | Element | undefined | The arrow to be presented with the frame. |
| arrowPosition | String | 'top' | Margin direction to allow for arrow, 'top', 'bottom', 'left', and 'right'. |
| children | node  | [] | Content to display within the popup content. |
| classNameInner | String | null | Class name to append to the inner content div. |
| closeOnEsc | Bool | false | Should the popup trigger a close event on esc keydown. |
| closeOnOutsideClick | Bool  | false | Should the popup trigger a close event click outside. |
| closeOnResize | Bool | false | Should the popup trigger a close when the window resizes. |
| contentHeight | Number | undefined | Required height of the content in px. |
| contentHeightMax | Number | -1 | Maximum height of the content in px. |
| contentWidth | Number | undefined | Required width of the content in px. |
| contentWidthMax | Number | -1 | Maximum height of the content in px. |
| isHeaderDisabled | Bool | false | Option to disabled the close button when bounds broken. |
| onRequestClose | Function | undefined | Callback function when popup close conditions are met. |
| refCallback | Function | undefined | Callback function to gain access to html ref. |

## React Props - _PopupArrow:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| refCallback | Function | undefined | Callback function to gain access to html ref. |

## React Props - _PopupOverlay:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| children  | Node  | []  | Any child content to be rendered. Used to ferry the popup content onto the dom. |

## React Props - _TetherComponent:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| classes | Object | undefined | A hash of tether classes which should be changed or disabled. |
| classPrefix | String | 'tether' | The prefix placed at the beginning of the default classes. |
| constraints | Array | undefined | Rule set to pass to tether. |
| content | element | undefined | Content to display within the popup frame. |
| contentAttachment | String   | undefined | String pair of top, middle, bottom, and left, center, right. |
| contentOffset | String   | undefined | String pair of top and left offset, ie "10px -4px".  |
| disableOnPosition | Bool | false | Should the tether be disable after presetation. |
| isEnabled | Bool | false | Should element be tethered to the page. |
| optimizations | Object | undefined | The ability to disable "gpu" and "moveElement" optimizations. |
| target | element  | undefined     | Required element to be presented. |
| targetAttachment | String | undefined | String pair of top, middle, bottom, and left, center, right. |
| targetModifier | String | undefined | Can be set to 'visible' or 'scroll-handle'. |
| targetOffset | String | undefined | String pair of top and left offset, ie "10px -4px". |
| onUpdate | Function | undefined | Callback function when each tether component is adjusted. |
| onRepositioned | Function | undefined | Callback function when the tether is moved. |

## Example:
```
import React from 'react';
import Popup from 'terra-popup';

class PopupExampleComponent extends React.Component {
  constructor(props) {
    super(props);
    this.handleButtonClick = this.handleButtonClick.bind(this);
    this.handleRequestClose = this.handleRequestClose.bind(this);
    this.setButtonNode = this.setButtonNode.bind(this);
    this.getButtonNode = this.getButtonNode.bind(this);
    this.state = { open: false };
  }

  setButtonNode(node) {
    this.buttonNode = node;
  }

  getButtonNode() {
    return this.buttonNode;
  }

  handleButtonClick() {
    this.setState({ open: true });
  }

  handleRequestClose() {
    this.setState({ open: false });
  }

  render() {
    return (
      <div>
        <Popup
          classNameArrow="example-arrow-class"
          classNameContent="example-content-class"
          classNameOverlay="example-overlay-class"
          contentAttachment="top center"
          contentDimensions="50x 25x"
          isArrowDisplayed
          disableHeader
          isOpen={this.state.open}
          onRequestClose={this.handleRequestClose}
          targetRef={this.getButtonNode}
        >
          <p>this is example popup content</p>
        </Popup>
        <button onClick={this.handleButtonClick} ref={this.setButtonNode}>
          Example Button Text
        </button>
      </div>
    );
  }
}

export default PopupExampleComponent;
```

**Comment by bjankord** [comment]
This has been released in terra-popup@1.0.0
