### ISSUE TITLE
The type of each prop in the props table is always `custom`

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#377]
The type for all the props in each component in http://engineering.cerner.com/terra-core/#/site and  http://engineering.cerner.com/terra-clinical/#/site is always `custom`. react-docgen used to return the correct type. terra-core currently depends on react-docgen 2.13.0. Looks like this issue is fixed in react-docgen 2.14.0. See https://github.com/reactjs/react-docgen/issues/178

**Comment by emilyrohrbough** [comment]
This [issue](https://github.com/cerner/terra-core/issues/371) also addresses these concerns.
