### ISSUE TITLE
webpack 2.6.0 can't find variable: Promise

### ISSUE THREAD

**Issue by windse7en** [cerner/terra-core#385]
### Description of Issue
After the new release webpack 2.6.0, there is a defect on Promise polyfill.

###System Configuration
#### Component Version
```
"webpack": "^2.4.1"
```

#### Browser and Version
IE 10 & phantomjs (nightwatch test)

### Steps to Reproduce the Issue
1. Make sure you install webpack 2.6.0
2. `npm run start`, try to hit http://localhost:8080/#/tests/button-tests/default in IE 10
3. You will get `can't find variable: Promise` error in the IE console.

### Other Resources
[Webpack issue link](https://github.com/webpack/webpack/issues/4916)

**Comment by windse7en** [comment]
Temporary solution: Lock webpack version to 2.5.1: #386

**Comment by bjankord** [comment]
Looks like this is being fixed in this PR. https://github.com/webpack/webpack/pull/4923
Waiting on a release that includes the fix now before we can unlock webpack version.

**Comment by Matt-Butler** [comment]
It looks the webpack PR has been merged now.
