### ISSUE TITLE
Enhance props table to filter props to display

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#391]
# Issue Description
We have a need to avoid displaying some props in various components. It would be nice to be able to filter which props were displayed for certain components when rendering a prop table.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- [ ] Ability to pass an object to props-table component to use as a filter for props it hides.
- [x] Ability to pass a heading to display component name. Useful for prop tables of sub components.

## Current Behavior
No ability to hide props we don't want to publicize.
No ability to set heading for props table.

**Comment by emilyrohrbough** [comment]
It would also be nice to add an additional prop to handle component name. The default props table displays the title **Props**, but some packages have subcomponents and the current way to distinguish these additional props table is to render a heading above the props title.

**Comment by emilyrohrbough** [comment]
> Ability to pass a heading to display component name. Useful for prop tables of sub components.

This was satisfied in https://github.com/cerner/terra-core/pull/681
