### ISSUE TITLE
Overlay Component

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#394]
# Issue Description
Create overlay component. 

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The overlay component creates an overlay relative to the container which triggered the overlay. 
This component will block interactions and fade out all elements of the triggering container. 

## Current Behavior
N/A

**Comment by emilyrohrbough** [comment]
Resolved in #510

**Comment by bjankord** [comment]
Released at v1.0.0 https://www.npmjs.com/package/terra-overlay
