### ISSUE TITLE
Calendar button on terra-date-picker has type "submit" causing forms to submit.

### ISSUE THREAD

**Issue by viren140290** [cerner/terra-core#396]
## Progress
- [ ] Design Input
- [x] Expected Behaviour
- [x] Tech Design
- [x] Development
- [ ] Functional Validation
- [ ] UX Validation
- [ ] Released

# Bug Report

Request to update terra-date-picker calendar icon to not have type submit. Preferably have a type button instead.

## Expected Behavior

When terra-date-picker is used inside a form, on clicking the calendar icon the calendar should open and the form should not be submitted
## Current Behavior

When terra-date-picker is used inside a form, on clicking the calendar icon the form submits instead of just opening the calendar. The reason for this is the calendar icon is a button with type submit.
## Steps to Reproduce

1. Render terra-date-picker inside a <form>
2. Click the date picker calendar icon.

## Environment

* Component Version: 0.3.1
* Browser Name and Version: Chrome and Firefox
* Operating System and version (desktop or mobile): OSX 10.11.6

**Comment by bjankord** [comment]
Tech Design: Explicitly set `type="button"` on the date picker button to prevent it from acting as `type="submit"`

**Comment by Matt-Butler** [comment]
Technical story only. https://github.com/cerner/terra-core/pull/395 resolves this issue

**Comment by Matt-Butler** [comment]
Released in https://github.com/cerner/terra-core/releases/tag/terra-date-picker%400.3.2
