### ISSUE TITLE
Easier MultiSelectList API

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#397]
# Issue Description
Our current multiselect list api looks as followed

    <MultiSelectList maxSelectionCount={2}>
        <MultiSelectList.Item content={<p>test</p>} key="123" isSelectable />
        <MultiSelectList.Item content={<p>test</p>} key="124" isSelectable />
        <MultiSelectList.Item content={<p>test</p>} key="125" isSelectable />
    </MultiSelectList>

If a user is trying to make all of the items in the list selectable, I find it rather tedious to have to put isSelectable on every single Item.

I propose we offer an api where you can pass a single boolean attribute isWholeListSelectable, or maybe even isSelectable to the parent component that will make all the items selectable by default.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Pass this in to make the entire list selectable

    <MultiSelectList maxSelectionCount={2} isWholeListSelectable>
        <MultiSelectList.Item content={<p>test</p>} key="123" />
        <MultiSelectList.Item content={<p>test</p>} key="124" />
        <MultiSelectList.Item content={<p>test</p>} key="125" />
    </MultiSelectList>

## Current Behavior
If a user is trying to make all of the items in the list selectable, I find it rather tedious to have to put isSelectable on every single Item

**Comment by bjankord** [comment]
My thoughts are a component named `<MultiSelectList>` shouldn't need to set a prop to set all ListItems within it to be selectable. isSelectable should be the default behavior of ListItems within a MultiSelectList. Users would have the option to set `isSelectable={false}` to opt out of the implicit selectability of ListItems within MultiSelectList.

Implementation wise, I see this being clone the children, add `isSelectable` to all `MultiSelectList.Item`s unless`isSelectable={false}` is already set on a `MultiSelectList.Item`

**Comment by dkasper-was-taken** [comment]
This issue is related to #432

**Comment by emilyrohrbough** [comment]
It was decided an exception would be made in regards to defining default boolean props of false. The exception is if a subcomponent is designed to be used by multiple higher order components with different behaviors and these HOC expect varying default properties of the subcomponent, the defaultProps value could be defaulted to undefined. Thus, the HOC is responsible for the default properties. This allows for a cleaner API.

These changes reflect the suggestions made in #439.

Documentation updates have been made in this [pull request](https://github.cerner.com/terra/conventions/pull/23).

**Comment by emilyrohrbough** [comment]
Resolved in #439.

**Comment by bjankord** [comment]
This has been released in terra-list@v0.5.0
