### ISSUE TITLE
Demographics Banner needs default values for all labels

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#399]
# Issue Description
Right now, the Demographics Banner has default labels for date of birth and deceased if values for those are passed into the Demographics Banner props. However, not all of the label props have default values, which they should to make the API easier for consumers to use.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Gestational Age and Post Menstrural Age need default values for their labels.

**Comment by JakeLaCombe** [comment]
Pull Request - https://github.com/cerner/terra-core/pull/411

**Comment by bjankord** [comment]
Does this still need functional verification?

**Comment by JakeLaCombe** [comment]
Yeah, I think it does. Sorry about that. I got too excited when I got the final approvals on the code review.

**Comment by bjankord** [comment]
No worries, I was closing this issue out, then I saw the label was still on here for functional validation so figured I'd check.

**Comment by bjankord** [comment]
With #431 merged, is there anything here that needs functional verification or can this be closed out? @JakeLaCombe @mmalaker

**Comment by mmalaker** [comment]
Functional verification completed on PR #431
