### ISSUE TITLE
Feature to format the date and the value sent back in ISO8601 format

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#401]
# Issue Description
Add feature to format the date and the value sent back in ISO8601 format

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

When the value of the date picker is accessed / returned it is formatted in ISO8601 format

## Current Behavior

When the value of the date picker is accessed / returned, it is formatted as it was entered into the input.

<img width="794" alt="screen shot 2017-05-25 at 4 42 50 pm" src="https://cloud.githubusercontent.com/assets/633148/26471884/42e6328e-4169-11e7-844e-ac9a9e2fa78d.png">

**Comment by dnguyenchevy** [comment]
The real concern with this issue is when you start introducing internationalization.

Looks like there's an internationalization issue already open, https://github.com/cerner/terra-core/issues/246.
