### ISSUE TITLE
Modal Dialog Component

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#416]
# Issue Description
Create Modal Dialog component. 

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The Modal Dialog is a more opinionated, structured HOC of modal. It will include a header, content header, content, and footer subcomponent. 

## Current Behavior
N/A

**Comment by Matt-Butler** [comment]
Work for the modal dialog component has been started on this branch: https://github.com/cerner/terra-core/tree/modal-dialog

**Comment by tm4027** [comment]
we are dividing the elements up and have some requirements around Modals on the TRM side which will be a good starting point.

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by bjankord** [comment]
Closing until we get OCS design input
