### ISSUE TITLE
Adjust focus styles on lists

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#419]
# Issue Description
The focused styles on lists are larger than the list item rows. Also, when an icon is present, the focused style expands around it (see screenshot). This seems isolated to Safari and Chrome.

## Issue Type
Minor cosmetic bug fix.
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Focus outline should be roughly the same size as the list item row.

## Current Behavior
See description

## Steps to Reproduce
1. Go to https://terra-core-deployed-pr-387.herokuapp.com/static/#/site/list on Chrome or Safari.
2. Click or tab to a list item to give it focus.
3. View the focused outline style.

## Environment

* Browser Name and Version: Chrome and Safari

**Comment by mmalaker** [comment]
<img width="478" alt="screen shot 2017-05-30 at 3 35 19 pm" src="https://cloud.githubusercontent.com/assets/22304762/26643740/fd558ef2-45f7-11e7-958e-0e582938308f.png">

**Comment by Matt-Butler** [comment]
It looks like the height of 20px is causing the chevron to expand outside the list item. Removing/updating the height should fix the issue
https://github.com/cerner/terra-core/blob/master/packages/terra-list/src/ListItem.scss#L20

**Comment by Matt-Butler** [comment]
@emilyrohrbough Sorry, I didn't see you had a pull request out for lists.

I have a fix for this issue on this branch: https://github.com/cerner/terra-core/tree/list-focus-style
