### ISSUE TITLE
Triggering select actions with spacebar

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#421]
# Issue Description
Currently, selectable lists and tables can be triggered through keyboard navigation using the tab key to set focus and the enter key to select. For accessibility, we may want to include spacebar as a selection option.

## Issue Type
Spike and minor enhancement
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- Research usage of spacebar as a keyboard selection option
- Utilize spacebar select consistently where appropriate

## Current Behavior
Spacebar does not trigger select on selectable lists or tables.

**Comment by Matt-Butler** [comment]
This should be a pretty quick fix:
List
https://github.com/cerner/terra-core/blob/master/packages/terra-list/src/SingleSelectList.jsx#L6
https://github.com/cerner/terra-core/blob/master/packages/terra-list/src/MultiSelectList.jsx#L6

Table
https://github.com/cerner/terra-core/blob/master/packages/terra-table/src/SingleSelectableRows.jsx#L7

**Comment by emilyrohrbough** [comment]
PR #436 added spacebar selection to tables.

**Comment by emilyrohrbough** [comment]
PR #439 added spacebar selection to lists.

**Comment by bjankord** [comment]
This has been released in terra-list@v0.5.0 and terra-table@v0.6.0
