### ISSUE TITLE
terra-date-picker calendar icon smaller than expected

### ISSUE THREAD

**Issue by viren140290** [cerner/terra-core#422]
# Issue Description

When trying to render terra-date-picker in our rails application, the calendar icon seems to be smaller than the expected size.
![terra-date-picker](https://cloud.githubusercontent.com/assets/1681774/26652694/6598c4b6-4616-11e7-9767-a45ea0cdaa56.png)

The only difference I could see was the calendar button seems to have height set to 24px in my app vs auto on the terra site example

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior

Button has the same height as the input box
## Current Behavior

Button doesn't have the same height as the input box

## Environment

* Component Version: 0.3.2
* Browser Name and Version: Chrome 58.0.3029.110 (64-bit)
* Operating System and version (desktop or mobile): OS X 10.11.6

**Comment by Matt-Butler** [comment]
Hey @viren140290, is there an additional class adding a height of 24px to the button?

**Comment by viren140290** [comment]
@Matt-Butler  the only classes I see on the button are terra-Button terra-Button--default terra-DatePicker-button . We have not added any custom classes or havent added any styles for the  Button element

**Comment by viren140290** [comment]
The whole form is also wrapped with <Base> from terra-base

**Comment by viren140290** [comment]
I dug a lil deeper and realized that in the box model the inner content for my app  is of size
14 * 14 vs on terra's site its 14 * 20

**Comment by bjankord** [comment]
I'm gonna mark this as a bug, but we'll need to have a deeper look into this to figure out what the root cause of this is. Let's plan on syncing up tomorrow @viren140290.

**Comment by benbcai** [comment]
@viren140290 The only [additional style](https://github.com/cerner/terra-core/blob/master/packages/terra-date-picker/src/DatePicker.scss#L31-L41) the date-picker adds to the button is to remove the start border radius and adjust the left margin a bit. Could you add just a [normal button](http://engineering.cerner.com/terra-core/#/site/button) with an icon to your app to see if you see the same thing? Just trying to see if this happens only with the calendar button or all buttons in your app.

**Comment by Matt-Butler** [comment]
The difference between the two datepicker buttons is the padding:

![screen shot 2017-06-02 at 1 48 01 pm](https://cloud.githubusercontent.com/assets/8146159/26740176/2aa572ca-479a-11e7-9e09-74e47ae50905.png)
terra example is the padding on the right.

**Comment by Matt-Butler** [comment]
I am having a difficult time narrowing this issue down to which css is causing this issue. We need to update the height of the datepicker button to scale with the font-size. Below you can see as we update the font-size, the datepicker button maintains a static height.

![datepicker](https://cloud.githubusercontent.com/assets/8146159/26740435/269fdbb0-479b-11e7-99b7-f752a261d7b1.gif)

**Comment by Matt-Butler** [comment]
The search field component is going to have pretty similar styling as this component. We should probably have the two components match.
