### ISSUE TITLE
Time-input Component

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#424]
# Issue Description
Create a time input component

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The time input component should internally compose two independent inputs: an hour input for entering the hour and a minute input for entering the minute. Having two separate inputs makes managing user interaction easier. The component should appear visually as just one time input.The component should automatically prepend a 0 to the hour if the entered value is between 3 and 9 for the hour and prepend a 0 to the minute if the entered value is between 6 and 9. For example, the the user type 5 followed by 8, the time should a appear as 05:08. Pressing the Up arrow key should increment the hour or minute by 1 and pressing the down arrow key should decrement the hour or minute by 1. Pressing the left or right arrow key should go back and forth between the hour and minute inputs. The component will support only the 24-hour format. Support the 12-hour format with AM/PM will be a future enhancement.

## Current Behavior
N/A

**Comment by bjankord** [comment]
This component has been released to npm: https://www.npmjs.com/package/terra-time-input
