### ISSUE TITLE
List Add additional examples for functional verification

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#426]
# Issue Description

Add additional examples for functional verification.  We currently have examples with text, we should add additional examples with several different types of content.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior

Additional examples with different types of content have been added for list

**Comment by mmalaker** [comment]
Verification completed on PR #423
