### ISSUE TITLE
Update Demographics examples to use the Image component for the patient photo

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#428]
# Issue Description
It would be a more helpful example for our consumers to use the Image component for the patient photo.  That way they can get the bigger picture of the entire ecosystem

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/pull/431

**Comment by windse7en** [comment]
Close this issue, as it's merged into master by #431 PR.
