### ISSUE TITLE
Move terra-toolkit into its own repo

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#430]
# Issue Description
Moving terra-toolkit into its own repo will allow us to reduce the slug size of terra-core.  It will also allow us to more closely align the structure of the nightwatch tests between terra-core and terra-clinical

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

**Comment by windse7en** [comment]
# Issue Description
There is a relative path based on the current command directory, it throws the No such file error when we run `npm run test:nightwatch-default` under `pacakges/.../` folder. Error message screenshot:
![screen shot 2017-06-22 at 11 21 07 am](https://user-images.githubusercontent.com/3724179/27487997-0efe0c8c-57fb-11e7-8e4f-7ba56c373447.png)


## Current Behavior
In `node_modules/terra-toolkit/lib/scripts/nightwatch.js`, line 12 to use file absolute path:

## Fix it temporarily
Update to path based on the file directory:
```
if (shell.exec(resolve(__dirname, 'nightwatch-process.js') + ' --config tests/nightwatch.conf.js -e ' + driver + '-tiny,' + driver + '-small,' + driver + '-medium,' + driver + '-large,' + driver + '-huge,' + driver + '-enormous').code !== 0) {`
```

And update relative path in terra-clinical-action-header `package.json`
```
"test:nightwatch-default": "WEBPACK_CONFIG_PATH=../../../packages/terra-clinical-site/webpack.config SPECTRE_TEST_SUITE=terra-clinical-action-header node ../../node_modules/terra-toolkit/lib/scripts/nightwatch.js",`
```

After those, `npm run test:nightwatch-default` works in package level and root level.

## Steps to Reproduce
1. Clone and install the `terra-clinical` repo.
2. Change directory to any specified package like `packages/terra-clinical-action-header/`
3. Run `npm run test:nightwatch-default`, you will see the error.

**Comment by emilyrohrbough** [comment]
Resolved. Moved to new repository in this PR https://github.com/cerner/terra-toolkit/issues/1 and removed from terra-core in #613.
