### ISSUE TITLE
Selectable Lists need the ability to selectively enabled/disabled chevrons and selectability.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#432]
# Issue Description
Previously SingleSelectList and MultiSelectList defaulted their children to isSelectable true, and would set the value of it's children's hasChevron according to it's own hasChevrons prop. This provided that the child items hadn't explicitly set their own isSelectable and hasChevron prop, in which case it would use that value.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Given the intention was to prevent an unset bool, the best course might be for ListItem to not default boolean values, but have the HOC of multi and single select be defaulted.  As the 4 checks in the ListItem are looking for a positive value, this shouldn't hurt the ListItem's functionality within the basic List implementation.

**Comment by emilyrohrbough** [comment]
It was decided an exception would be made in regards to defining default boolean props of false. The exception is if a subcomponent is designed to be used by multiple higher order components with different behaviors and these HOC expect varying default properties of the subcomponent, the defaultProps value could be defaulted to undefined. Thus, the HOC is responsible for the default properties. This allows for a cleaner API.

This addresses the issue #397 

Documentation updates have been made in this [pull request](https://github.cerner.com/terra/conventions/pull/23).

**Comment by emilyrohrbough** [comment]
Resolved in #439.

**Comment by bjankord** [comment]
This has been released in terra-list@v0.5.0
