### ISSUE TITLE
Datepicker date format is hard coded

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#433]
# Issue Description

The datepicker date format is currently hard coded to `'MM/DD/YYYY'`. We need to allow consumers to pass in a date format as props.

https://github.com/cerner/terra-core/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L139
https://github.com/cerner/terra-core/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L72

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Placeholder date format can be changed through props.

## Current Behavior
Placeholder date format cannot be changed through props.

**Comment by Matt-Butler** [comment]
We should be able to use the formats from moment: 
http://momentjs.com/docs/#/i18n/locale-data

Under localized-formats

```
moment().format('[today] L'); 
```

If we update locale, it should update the format we need.

**Comment by benbcai** [comment]
We decided not to add the format prop for consumers to specify a format to use. The design of the date-picker component is that it will only support one date format per locale. The format will be what is defined by the `L` property in the locale data in Moment for that given locale. For example, if the provided locale is `en`, the format will be `MM/DD/YYYY`, which is also being used as the placeholder text. The following are the defined `L` format for each of our currently supported locales:

```javascript
moment.locale('de');                                     // 'de'
moment().format('L');                                    // '21.06.2017'
moment.localeData()._longDateFormat.L    // 'DD.MM.YYYY'

moment.locale('en');                                     // 'en'
moment().format('L');                                    // '06/21/2017'
moment.localeData()._longDateFormat.L    // 'MM/DD/YYYY'

moment.locale('en-GB');                               // 'en-gb'
moment().format('L');                                    // '21/06/2017'
moment.localeData()._longDateFormat.L    // 'DD/MM/YYYY'

moment.locale('es');                                     // 'es'
moment().format('L');                                    // '21/06/2017'
moment.localeData()._longDateFormat.L    // 'DD/MM/YYYY'

moment.locale('fi-FI');                                   // 'fi'
moment().format('L');                                    // '21.06.2017'
moment.localeData()._longDateFormat.L    // 'DD.MM.YYYY'

moment.locale('fr');                                       // 'fr'
moment().format('L');                                    // '21/06/2017'
moment.localeData()._longDateFormat.L    // 'DD/MM/YYYY'

moment.locale('pt');                                      // 'pt'
moment().format('L');                                    // '21/06/2017'
moment.localeData()._longDateFormat.L    // 'DD/MM/YYYY'
```

The work to internationalize the date picker will be on https://github.com/cerner/terra-core/issues/246
