### ISSUE TITLE
Spike on replacing phantomJS usage with headless chrome

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#440]
# Issue Description
[Now the Chrome 59 is released on the stable channel](https://chromereleases.googleblog.com/2017/06/stable-channel-update-for-desktop.html), we can start to exploring replacing our usage of phantomJS in terra-toolkit with the headless mode in Chrome.

More info on using headless Chrome:
* https://developers.google.com/web/updates/2017/04/headless-chrome
* https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Explore what work is need to replace PhantomJS usage in terra-toolkit with headless mode Chrome.

**Comment by Matt-Butler** [comment]
https://github.com/nightwatchjs/nightwatch/issues/1439

**Comment by bjankord** [comment]
Related: https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

**Comment by bjankord** [comment]
With terra-toolkit v2 released, it now uses headless chrome
