### ISSUE TITLE
Demographics Banner photo size

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#441]
# Issue Description

We need to add default height/width for the demographics banner photo.
https://github.com/cerner/terra-core/blob/master/packages/terra-demographics-banner/src/DemographicsBanner.scss

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Differently sized images fit inside the demographics banner.

## Current Behavior

Image size is currently unstyled.

**Comment by JakeLaCombe** [comment]
Is this something that the Demographics Banner should be supporting? While I agree that you the image size needs to be restricted in this component, I feel that's more of a responsibility on the developer ensuring the image is created with the appropriate size as opposed to the demographics banner adjusting it for them.
