### ISSUE TITLE
Localize date of birth in demographics banner

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#446]
# Issue Description
Demographics banner currently has text translations that flex by locale, but does not flex the date of birth format.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The date of birth format flexes to the correct format when locale changes.

## Current Behavior
The date of birth format is static.

**Comment by JakeLaCombe** [comment]
Personally, I don't think the demo banner should be applying i18n to the Date of birth, as different apps at Cerner have different standards for how the date is displayed.

For this issue, I think it's more of an issue with updating the doc site to translate the date of birth before it is passed in as opposed to having the banner do this.

**Comment by mjhenkes** [comment]
+1 I agree with Jake

**Comment by mmalaker** [comment]
Closing as locale switching is not applicable to DOB in demo banner

**Comment by bjankord** [comment]
Released in terra-demographics-banner@0.4.0
