### ISSUE TITLE
Button default type attribute

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#453]
# Issue Description
For button, we need to add a prop for type and default type. Currently, type is not required for the button component.

```
Always specify the type attribute for the <button> element. Different browsers may use different default types for the <button> element.
```
https://www.w3schools.com/tags/att_button_type.asp

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by bjankord** [comment]
Resolved in #468
