### ISSUE TITLE
Add prevent defaults to onKeyDown event handlers

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#455]
# Issue Description
Add prevent defaults to onKeyDown event handlers within the SingleSelectList, MultiSelectList, and SingleSelectableRows components.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by Matt-Butler** [comment]
What issue are we solving by adding prevent default to these components?

**Comment by emilyrohrbough** [comment]
When @dkasper-was-taken was working on popup, he noticed we never provided a preventDefault when keydown occurs.  He was using a button to launch the popup and when a keyDown event occurred, the popup keyDown event was also being triggered, causing an infinite loop of presenting the popup.

**Comment by Matt-Butler** [comment]
@emilyrohrbough thanks for the info

**Comment by emilyrohrbough** [comment]
Resolved in #521
