### ISSUE TITLE
Phase 1 / Q2 

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#456]
# Issue Description
Issue to keep track of miscellaneous tasks to complete before we release v1. Phase 1 / Q2 will be complete Jun 30th. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other
---
### Todo:
- [ ] Constrain dependencies @ 1.x

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/commit/26b5745da79bda497dfc12a48f12add146193aa3
