### ISSUE TITLE
Only lint/test packages that have impacted tests

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#46]
# Issue Description
Linting/Testing is starting to take a bit of time. We should investigate only testing packages that have impacted tests.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Only lint/test packages that have modified code.

## Current Behavior
CI runs lint/tests for all packages.

**Comment by Matt-Butler** [comment]
https://codersmind.com/eslint-changed-files-upgrade-codestyle/

**Comment by Matt-Butler** [comment]
https://facebook.github.io/jest/docs/cli.html#lastcommit

**Comment by bjankord** [comment]
Yeah these are good resources. I think the bulk of the time spent on tests is with the nightwatch tests. If we can identify a way to only run the nightwatch tests for components that have been updated, we'd see a big time reduction when it comes to tests.

**Comment by bjankord** [comment]
lerna@v2.0.0-rc.5 added an `--only-updated` option to exec and run subcommands. This would look like `lerna run --only-updated test` which would run the npm `test` script in only packages that have been updated since the last tag was created.
