### ISSUE TITLE
Update to the newest SVG icons

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#465]
# Issue Description

Update to the newest SVGs in cerner-one-style-icons. There have been changes since the initial 1.0 release.
https://github.com/cerner/terra-core/blob/master/packages/terra-icon/package.json#L25

https://github.com/cerner/one-cerner-style-icons/commits/master

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by mjhenkes** [comment]
@Matt-Butler @neilpfeiffer Should we wait until they have a tagged release or just update to master?

**Comment by ryanthemanuel** [comment]
Should we try and get on a schedule with these updates, so none of us forget?

**Comment by bjankord** [comment]
I'd prefer to wait for a tagged release so its more predictable what we're getting. We should reach out to them and see if need any help releasing.

**Comment by Matt-Butler** [comment]
We should wait for a tagged release on github.

**Comment by PaulSolDev** [comment]
Orion JIRA created
