### ISSUE TITLE
[terra-image] Add onLoad and onError to determine if an image successfully loaded

### ISSUE THREAD

**Issue by mschile** [cerner/terra-core#466]
# Issue Description
In order to determine if an image successfully loaded or not, two new func properties, onLoad and onError, should be added to terra-image and set on the underlying img.

This functionality is needed for #429.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
onLoad or onError is called when image loads or fails.

## Current Behavior
N/A

**Comment by Matt-Butler** [comment]
resolved in https://github.com/cerner/terra-core/pull/474
