### ISSUE TITLE
Border around Container Component

### ISSUE THREAD

**Issue by KwarnerCernerUX** [cerner/terra-core#467]
# Issue Description

Looking to add a border around the container component to help differentiate multiple containers on a page.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Border - border: 1px center * #BCBFC0 100%opacity: 100%radius: 0px

## Current Behavior

Currently there is no border around the container component, so it's essentially floating content.

**Comment by neilpfeiffer** [comment]
Met with Laura, the Kiosk project designer needing the initial enhancement request and it is no longer needed. Closing Issue.

**Comment by papasmile** [comment]
Our main use case for visually contained content would be solved by fixed table headers, see https://github.com/cerner/terra-core/issues/1101
