### ISSUE TITLE
Base component add terra-Base class on html tag

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#490]
# Issue Description
We discussed in a meeting the other day about having the base component automatically add the class `terra-Base` on the html tag.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
In meeting on June 22, 2017 we talked about just dropping the `terra-Base` class from the codebase altogether and having the global styles target `html` and `body` elements directly.
