### ISSUE TITLE
Base component lang tag

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#491]
# Issue Description
We discussed in a meeting last week about having the base component ensure locale is in sync with the html lang tag. When in non-prod, the base component should thrown an error when the locale and html lang tag do not match. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
In meeting on June 22, 2017, @mhemesath mentioned we need to be careful with how we implement this if we do it as there can be nested locales in certain applications.
