### ISSUE TITLE
Button group onChange wrong index

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-core#493]
# Issue Description
[This function](https://github.com/cerner/terra-core/blob/master/packages/terra-button-group/src/ButtonGroup.jsx#L82) assumes that setState is a synchronous function. However, this is not the case, and thus the onClick function passes the wrong selectedIndex to the onChange method.

## Issue Type
- [X] Bug

## Expected Behavior
The method should passes the new selectedIndex, not the old one.

## Current Behavior
The code as is passes the previously selected index. The visual updates fine as the state is updated, but because of the order of events, the onChange receives the wrong parameter.

## Environment

* Component Version: 0.1.0, but master is still wrong
* Browser Name and Version: All
* Operating System and version (desktop or mobile): desktop mac

**Comment by Matt-Butler** [comment]
Resolved in #495
