### ISSUE TITLE
Form examples display submission values

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#494]
# Issue Description

In all of our form component examples, it would be useful for consumers to be able to view the submission values. The example at the bottom of the form page demonstrates this: http://engineering.cerner.com/terra-core/#/site/form. We should do the same for all of the form components so we can test the expected behavior:
- [ ] date picker
- [ ] time input
- [ ] select
- [ ] search field

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
The Date Picker component updates the input box with the selected calendar date. Additionally, an example is provided which displays the selected date retrieved via an onChange callback.

<img width="478" alt="screen shot 2017-07-26 at 4 27 07 pm" src="https://user-images.githubusercontent.com/14099737/28644525-8ad22f62-721f-11e7-9c8d-9ce4334cac89.png">

**Comment by bjankord** [comment]
This has been released in terra-site@1.5.0
