### ISSUE TITLE
Spike on visual regression test strategy

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#497]
# Issue Description
We have code in place to generate screenshots with our nightwatch tests. The next step we need to figure out is how we can set up visual regression testing with the screenshots. This spike is to explore this concept.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Visual regression testing strategy proposal documented.

**Comment by mjhenkes** [comment]
Something to investigate:
https://github.com/tacoss/dayguard

**Comment by bjankord** [comment]
Spike: https://docs.google.com/document/d/111IJcMLKueMtlq_DlpWgABmoIJPJURdOED6IJIudA90/edit

**Comment by bjankord** [comment]
With https://github.com/cerner/terra-toolkit/pull/18 merged down, I think we can close this. What do you think @mhemesath @mjhenkes ?
