### ISSUE TITLE
Spike on accessibility testing strategy

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#498]
# Issue Description
We have code in place to run accessibility tests with our nightwatch tests. The next step we need to figure out is how we can set up tooling for accessibility testing. This spike is to explore this concept.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Accessibility testing strategy proposal documented.

**Comment by bjankord** [comment]
React added new doc on accessibility: https://facebook.github.io/react/docs/accessibility.html

[Recommends taking a look at](https://facebook.github.io/react/docs/accessibility.html#testing-accessibility-in-the-browser) the following projects:

* https://www.deque.com/products/axe-core/
* https://github.com/dequelabs/react-axe

**Comment by Matt-Butler** [comment]
https://github.com/GoogleChrome/lighthouse#using-the-node-cli

**Comment by Matt-Butler** [comment]
In this video they demonstrate their travis-ci + lighthouse setup.
https://www.youtube.com/watch?v=CubrYp4cuyY&list=PLNYkxOF6rcIA3IPVZzQw1RrFVud3_qcAY

**Comment by bjankord** [comment]
Plan is to move forward with use https://github.com/dequelabs/axe-core to drive our programmatic accessibility testing. Work is being done in terra-toolkit to add this into our testing framework.
