### ISSUE TITLE
Add npm whoami check when publishing

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#522]
# Issue Description
To ensure we are using an authenticated NPM account when we run the publish command, we should check using `npm whoami` and bail if we are not signed in to an authenticated account

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Check `npm whoami`  an ensure we're logged into to an authenticated NPM account before continuing with the publishing scripts.

## Current Behavior
Users can run the publish script without being logged into NPM. This results in tags being created but nothing is published to NPM. This puts the repo in an odd state as trying to publish with lerna will note there are no changes since the last commit.

**Comment by emilyrohrbough** [comment]
This issue was resolved with PR #711.
