### ISSUE TITLE
Time input colon underlined on safari

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#527]
# Issue Description

Time input colon underlined on safari

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Chrome:
![screen shot 2017-06-28 at 10 20 59 am](https://user-images.githubusercontent.com/8146159/27645414-9dc5e86a-5beb-11e7-92cc-35637b7ec2ab.png)

## Current Behavior

Safari:
<img width="125" alt="screen shot 2017-06-28 at 10 20 53 am" src="https://user-images.githubusercontent.com/8146159/27645424-a61777c2-5beb-11e7-835c-2578fecf9b81.png">

Underline under the colon

**Comment by bjankord** [comment]
# Tech Design

Adding `padding: .1em 0;` to the `time-input` [selector](https://github.com/cerner/terra-core/blob/master/packages/terra-time-input/src/TimeInput.scss#L4) should resolve this.

<img width="1300" alt="screen shot 2017-07-28 at 10 49 06 am" src="https://user-images.githubusercontent.com/633148/28725236-824c32d4-7382-11e7-9a00-dc553e5244ff.png">

**Comment by jordanlawrence15** [comment]
design looks good.
