### ISSUE TITLE
Update search field styles on iOS devices

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#528]
# Issue Description

The search field text boxes have rounded corners on iOS 10.2

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

<img width="247" alt="screen shot 2017-06-28 at 10 26 17 am" src="https://user-images.githubusercontent.com/8146159/27645668-406f842c-5bec-11e7-9b65-8b5ae5110cb1.png">

## Current Behavior

iOS 10.2

![searchfield](https://user-images.githubusercontent.com/8146159/27645877-e145c2a8-5bec-11e7-97a9-bf88ba8428ae.png)

**Comment by bjankord** [comment]
Take a look at: https://css-tricks.com/webkit-html5-search-inputs/

**Comment by bjankord** [comment]
This currently has the following styles applied, though it is still rendering oddly in Mobile Safari.
```css
    -webkit-appearance: textfield;
    -moz-appearance: textfield;
    appearance: textfield;
```

<img width="1340" alt="screen shot 2017-08-30 at 8 49 29 am" src="https://user-images.githubusercontent.com/633148/29875678-5743427e-8d60-11e7-9777-7da88ad9ec7e.png">

**Comment by bjankord** [comment]
## Tech Design
I plan to switch the `appearance: textfield;` line to `appearance: none;`. This will allow the input to render like other text based inputs.

<img width="1337" alt="screen shot 2017-08-30 at 9 08 02 am" src="https://user-images.githubusercontent.com/633148/29876568-cfe52038-8d62-11e7-882c-348a16bfe44a.png">
