### ISSUE TITLE
Multi-Select List Interaction Styles

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#529]
# Issue Description

The multi-select list item background stays highlighted when it is unselected.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

List item is not highlighted when deselected

## Current Behavior

List item is highlighted when deselected

![list_item_deselect_ios10](https://user-images.githubusercontent.com/8146159/27646490-5cefb8cc-5bee-11e7-8915-624e22ad86e5.png)

## Steps to Reproduce

1. Visit the list examples on an iOS device
2. Select a multiselect list item
3. Deselect an item
4. The item is has a highlighted background color.

## Environment

* Component Version: 0.9
* Browser Name and Version: Safari 10.2
* Operating System and version (desktop or mobile): iOS 10.2

**Comment by emilyrohrbough** [comment]
Looking into the issue, the list items are being deselected correctly. The reason the item has a highlighted background is the onHover and onFocus styles are being applied. This 'focus' color is slight lighter than the selected color. However, the colors are very similar which can be confusing.

![listselections](https://user-images.githubusercontent.com/14099737/28801671-32d30b54-7618-11e7-92c9-1d3adf9e0990.gif)

@neilpfeiffer Do you have an suggestions on this logged issue?
