### ISSUE TITLE
Modal Manager does not scale with font-size

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#530]
# Issue Description

When using a different base font-size, the modal manager does not position correctly.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

The modal is positioned in the center of the viewport

## Current Behavior

The modal is positioned in the top left

 of the viewport

## Steps to Reproduce

1. Change the font-size to very large
2. Open the modal manager example

![modal_manger](https://user-images.githubusercontent.com/8146159/27646957-af031f2c-5bef-11e7-8e4e-cbfcce38629b.gif)

## Environment

* Component Version: 0.1.0
* Browser Name and Version: Chrome (v 58)
* Operating System and version (desktop or mobile): desktop

**Comment by dkasper-was-taken** [comment]
While we are updating this, UX will be giving us new sizes for the modal. Similar to the grid system setup with popup. I imagine those changes could be incorporated into this.

**Comment by emilyrohrbough** [comment]
Resolved in PR #611
