### ISSUE TITLE
Remove red ring from required fields in Firefox

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#531]
# Issue Description
In Firefox, it looks like the form inputs that have a `required` attribute on them are displaying with a red outline. This is likely a Firefox specific style. We'll want to remove this to normalize the look of form fields across the supported browsers.

<img width="1159" alt="screen shot 2017-06-28 at 1 10 13 pm" src="https://user-images.githubusercontent.com/633148/27653102-a387d548-5c03-11e7-8df9-15452fd482e5.png">

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Required fields do not display a red outline around the input

## Current Behavior
Required fields display a red outline around the input

## Steps to Reproduce

1. Navigate to https://terra-ui.herokuapp.com/components/core/form
2. Scroll down to one of the examples that includes a required form input

## Environment

* Component Version: Form Version: 0.6.0
* Browser Name and Version: Firefox 54.0 
* Operating System and version (desktop or mobile): Desktop (Mac)

**Comment by Matt-Butler** [comment]
<img width="459" alt="screen shot 2017-07-06 at 12 14 22 pm" src="https://user-images.githubusercontent.com/8146159/27923711-f0807afc-6244-11e7-9178-26e88b7323eb.png">
