### ISSUE TITLE
Stylelint deprecation warning

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#534]
# Issue Description

```
Deprecation Warning: 'selector-no-id' has been deprecated and in 8.0 will be removed. Instead use 'selector-max-id' with '0' as its primary option. See: https://stylelint.io/user-guide/rules/selector-no-id/
```
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by bjankord** [comment]
stylelint-config-sass-guidelines v2.2.0 has been released which bumps stylelint version to 7.12.0 and replaces deprecated `selector-no-id` rule with `selector-max-id` rule.
[These lines](https://github.com/cerner/terra-core/blob/master/package.json#L91-L92) with the caret should pull in these latest releases.

Ran `npm test` on master on a clean install and I'm no longer seeing the deprecation warnings.
