### ISSUE TITLE
Update demographics to use heading component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#535]
# Issue Description

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

## Pull Request to resolve Issue: 
[Explicitly set font-size / line-height for person name - PR #779 ](https://github.com/cerner/terra-core/pull/779)

**Comment by sbshetty01** [comment]
@mmalaker @bjankord the person name appears to be much larger in size in IE11 compared to the other browsers. I am guessing that should be fixed by this switch. Something we noticed when we switched to using the Heading component in our application.

**Comment by emilyrohrbough** [comment]
The change needed for this conversion replaces

```
<h1> ... </h1>
```
with 
```
<Heading level={1} > ... </Heading>
```

This changes the font sizes to `2.286 rem` from `1.5 em`. @neilpfeiffer what is the appropriate [heading size](http://engineering.cerner.com/terra-core/#/site/heading) to use to make this change? Below is a screenshot of the proposed changes on the left compared to current implementation.

![screen shot 2017-08-01 at 2 25 33 pm](https://user-images.githubusercontent.com/14099737/28843132-b3e81628-76c5-11e7-8842-dae1a69c62bd.png)

**Comment by emilyrohrbough** [comment]
The direct size conversion would be `2.14 rem` which is not size option of the heading component.

**Comment by bjankord** [comment]
I'd prefer we set the font-size for the heading element in [DemographicsBanner.scss](https://github.com/cerner/terra-core/blob/master/packages/terra-demographics-banner/src/DemographicsBanner.scss) compared to using the `<Heading />` component. This will give us more direct theming capabilities which will be scoped locally to the demographic banner styles.

**Comment by tm4027** [comment]
Mike McCurdy working on this

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by jordanlawrence15** [comment]
At any size larger than small: 1.286 rem
Small/tiny: 1.143 rem
