### ISSUE TITLE
No OnChange Callback on KeyDown Changes

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#536]
# Issue Description
Users have the ability to change the time input by manually inputing time or using the keyboard arrows. When the keyboard errors are used to change the time, there is no onChange check or callback occurring.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
On any input change, the onChange prop is checked and called if appropriate.

## Current Behavior
Currently we are not checking for `this.props.onChange` within the `handleInputKeyDown` function. Added these lines after setting the state would fix the issue.

```
    if (this.props.onChange) {
      let enteredTime;
      if (type === inputType.HOUR) {
        enteredTime = stateValue.concat(':', this.state.minute);
      } else {
        enteredTime = this.state.hour.concat(':', stateValue);
      }

      this.props.onChange(event, enteredTime);
    }
```

**Comment by bjankord** [comment]
That has been released in terra-time-input@1.2.0
