### ISSUE TITLE
Allow for assignment of SelectField option values

### ISSUE THREAD

**Issue by madelineisabelle** [cerner/terra-core#538]
# Issue Description
SelectFormField only lets you set the display of a select field, which will be inconvenient with translations. Adding the ability to set both the display and value of each option in a SelectField would fix this.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The SelectField should let the consumer set both the value and display for an option.

## Current Behavior
The SelectField only takes in a display for each option and uses that as the option's value.

**Comment by emilyrohrbough** [comment]
Released in terra-forms v1.2.0
