### ISSUE TITLE
Minor mistakes in terra-form

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#540]
# Issue Description
Terra form has a few mistakes to it
- Field has the wrong import in the doc file. It should say 'terra-form/lib/field', not 'terra-form/lib/fieldset'
- For the numberfield, defaultValue should allow for proptypes of both string and number.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by bjankord** [comment]
Released in terra-form v1.2.0
