### ISSUE TITLE
NumberField component do not set value to empty string when NumberField value is zero

### ISSUE THREAD

**Issue by nagrawal3** [cerner/terra-core#544]
# Issue Description

Not able to empty the number field if the previous value set on number field is 0.

Below are the screen shots explaining the same:

In the below picture, both the number fields have some value set
<img width="501" alt="screen shot 2017-07-03 at 3 05 41 pm" src="https://user-images.githubusercontent.com/11468095/27806650-63882950-6001-11e7-9699-f44c81990fff.png">

Upon click on clear button, I am again rendering the number fields by sending the value as empty string (''). The number field which has non-zero value is being emptied, but the other one still shows 0
<img width="499" alt="screen shot 2017-07-03 at 3 05 55 pm" src="https://user-images.githubusercontent.com/11468095/27806651-63910f0c-6001-11e7-8589-46e9577c5989.png">

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

NumberFiled should be set to empty when value attribute is provided with empty string.
## Current Behavior

In the above scenario still able to see 0 displayed on the NumberField.

## Environment

* Component Version: 1.0.0
* Browser Name and Version: Safari 10.1.1
* Operating System and version (desktop or mobile): Mac OS X El Capitan 10.11.6

**Comment by JakeLaCombe** [comment]
Would you be able to provide code to see the example? I'm curious as if this is a problem with just control or uncontrolled values

**Comment by JakeLaCombe** [comment]
After investigation, this appears to be an issue on the application side. If other issues occur, feel free to log them here!
