### ISSUE TITLE
Convert Responsive Element component to CSS modules

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#561]
# Issue Description
To better align with modern CSS practices and modern CSS theming capabilities, we want to update this component to use CSS modules and if applicable, CSS custom properties.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Component styles are converted to use CSS modules. If applicable, convert SCSS variables to CSS custom properties.

## Current Behavior
Component styles use manual name spaced classes and SCSS variables.

**Comment by Matt-Butler** [comment]
We can clean up a lot of the code in the responsive element by doing something like this:

breakpoints.scss
```
:export {
  tiny: 544;
  small: 768;
  medium: 992;
  large: 1216;
  huge: 1440;
}
```

ResponsiveElement.jsx
```
import breakpoints from './breakpoints.scss'

console.log(breakpoints.tiny);
// returns 544
```

**Comment by bjankord** [comment]
I'll plan on picking this one up. The export feature looks nice.

**Comment by mhemesath** [comment]
The exports is nice but it creates an inconsistency with custom properties. The export is defined at transpile time but the custom properties can change past that. It's OK if we want use the exports, but we'll need the ability to override those defaults so that if anyone needs dynamic breakpoints (via theming) they can create a container component to wrap this one and set that dynamically.

**Comment by mhemesath** [comment]
Even more ideal would be the ability for the component to handle being passed integers OR custom properties. If handled custom properties, it would simply look up the value. This would future proof the component when we switch to 100% custom props that aren't compiled down.

**Comment by bjankord** [comment]
Yeah I think the tricky thing with this component is CSS custom properties don't work inside of media queries. 

From the [spec](https://www.w3.org/TR/css-variables-1/#using-variables),
> The var() function can be used in place of any part of a value in any property on an element. The var() function can not be used as property names, selectors, or anything else besides property values. (Doing so usually produces invalid syntax, or else a value whose meaning has no connection to the variable.)

Essentially, you can't use it in a media query.
I haven't spent much time thinking on how to solve this but I think it will be tricky.

**Comment by bjankord** [comment]
Closing this as no longer applicable.

**Comment by mhemesath** [comment]
Why is this no longer applicable?

**Comment by bjankord** [comment]
Reopening, we'll look into using the export syntax used here: https://github.com/cerner/terra-core/blob/918d02e27f5e1cf10e2b7ffd9e51a3a824166f44/packages/terra-dynamic-grid/src/DynamicGrid.scss
