### ISSUE TITLE
Lerna V2

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#582]
# Issue Description

## Lerna v2 has been released
https://github.com/lerna/lerna/releases/tag/v2.0.0

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
Build is failing, once that is stabilized, we can update to v2.0.0 https://travis-ci.org/lerna/lerna/builds
