### ISSUE TITLE
Update Modal to use overlay

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#601]
# Issue Description

We built the modal with overlay before we built an overlay component. Now that we have an overlay component done, the modal should be composed of the overlay. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by emilyrohrbough** [comment]
At this time the integration of terra-overlay
