### ISSUE TITLE
ModalManager container causes incorrect layout when inside overflow

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#610]
# Issue Description

The container element that the ModalManager renders inside the modal has a few styles that aren't necessary to function and create issues in situations when the body element is overflowed.

The styles just need to be removed.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

The ModalManager presentation should not affect body scroll position.

## Current Behavior

The ModalManager presentation causes the body to scroll to top and remains there even after closing the modal.

**Comment by emilyrohrbough** [comment]
Resolved in #611
