### ISSUE TITLE
Normalize CSS custom property naming convention

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#619]
# Issue Description
With converting SCSS variables to CSS custom props, we've diverged on naming the variables.
To help normalize the naming, I propose we keep it simple for CSS custom property names and go with all lower-case and separate words with single hyphen.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
CSS custom property names normalized to  follow all lower-case / single hyphen to separate words naming convention

## Current Behavior
CSS custom property names follow SUIT CSS naming convention

**Comment by mhemesath** [comment]
I think we should follow the same naming convention as the rfc.. specifically that we do

```
--<ns>-<module>-<cssproperty>--<modifier>
```

This is easier to read than separating everything with dashes. If a property is multiple words it should be camel case.

**Comment by mhemesath** [comment]
Sorry didn't mean to close

**Comment by emilyrohrbough** [comment]
> I propose we keep it simple for CSS custom property names and go with all lower-case and separate words with single hyphen.

This is the approach I have used for convert each component in terra-clinical.

**Comment by bjankord** [comment]
@mhemesath Applying the rfc for class names to custom properties has proven tricky to ensure the naming pattern is consistent across components, even with regex lint checking in place based on this comment: https://github.com/cerner/terra-core/pull/603#discussion_r127444576

I can understand the readability concern between these two

`.terra-button-active-background-color-primary`
vs
`.terra-Button-activeBacgroundColor--primary`

My concern is even with regex lint checking in place for the rfc naming convention, its hard to remember when to use camel case or double hyphens.

All of these seem to pass the regex

* `.terra-Button-activeBacgroundColor--primary`
* `.terra-Button-active-bacground-color--primary`
* `.terra-Button-active-bacground-color-primary`

When using all lowercase and hyphens to separate words, it matches CSS's natural naming convention used in properties and values and its easy to remember how to write.

**Comment by mhemesath** [comment]
@bjankord  if thats the consensus of the team we can go forward with your proposed approach.
