### ISSUE TITLE
Selectable Button Group

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#620]
# Issue Description

The selectable button group no longer toggles selected onClick. Before when selected, it had additional styling. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

Expected:
![selectable-button-group](https://user-images.githubusercontent.com/8146159/28224723-d0827258-6895-11e7-82ac-22cf847c73ef.gif)

Actual: 
http://engineering.cerner.com/terra-core/#/tests/button-group-tests/selectable-button-group

**Comment by bjankord** [comment]
This has been released in terra-button-group@1.2.0
