### ISSUE TITLE
Move terra-props-table dev dependency to root level

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#624]
# Issue Description
When updating the generator, I noticed terra-props-table is added as a dev dependency at the package level to run the props-table script. This could be a dev dependency to the root level and would reduce the heroku slug size. 

Terra-clinical made a similar change of placing terra-toolkit at the top level and also places terra-props-table at the top level. 

This change would make the terra-core and terra-clinical props table scripts match and allow for the packages to be be more consistent at a package level. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by Matt-Butler** [comment]
Since props-table is in the core-repo, it gets installed once and symlinked with the rest of the packages. When it is installed in clinical, it cannot be symllinked and instead installed multiple times making the slug huge.
