### ISSUE TITLE
Modal custom props do not get passed to modal correctly

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#625]
# Issue Description
Setting a custom prop like `id="foo"` on a `<Modal>` component fails to render an `id` in the DOM.

This looks like it can be fixed by assigning custom props to the `<Modal>` component rather than the `<Portal>` component.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Setting a custom prop like `id="foo"` on a `<Modal>` component should render an `id` in the modal container element.

## Current Behavior
Setting a custom prop like `id="foo"` on a `<Modal>` component fails to render an `id` in the DOM.

## Steps to Reproduce

1. Add `id="foo"` to `<Modal>` component

## Environment

* Component Version: Modal v1.0.0

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/blob/master/packages/terra-modal/src/Modal.jsx#L117

Custom props are currently being added to the portal component. To resolve this issue, I'll move custom props to modal component.
