### ISSUE TITLE
Migrate blue_steel layouts to Terra

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#629]
# Issue Description
Consumers are looking to migrate from blue_steel over to Terra. In order to do this successfully, we should include the blue_steel layouts inside Terra.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
It should look identical to the blue_steel layout templates. UX may need to adjust some functionality on it to better handle responsiveness.

**Comment by bjankord** [comment]
Discussed in meetings, consensus is to make this in a separate repo outside of terra to make blue_steel migrations easier for consumers.
