### ISSUE TITLE
Props-table arrayOf

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#630]
# Issue Description

<img width="975" alt="screen shot 2017-07-17 at 2 54 55 pm" src="https://user-images.githubusercontent.com/8146159/28287089-f70e7676-6aff-11e7-9f40-afe5e745614d.png">
Datepicker props table: http://engineering.cerner.com/terra-core/#/site/datepicker

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
Released in terra-props-table v1.2.0
