### ISSUE TITLE
Update Modal usage example in README

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#634]
# Issue Description

The Modal's README still references the `isOpened` prop that was recently changed to `isOpen`. This is causing some confusion.

https://github.com/cerner/terra-core/blob/master/packages/terra-modal/docs/README.md

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

## Expected Behavior

The example uses the `isOpen` prop.

## Current Behavior

The example uses the `isOpened` prop.

**Comment by Matt-Butler** [comment]
Resolved in #635
