### ISSUE TITLE
Datepicker popup arrow rtl

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#637]
# Issue Description
When dir=rtl, the datepicker popup arrow does not point at the text-field. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Current Behavior

![datepicker-arrow](https://user-images.githubusercontent.com/8146159/28339698-9105b37a-6bd2-11e7-9d44-6df0396bb715.gif)

**Comment by bjankord** [comment]
This has been released in terra-date-picker@1.11.0
