### ISSUE TITLE
Search Field Modifications (Button and Clear Handler)

### ISSUE THREAD

**Issue by scabraha** [cerner/terra-core#643]
# Issue Description
The current search field will show a search button regardless of if auto search is used. Our app's search requirements are to always auto search so a dedicated search button isn't needed. In addition, the current API doesn't allow us to specify a clear handler - something that we need to know of so our state can be updated correctly when the user clicks the clear button. See screenshots for our visual component.

![image](https://user-images.githubusercontent.com/9515905/28388403-3e8be8aa-6c98-11e7-9b28-4b10024535a3.png)

![image](https://user-images.githubusercontent.com/9515905/28388389-33f45940-6c98-11e7-86db-182ca4870a83.png)

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- [ ] Allow app developers to specify if the search button should show or not
- [ ] Allow app developers to execute code when the clear search is called so that state can be updated appropriately

## Current Behavior
N/A

**Comment by hboege** [comment]
The part about the clear button not calling a callback method was logged in https://github.com/cerner/terra-core/issues/541.  Please see that issue for a work around.

**Comment by bjankord** [comment]
Take a look at #645, this should provide functionality to achieve what you want
