### ISSUE TITLE
Slide Group Keyboard Focus

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#647]
# Issue Description

When tabbing through the slide group examples, the isAnimate examples allow the user to focus elements in the background. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Keyboard navigation is only able to focus the first component in the slide group.

## Current Behavior

Keyboard navigation is able to focus components behind the first component in the slide group.
![slide_group](https://user-images.githubusercontent.com/8146159/28439012-d0fbe5aa-6d65-11e7-9af9-865f111ca944.gif)

1. Navigate to http://engineering.cerner.com/terra-core/#/site/slide-group
2. Hit increment a couple times on the isAnimated example.
3. Users are able to focus buttons behind the first component.

**Comment by Matt-Butler** [comment]
The toggle component has to handle this same type of behavior. @bjankord added `visibility: hidden` to containers that should not be focused.

https://github.com/cerner/terra-core/blob/master/packages/terra-toggle/src/Toggle.scss#L12

**Comment by bjankord** [comment]
This has been released in terra-slide-group@1.9.0
