### ISSUE TITLE
Fix popup triggering shift when opened in certain scenarios

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#649]
# Issue Description
In certain scenarios, opening the popup triggers the page to shift slightly the width of scrollbar.

![popup-shift](https://user-images.githubusercontent.com/633148/28482572-8a2526a4-6e2e-11e7-89af-1e1748be7728.gif)

The known scenarios are:
* using popups on Mac with a USB mouse plugged in
* using popups on windows? needs more detail

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Opening a popup should not shift the page

## Current Behavior
Opening a popup should will shift the page in certain cases

## Steps to Reproduce

1. Plug in USB mouse on Mac
2. Open up popup 
3. View page shift

## Environment

* Component Version: Popup
* Browser Name and Version: Chrome latest
* Operating System and version (desktop or mobile): Mac OS (El Capitan)

**Comment by dkasper-was-taken** [comment]
This issue involves the overlay shifting the overflow style of document body. When a browser is using a fixed width scrollbar, setting overflow hidden on the document body removes the scrollbar, which triggers a change in the width of the page, and content with 100% widths will change positioning, resulting in a shift of content.

**Comment by dkasper-was-taken** [comment]
There is a work around, that involves changing the base html template to not use document body for scrolling, but instead use an inner content div that provides an the overflow: auto styling.  Then within the overlay, you add an inner scrolling invisible div that eats scrolls.

```
#root {
  height: 100%;
  overflow: auto;
  padding: 20px;
  position: relative;
}
.site-body {
  height: 100vh;
  overflow: hidden;
  width: 100vw;
}
```

**Comment by dkasper-was-taken** [comment]
If this change is taken, we could potentially be able to move this popup specific code into the base overlay implementation, and popup could begin consuming the base overlay.

**Comment by mhemesath** [comment]
What about always having the body display a scrollbar? In OSX it will still be hidden by default, in other operating systems I think it will just show a disabled scrollbar The other solution, which is one I think we'l need eventually anyway, is to improve the logic of the popup such that it detects which quadrant it is in and aligns itself to the opposite quadrant.

**Comment by dkasper-was-taken** [comment]
@mhemesath Can you clarify what you mean by aligning itself with the opposite quadrant? It current flips to use available space across a mirrored axis and flips it's position when using bi-directionality. Are you saying you want it to flip to 90 degree angles with available space? Is so, how does this fix the current issue, since is has nothing to do with the popup?

**Comment by dkasper-was-taken** [comment]
For reference, this doesn't incorrectly position the popup, that logic is accounted for. Its simply the annoyance of the screen shifting when attempting to remove the scrolling from body.
