### ISSUE TITLE
Firefox doesn't have focus styles for form inputs triggered with tab

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#664]
# Issue Description
Firefox doesn't show any noticeable styles on a form that were tabbed into with the tab key. This can be hard to determine what element you are editing when you are using keyboard navigation.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Firefox has a blue outline for focus style like how Chrome and Safari do focus styles.

## Current Behavior
Firefox has styles that are either non existent or not noticeable.

## Steps to Reproduce
1. Go to https://terra-core-deployed.herokuapp.com/static/#/site/form
2. Tab until you are inside an input element

## Environment
* Component Version: Terra Form 1.1.0
* Browser Name and Version: Firefox 53.0.3
* Operating System and version (desktop or mobile): Desktop Mac OSX 10.10

**Comment by alex-bezek** [comment]
@JakeLaCombe it also appears that in chrome, inputs marked as required don't have a blue outline on focus as well

https://github.com/cerner/terra-core/issues/755
This issue was made to uplift the input component to have proper focus styling for OCS and Consumer. It also is going to evaluate styles for legacy, so maybe we will take care of it there
https://github.com/cerner/terra-core/issues/755

**Comment by neilpfeiffer** [comment]
Preparing callouts for replacing native focus styling for form elements.

**Comment by neilpfeiffer** [comment]
**Design Input**

- For all input, textarea, and select elements, lets try these `:focus` styles:
```
outline: none;
border-color: #0092e0;
box-shadow: 0 0 1px #fff, 0 0 1px 3px rgba(76,178,233,0.50), 0 0 7px 4px rgba(76,178,233,0.28);
```


- For all buttons, lets try these `:focus` styles:
```
outline: none;
box-shadow: 0 0 1px #fff, 0 0 1px 3px rgba(76,178,233,0.50), 0 0 7px 4px rgba(76,178,233,0.28);
```

**Comment by emilyrohrbough** [comment]
@neilpfeiffer We have had some discussion offline regarding troubles with applying these focus stylings on the form components, particularly the select, radio, and checkboxes. I found [this article](https://developer.mozilla.org/en-US/docs/Property_compatibility_table_for_form_widgets) which might provided good insights into form styling. It was last updated July 2017.

**Comment by neilpfeiffer** [comment]
**Status: Unresolved**

Closing this issue. Will be fixed with new updates to form items (inputs, checkbox/radio, textarea, select), buttons, et.al. with new OCS styling coming soon.
