### ISSUE TITLE
[terra-form] TextareaField and TextField with character remaining counter

### ISSUE THREAD

**Issue by dnguyenchevy** [cerner/terra-core#666]
# Issue Description
Display a message that shows how many character remains in the text field.

**Example:**

![textareaexample](https://user-images.githubusercontent.com/5448499/28632518-768734fe-71f6-11e7-9700-921ffc60926b.gif)

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Provide option to component to display character remaining count for textfield. Refer to example above.

## Current Behavior
N/A

**Comment by bjankord** [comment]
cc/ @neilpfeiffer @jordanlawrence15 @mmalaker

**Comment by tm4027** [comment]
will review and add to text form element

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by neilpfeiffer** [comment]
related: **Forms - Text Field, Textarea Field (maxLength + character counter)** #736

**Comment by mjhenkes** [comment]
closing as duplicate: 736
