### ISSUE TITLE
terra-i18n-plugin cachebusting with filename hashing

### ISSUE THREAD

**Issue by brhoades** [cerner/terra-core#668]
# Issue Description
It is currently not possible to add hashes to the dynamically loaded translation filenames without adding hashes to all of webpack's output filenames. Without having hashes in filenames, serving assets from services like cloudfront is risk; there's no guarantee that a returned translation file is the version that was expected. Additionally, as major web frameworks like Rails or Django depend on asset filenames being known and static within a view/template, this is a large encumbrance for adoption within those frameworks.

## Issue Type
Enhancement

## Current Behavior
In our project webpack outputs an entry file to our react root `clipboard-allergies.js`. This file is loaded by name from Django in a template: `{% static 'js/clipboard-allergies.js %}`. Django then handles serving this asset; it adds a hash to the name and later serves the asset from any number of hosts. The resulting file, for example, cloud then be served with the name `clipboard-allergies.aac6f321.js`. In this case Django handles cachebusting all of our static content by hashing it manually.

The generated translation files are not served directly from Django but are instead loaded via `require.ensure`. Since the filenames are then not hashed they may not be cachebusted from a service like cloudfront if they were updated. Fortunately webpack offers a mechanism to add hashes to filenames:

```
webpack.config.js
...
  output: {
    filename: '[name].[hash].js',
  }
...
```

Which would hash and appropriately load the translation. However, webpack only supports one output filename schema. This means that Django could no longer load our Javascript file by name and the static asset pipeline we use breaks down.

## Workaround

Our current workaround is subpar. We have added a query parameter with the hash to our filename schema:

```
webpack.config.js
...
  output: {
    filename: '[name].js?[hash]',
  }
...
```

This still outputs all files with their normal names. 

```
Version: webpack 1.15.0
...
                                               Asset     Size  Chunks             Chunk Names
         clipboard-allergies.js?1d2d2ee17408db2398e7    54 kB      20  [emitted]  clipboard-allergies
           1.pt-translations.js?84cbf7ea21a2396c6b3c  4.59 kB       1  [emitted]  pt-translations
       1.pt-translations.js.map?84cbf7ea21a2396c6b3c    15 kB       1  [emitted]  pt-translations
...
```

The benefit here is that `require.ensure` will load files with the query parameter included:

![screen shot 2017-07-24 at 4 10 19 pm](https://user-images.githubusercontent.com/4763746/28644682-1eb7084c-7220-11e7-89ef-c0bbcf2e1031.png)

This has the desired effect of forcing the client to cachebust a file... usually. It's contingent on a few things. First, if we're using cloudfront, it has to be configured to use query parameters as a key. In all cases there's no guarantee that the returned file has the provided hash. Unlike a file where it had the hash in its name, the query parameter simply acts as a one-time, blind cachebust.

## Desired Behavior

It seems that terra-i18n-plugin should be able to add hashes into the generated translation filenames. After speaking with @bjankord, it seems as though it should be possible to use [WebpackManifestPlugin](https://github.com/danethurber/webpack-manifest-plugin) (or something similar) to accomplish this. The ManfiestPlugin outputs a stats.json file which maps filenames to those names with hashes included. Although there are questions about whether ManfiestPlugin can only run after all files are generated, even hashing the file as-is when `require.ensure` is called should allow for this functionality.

**Comment by brhoades** [comment]
We've found a workaround that meets our needs. In webpack 3 (and maybe earlier versions) it's possible to specify the chunk filename separately from the normal output filename:

```js
// ...
  output: {
    filename: '[name].js',
    chunkFilename: '[name]-[id].[chunkhash:8].js',
    path: path.resolve(__dirname, '../dist'),
},
// ...
```

Which leads to output where translation filenames are properly hashed:

```
                           Asset     Size  Chunks                    Chunk Names
    fr-intl-local-10.653dcbec.js  66.8 kB      10  [emitted]         fr-intl-local
     intl-polyfill-0.d2a27e7a.js   445 kB       w0  [emitted]  [big]  intl-polyfill
   fr-translations-2.392bc4b7.js  27.1 kB       2  [emitted]         fr-translations
fi-FI-translations-3.85d71ef2.js  18.1 kB       3  [emitted]         fi-FI-translations
   es-translations-4.fc994d1f.js  53.5 kB       4  [emitted]         es-translations
   en-translations-5.a813878e.js  34.3 kB       5  [emitted]         en-translations
en-US-translations-6.c682ea7a.js  34.3 kB       6  [emitted]         en-US-translations
en-GB-translations-7.ab185b42.js  34.3 kB       7  [emitted]         en-GB-translations
   de-translations-8.c9718ae3.js  18.9 kB       8  [emitted]         de-translations
     pt-intl-local-9.9709a70b.js    67 kB       9  [emitted]         pt-intl-local
   pt-translations-1.2653ec59.js    23 kB       1  [emitted]         pt-translations
 fi-FI-intl-local-11.644c625d.js  67.5 kB      11  [emitted]         fi-FI-intl-local
    es-intl-local-12.fd5a73a2.js  66.3 kB      12  [emitted]         es-intl-local
    en-intl-local-13.1bdafaaa.js  65.4 kB      13  [emitted]         en-intl-local
 en-US-intl-local-14.4d5517ca.js  65.4 kB      14  [emitted]         en-US-intl-local
 en-GB-intl-local-15.5e6556b1.js  65.5 kB      15  [emitted]         en-GB-intl-local
 de-intl-local-16.cfa90bda.js     66.2 kB      16  [emitted]         de-intl-local
      clipboard-immunizations.js  2.99 MB      17  [emitted]  [big]  clipboard-immunizations
        clipboard-medications.js  2.92 MB      18  [emitted]  [big]  clipboard-medications
     clipboard-social-history.js  2.84 MB      19  [emitted]  [big]  clipboard-social-history
          clipboard-allergies.js  2.94 MB      20  [emitted]  [big]  clipboard-allergies
```

This suits our needs very well as our entry points do not have hashed filenames.

**Comment by bjankord** [comment]
Sounds like a good solution. Closing this as resolved.
