### ISSUE TITLE
Implement OCS Masked Inputs

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#675]
# Issue Description
Terra doesn't have type masking for it's inputs. Having type masking would allow us to restrict numeric fields to just numeric fields, and also restrict the formats of text inputs. (This maybe covered by https://github.com/cerner/terra-core/issues/383)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
We are able to add text masking to input fields

## Current Behavior
No masking occurs at the moment.

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by bjankord** [comment]
One possible solution: https://text-mask.github.io/text-mask/
