### ISSUE TITLE
Spike on infinite scroll functionality

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#678]
# Issue Description
We have use-cases for infinite scroll functionality. The open-source community provides a lot of pre-built solutions for this. This issue is for spiking on those solutions and landing on a recommending package to use for infinite scroll behavior.

We'll also want to sync with various teams to capture expected behavior for this type of component.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
An infinite scroll package is recommend that covers uses-cases we have.

**Comment by bjankord** [comment]
@emilyrohrbough's documented the spike on infinite scroll packages here: https://docs.google.com/spreadsheets/d/1X6oFGEq4uJuyMWOYmjn6v596dtk8bA1kH2bRrUM3UZY/edit#gid=0

**Comment by emilyrohrbough** [comment]
The four packages I did the most research on were [`react-waypoint`,](https://github.com/brigade/react-waypoint), [`react-infinite`](https://github.com/seatgeek/react-infinite), [`react-infinite-scroll-component`](https://github.com/ankeetmaini/react-infinite-scroll-component), and [`react-infinite-scroller`](https://github.com/CassetteRocks/react-infinite-scroller). Of the four, I would recommend using the `react-infinite-scroller` package. 

The `react-infinite-scroller` package would require minimal effort to learn, include and use. Plus, it allows for both a window and parentNode scrollable element which allows for both an infinite scroll page and infinite scroller view model. This package is actively maintained, does not require additional dependencies, and has 100% functional test coverage.

**Comment by bjankord** [comment]
After talking with the users that we're requesting this, it is no longer as high priority. Bumping this from our Q3 milestone back into the backlog.
