### ISSUE TITLE
Centered Header Text

### ISSUE THREAD

**Issue by noahbenham** [cerner/terra-core#683]
# Issue Description

We need a way to center text on the Header component instead of the current left-aligned text.
For example:
<img width="325" alt="screen shot 2017-07-31 at 4 08 59 pm" src="https://user-images.githubusercontent.com/6981195/28798839-626074c2-760b-11e7-9581-b035aca8b897.png">

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Text is centered when relevant prop is provided.

## Current Behavior

Text can only be left-aligned.

## Steps to Reproduce

N/A

## Environment

* Component Version: 1.1.1
* Browser Name and Version: Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): macOS 10.12.6 (16G29)

**Comment by emilyrohrbough** [comment]
The Header component lives in terra-clinical. Moved logged issue there https://github.com/cerner/terra-clinical/issues/171
