### ISSUE TITLE
Form Input type tel

### ISSUE THREAD

**Issue by noahbenham** [cerner/terra-core#684]
# Issue Description

We need a way to specify `type="tel"` either as a prop on the existing NumberField or as a separate Form component. This will control what type of keyboard is opened on mobile devices.

If implemented as a separate component, we'll also need an `onChange` prop to sanitize input.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Input type is always standard number.

## Current Behavior

Input should be able to be telephone number.

## Steps to Reproduce

N/A

## Environment

* Component Version: 1.1.0
* Browser Name and Version: Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): macOS 10.12.6 (16G29)

**Comment by JakeLaCombe** [comment]
Try using a TextField component and specifying the type as a prop (https://github.com/cerner/terra-core/blob/master/packages/terra-form/src/TextField.jsx#L63). <TextField type="tel" /> should get you what you need

**Comment by bjankord** [comment]
@noahbenham Does @JakeLaCombe's suggestion work for you.

```js
import React from 'react';
import TextField from 'terra-form/lib/TextField';

// Controlled input example
<TextField 
  type="tel" 
  label="Telephone Number" 
  name="tel" 
  value={this.state.formData.telephone}
  onChange={this.handleTelephoneUpdate} 
/>
```

**Comment by noahbenham** [comment]
@bjankord I've confirmed @JakeLaCombe's suggestion is working. I was previously looking at the older `terra-ui.com` documentation. Thanks for all the hard work.
