### ISSUE TITLE
SlideGroup does not animate appropriately in IE11

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#687]
# Issue Description
The SlideGroup does not animate appropriately in IE11. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The SlideGroup should animate appropriately across all supported browsers.

## Current Behavior
Components pushed into the SlideGroup are not animated at all, and the animation for leaving items is present but very choppy.

## Steps to Reproduce

1. Visit http://engineering.cerner.com/terra-core/#/site/slide-group in IE11 browser
2. Behold the lousy animation

## Environment

* Component Version: 1.1.0
* Browser Name and Version: IE11
* Operating System and version (desktop or mobile): Windows 10

**Comment by emilyrohrbough** [comment]
Additionally, it appears bidi animation appears to animate from outside of the slide. 

Noticed in chome.

**Comment by emilyrohrbough** [comment]
It appears using cac() within transform is an IE [bug](https://connect.microsoft.com/IE/feedback/details/762719/css3-calc-bug-inside-transition-or-transform) that was not fixed. Here is a suggested workaround from [stackoverflow](https://stackoverflow.com/questions/21142923/ie-10-11-css-transitions-with-calc-do-not-work/21381301#21381301)
