### ISSUE TITLE
Infinite Scroller Component

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#691]
# Issue Description
Create Infinite Scroller component.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
A component that infinitely loads content within a scrollable container that by only rendering content the user is able to see or might soon see.

**Comment by jordanlawrence15** [comment]
@emilyrohrbough does this include pagination as well, or just specifically infinite scroll?

**Comment by emilyrohrbough** [comment]
@jordanlawrence15 This is specifically infinite scroll

**Comment by bjankord** [comment]
Spike: https://github.com/cerner/terra-core/issues/678

**Comment by emilyrohrbough** [comment]
# Tech Design for Infinite Scroller
## Summary:
The terra-infinite-scroller component is a component that infinitely loads content within a scrollable container 
that only renders content the user is able to see or might soon see. This component wraps the react-infinite-scroller.


## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| children | object or array | undefined | The items to be rendered |
| loader | node | 'Loading...' | The loading content to display if content is at the end of the page and content is not fully loaded. |
| threshold | number | 250 | The distance in pixels before the end of the items that will trigger a call to loadMore. |
| responsiveTo | string | false | Add scroll listeners to the window, or else, the component's parentNode. |
| loadMore | func | null | A callback when more items are requested by the user. |

## Example:
```js
import InfiniteScroller from 'terra-infinite-scroller';

const loaderMessage = <div>Please wait patiently while we load more content.</div>

<InfiniteScroller threshold="500"  responsiveTo="parent" loader={loaderMessage}>
  <div>Element 1</div>
  <div>Element 2</div>
  <div>Element 3</div>
  <div>Element 4</div>
</InfiniteScroller>
```

## CSS Classes:
| Selector         | Description |
|------------------|-------------|
| .infinite-scroller | Sets the infinite scroller container style |
| .loader | Sets the loader container style |

**Comment by jordanlawrence15** [comment]
Do we plan to change the loader based on framework, or is the 'Loading...' seen in the live demo the planned direction?

**Comment by emilyrohrbough** [comment]
The `Loading...` would be provided by us since we would have to provide translations.

**Comment by emilyrohrbough** [comment]
Per @jordanlawrence15 suggestion, adding the prop `endReached` to indicate the end of the loadable content is reached. I don't love the name and would love suggestions.

**Comment by jmsv6d** [comment]
I think `endContent`, `endReachedContent`, or something similar would be more appropriate.

**Comment by emilyrohrbough** [comment]
@jmsv6d I like `endContent`, I think I will update loader to `loaderContent` to be consistent

**Comment by jmsv6d** [comment]
+1 for tech design

**Comment by bjankord** [comment]
+1 on tech design

**Comment by nickpith** [comment]
This is Nick Smith. Are you all sure that `react-infinite-scroller` is a "true" infinite scroller where it recycles views from the top and bottom that come out of view? 

Based on looking at their [demo page](https://cassetterocks.github.io/react-infinite-scroller/demo/), it is only appending to the bottom of the page. This will eventually run into a large number of DOM elements as a user scrolls. A "true" infinite scroll component should be operating under the "adapter" or "recycled view" pattern where a callback is made to render only the views that are necessary in the scroll viewport.

**Comment by mjhenkes** [comment]
@nickpith it's not a true infinite scroller. We agree that this component should not simply append to the bottom of the page and will likely have to create our own component. This will have the unfortunate side effect of pushing out the delivery date of this component.

**Comment by nickpith** [comment]
What is the expected use case of the infinite scroller? Is it intended for lists of content where each item is a constant height? Or is it supposed to be a general purpose scroller for any kind of content that can be variable per child in the scroller? 

I would assume it is desired for list type usage where the items have roughly a constant height but I was curious.

**Comment by bjankord** [comment]
It is supposed to be a general purpose scroller for any kind of content that can be variable per child in the scroller.

**Comment by nickpith** [comment]
In that case, I'm not sure you can ever make a general purpose infinite scroller that only renders what is in view.

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by bjankord** [comment]
Closing until we get OCS design input
