### ISSUE TITLE
Create spacer component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#696]
# Issue Description
Create Spacer component

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Component or components to add margin and padding with UX specified dimensions.

**Comment by bjankord** [comment]
Notes from the war room:
Make utils for both padding and margin
<Margin><Button /></Margin>
<Padding><Button /></Padding>
Props
Top, bottom, left, right, vertical, horizontal
Use constants for prop values: 
Use responsive element for responsive margin
Can we combine <Margin />, <Padding /> into 1 component: <Spacer />
Do we wrap child elements in div or do we apply styles to the child element

**Comment by tm4027** [comment]
Orion JIRA created

**Comment by mjhenkes** [comment]
+1

**Comment by StephenEsser** [comment]
Will this component be able to flex between block and inline-block?

**Comment by bjankord** [comment]
@StephenEsser We can add a prop for this. I'm thinking default to block, and have an `isInlineBlock` prop thats defaulted to false.

**Comment by emilyrohrbough** [comment]
@bjankord That would make sense to me. That'd align with how Field was initially implemented.

**Comment by tm4027** [comment]
JIRA created

**Comment by emilyrohrbough** [comment]
Resolved in #1011
