### ISSUE TITLE
Arrange does not properly expand it's fit end and start aligned elements.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#699]
# Issue Description
Arrange fit elements lack "flex: 0 0 auto" styling, so end elements do not properly expand with various content.

This works correctly on IE 10, but does not work on Firefox, Chrome, and Safari.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

![screen shot 2017-08-03 at 1 06 03 pm](https://user-images.githubusercontent.com/22619500/28936776-5e6ae51a-784e-11e7-969e-7239455bd4fa.png)

**Comment by cwalten** [comment]
We are having similar issues, only in IE, where items are pushed off of the viewable window if the elements in 'fill' get too wide.

<img width="559" alt="ie arrange not fitting on screen" src="https://user-images.githubusercontent.com/19825717/30223366-346771e4-9490-11e7-8be5-b43b66301155.png">

**Comment by emilyrohrbough** [comment]
Resolved in #926.
