### ISSUE TITLE
Update Table Documentation

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#713]
# Issue Description
There is no documentation provided on the component in the table package.

The table package contains the following components:  table, table header, table subheader, table header cell, table cell, table rows, table row, and single selectable rows. 

We should provide documentation on these, especially to note the difference between when to use row vs rows vs selectable rows. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by yuderekyu** [comment]
Wasn't this addressed on #863?
