### ISSUE TITLE
Red ring should not be displayed around the Select field like other form fields

### ISSUE THREAD

**Issue by raghuvarunreddypothulavenkata** [cerner/terra-core#714]
# Issue Description

The latest version of terra-form removed the red ring to be displayed around all the required form components. But it was not removed in the Select component.
![screen shot 2017-08-09 at 2 35 45 pm](https://user-images.githubusercontent.com/9399361/29142395-684f229e-7d17-11e7-8c51-1045df931ace.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

The Select field should work like other Form fields and shouldn't display the red ring even if it is required.

## Current Behavior

The Select field displays a red shadow now if it is required.

## Steps to Reproduce

1. Open in FireFox and go to Form SelectField component (required field).
2. Try submitting the form.
3. Red ring gets displayed around SelectField.

## Environment

* Component Version: 1.3.0
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): MacOS

**Comment by JakeLaCombe** [comment]
Fixed in #719

**Comment by bjankord** [comment]
This has been released in terra-form@1.4.0
