### ISSUE TITLE
Spike on text masking for DatePicker and Numeric Input

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-core#715]
# Issue Description
We need to support text masking for the DatePicker component and Numeric Input. There are several open-source text masking libraries available. A previous [spike](https://jira2.cerner.com/browse/TERRAUI-601) was done for the TimeInput component to mask time entry but later decided to separate TimeInput into an hour input and minute input so there was no longer a need to use a masking library. Now the DatePicker and Numeric Input will need to handle text masking, we need to revisit the spike.

This spike will help guide the direction for #303.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

## Expected Behavior
An OS text masking library or roll our own masking is recommended to handle masking for DatePicker and Numeric Input.

**Comment by bjankord** [comment]
Duplicate to https://github.com/cerner/terra-core/issues/675
