### ISSUE TITLE
Tech Design terra-card

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-core#717]
# Tech Design for Card
## Summary:
The Card Component is used as container for other divs. 

PR:
TBD

### Card:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| padding | array or bool | true | option to pass in a single boolean to turn on/off, or an array to specify each side using css short hand https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties |
| children | node | none | Child Nodes |

## Example:
```
import React from 'react';
import Card from 'terra-card';

const CardDefault = () => (
  <div>
    <Card children={"Hello World!!"}/>
</div>
);

export default CardDefault;

```

## CSS Classes:
| Selector | Description |
|----------|------|
| .well-card | Outer Container of the Card |
| .well-card-container | Inner part of the card used to contain children prop |
| .u-pa--sm | 10px padding |
| .u-pv--sm | 10px padding vertical |
| .u-ph--sm | 10px padding horizontal |
| .u-pt--sm | 10px padding top |
| .u-pb--sm | 10px padding bottom |
| .u-pl--sm | 10px padding left |
| .u-pr--sm | 10px padding right |

**Comment by mjhenkes** [comment]
@WhiteLight1107 could you move the tech design to #313? Also do you have any UX design that could be attached?

**Comment by WhiteLight1107** [comment]
@mjhenkes  Done

**Comment by mjhenkes** [comment]
@WhiteLight1107 thanks
