### ISSUE TITLE
Collapsible Menu View

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-core#724]
# Issue Description
The collapsible menu view is a component that will contain collapsible menu items/item groups that can display with a button/button group style in the space available, while any items that cannot fit will be rolled up into a menu that will be displayed from a '...' button. 

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by jmsv6d** [comment]
# Tech Design for CollapsibleMenuView
## Summary:
The collapsible menu view is a mechanism that can be used in toolbar scenarios where actionable items will be displayed face-up and flex based on the space available. Any items that can not fit in the available space will be rolled into a "..." menu. 

CollapsibleMenuView.Item will flex between a button when displayed face-up and a Menu.Item when in a menu. An item can have an onClick action and/or contain menuItems that will be displayed in a menu when clicked (they will be displayed in a submenu if the item is rolled into the "..." menu)

CollapsibleMenuView.ToggleItem will flex between a checkbox with a label when displayed face-up and a selectable Menu.Item when in a menu. 

CollapsibleMenuView.ItemGroup will flex between a button group when displayed face-up and a Menu.ItemGroup when rolled into the "..." menu. A selectable ItemGroup will have toggle style selection. An Item group that is not slectable will have it's children roll into the "..." menu as non selectable Menu.Items. 

CollapsibleMenuView.Divider will flex between a vertical divider when displayed face-up and a Menu.Divider when in a menu.


## Responsiveness:
Items will be added to "..." menu when there is not enough space for it to be displayed face-up. 
Items will be displayed face-up when the space is available
The "..." menu will not be rendered if there is enough space to display all items face-up.

## Bidirectionality
Alignment will the mirrored in the right to left orientation

## Accessibility
Accessibility should be handled by subcomponents.

## React Props:
### CollapsibleMenuView
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| children | node | null    | List of CollapsibleMenuView.Items/CollapsibleMenuView.ItemGroups |
| menuWidth | string | '240' | One of the set menu width sizes to indicate the width needed for the "..." menu |


### CollapsibleMenuView.Item
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| icon | Element | null | Option icon to display inline with the item text. This will only be displayed when the item is displayed face-up as a button |
| text | String | '' | Text to be displayed in the element |
| isReversed | Bool | false | Indicates if the icon and text order should be reversed |
| isSelected | Bool | false | Indicates if the item should be initially selected when placed inside an ItemGroup |
| menuItems | Array | [] | List of CollapsibleMenuView.Items/ItemGroups/Dividers to be displayed from the item in a menu (or submenu) |
| onClick | Func | null | Callback function called when the item has been clicked |
| shouldCloseOnClick | Bool | false | Indicates if clicking the item should trigger the menu the item is displayed in to close | 
| menuWidth | string | '240' | One of the set menu width sizes to indicate the width needed if a menuItems are given |

### CollapsibleMenuView.Toggle
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| text | String | '' | Text to be displayed in the element |
| isSelected | Bool | false| Indicates if the item should be initially selected | 
| onChange | Func | null | Callback function called with the event and selection state, when the selection state has changed |
| shouldCloseOnClick | Bool | false | Indicates if clicking the item should trigger the menu the item is displayed in to close | 

### CollapsibleMenuView.ItemGroup
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| onChange | Func | null | Callback function called with the event and selected index when the selected Item changes |
| isSelectable | Bool | false | Indicates if the ItemGroup should be selectable |
| children | node | [] | Items to be grouped together | 

### CollapsibleMenuView.Divider
This element wouldn't have any props

## Example:
```
<CollapsibleMenuView alignment="start">
  <CollapsibleMenuView.Item
    key="Item1"
    icon={icon}
    text="Click Me"
    menuItems={[
      <CollapsibleMenuView.Item text="Menu Item 1" key="Item1.1" shouldCloseOnClick/>,
      <CollapsibleMenuView.Item text="Menu Item 2" key="Item1.2" shouldCloseOnClick/>,
      <CollapsibleMenuView.Item text="Menu Item 3" key="Item1.3" shouldCloseOnClick/>,
    ]}
  />
  <CollapsibleMenuView.Item
    key="Item2"
    text="Click Me"
    onClick={() => alert("I've been clicked!")}
  />
  <CollapsibleMenuView.Divider key="Divider1" />
  <CollapsibleMenuView.ItemGroup key="Item3" isSelectable>
    <CollapsibleMenuView.Item
      key="Item3.1"
      text="Option 1"
    />
    <CollapsibleMenuView.Item
      key="Item3.2"
      text="Option 2"
    />
  </CollapsibleMenuView.ItemGroup>
  <CollapsibleMenuView.Divider key="Divider2" />
  <CollapsibleMenuView.Toggle key="Toggle1" text="Toggle Item" />
  <CollapsibleMenuView.Toggle key="Toggle2" text="Toggle Item" isSelected />
</CollapsibleMenuView>
```

## CSS Classes:
| Selector         | Description |
|------------------|-------------|
| .collapsible-menu-view | Top level CollapsibleMenuView container |
| .menu-button | "..." menu trigger element |
| .face-up-item | Face-up child elements |


## Notes:
It needs to be determined if there is a need for sections that will collapse all children together vs. having the Divider all elements collapse independently. 

I am thinking that a CollapsibleMenuView will manage it's own open/close state for menus contained within it for the ease of maintaining consistent functionality when a menu on a CollapsibleMenuView.Item gets rolled into the "..." button. Any action that would close the menu on the CollapsibleMenuView.Item should close the "..." menu when it gets rolled inside.

**Comment by jmsv6d** [comment]
UX designs can be found with the menu here: https://wiki.ucern.com/x/aMjMY

**Comment by tm4027** [comment]
Orion JIRA created

**Comment by tbiethman** [comment]
This looks really cool Jaime, huge improvement over the CollapsibleButtonView.

@neilpfeiffer Should we allow consumers to provide a custom overflow button? I know some teams have requested something other than the standard ellipses in the past.

I'm also curious if we can come up with a responsive pattern that doesn't require us to do the exact width calculations. Whether it be X number of buttons/groups per breakpoint or something else, it wouldn't be perfect, but I know that width calculation logic wasn't exactly cheap or without bugs in our previous implementation.

**Comment by jmsv6d** [comment]
What would you think of leaving the width calculation logic as the default behavior, but adding props, similar to the responsiveElement, where consumers could choose the number of items that should be displayed face-up at each breakpoint?

**Comment by bjankord** [comment]
+1 on tech design. I would recommend holding of on adding props, similar to the responsiveElement until we notice issues with the current approach.
