### ISSUE TITLE
Transitive dependency translations not getting pulled in

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-core#730]
# Issue Description
While developing the clinical-alert it came to my attention that the base alert translations were not being aggregated for the site unless the alert was included as a direct dependency on the site. Some investigation needs to be done on why this is occurring. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Translations in modules that are transitive dependencies should be pulled in to the aggregate translations. 

## Current Behavior
Modules with translations need to be a direct dependency in order for their translations to be included. 

## Steps to Reproduce
1. Remove terra-alert as a direct dependency in terra-clinical-site
2. Clean install 
3. Note that the aggregate-translation files do not include translations for terra-alert, despite being a dependency of terra-clinical-alert. 

## Environment

* Component Version: terra-i18n-plugin v1.0.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): Mac OS X El Capitan

**Comment by bjankord** [comment]
My first thought is it may be related to nested node_modules directories.

Given terra-alert is a dependency of terra-clinical-alert and terra-clinical-alert is a dependency of terra-clincal-site, the directory structure after running npm install may look like the following for terra-clinical site:

* terra-clinical-site
  * node_modules
    * terra-clinical-alert
      * node_modules
        * terra-alert

We would need to test and see if thats the case. If that is how the directory structure is modeled, our i18n-aggregator-plugin may only be looking in the first level node_modules directory.

**Comment by emilyrohrbough** [comment]
The i18n-aggregator-plugin is only looking at the first level node_modules directory. https://github.com/cerner/terra-core/blob/master/packages/terra-i18n-plugin/src/I18nAggregatorPlugin.js#L36

**Comment by bjankord** [comment]
This has been released in terra-i18n-plugin@1.4.0
