### ISSUE TITLE
Terra Hookshot

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#739]
# Issue Description
Create Tether alternative capable of handling arrow offsets, target positions, mobile zoom, and shrink package size.

## Issue Type

- [x] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Current Behavior
Currently the tether implementation used for popups is unable to handle mirrored offsets and correct positioning when zoomed on mobile.  It also has a considerable code footprint to account for a myriad of positioning options and support for browsers that are no longer needed. Also as a closed system, it does not allow for seamless arrow positioning, as positional margins are not an option.

**Comment by dkasper-was-taken** [comment]
# Tech Design for Terra-Magic
## Summary:
This component is design as a light weight replaced for tether. Incorporating a margin to allow for positioning of arrows more easily, mirroring of offsets to account for flipped, rotated, and overlapped positions, fallback behaviors, and correct positioning when zoomed on a mobile device.

## Responsiveness:
The portal'd content responds either to the size of the bounding rect or window.

## Bidirectionality
This component is unaffected by bidirectionality, it assumes your method of bidi may differ, so assumes you'll flip your own values accordingly.

## Accessibility
There are no accessibility concerns with this component.

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| children | node | null    | JSX children |
| arrowDepth | number | 0 | Depth in px of the margin to allow for an arrow. |
| attachmentBehavior | string | auto |  If the primary attachment in not available, how should the content be positioned. |
| boundingRef | func | null | Reference to the bonding container, will use window if nothing is provided. |
| content | element | required | The MagicContent to be magicked. |
| contentAttachment | string | required | String pair separated by a space using values of top, middle, bottom, and left, center, right. |
| contentOffset | string | '0 0 ' |  String pair of top and left offset, ie "10px -4px". |
| isEnabled | bool | false | Should element be actively magicked to the page. |
| isOpen | bool | false | Should element be presented. |
| onPosition | func | null | Callback function when the magic is moved. |
| targetRef | func | required | Required element to be presented and magicked to. |
| targetAttachment | string | null | String pair of top, middle, bottom, and left, center, right. Will mirror content is none provided. |
| targetOffset | string | '0 0" | String pair of top and left offset, ie "10px -4px". |

## Example:
```
        <Magic
          arrowDepth="10"
          attachmentBehavior="flip"
          boundingRef={boundingRef}
          content={magicContent}
          contentAttachment="bottom right"
          contentOffset="-10 0"
          isEnabled={this.isContentSized}
          isOpen={isOpen}
          onPosition={this.handleOnPosition}
          targetRef={targetRef}
          targetAttachment="top left"
        />
```

**Comment by bjankord** [comment]
+1

**Comment by mhemesath** [comment]
Can we call this something more descriptive than `Magic`? My issue with naming things abstractly is that as soon as it happens more than 1 time it becomes very confusing. So in my experience its better to just avoid it all together. A name like  `AdjacentContainer` is boring, but it at least lets people reading the code have a general idea of its purpose.

> This component is unaffected by bidirectionality, it assumes your method of bidi may differ, so assumes you'll flip your own values accordingly.

I disagree with this. I think should be enabled by default.

Not sure how you plan on implementing this, but this would actually be quite trivial to do with CSS grids. Essentially we can create a grid that resembles this:
```
* * *
* * *
* * *
```
The content always goes in the middle region whereas the attached content can then go in one of the outer regions depending on desired placement. Grids auto handle bidi, and I believe little-to-no positional logic will be needed other than programming the grid regions.

**Comment by dkasper-was-taken** [comment]
The name was deliberately vague and stupid because it's a placeholder, since I've done all this work in my spare time at home I didn't bother with a real name yet.

After discussion with Brett I'm moving the bidirectionaly logic that was previously located within the poup into the lower level component. We can't use the post css rtl because it incorrectly affects element positioned with screen coordinates and page offset. Rather we flip the prop values for attachment points to bidi when it's detected, achieving the same effect without affecting positioning logic.

**Comment by dkasper-was-taken** [comment]
Updated 'arrowDepth' to 'attachmentMarign'.

**Comment by JakeLaCombe** [comment]
We talked as a team, and decided to rename it Gimbal. https://en.wikipedia.org/wiki/Gimbal

**Comment by bjankord** [comment]
+1, sounds good.

**Comment by ryanthemanuel** [comment]
+1 you jerks

**Comment by neilpfeiffer** [comment]
+1 on hookshot

**Comment by alex-bezek** [comment]
+1
![image](https://user-images.githubusercontent.com/8029578/29729088-51acaf08-89a0-11e7-8b8b-f3e7e754e5bf.png)

**Comment by mjhenkes** [comment]
+1

**Comment by jmsv6d** [comment]
Reopening issue to start work on tests.
