### ISSUE TITLE
Uplift terra-popup to support advanced positioning and dynamic sizing.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#740]
# Issue Description
Currently the popup relies on fixed height and widths to handle it's positioning. There has been an ask from consumer to allow for dynamic sizes.

Reliant on work from issue #739 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
A custom/dynamic size option is to be added to the popup to allow content to size popup based on it's own size.

**Comment by dkasper-was-taken** [comment]
Current discussion has risen in how to handle a dynamically sized popup. The issue being that a dynamically sized popup when bound will no longer be able to handle it's own scrolling. So if it was handling it's scrolling prior, a bounding outer container would force a double scroll bar situation.

My current proposal is that is a height or width is set as dynamic to decorate content with a prop stating that it is bound in order to allow the content to set it's own sizing to 100% and as such fill the container, providing correct scrolling and allowing flex enabled headers.

**Comment by mhemesath** [comment]
Really the popup should pretty much be equivalent to the popover in bootstrap https://v4-alpha.getbootstrap.com/components/popovers/.  Assume a width, and have no constraint on height. This is very simple to achieve.

Past that is the use case where the content needs a bound width/height, which is a legitimate use case. Because that use case is more advanced, it should be built on the simple, static popup with no height contraint.. rather than the simple popup being the special case.

**Comment by mjhenkes** [comment]
The bootstrap popup does not meet our UX requirements. The popup does not become fullscreen at small view ports. It does not dynamically move the display position based on popover location. 

We can assume a width with no constraint on height, but when presented in a small view port or with a very large height we need to introduce a height constraint to allow all layouts to be able to be implemented. For example, something with a fixed header.

The benefit of @dkasper-was-taken 's solution is that the simple pop-up is not treated as a special case, when a dynamic size is selected, the only difference is that a 'bounded' prop will be set on the popover content to allow it to layout differently if it chooses to.

**Comment by dkasper-was-taken** [comment]
# Tech Design for Terra-Popup Update
## Summary:
This component is design as a light weight replaced for tether. Incorporating a margin to allow for positioning of arrows more easily, mirroring of offsets to account for flipped, rotated, and overlapped positions, fallback behaviors, and correct positioning when zoomed on a mobile device.

## Responsiveness:
All popup sizes, including custom, respond to the bounds of the bounding rect or window. If using custom sizes, children will be decorated with a prop to indicate that they needs to update their display. This is specifically to account for custom sizes that set their own scroll or what to retain a header.

## Accessibility
The tadIndex behavior has been update to work the same as the modal, correctly highlighting the popup on all browsers. Chrome and IE we previous offenders.

## New React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| targetAttachment | string | null | Attachment point for the target. |

## Updated React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| contentHeight | string | '80' | 'custom', '40', '80', '120', '160', '240', '320', '400', '480', '560', '640', '720', '800', '880'. |
| contentWidth | string | '240' | 'custom', '160', '240', '320', '640', '960', '1280', '1760'. |

## Example:
```
       <Popup
          contentAttachment="top left"
          contentHeight="custom"
          contentWidth="custom"
          isOpen={this.state.open}
          onRequestClose={this.handleRequestClose}
          targetRef={() => document.getElementById('popup-standard-button')}
          targetAttachment="bottom center"
        >
          <ExamplePopupContent />
        </Popup>
```

**Comment by bjankord** [comment]
+1 on tech design. Nice work @dkasper-was-taken

**Comment by ryanthemanuel** [comment]
+1 on tech design.  The only thing I would question is the word "custom" for the height and width.  Would "dynamic" be more appropriate?  Or something else?

**Comment by emilyrohrbough** [comment]
With "custom" do you mean responsive?

**Comment by tm4027** [comment]
JIRA created

**Comment by dkasper-was-taken** [comment]
I'm fine renaming custom to something else.  The concept allows the popup on each update to adjust to the content of the popup, rather than a prescribed size.

So custom, dynamic, unbounded, etc. Anyone want to way-in on their favorites?

**Comment by emilyrohrbough** [comment]
unbounded

**Comment by bjankord** [comment]
+1 for dynamic.
