### ISSUE TITLE
Add Tests for I18n Aggregation Plugin

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#747]
# Issue Description
The I18n plugin we have doesn't have any tests. To ensure it's functionality, we need to add in tests.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by JakeLaCombe** [comment]
I tested a similar aggregation plugin at this pull request. You can view what I did here. https://github.com/cerner/terra-core/pull/758

Essentially for this tests, it's better to make sure the filesystem method parameters are correct as opposed to ensuring that new files are written. A straight up Unit Tests.

**Comment by bjankord** [comment]
This has been released in terra-i18n-plugin@1.4.0
