### ISSUE TITLE
alert consumer theme

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-core#748]
# Alert Consumer Theme

## Issue Type

- [X] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Alert Actions**:

For actions/footer a container will be provided, it will support up to 2 buttons one primary and one secondary

Right now they are in the top right corner, in the consumer theme the buttons will need to be moved to the bottom left corner. Also only one button is being supported inside Alert (the onDismiss button is added if onDismiss is turned on but there is no support for two action buttons and no onDismiss button)

4 Props will be need to be added in order to accomplish this 

primaryActionFunction: PropTypes.func
-Default Value: None
-function for the primary function

primaryActionText: PropTypes.string
-Default Value: TBD
-Text for the primary buttong

secondaryActionFunction: PropTypes.func
-Default Value: None
-function for the secondary function, if the onDismiss property is on then this function will be set to that function

secondayActionText: PropTypes.string
-Default Value: TBD
-Text for the primary buttong

Due to the addition of these new properties, the pre-existing property "action" can be removed

**Responsive Element**
In OCS there is no need for a responsive element in Alert(since the buttons are always in the same place regardless of mobile vs. desktop) so this can be removed

**New Icons**
New Icons will be required to meet consumer callout, so  new Terra-Icons themes will be needed.
This will be done with the css property "content" for each of the different themes that will be
needed

**Status Bar**
Each alert has a box-shadow prop for the status bar, this is already themed so in order to turn it off when the  consumer theme is enabled, the box-shadow should be set to either " " or to the same as the background color

**Comment by WhiteLight1107** [comment]
Callouts:
[Alert_Banner_CONSUMER.pdf](https://github.com/cerner/terra-core/files/1250009/Alert_Banner_CONSUMER.pdf)

**Comment by emilyrohrbough** [comment]
If this is a terra-consumer component, should we log this issue in the [terra-consumer repo](https://github.com/cerner/terra-consumer/issues) and close it here?

**Comment by WhiteLight1107** [comment]
@emilyrohrbough just a theme update, my mistake shouldn't of said terra-consumer in the tech design fixed it

**Comment by jmsv6d** [comment]
I wouldn't want to be too hasty in removing the action prop, as it would be a non-passive change. Could we possibly keep the the action prop and add a secondaryAction prop that accepts an element as well?

**Comment by WhiteLight1107** [comment]
@jmsv6d  my issue with that is that custom elements are being passed into the action prop 
`action={<Button .... />}`  when it should just be a button of the current theme, thats why I just want to pass in the function

**Comment by tm4027** [comment]
Orion Reviewed

**Comment by bjankord** [comment]
@neilpfeiffer We need design input on this to move forward.

**Comment by mhemesath** [comment]
What is the blocker on this?

**Comment by bjankord** [comment]
Closing this until we get design input from OCS.
