### ISSUE TITLE
Status View Component

### ISSUE THREAD

**Issue by alex-bezek** [cerner/terra-core#752]
# Issue Description
As an application developer, I need "Status View" card which can fulfill the needs of both the `Error View` Component, and the `No Data` Component
http://engineering.cerner.com/terra-clinical/#/site/no-data-view
http://engineering.cerner.com/terra-clinical/#/site/error-view

## Questions
I also want to figure out if terra-core just containers a `Custom Type` view which takes any text and icon to display, allowing terra-consumer and terra-clinical to wrap it providing proper types. Or to bake all the common types into terra-core, theme the icons, and also provide a custom type for consumer to use. 

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

This should work similar to terra-clinical [No Data View component ](https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-no-data-view) with theming option to satisfy terra-consumer and Cerner OCS and Error view e.g Not Authorized, No results found, Error Loading etc.

### Considerations:
- Meets specification of [No Data View component ](https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-no-data-view) in terra-clinical. 
- Meet specification of terra-consumer e.g having divider, heading / subtext alignment options 
- Covers most of the Cerner one style No Data view component ( Where can I get the callout for OCS component ?) @alex-bezek @mhemesath 
- Meets specification of [Error view - terra-clinical](https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-error-view)  and terra-consumer

### Responsiveness:
- TBD

### Bidirectionality
- TBD

### Accessibility
- TBD

### React Props:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
|icon| element| undefined | The icon component displayed on the top. It can be any icon consumer wants|
| heading | string | required | The title of the status view. |
| subtext | string | undefined | The subtext description of the no data view. |
| subtextContent | element  | undefined | The content to be rendered last. The consumer has total control on what to display inside this. |
| ~~isIconHidden~~ | bool  | false      | Whether or not the Icon should be displayed. |

Question : If icon is not passed then Icon will not be rendered then I believe we don't need isIconHidden. Let me know if I am missing any use case for this prop.

### React Props:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| type | string | required | The objective of the status view component is defined by consumer by selecting type. As per type we internally decide which icon and heading will be rendered. See more details on `type` below|
| heading | string | undefined | If heading is provided then it will take precedence over the heading value from Type-Icon mapping. |
| subtext | string | undefined | The subtext description of the no data view. |
| subtextContent | element  | undefined | The content to be rendered last. The consumer has total control on what to display inside this. |
| isIconHidden | bool  | false      | Whether or not the Icon should be displayed. |

### React Props:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| type | string | required | The objective of the status view component is defined by consumer by selecting type. As per type we internally decide which icon and heading will be rendered. See more details on `type` below|
|icon| element| undefined | The icon component displayed on the top. It can be any icon consumer wants. This icon will be honored if `type` is CUSTOM.|
| heading | string | undefined | The title of the status view. This heading will be honored if `type` is CUSTOM. |
| subtext | string | undefined | The subtext description of the no data view. |
| subtextContent | element  | undefined | The content to be rendered last. The consumer has total control on what to display inside this. |
| isIconHidden | bool  | false      | Whether or not the Icon should be displayed. |

### Prop - type:
| value | Icon | Heading | 
|-------|-------|---------|
|  CLINICAL  |    TBD      |    TBD        |
|  NO_DATA  |    folder icon      |    No Data        |
|  NO_RESULT  |    Magnifying glass      |    No Matching Results   |
|  NOT_AUTHORISED  |    lock      |    Not Authorized   |
|  SENSITIVE_DATA  |    lock      |    Sensitive Data   |
|  ERROR  |    triangle      |    Error   |
|  NO_INTERNET  |    triangle      |    No Internet Connection   |
|  ERROR_LOADING  |    triangle      |    Error Loading   |
| CUSTOM | given icon | given heading |

I feel this list will go long with time. Being this component at terra-core level it would be nice if we keep the icon and heading configurable as mentioned in Approach 1. 

### Example:
```
import React from 'react';
import NoDataView from 'terra-no-data-view';

<NoDataView  />
<ThemeProvider themeName="terra-consumer-theme/cerner-one-style">
      <NoDataView />
 </ThemeProvider>
```

### CSS Classes:
| Selector                    | Description |
|-----------------------------|-------------|
| .status-view            | The root class for the CSS component. It will be applied under all theme. It will have common css across all the theme like left and right padding for card component. |
| .icon           | The class for the icon to set the size of icon and alignment |
| .heading           | The class for the heading to set text size and color and if required line height|
| .subtext           |  The class for the subtext to set text size and color and if required line height.  |
| .subtext-content | The class for the subtext to set alignment. |
|.divider| The class will decide whether horizontal rule will be rendered or not |

Note: Themed variable will be used to set the values wherever required for different themes (terra-clinical, terra-consumer and OCS). Be default terra-clinical theme will be applied.

### StatusView.scss
```
 @include cerner-consumer-theme {
   --terra-statusview-icon-size: TBD ;
     --terra-statusview-heading-text-size: xxRes-Large (30 mobile /36 px desktop);
     --terra-statusview-heading-text-color: text-Light;
     --terra-statusview-subtext-text-size: Body ;
     --terra-statusview-subtext-text-color: Text-Dark;
     --terra-statusview-divider: block;
     --terra-statusview-heading-line-height: TBD;
     --terra-statusview-subtextcontent-aligment: center;
  }

  @include cerner-clinical-theme {
     --terra-statusview-icon-size: 100x100px ;
     --terra-statusview-heading-text-size: 24 px;
     --terra-statusview-heading-text-color: --black-60 ;
     --terra-statusview-subtext-text-size: 14 px ;
     --terra-statusview-subtext-text-color: --black-40;
     --terra-statusview-divider: none;
     --terra-statusview-heading-line-height: 28px;
     --terra-statusview-subtextcontent-aligment: center;
   }
```

Note : I am assuming the padding between the elements e.g. heading, subtext, divider and content will be common across the theme.

**Comment by alex-bezek** [comment]
@amf9t2 
## approach 1
I'm assuming we would then also have to create terra-consumer and terra-clinical wrappers to provide the correct icons in an easily usable fashion. 

I think we decided in the war room to not support `subtextAlignment` . @neilpfeiffer can confirm if thats where we landed. 

> Question : If icon is not passed then Icon will not be rendered then I believe we don't need isGlyphHidden. Let me know if I am missing any use case for this prop.

I agree. If we do keep it (or in the other option) we also want to rename `Glyph` to `Icon`

> Responsiveness
Did we determine from Sarah that the medium/large components are different, or up to the user to not provide subtextContent. Not that its responsive to show/not-show the subtextContent? 
Also I think our mockups have responsive `Heading` font size and icon size

## Approach 2
If we provide a type, i think we would still need to expose a `custom` type that consumer could use to make ones with different headers. That or it can also take a header prop to override any type.

**Comment by emilyrohrbough** [comment]
`subtextContent` of type node. 

If we take the second approach, I feel it would still be valuable to include the `heading` prop. I think default headings are appropriate as indicated above, but I'm not sure the heading should be strictly locked to the icon.

**Comment by zhongyn** [comment]
i like approach 1. It provides the flexibility for applications requiring custom icon and heading.

**Comment by zhongyn** [comment]
if a specific status view is widely used in an application, the view can be defined in one place and reused across the app.

**Comment by mhemesath** [comment]
`StatusView` seems a little generic and there is already a `terra-status` component. I'm wondering if rather than `View` a better term is `Template` being this this is really used as such. E.g. `ResourceStatusTemplate` which can then be used to create `ErrorView` and `NoDataView`

**Comment by jmsv6d** [comment]
Based on Friday's war room discussion, for approach 2 the terra-core component should only contain the types that are common between clinical and consumer with the additional custom type (as well as an icon and heading prop that can be used for the custom type) so that terra-consumer can expand on it (I believe clinical doesn't need any types beyond the common ones)

**Comment by jmsv6d** [comment]
Looking back at Neil's comments on the old issues the common types are: (1)No Data, (2)No Matching Results, (3)Not Authorized, (4)Error

**Comment by amf9t2** [comment]
@alex-bezek  Yes as per discussion with Sarah we decided to have independent component for `medium` category. We could achieve that without passing content and icon as per approach 1 but issue is with divider. As divider by default is added for consumer theme whereas in the `medium` case we don't want divider so it is better we have independent component inside same package.

For approach second : If we take heading as prop, we will still need type to decide icon from mapping and given heading will take the priority. I guess you are saying the same.

**Comment by amf9t2** [comment]
@mhemesath  how about ResponseStatusViewTemplate ? 
All the variation(NO_DATA, NO_RESULT, SENSITIVE_DATA, ERROR etc) is connected to a response of a user action.

**Comment by amf9t2** [comment]
Thanks for the feedback.
The above discussion direct us to combine the approach 1 and approach 2 where consumer either has to set the type or provide icon and heading. One of these will be mandatory.

### Combine Approach   - Common - Custom
### React Props:
| Prop | Type | Default | Description |
|-------|-------|---------|---------------|
| type | string | required | The objective of the status view component is defined by consumer by selecting type. As per type we internally decide which icon and heading will be rendered. See more details on `type` below|
|icon| element| undefined | The icon component displayed on the top. It can be any icon consumer wants. If type is not provided then this becomes required with heading.|
| heading | string | undefined | The title of the status view. If type is not provided then this becomes required with icon. If type is provided then it will take precedence over the heading value from Type-Icon mapping. |
| subtextAlignment | string | center | Set the alignment of subtext (description). The value should be one of 'Left' and 'Center'|
| subtext | string | undefined | The subtext description of the no data view. |
| subtextContent | element  | undefined | The content to be rendered last. The consumer has total control on what to display inside this. |
| isIconHidden | bool  | false      | Whether or not the Icon should be displayed. |

Let me know if this fulfills all our use-case.
@jmsv6d @alex-bezek

**Comment by jmsv6d** [comment]
I you changed `subtextContent` to be of type node I don't think the subtext prop is needed. And I'm not sure if we want the heading string to be over-ridden for the built-in types, I think that the heading prop should only be used when the type is custom. But I would want @neilpfeiffer to confirm both of these.

**Comment by amf9t2** [comment]
![image](https://user-images.githubusercontent.com/6234682/29840542-fb76c440-8cc7-11e7-8a29-fd59c54009e0.png)
This is one of the use-case for terra-consumer where `message` will be subtext and buttons will be subtextContent. So we will need `subtext` as a separate prop. Same applies for [OCS No data component](https://wiki.ucern.com/display/UserExperience/No+Data+Pattern).

The type prop will be taking one of these type CLINICAL, NO_RESULT, ERROR etc (se above Prop - type table). My understanding is we want consumer to pass heading text  If they doesn't like the predefine heading for a particular type.

**Comment by jmsv6d** [comment]
It's fine if you guys need both, I was just thinking that in our legacy stuff the two were mutually exclusive. As far as the heading goes, the heading messages are specific to the types, if a consumer needs something that displays a different message, then perhaps there's a need for a new type to be defined.

**Comment by amf9t2** [comment]
Discussed with @mhemesath about the component name from `StatusView` to `ResponseStatusView`.

Any one has any thoughts or concern on `ResponseStatusView` name ?

**Comment by amf9t2** [comment]
@jmsv6d  how about adding new type called `CUSTOM` and honoring icon and heading given via props. So if consumer doesn't like our mapping then they will have to set type CUSTOM and provide icon and heading. With this `type` prop become mandatory and if selected type is 'CUSTOM' then given  icon and heading will be rendered.

**Comment by neilpfeiffer** [comment]
Adding label "Needs Design Input" until UX delivers finalized API wireframe and theme variations. I will remove label when needed documentation is added.

**Comment by jmsv6d** [comment]
I just wanted to confirm that the only types that should be in the terra-core component are NO_DATA, NO_RESULT, NOT_AUTHORIZED, ERROR, and CUSTOM. There will need to be another component made in terra-consumer that wraps the terra-

**Comment by jmsv6d** [comment]
I just wanted to confirm that the only types that should be in the terra-core component are NO_DATA, NO_RESULT, NOT_AUTHORIZED, ERROR, and CUSTOM. There will need to be another component made in terra-consumer that wraps the terra-core component and uses the custom type to create the types that are specific to consumer. Just like what we've done with alert for clinical specific alert types.

**Comment by alex-bezek** [comment]
Correct. The current goal is for terra-core to implement the component that matches those types. From there @amf9t2 is looking into this issue on theming the icons for each type based on consumer vs clinical https://github.com/cerner/terra-core/issues/587

**Comment by jmsv6d** [comment]
Awesome. I think this looks good then +1

**Comment by emilyrohrbough** [comment]
+1 combined approach looks good to me. I like we are following a similar pattern to alert by using CUSTOM to handle the differences between core, clinical and consumer needs. 

In response to changing the name of the component, IMO `StatusView` is fine. To me, `RepsonsiveStatusView` makes me think this status would be updating on the fly or adjusting its layout for page resizing due to concept associated with responsive element.

**Comment by bjankord** [comment]
+1 to combined approach. I'm cool with naming it `ResponseStatusView`. In regards to `StatusView.scss` and the mixins, the default theme values should be written as fallback syntax. e.g. `border-radius: var(--terra-badge-border-radius, 0.25em);`, no need for a `cerner-default-theme` mixin. The `cerner-one-style-theme` will be named `cerner-clinical-theme`.

**Comment by amf9t2** [comment]
@neilpfeiffer any update on UI design input ?

**Comment by amf9t2** [comment]
@neilpfeiffer any update on UI design input ?

**Comment by bjankord** [comment]
Duplicate to https://github.com/cerner/terra-core/issues/1028
