### ISSUE TITLE
Create consumer theme for form fieldset

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#754]
# Issue Description
To match consumer UX, we want to enable the theming of terra fieldsets.
Here is a screenshot of the current component:
<img width="294" alt="screen shot 2017-08-28 at 9 26 05 am" src="https://user-images.githubusercontent.com/633148/29777823-f4f0c4c2-8bd2-11e7-9986-d190d74fd6eb.png">

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
CSS custom properties are added to enable the theming of the `<Fieldset />` component to match consumer UX visuals.

**Comment by neilpfeiffer** [comment]
Adding label "Needs Design Input" until UX delivers finalized API and theme variations. I will remove label when needed documentation is added.
