### ISSUE TITLE
Create file to store global values used in both CSS and JS

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#756]
# Issue Description
We have values like media queries which are common amongst there use in various component but are defined individually in each component. It would be nice to dry this up and have 1 standard location for values like these. 

One option may be to create a SCSS file in the `<Base />` component and use CSS modules `:export` syntax to make global values for use in CSS and JS.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Values like media query breakpoints are defined in 1 location and accessible in both our CSS and JS codebase.

**Comment by mhemesath** [comment]
> One option may be to create a SCSS file in the <Base /> component and use CSS modules :export syntax to make global values for use in CSS and JS.

I recommend that we just create a module to get the breakpoint values.... We don't need every consumer importing that CSS file directly

**Comment by bjankord** [comment]
N/A
