### ISSUE TITLE
Add <pre> tags to improve readability 

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#766]
# Issue Description
Some component's props are of type shape. The props table displays these object structures, but they are not easily readable if the shape is large. Adding the `<pre>` tags around the output would improve readability. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

<img width="1098" alt="screen shot 2017-08-30 at 10 30 33 am" src="https://user-images.githubusercontent.com/14099737/29880788-51c1ad00-8d6e-11e7-9ecf-b734d896760a.png">

## Current Behavior

<img width="1098" alt="screen shot 2017-08-30 at 10 28 43 am" src="https://user-images.githubusercontent.com/14099737/29880852-7efe4882-8d6e-11e7-8e5f-dc734780e3d9.png">

**Comment by saigorantla** [comment]
I will be working on this issue

**Comment by saigorantla** [comment]
@emilyrohrbough is this enhancement to add <pre> tag on all table columns or just type and Description columns data? as those are the two columns that can possibly have large data?

**Comment by emilyrohrbough** [comment]
I would expect to see tag added to the type column. 

Take a look at these lines
https://github.com/cerner/terra-core/blob/master/packages/terra-props-table/src/PropsTable.jsx#L19
https://github.com/cerner/terra-core/blob/master/packages/terra-props-table/bin/generateMarkdown/generatePropType.js#L2

**Comment by saigorantla** [comment]
Looks like pre tag has some styling, with gray background, below image will shows how it will look after code changes.

![pre-tag](https://user-images.githubusercontent.com/8334184/30240773-01e24ada-953c-11e7-9cdb-17fa6b2c5363.png)

I personally don't like gray background on pre tag in a row that contains white background (referring to one of type row in screen shot) let me know if thats acceptable or we need to update background of pre tag accordingly.

**Comment by emilyrohrbough** [comment]
I agree. I think we will want to update the background of any pre tags that occur in a white row. Additionally, it seems the pre tag is adding addition bottom-margin that can also be removed.

**Comment by bjankord** [comment]
Let's move forward with a PR for this. We can address the `pre` background color in another PR.

**Comment by emilyrohrbough** [comment]
Resolved in #873
