### ISSUE TITLE
can't scroll page after closing popup on IE

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-core#782]
# Issue Description
On IE11, after closing terra-popup, page can't be scrolled. Inspecting the dom shows that the style "overflow: hidden" on html tag is not removed after popup is closed
![terra-popup-ie-no-scroll](https://user-images.githubusercontent.com/5943136/30134147-b93b08ca-931b-11e7-8c30-c259fd0d8abe.gif)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Steps to Reproduce

1. open http://terra-ui.herokuapp.com/components/core/popup on IE
2. open a default popup
3. close the popup
4. try to scroll the page, which doesn't work

## Environment

* Component Version: 
* Browser Name and Version: IE 11
* Operating System and version (desktop or mobile): IE virtual machine on MAC

**Comment by bjankord** [comment]
This has been released in terra-popup@1.9.0
