### ISSUE TITLE
Menu - keyboard sub-menu navigation and arrow key functions

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#784]
# Issue Description
The menu component needs enhancements for keyboard navigation:
- Tab key should set focus within a sub-menu to the first item in that sub-menu. Currently you have to tab several times to get to the sub-menu items.
- Enable arrow keys (in addition to Tab) to move focus between menu items.
- Action and Close Actions available in the menu and submenu examples respond to mousepress but not "enter" on keyboard

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

Here is a link to keyboard navigation recommendations:
http://webaim.org/techniques/keyboard/

**Comment by PaulSolDev** [comment]
Orion JIRA created
