### ISSUE TITLE
Time input example - Time Provided label and value do not mirror correctly in RTL

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#789]
# Issue Description
The "Time Provided:" label and value display LTR even when the page is switched to RTL. Note that this is an issue with the example page and not a bug in the component itself.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
"Time Provided" label and value should be mirrored in RTL.

## Current Behavior
- "Time Provided" label and value display LTR when the examples are displayed in RTL.
- There is also an issue where an extra colon character is added to the text when switching between LTR and RTL.

## Steps to Reproduce
1. Go to the time input example page .
2. Switch from LTR to RTL.
3. View the Time Provided label and value.

## Environment
* Component Version: current
* Browser Name and Version: all
* Operating System and version (desktop or mobile): all

**Comment by emilyrohrbough** [comment]
If you notice, this is an issue is several placed on the example page. Notice 'Theme:' or 'Locale:' followed by their drop downs.
