### ISSUE TITLE
Update site example for terra-popup.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#791]
# Issue Description
Update site example for terra-popup, include more variance in the examples, and correct the span styling inside the listitems, on certain browsers it's affecting the focus styling.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
@dkasper-was-taken Do you know if this is still applicable?

**Comment by dkasper-was-taken** [comment]
@bjankord I believe the span issue has been solved, but the varying range of examples are still applicable. @mmalaker Was interested in better examples.

**Comment by bjankord** [comment]
Ok lets add these when we get storybook set up.
