### ISSUE TITLE
Add new i18n locales 

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-core#805]
# Issue Description
Adding terra-i18n support for new locales: 

- ar
- es-US
- es-ES
- pt-BR
- fr-FR

We also need to add the translations in core/clinical components: https://github.com/cerner/terra-core/issues/806

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by zhongyn** [comment]
https://github.com/cerner/terra-core/pull/800

**Comment by bjankord** [comment]
This has been released in terra-i18n@1.8.0
