### ISSUE TITLE
Add theming capability to overlay component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#809]
# Issue Description
To enable modern CSS theming capabilities, we want to update this component to use CSS custom properties for styles that could be themed.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Themable component styles are converted from static values to CSS custom properties.

## Current Behavior
Component styles are static and do not support theming.

**Comment by tm4027** [comment]
Is this an attribute being applied to a single component or a unique component itself?
