### ISSUE TITLE
webpack dev server not working in IE

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-core#810]
# Issue Description
When serving terra-site locally with webpack dev server, home page fails to load in IE.

![screen shot 2017-09-14 at 9 41 12 am](https://user-images.githubusercontent.com/5943136/30436050-e648d91c-9930-11e7-9f71-9f5260e4be2b.png)
![screen shot 2017-09-14 at 9 42 02 am](https://user-images.githubusercontent.com/5943136/30436108-02729a9c-9931-11e7-9e55-e4f37dc5c27f.png)

However, serving terra-site on express server works. Very likely that babel-polyfill can't polyfill webpack dev server hotloading module.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Steps to Reproduce

1. git pull master
2. npm run clean:install
3. npm run start
4. visit localhost:8080, (10.0.2.2:8080 for virtualbox/IE)

## Environment

* Component Version: latest master
* Browser Name and Version: IE 11
* Operating System and version (desktop or mobile): MAC, virtualbox

**Comment by mjhenkes** [comment]
@zhongyn is this still an issue?

**Comment by zhongyn** [comment]
@mjhenkes @emilyrohrbough it works now by testing the latest master branch
