### ISSUE TITLE
Running jest tests from a nested package fails in regards to file path issues on Windows

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#813]
# Issue Description
On Windows 10, running jest tests from a nested package fails in regards to file path issues. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Contributors can run jest tests for individual packages on Windows

## Current Behavior
Contributors cannot run jest tests for individual packages Windows

## Steps to Reproduce
1. Clone repo
2. Run `npm install`
3. Change directories to a component directory. e.g `packages/terra-alert, packages/terra-button`
4. Run `npm run test:jest`

## Environment
* Operating System and version (desktop or mobile): Windows 10

**Comment by Singleton06** [comment]
Any time that I run this on windows from a package's directory, it usually just fails because it is unable to find any tests that match.
```
C:\installs\workspaces\dustin-terra\terra-core\packages\terra-search-field>npm run test:jest

> terra-search-field@1.12.1 test:jest C:\installs\workspaces\dustin-terra\terra-core\packages\terra-search-field
> jest ./tests/jest/* --config ../../jestconfig.json

No tests found
In C:\installs\workspaces\dustin-terra\terra-core
  1987 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 88 matches
  testPathIgnorePatterns: \\node_modules\\ - 1987 matches
Pattern: ./tests/jest/* - 0 matches
```

However, if I run this from the command line it works (after installing jest globally):
```
jest ..\\terra-search-field\\tests\\jest --config ../../jestconfig.json
```

I then tried updating the package.json to the following and was able to get it to work as well:
```
"test:jest": "jest ..\\\\terra-search-field\\\\tests\\\\jest --config ../../jestconfig.json",
```

I realize this isn't the solution to this but it gives us an idea of how the matching is off.

**Comment by emilyrohrbough** [comment]
Try updating the script to `"test:jest": "jest node tests/jest/* --config ../../jestconfig.json",`
