### ISSUE TITLE
Add ability to disable items in menu and collapsible menu view

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#817]
# Issue Description
Collapsible Menu (PR #793) doesn't allow a menu to have a disabled item.  We have a scenario where we need to put several buttons in a collapsible view, but some buttons may need to be disabled.

## Issue Type
- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Buttons should appear disabled when the consumer indicates the menu item is disabled.  In the menu, the items should appear disabled, so the user knows they can't click it.

**Comment by neilpfeiffer** [comment]
**Design Input**
For any item that is disabled, use either `opacity: 0.3;` or a color fill of terra-gray-30 or `#BCBFC0`, also be sure to prevent any `:hover`, `:focus`, & `:active` styles and not switch the cursor to pointer (stays default cursor).

**Comment by hboege** [comment]
Our team would be willing to contribute the solution to this issue if it would help expedite its availability.
