### ISSUE TITLE
Long Title 🥇 

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#819]
<img width="269" alt="screen shot 2017-09-14 at 6 00 37 pm" src="https://user-images.githubusercontent.com/8146159/30461908-ac87564a-9976-11e7-8178-92fbafa53089.png">

**Comment by emilyrohrbough** [comment]
@Matt-Butler Is the issue here that the close button is hidden when a long title is provided in a submenu?

**Comment by mjhenkes** [comment]
@emilyrohrbough title is spelled tittle. 😆

**Comment by mjhenkes** [comment]
https://github.com/cerner/terra-core/pull/820

**Comment by mjhenkes** [comment]
Resolved
