### ISSUE TITLE
Add OCS clincal theme to body background

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#825]
# Issue Description
The OCS UX team has designed a background they would like to have applied to all OCS clinical applications. This issue is to cover implementing this background through our theming layer for OCS clinical.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
When users are viewing a site using terra-base and the OCS clinical theme, the background is styled to match the OCS clinical approved background style.

**Comment by bjankord** [comment]
This is blocked on #826

**Comment by neilpfeiffer** [comment]
Need to get green-light before merging from OCS:Clinical
