### ISSUE TITLE
Datepicker shows incorrect year in select when supplied out of range date

### ISSUE THREAD

**Issue by doogthemushroom** [cerner/terra-core#828]
# Issue Description
If the date picker is supplied with a date outside the range of allowable dates, the year Select displays the incorrect year.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Display the correct year value in the Select, and have the value disabled.

## Current Behavior
The invalid month is displayed in the month/day picker, while the Select shows the incorrect year. Attempting to change to the correct year is not possible until first changing to another year (onChange isn't occurring until that point).

## Steps to Reproduce
Supplied:
range -  September 18, **2011** to September 18, **2017**
selectedDate - September 18, **2009**

The result looks like:

![wrong year](https://user-images.githubusercontent.com/1391996/30566998-fc562870-9c93-11e7-8363-3d41ca0d4eca.png)

This is the month of September 2009, while the Select's say it is September 2011.

## Environment
* Component Version: terra-date-picker
* Browser Name and Version: 1.9.0
* Operating System and version (desktop or mobile): desktop

**Comment by benbcai** [comment]
This issue occurs because the default date provided is outside the min/max date range. The change to address this issue is when the default date is out of range or excluded, putting focus on the input field or clicking on the calendar button will clear that unacceptable default date as if no default date was provided.

**Comment by bjankord** [comment]
This has been released in terra-date-picker 1.17.0
