### ISSUE TITLE
Add support for disabled values in terra-select component

### ISSUE THREAD

**Issue by doogthemushroom** [cerner/terra-core#829]
# Issue Description
I would like to contribute a change to the select component to add support for disabled options.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
There would be an additional value in the options array for specifying if a option is disabled. This would be an optional value, and if not supplied the option would be selectable. For example...

Current option value:
```javascript
options={[
  { value: 'm', display: 'moo' },
  { value: 'b', display: 'boo' },
  { value: 'z', display: 'zar' }
]}
```
Results in select with 3 options 'moo', 'boo', and 'zar'.

New option value:
```javascript
options={[
  { value: 'm', display: 'moo' },
  { value: 'b', display: 'boo', disabled: true },
  { value: 'z', display: 'zar' }
]}
```
Results in select with 3 options 'moo', 'boo' (disabled), and 'zar'.

## Current Behavior
N/A

**Comment by neilpfeiffer** [comment]
**Design Input**
For any item that is disabled, use either `opacity: 0.3;` or a color fill of terra-gray-30 or `#BCBFC0`, also be sure to prevent any `:hover`, `:focus`, & `:active` styles and not switch the cursor to pointer (stays default cursor).

**Comment by mmalaker** [comment]
Functional verification completed. The disabled values now display and function correctly.

**Comment by PaulSolDev** [comment]
Orion JIRA created
