### ISSUE TITLE
Signature: Right clicking Signature Component causes "sticky" draw

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#832]
# Issue Description

Right clicking inside of a Signature Component can cause a "sticky" effect that continuously draws line segments without the mouse being pressed and requires an additional click to deactivate.

![stickysignature](https://user-images.githubusercontent.com/6720991/30609208-5c92d010-9d40-11e7-9f2e-d77c941b791c.gif)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

Right click should not trigger drawing

## Current Behavior

Right click causes sticky drawing

## Steps to Reproduce

1. Navigate to http://engineering.cerner.com/terra-core/#/site/signature
2. Right click and release inside of the Signature component and continue moving the mouse
3. Observe the lines will draw as the mouse moves

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by dkasper-was-taken** [comment]
This can also be reproduced using the left click, and leaving the confines of the browsers. I believe we'd need to investigate a mouseout event in addition to the current mouseup.
