### ISSUE TITLE
Cards need ability to set base color.

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-core#836]
# Issue Description
Cards may need a different base text color than the body in dark themes.

## Issue Type
- [x] Enhancement

## Expected Behavior
A dark theme can be configured (dark background color with light text) leaving white cards to have a dark base color so that text within cards is always dark.

## Current Behavior
If I set the base background color to a dark color I will want to set the base text color to a light one. However, this has the effect of causing text within cards to display as a light color as well and be unreadable.

## Steps to Reproduce
1. Set `--terra-base-background-color` to a dark color
2. Set `--terra-base-color` to a very light color.
3. Create a card with text in it.
4. The text in the card is also very light and difficult to read.

## Notes
This can be solved a few ways:
1. Provide a card-text-color value that has the same value as the `--terra-base-color` by default.
2. If we can rely on cascading themes (which we can't for IE11), we could have cards leverage a light/dark theme. but this may result in the same solution as #1.
3. Target text outside of cards as special title components and give that a custom property to change to light. This would end up leaving base text color to be dark. Downside here is that we would  need to theme every text that's outside of a card on a dark background.

**Comment by mhemesath** [comment]
I thought about this a bit more and would like to propose we simply add this to cards:

```css
.card {
  color: var(--terra-card-color, inherit);
}
```

This will leave cards be default to inherit the base color (as it does today) but allow a theming override hook.  @bjankord or @neilpfeiffer  any reservations?

**Comment by bjankord** [comment]
@mhemesath looks good to me

**Comment by WhiteLight1107** [comment]
Merged PR:https://github.com/cerner/terra-core/pull/851
