### ISSUE TITLE
CLI outputs YError: Too many arguments provided. Expected max 2 but received 3 when running webpack dev server

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#845]
# Issue Description
When running `npm start` to run the webpack dev server, we're seeing the following error ouput:

```sh
YError: Too many arguments provided. Expected max 2 but received 3
```

Webpack compiles correctly and starts the server, however this error may be concern to new contributors. It looks like there are some issues logged against webpack for this issue.

* https://github.com/webpack/webpack-dev-server/issues/1087
* https://github.com/webpack/webpack-dev-server/issues/983

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Running `npm start` should not generate any error messages in regards to number of arguments provided

**Comment by yuderekyu** [comment]
I'm not seeing this error output when executing `npm start` to run the webpack dev server - this a non issue now?

**Comment by bjankord** [comment]
I think this issue was resolved when we updated to webpack v3. Gonna close this.
