### ISSUE TITLE
Capybara FirefoxDriver not able to select options

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-core#849]
# Issue Description
When running Capybara using FirefoxDriver and Selenium, the Capybara function [select](http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Actions#select-instance_method) does not have any effect.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Capybara functions should be usable on Terra components, in particular select on select boxes.

## Current Behavior
The Capybara function select has no effect on Terra-form select boxes.

## Steps to Reproduce
The Capybara test line `select '3', from: select_fields[0][:name]` has no effect on the view of the page, indicated by failing tests (selection did not change) and by screenshots at the time of the test failure. This line is working with automated tests pointing at Chrome.

## Environment
* Component Version: terra-form 1.9.0
* Browser Version: FirefoxDriver from Selenium (local Firefox instances, in particular build 43, seem to be working correctly)

**Comment by hboege** [comment]
What is the outcome for this issue?  Although it is closed, I don't see any attached pull request, so it seems like this is still a significant problem for teams using capybara tests for gray box testing.

**Comment by mhemesath** [comment]
Terra selects are not HTML select elements so you should not use the `select` helper to activate them.

**Comment by hboege** [comment]
While the terra-form-select is not a select element, this issue was originally logged against terra-form's [select control](https://github.com/cerner/terra-core/blob/master/packages/terra-form/src/Select.jsx#L94), which is a HTML select element.
Should this be reopened to address terra-form's select?  Or is the older control deprecated in favor of terra-form-select?

**Comment by mhemesath** [comment]
> Should this be reopened to address terra-form's select? Or is the older control deprecated in favor of terra-form-select?

No this should remain closed. Terra selects are not using the native control because it does not wrap well on mobile (cuts off text) and does not match the design from our UX team.

**Comment by hboege** [comment]
I was able to speak with a contributor and learned that the new terra-form-select is the new preferred control, as the old terra-form/select is being (or has been deprecated).  Thus, there is nothing to fix as the issue is logged for a deprecated component.
