### ISSUE TITLE
Safari animation issues for SlidePanel

### ISSUE THREAD

**Issue by madelineisabelle** [cerner/terra-core#852]
# Issue Description
When a SlidePanel is being used and the mainContent mounts at the same time the panelContent is being opened and closed, there are animation issues in Safari that cause the content to be skewed and sometimes off of the screen. This is happening in large screen sizes as well as small screen sizes in Safari. @dkasper-was-taken believes this will require the CSSTransition portion of SlidePanel's animation to be replaced.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
The panelContent should transition to meet the mainContent without going off of the screen.

## Current Behavior
The panelContent and mainContent are skewed and only partially on the screen.

## Steps to Reproduce
How we have produced this issue: 
1. Create a SlidePanel
2. Have a list as the mainContent that triggers the panelContent to open
3. To allow for consecutive selections in the list, when the panelContent closes, rerender the list
4. View animation issues in Safari

## Environment
* Component Version: slide-panel 1.9.0
* Browser Name and Version: Safari 10.0.1
* Operating System and version (desktop or mobile):  desktop--mac

<img width="656" alt="slidepanelsmallscreen" src="https://user-images.githubusercontent.com/8262756/30748101-d302abcc-9f74-11e7-9300-566e71e79da5.png">
<img width="797" alt="slidepanellargescreen" src="https://user-images.githubusercontent.com/8262756/30748122-e2f557d2-9f74-11e7-80cd-19b3350a2e0a.png">

**Comment by dkasper-was-taken** [comment]
After recreating the example structure in our own site page and testing across all browsers, I looked further into the consumer implementation and it appears it's an issue with state being managed too high in the structure and using functional components all the way down, forcing remounts of all components, thus retriggering layouts.

**Comment by dkasper-was-taken** [comment]
I can help with updating the implementation to function correctly.

**Comment by dkasper-was-taken** [comment]
Uncovered the problem, using a loading indicator in a slide panel with focus trap turned on causes the slidepanel to receive focus, forcing it on screen, and then animates. Closing issues.
