### ISSUE TITLE
Locales should fallback to base locale if regional locale not present.

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-core#854]
# Issue Description
1. Currently terra supports `es`, but if `es-ES` is requested it will fail. Ideally it would fallback to just 
`es`.
2. if the locale is identified as `es` but `ES` is passed in it will fail.  Locales should be case insensitive. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ x ] Bug
- [ ] Other

## Expected Behavior
If requesting a regional locale that doesn't exist (e.g. es-ES), i18n will fallback to es. The given locale string should not be case-sensitive. 

## Current Behavior
It fails if the locale doesn't exactly match.

## Steps to Reproduce

1.  Wrap terra with i18n provider. Pass a locale such as `es-ES` that isn't supported.

**Comment by zhongyn** [comment]
as i know es-ES is supported by terra-i18n: https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/src/i18nSupportedLocales.js

**Comment by zhongyn** [comment]
agree that if a regional locale is not found, it will fallback to the base locale. (`a-b` fallbacks to `a`)
