### ISSUE TITLE
Create selectable sub-component for Single and Multi Lists

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-core#856]
# Issue Description
Create sub-component as a common underlying implementation for the single and multi select list components.  Allowing consumers to directly consume this component if they wish to managed there own state.  Also break out common functions to a utilities file, for consumers to use in their custom implementations.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by dkasper-was-taken** [comment]
# Tech Design for SelectableList
## Summary:
SelectableList consumes List, MultiSelectList and SingleSelectList consume the Selectable List API.

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| children | node | null | JSX children |
| isDivided | bool | false | Whether or not divider lines are present. |
| disableUnselectedItems | bool | false | Whether or not unselected items should be disabled. |
| hasChevrons | bool | false | Whether or not the ListItems should have chevron styles. |
| onChange | func | null | Function callback returning the event and index. |
| selectedIndexes | array | [] | Array of numbers indicating the selected indexes. |

## Example:
```
 <SelectableList
  isDivided={isDivided}
  onChange={this.handleOnChange}
  selectedIndexes={[this.state.selectedIndex]}
  hasChevrons={hasChevrons}
  disableUnselectedItems={false}
>
  {children}
</SelectableList>
```

**Comment by emilyrohrbough** [comment]
For #835 @dv297 suggested the onChange would be have the following parameters: 

> The following parameters:
the event triggering the onChange
the sorted list of the indexes for the rows selected
the index of the last item selected

This might be a good place to include these parameters.

**Comment by dkasper-was-taken** [comment]
Are you referring to the SingleSelect and MultiSelect unmanaged components? If so, that makes sense.

I wouldn't think that those values would be returned from the managed SelectableList.

**Comment by emilyrohrbough** [comment]
Ah very true. This might be a good enhancement elsewhere then for MultiSelect.
