### ISSUE TITLE
Allow terra components to not trim whitespace

### ISSUE THREAD

**Issue by madelineisabelle** [cerner/terra-core#864]
# Issue Description
Currently, multiple whitespaces are being trimmed in our project and we are consuming terra-core and terra-clinical. It is specifically happening with clinical action header and clinical item display, but I don't believe any coding for preventing this from happening has been done anywhere. On @jmsv6d's reccommendation, I am logging this issue to open up the conversation on this so it can be decided whether it will be handled by terra-core and terra-clinical or we will need to find a different solution. 

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Any whitespace that is in the string would be displayed.

## Current Behavior
Multiple whitespace characters are trimmed to a single whitespace.

![screen shot 2017-09-25 at 4 09 35 pm](https://user-images.githubusercontent.com/8262756/30831125-f704721e-a20b-11e7-8b7b-4b5c813511a7.png)

The string being displayed in the text field does not match the string that is displayed in the action header as the whitespace is being trimmed.

**Comment by dkasper-was-taken** [comment]
Ensuring whitespace removal is not a function of the terra components. Within html text additional white space is removed by default. If you want to ensure that you maintain white space characters you'll need to inject your own character entity to maintain them.
1 space:  &nbsp;
2 spaces:  &ensp;
4 spaces:  &emsp;

Example:
<p>This text is &emsp; spaced</p>
