### ISSUE TITLE
Add documentation to terra-table detailing how onChange is used

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#865]
# Issue Description
Single Selectable Rows has an attribute called onChange that can help a developer get the index of a selected table row. However, it's not clear from the documentation on how it should be used.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
onChange is documented in the props.

## Current Behavior
onChange is not documented

**Comment by JakeLaCombe** [comment]
If you like, we can add additional documentation to the table page as well

**Comment by corymcdonald** [comment]
Gonna grab this!
