### ISSUE TITLE
Add the ability to add defaultSelected to SelectField

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#868]
# Issue Description
Reset buttons reset form elements to the previous value of a form element. For select boxes though, it will reset to the default value of the select field unless selected or defaultSelected is set on the option that is selected

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Option nodes can have the selected and defaultSelected values set.

## Current Behavior
Option nodes do not set selected or defaultSelected

**Comment by yuderekyu** [comment]
React doesn't allow `selected` to be set within options. Instead, they expect consumers to set a select's `value` to the state. https://reactjs.org/docs/forms.html#the-select-tag
