### ISSUE TITLE
Update Enzyme to v3.x

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#871]
# Issue Description
This is the most up-to-date version, plus v3.x provides support for > React 16! 🎉  They authors have even provided a v2 to v3 [migration guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md). 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by bjankord** [comment]
@emilyrohrbough Haven't had a chance to look into this, do you know, is enzyme v3 compatible with react v15, or is it only compatible with react v16?

**Comment by emilyrohrbough** [comment]
V3 requires the configuration of a react adaptor, where the adaptor chosen is the react version listed as the project dependency. The [configuration](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#configuring-your-adapter) appears to be simple, including the following in a setup file:

```import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

I'm not sure yet how this would tie in with our monorepo structure and current jest setup that creates global enzyme methods.

**Comment by mhemesath** [comment]
I'd think it would be sufficient to just use `enzyme-adapter-react-15.
