### ISSUE TITLE
Support ContentContainer footer

### ISSUE THREAD

**Issue by noahbenham** [cerner/terra-core#872]
# Issue Description

CareAware Connect Messenger uses a custom content container with a header, as well as a footer (`Send a message...`). We'd like to consume Terra's `ContentContainer` but cannot until footers are supported.
<img width="391" alt="screen shot 2017-09-27 at 5 14 10 am" src="https://user-images.githubusercontent.com/6981195/30908287-c4e2bbdc-a342-11e7-9cb0-dfc0e797c645.png">

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

`ContentContainer` should allow specifying both a header and footer, or just one.

## Current Behavior

`ContentContainer` only allows a header.

## Steps to Reproduce

N/A

## Environment

* Component Version: `1.10.0`
* Browser Name and Version: Chrome 60.0.3112.113 (Official Build) (64-bit)

* Operating System and version (desktop or mobile): macOS 10.12.6 (16G29)

**Comment by noahbenham** [comment]
@emilyrohrbough Do you have a rough timeline for addressing this?

**Comment by mjhenkes** [comment]
@noahbenham, we'll need to prioritize this work with the work already on our schedule. We also need to discuss with UX the implications of adding footer support. Primarily footers interaction with keyboards on mobile devices.

**Comment by tm4027** [comment]
JIRA created

**Comment by neilpfeiffer** [comment]
Had meeting this morning with UX Designers and initial concepts looked good. @noahbenham will work with @dkasper-was-taken to do a contribution to enhance the Terra content-container to add the footer and investigate any potential issues raised. Tech Design to follow.

**Comment by noahbenham** [comment]
# Tech Design for Content Container
## Summary:
Introduce content-container footer to allow sticky bottom-aligned content such as buttons, input, etc. This initial change would require consumers to designate content for this space and does not include footer functionality like terra-clinical-header.

## Requirements:
N/A

## Requirements Added:
N/A

## Requirements Dropped:
N/A

## Responsiveness:
N/A

## Bidirectionality
N/A

## Accessibility
N/A

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| footer | node | null    | The footer element to be placed within the footer area of the container. |

## Example:
```jsx
<ContentContainer
  header={<h1 blurb />}
  footer={<Button />}
  fill
>
  {container}
</ContentContainer>
```

## CSS Classes:
| Selector         | Description |
|------------------|-------------|
| .content-container > .footer | Matches existing header style       |

**Comment by dkasper-was-taken** [comment]
+1

**Comment by emilyrohrbough** [comment]
+1

**Comment by bjankord** [comment]
+1 on tech design.

**Comment by tbiethman** [comment]
+1

**Comment by mjhenkes** [comment]
+1
