### ISSUE TITLE
Component Placeholder for asynchronous or slow loading 

### ISSUE THREAD

**Issue by tm4027** [cerner/terra-core#877]
# Issue Description

## Issue Type

- [ ] New Feature
- [X ] Enhancement
- [ ] Bug
- [ ] Other

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by bjankord** [comment]
@tm4027 Does the loading overlay at the bottom of this page work for your use case?
https://terra-ui.herokuapp.com/components/core/overlay
