### ISSUE TITLE
Uplift Select component for OCS

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-core#880]
# Issue Description
Uplift select component to support ocs expected behavior.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by jmsv6d** [comment]
# Tech Design 
## Summary:
The first phase of the uplift will be to maintain existing functionality. Add needed theme-able variables, and to replace the select, with a custom drop down consuming terra-hookshot.

## Responsiveness:
Options in the menu will wrap when there is not enough space and the value will be truncated when displayed in the input. The list will scroll when menu reaches the height of it's container.

## Accessibility
User should be able to navigate the options using the arrow keys and select using space or enter.
User should be able to tab to select field and press enter to open dropdown.

## React Props:
In this phase I don't believe any new props are needed. Some props may need to be added in future phases, but I believe those changes can be made passively.

## Theme-able styles:
Input border radius
Input borer color
Input background color
Down arrow color
Menu container transparency and blur
Menu container corner radius
Menu Item hover state color
Menu item hover text style
Menu item select state color
Menu item select text style
Font family
Font style
Menu dropshadow
Bounded menu margins

**Comment by bjankord** [comment]
> The list will scroll when menu reaches the height of it's container.

Should we set a max-height on the dropdown?

**Comment by mjhenkes** [comment]
For the first pass at select we're scoping out the option of switching to a modal at small breakpoints.
We also need to spike on blurred drop down backgrounds.

**Comment by emilyrohrbough** [comment]
Are the hover styles expected to be the same as focus styles? 

What about hover/focus of selected option?

**Comment by jmsv6d** [comment]
@bjankord  Are you thinking adding a prop for max-height, or a themeable variable?

**Comment by jmsv6d** [comment]
@neilpfeiffer  Would you be able to answer @emilyrohrbough questions?
I don't see anything in the zeplin files for focus styles on menu items or hover/focus of selected items.

**Comment by StephenEsser** [comment]
I think this component meets the criteria as something that should optionally accept children.

Something similar to:
```
<Select>
  <Select.Option value="red">Red</Select.Option>
  <Select.Option value="blue">Blue</Select.Option>
</Select>
```

**Comment by mjhenkes** [comment]
@StephenEsser agreed. The question is are we ok with this update being non passive for do we support both 'children' and 'options'.

**Comment by jmsv6d** [comment]
@mjhenkes Not again! I think I would support a non-passive change for that switch.

**Comment by StephenEsser** [comment]
My preference is to use children to give users a larger range of functionality and freedom without needing to add something into the API each time a new use case arises. ( Like what happened with display / value https://github.com/cerner/terra-core/pull/595)

But I know there was a strong pull from consumer for `options` as a convenience to auto generate from a data structure. I think it would be possible to keep both and just keep the options mutually exclusive with a logical or. 

```
<select>
  {children || generate(options)}
</select>
```

**Comment by jmsv6d** [comment]
The select component already has the deprecated `choices` prop as well as the 'options' prop. Adding children on top of those seems really excessive. If we want to add children as an option I say we should at minimum do a major version bump to remove the `choices` prop, and then if we'd be doing the major version bump anyway it would make sense to remove `options` as well and just use children.

**Comment by bjankord** [comment]
+1 for major version bump using children. +1 on tech design.

**Comment by emilyrohrbough** [comment]
+1 based on discussion.

**Comment by StephenEsser** [comment]
+1

**Comment by mjhenkes** [comment]
+1

**Comment by tm4027** [comment]
JIRA created
