### ISSUE TITLE
Adjust Type Check in SingleSelectableRows of terra-table

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#881]
# Issue Description
[In SingleSelectableRows](https://github.com/cerner/terra-core/blob/terra-table%401.11.0/packages/terra-table/src/SingleSelectableRows.jsx#L119), there is a line that checks if the child element is a "TableRow". This type check is included to ensure that TableHeaders are not given any "selection" related props when wrapped by SingleSelectableRows 

However, many consumers of component libraries will create consumption layers above the component. This gives the consumer the flexibility to compose the components however they desire and separate out concerns of a Row to its own component, rather than cluttering the Table component with the display of the Row. 

For example, a consumer may create a "FooTable" which displays information about foo in "FooRow"'s. FooRow will use TableRows internally, but because of this type check, the FooRow won't get the new props normally given to TableRows by SingleSelectableRows.

```
const FooRow = ({ foo }) => {
  const fooDate = foo.date.format(desiredFormat);
  const { a, b, c } = foo;
  
  return (
    <Table.Row>
      <Table.Cell key={'COLUMN_0'} content={fooDate} />
      <Table.Cell key={'COLUMN_1'} content={a} />
      <Table.Cell key={'COLUMN_2'} content={b} />
      <Table.Cell key={'COLUMN_3'} content={c} />
    </Table.Row>
  );
};
```

When wrapped by SingleSelectableRows, FooRow cannot be selected. This type check could be adjust to check if something is a TableHeader, preserving the intended behavior but opening up a more desired behavior of allowing custom components that use TableRow internally. Other solutions may also be desired, as there might be a use case for people to create their own TableHeader, although this seems less likely  than creating their own custom TableRow. 

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Any component that renders TableRow and is consumed by SingleSelectableRows should be able to be selected.

## Current Behavior
Any component that renders TableRow and is consumed by SingleSelectableRows cannot be selected.

**Comment by emilyrohrbough** [comment]
Resolved in #906
