### ISSUE TITLE
Add disableCloseOnEsc Prop to Overlay

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#909]
# Issue Description
Provide an opt-out of the defaulted close on escape behavior.

Proposal to add `disableCloseOnEsc` prop. Default value `false`. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Allow consumers to decide if close on escape is desired.

## Current Behavior
When an onRequestClose function is provided, overlay always closes on escape.

**Comment by bjankord** [comment]
@emilyrohrbough What's the logic around disabling the ability to close via `esc` key? This feature is built in for accessibility reasons.

**Comment by emilyrohrbough** [comment]
I came across this prop in Modal. It made me consider the possibility that consumers may want to disable close on escape for overlays as well, in particular overlays relative to container.

**Comment by emilyrohrbough** [comment]
Holding off on adding this functionality until a specific need is in place.
