### ISSUE TITLE
Create Layout

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-core#919]
# Issue Description
We'd like to create a Layout component that would provide consumers with a good starting for application development.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The current idea for the Layout revolves around three defined content regions:
* header: A header region at the top of the layout. It remains fixed (using flexbox).
* content: A region in the body of the layout. The content region is displayed below the header and can overflow.
* menu: A region in a sidebar-type disclosure that can be toggled on/off. This can also be pinned onscreen or hidden altogether.

Tech design to come.

**Comment by emilyrohrbough** [comment]
Would this take place of https://github.com/cerner/terra-core/issues/312?

**Comment by bjankord** [comment]
Yes, we can close #312 and mark it as duplicate as this has a better issue description / expected behavior.

**Comment by tbiethman** [comment]
Whoops, sorry I missed that one. Though I did think it was weird the layout tag already existed...

# Tech Design

| Prop | Type | Default | Description |
|----------|------|---------|--------------|
| toolbar | element | undefined | The component to be rendered in the Toolbar region. |
| menu | element | undefined | The component to be rendered in the Menu region. |
| menuText | string | undefined | String used to decorate the various menu toggle controls. |
| children | element | undefined | Children will be rendered in the layout's Content region. |

## Design Decisions

At desktop breakpoints (medium through huge), the menu is disclosed using a built-in hover mechanism. It can also be pinned open, at which point the menu will squish the content instead of overlay it. Also, at these breakpoints, the menu does not overlay or squish the toolbar content.

At the tablet breakpoint (small), the menu is disclosed by a programatic toggle provided to the toolbar content. The toolbar content must adhere to a layout-specific prop API and properly display a toggle button if necessary. The toolbar is overlaid by the menu when open at this point, and the menu is closed by clicking in the negative overlay space.

The phone breakpoint (tiny) behaves similarly to the tablet breakpoint, with the main difference being the menu size. It is almost fullscreen here, leaving only enough space to allow for dismissal.

## Example

```jsx
<Layout
  toolbar={<ToolbarExample />}
  menu={<MenuExample />}
  menuText="Menu"
>
  <ContentExample />
</Layout>
```

## Visual Examples

### Desktop Size (medium - huge)

![desktop_layout](https://user-images.githubusercontent.com/1711637/31551856-762fc62c-affb-11e7-9498-5c8efde85f18.gif)

### Tablet Size (small)

![small_layout](https://user-images.githubusercontent.com/1711637/31552008-dd707c50-affb-11e7-81a3-2aa80c5143fa.gif)

### Phone Size (tiny)

![tiny_layout](https://user-images.githubusercontent.com/1711637/31552099-15d0ffca-affc-11e7-8181-5887f5cbdf14.gif)

## Potential Changes

The only styled components built into the layout control the disclosure of the menu. While those components are all individually theme-able, we may want to allow consumers to provide completely custom components in those areas.

**Comment by mjhenkes** [comment]
+1 As mentioned my only concern would be the styling on the menu disclosure but I think thats appropriately mitigated through theme-able variables. Could you document what you intend to be theme-able on this tech design? Additional customization options (ex changing the responsive break points) could be added later passively.

**Comment by mhemesath** [comment]
Is this menu intended to support consumer? What specific solutions is this intended to be used for?

**Comment by tbiethman** [comment]
Update: Added Theme-able Variables section to Tech Design

@mjhenkes

**Comment by tbiethman** [comment]
@mhemesath This layout is intended to support any application that has its needs met by the layout. It was derived from some of the work done to support clinical application workflows, but the layout itself lacks any clinical-specific characteristics. Discussions with the core Terra and UX teams led to us including it in the core repo as the first (of many?) layouts provided by Terra, with its initial use case being a replacement for the existing BlueSteel layout.

Based on what I've seen of the Consumer layout and menu, I'm not sure this would fit its needs 100%. Do you think it'd be feasible to align the two?

**Comment by mhemesath** [comment]
@tbiethman  thats a question for UX. If it doesn't meet the needs of consumer then I don't think it should be here.. because as consumer's layout is already done I could make the hypothetical argument that ours should be in core already.....

**Comment by tbiethman** [comment]
This issue was moved to the terra-framework repository: https://github.com/cerner/terra-framework/issues/2
