### ISSUE TITLE
Forms: Checkbox/Radio long text wrapping

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#925]
# Issue Description
Correct the text wrapping for long labels for Checkboxes and Radio buttons.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Multiword and single word (non-breaking character labels) should maintain text alignment and not wrap underneath the input.

![image](https://user-images.githubusercontent.com/1355485/31566604-ff14e4ec-b030-11e7-9c8d-32cc0253fa4f.png)

![image](https://user-images.githubusercontent.com/1355485/31566606-02c4873c-b031-11e7-8e91-be99ef79c188.png)

## Current Behavior
Multiword and single word (non-breaking character labels) wrap underneath the input. 

![image](https://user-images.githubusercontent.com/1355485/31566243-57253670-b02f-11e7-8f16-48c2f65dd8b8.png)

![image](https://user-images.githubusercontent.com/1355485/31566252-5e992510-b02f-11e7-942a-58aa262435a6.png)

**Comment by neilpfeiffer** [comment]
Can be resolved when radios and checkboxes uplifted to new OCS/themes - meets same design input guidelines.

**Comment by skalyanmoguloju** [comment]
@neilpfeiffer: is this issue open? If so can I get assigned to me?

**Comment by jmsv6d** [comment]
@skalyanmoguloju This should be getting resolved with this issue: https://github.com/cerner/terra-core/issues/960 that's currently being worked on.

**Comment by bjankord** [comment]
Resolved in #1135
