### ISSUE TITLE
Allow the embedded content consumer to communicate with its iframe content

### ISSUE THREAD

**Issue by rasthana** [cerner/terra-core#927]
# Issue Description
The EmbeddedContentConsumer component allows embedding iframe content in order to present non-react content within react applications. The content in these embedded frames use XFC's messaging system to communicate with the application. Currently, the component provides a mechanism for the content (Provider) to communicate with it containing frame. However, there is no mechanism in place for the container to communicate with the content.

I would like to enhance the embedded content consumer to provide a standard to allow the parents of the EmbeddedContentConsumer to communicate with its content.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The EmbeddedContentConsumer wraps the XFC frame and exposes communication with the provider through function props. Theoretically, if the consumer provides access to the XFC frame then its parents will be able to trigger handlers defined by their providers.

The XFC frame, created after the Consumer has been successfully mounted, can be exposed to the parent component an onMount function prop.
- `onMount` - Notifies the component that the container has been mounted. Provides a frame to trigger events on the provider.

Another approach would expose a function on the EmbeddedContentConsumer that allows triggering events on the provider. The parent would obtain a reference to the EmbeddedContentConsumer and invoke this "trigger" function.

**Note**
The EmbeddedContentConsumer currently notifies the container via the onLaunch and onAuthorize hooks. Providing a hook to monitor the "Mount" status would complete all the stages of an application life cycle provided by XFC.

## Current Behavior
There is no standard that allows the container to communicate with its content.

**Comment by rasthana** [comment]
# Technical Design
Allow EmbeddedContentConsumer to communicate with its content.

## Possible Solutions
- [ ] EmbeddedContentConsumer provides an onMount hook and provides the xfc frame to allow its parents to invoke methods available on the frame.
`onMount(this.xfcFrame)`
- [ ] EmbeddedContentConsumer provides an onMount hook and provides itself to allow its parents to invoke instance methods.
`onMount(this)`
- [ ] Parents of EmbeddedContentConsumer declare a ref and invoke instance methods.
`
<EmbeddedContentConsumer
    ref={(element) => { this.embeddedContentConsumer = element; }}
/>
`

**Comment by emilyrohrbough** [comment]
Resolved in #938.
