### ISSUE TITLE
Broken link within terra-table documentation

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#931]
# Issue Description
Inside terra-table documentation, the link at the end of *Usage* is broken ([Source](https://github.com/cerner/terra-core/blob/master/packages/terra-table/docs/README.md)). The url has `MangedSelectableTable.md` instead of `ManagedSelectableTable.md`.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Link brings user to another page with more information.

## Current Behavior
Link brings user to a 404 page.

**Comment by hardikjain29** [comment]
I could help with this, if no one is?
