### ISSUE TITLE
install fails on windows machines

### ISSUE THREAD

**Issue by Singleton06** [cerner/terra-core#933]
# Issue Description

When checking out the project and trying to run 'npm install' on a windows machine, the build currently fails on the '$' sign.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

The project would install without failures.

## Current Behavior

I receive the following error when I try to check out the project with a fresh install and run 'npm install' from a windows machine.

https://gist.github.com/Singleton06/408d9446a6b34f25e6a29731f9070704

## Steps to Reproduce

1. Check out terra-core
2. Run 'npm install'

## Environment

* Component Version:  N/A
* Browser Name and Version: N/A, fails through command line
* Operating System and version (desktop or mobile): Windows 10 Enterprise

**Comment by emilyrohrbough** [comment]
Looks like collapsible-menu's package scripts need updated. Error occurred at 

> terra-collapsible-menu-view@1.1.1 compile:clean C:\installs\workspaces\terra\terra-core\packages\terra-collapsible-menu-view
> $(cd ..; npm bin)/rimraf lib

**Comment by emilyrohrbough** [comment]
[These scripts](https://github.com/cerner/terra-core/blob/master/packages/terra-collapsible-menu-view/package.json#L43) should match [these ones](https://github.com/cerner/terra-core/blob/master/packages/terra-badge/package.json#L23)
