### ISSUE TITLE
should terra-responsive-element honor consumer breakpoints ?

### ISSUE THREAD

**Issue by amf9t2** [cerner/terra-core#937]
# Issue Description
rwellness as an application consume topia as well as terra-core. Topia works on breakpoints as follows (@xs-breakpoint:   580px; @sm-breakpoint:   768px; @md-breakpoint:  1024px; @lg-breakpoint:  1276px; @xl-breakpoint:  1540px; @xxl-breakpoint: 2068px;)   and terra core works on set of breakpoints  $terra-responsive-breakpoints: ( tiny: 544, small: 768, medium: 992, large: 1216, huge: 1440).  

In a use-case where header  is a part of layout ( topia) and inside header the implementation uses terra-responsive-element then due to difference in breakpoint it behaves differently (medium 1024/992).

while using terra-responsive-element [0.4.0](https://github.com/cerner/terra-core/commit/db2fec58904dd16ccab541dd5d575eb1fc10284e#diff-d16b1e830995557be98868b27c8d4b1eR4) we were able to alter the breakpoints by overwriting via terra-legacy-theme variables but with the [updated version](https://github.com/cerner/terra-core/commit/1da437a91657073fb9b9b9d62656195489ab9d47#diff-d191d1b5335186affff95af87e7574dfR12) of terra-responsive-element it is not straight forward to do that.
I tried defining  $terra-responsive-breakpoints variables(with and without !important) inside application and importing via webpack ( sass-loader) but it didn't help.

I feel that we should honor consumer breakpoints by allowing them to overwrite breakpoints individually.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Consumer can use terra-repsonsive-element with their own set of breakpoints (tiny:, small:, medium:, large:, huge:) or using the default except one or two 

## Current Behavior
Terra responsive element currently works with below breakpoints
 $terra-responsive-breakpoints: (tiny: 580, small: 768, medium: 1020, large: 1024, huge: 1540)

**Comment by mhemesath** [comment]
Consumer breakpoints should align with core. Breakpoints aren't customizable.

**Comment by mhemesath** [comment]
FWIW - this should actually work to customize with SASS https://github.com/cerner/terra-core/blob/master/packages/terra-responsive-element/src/ResponsiveElement.jsx#L5

**Comment by amf9t2** [comment]
I tried overwriting again and it worked :). I have set $terra-responsive-breakpoints variable inside consuming application and import it via webpack (sass loader). 
Thanks.
