### ISSUE TITLE
Missing Contributor Startup Guide

### ISSUE THREAD

**Issue by Singleton06** [cerner/terra-core#940]
# Issue Description

Currently, we have a contributor guide, but as part of that guide there is not any documentation to indicate what steps need to be taken to build the project, etc.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior

There should be documentation.

## Current Behavior

N/A

## Things to document
- public URL for deployed terra-core: http://engineering.cerner.com/terra-core/#/site
- commands to run for common tasks
  - running tests
  - starting dev serve 
  - what to do before committing

Any additional ideas are greatly welcome!

**Comment by Singleton06** [comment]
Another idea would be to add the tech design template.

**Comment by Singleton06** [comment]
Need to have some documentation that currently scss changes only show up after re-running compile.

**Comment by Singleton06** [comment]
Checklist before committing:
* Make sure that you have updated tests
* Make sure that you have added an example to the terra-site for new functionality added
* Make sure you have updated the changelog (see http://keepachangelog.com/en/1.0.0/)

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-ui/pull/108
