### ISSUE TITLE
Search Field: clear field

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#943]
# Related Issues:
[#953 - Search Field: disabled state & fits container](https://github.com/cerner/terra-core/issues/953)
[#952 - Search Field: autosearch & minLength change](https://github.com/cerner/terra-core/issues/952)

----

# Issue Description
New features to add to the search field component:
- Add programmatic method to clear the search field.

*(10/20/2017) Update: generated two new issues to make PR smaller, see `Related Issues`*

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- items listed above

## Current Behavior
- user click to clear only

**Comment by neilpfeiffer** [comment]
Adding @Singleton06 as a watcher to issue.

**Comment by Singleton06** [comment]
@neilpfeiffer could we add an item here so that we have a programmatic way to set the content of the search field as well?  We are looking at re-writing a dialog that launches with the previously entered search already inside of it when it launches.

**Comment by bjankord** [comment]
> Add programmatic method to clear search field.
> could we add an item here so that we have a programmatic way to set the content of the search field as well

These can be achieved by exposing the [value](https://github.com/cerner/terra-core/blob/master/packages/terra-form/src/TextField.jsx#L120) of the input through a `value` prop similar to the [text field](http://engineering.cerner.com/terra-core/#/site/form/text-field). This would make the input a [controlled input](https://reactjs.org/docs/forms.html#controlled-components).

**Comment by mjhenkes** [comment]
@neilpfeiffer @Singleton06 Could we break this issue up into several smaller issues? Theres a lot here, too much for just one PR.

**Comment by neilpfeiffer** [comment]
Sounds good - I will divide it into 3 issues:  
(1) Disabled, (2) Clear actions/visuals, (3) autosearch + minimum characters.

**Comment by Singleton06** [comment]
For the clear button having a larger hit area and being tab-able, this appears to be something that the browser is adding as can be seen by this example[1] where all I am doing is using a HTML element with the type of "search".  This line[2] seems to be setting that property.

Given that we have a specific need for the programmatic way of clearing the search field (as well as sitting the initial field), could we move that enhancement to a separate issue?  

There might be a solution to the clear button tabbing and size, but I'm not that well versed with CSS and would prefer to not let that delay the progress on the other parts.

[1] - https://codepen.io/anon/pen/OxKMEQ?editors=1111
[2] - https://github.com/cerner/terra-core/blob/master/packages/terra-search-field/src/SearchField.jsx#L99

**Comment by Singleton06** [comment]
# Tech Design for Search Field controlled component support
## Summary:
Upgrade the search field control to be able to be a controlled component. This will allow for programmatic clearing and
setting of the search field.

## Requirements:
Discussion has been handled [here](https://github.com/cerner/terra-core/issues/943).  Basically, this is being done to
allow for a programmatic way of clearing the search field.

## Requirements Added:
When the consumer specifies the value prop, the control now becomes a controlled component.

## Responsiveness:
No Change should occur to the responsiveness.

## Bidirectionality
No change should occur to the bidirectionality.

## Accessibility
No change should occur to the bidirectionality.

## React Props:
|| Prop || Type || Default || Description ||
| value | String | '' | The value of the search field.  Use this to create a controlled search field. |
| onChange | func | undefined | Function to trigger when user changes the search value.  The text of the search changed will be passed as an argument to the function provided.  Provide a function to create a controlled search field.

## Example:
{code}
<SearchField
  value={this.state.searchValue}
  onChange={(value) => this.setState({ searchValue: value })}
/>
{code}

**Comment by Singleton06** [comment]
@mjhenkes or @emilyrohrbough  the one thing that I'm not quite sure how to handle with making this change is the onChange and 'handleTextChange' functionality interaction with each other.  Should it be that the onChange happens first?  Would it be expected that the onChange is able to reject a change in the property and then the onSearch or onInvalidSearch is called based on the result of the onChange somehow?

**Comment by emilyrohrbough** [comment]
I would suspect this would be what you'd want something like this in the `handleTextChange` function:

```
  handleTextChange(event) {
    const searchText = event.target.value;
    this.setState({ searchText });

 // onChange
    if(this.props.onChange) {
           this.props.onChange(event, searchText);
     }

    if (!this.searchTimeout) {
      this.searchTimeout = setTimeout(this.handleSearch, this.props.searchDelay);
    }
  }
```
Does this answer your questions?

**Comment by Singleton06** [comment]
Thanks for the code @emilyrohrbough, I'll have to test it out.  I'm not quite sure if that approach would allow the consumer to reject certain characters, etc, giving them control over what the value truly is.  For example, if they wanted only alphabetical characters, etc, I'm wondering if the search would still be performed in this approach.

**Comment by kschuste** [comment]
@Singleton06 would you more expect it to not set the state of the field?  Therefore, the consumer would be giving the onChange as an override, but still perform the search

{code}
handleTextChange(event) {
    if (this.props.onChange) {
      this.props.onChange(event, event.target.value);
    } else {
      this.setState({ searchText: event.target.value });
    }

    if (!this.searchTimeout) {
      this.searchTimeout = setTimeout(this.handleSearch, this.props.searchDelay);
    }
  }
{code}

**Comment by tm4027** [comment]
JIRA created

**Comment by Singleton06** [comment]
Sorry for the late response, @kschuste, I think what you have is more what I was thinking.
