### ISSUE TITLE
tests fail on windows because of file paths

### ISSUE THREAD

**Issue by Singleton06** [cerner/terra-core#945]
# Issue Description

There are a decent number of tests that seem to be performing checks that rely on path separators specific to the OS.  Those tests have the path with a forward slash, but when running on windows, it seems to have the error log happen with two backslashes.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
The tests would pass on windows

## Current Behavior

The tests fail on windows.

## Steps to Reproduce

1. Clone terra-core on a windows machine
2. run npm install at the root 
3. run npm start (@emilyrohrbough had indicated this solves the issue of jest failing due to missing traslations because of i18n aggregation that webpack does)
4. run npm test

## Additional Details
[Here](https://gist.github.com/Singleton06/ac5b214e934081cd325a2d22d7ad2f85) is a build that shows the issue.  Specifically, here is an example of the issue I'm seeing.

```javascript
  ? i18n-aggregator-plugin > when searching directories for translation messages with options outputFileSystem given > should fill the tranlsation files with the expected information for each locales

    expect(string).toContain(value)

    Expected string:
      "c:\\installs\\workspaces\\dustin-terra\\terra-core\\packages\\terra-i18n-plugin\\tests\\fixtures\\aggregated-translations\\en.js"
    To contain value:
      "aggregated-translations/en.js"

      at packages/terra-i18n-plugin/tests/i18n-plugin-spec.test.js:151:42
      at Array.forEach (native)
      at Object.<anonymous> (packages/terra-i18n-plugin/tests/i18n-plugin-spec.test.js:150:24)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

## Environment

* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): Windows 10

**Comment by bjankord** [comment]
Talked with @Singleton06, we should update these to use `path.join` any time we are using paths. 
`path.join` will use `/` on unix and `\\` on windows.

For any `import` or `require` statements, we don't need to use `path.join`.

**Comment by Singleton06** [comment]
Just to make sure no one might be duplicating effort, I've got the code finished to handle this. I'll try to get out a PR tomorrow

**Comment by Singleton06** [comment]
This can be closed now.
