### ISSUE TITLE
Test removing eslint-disable commit from generated icon files.

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#946]
# Issue Description
In our generated icon .jsx files, there is a comment to disable eslint. We should test removing it and see if can figure out what the logic was for that. Maybe its no longer needed?

https://github.com/cerner/terra-core/blob/19bc760400b640406e042f0ecbf87e7bb986f2d7/packages/terra-icon/scripts/src/generate-icon/template.txt#L1

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Generated icon files don't disable and re-enable eslint

## Current Behavior
Generated icon files disable and re-enable eslint

**Comment by emilyrohrbough** [comment]
It looks like `/* eslint-disable */` is included because these lines

```

SvgIcon.displayName = <%= JSON.stringify(icon.name) %>;
SvgIcon.defaultProps = <%= JSON.stringify(icon.attributes) %>;
```

**Comment by emilyrohrbough** [comment]
Result:

<img width="649" alt="screen shot 2017-10-22 at 9 10 07 am" src="https://user-images.githubusercontent.com/14099737/31862751-dd431bde-b708-11e7-8d1f-30cdfda560d3.png">
