### ISSUE TITLE
Search Field: disabled state & fits container

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#953]
# Related Issues:
[#943 - Search Field: clear field](https://github.com/cerner/terra-core/issues/943)
[#952 - Search Field: autosearch & minLength change](https://github.com/cerner/terra-core/issues/952)

----

# Issue Description
New features to add to the search field component:
1. Allow Search Field to be disabled (prop to pass disabled attribute to both input and button).
2. Add prop to allow for display to switch from fixed size to a resizable fluid/expanding style input (with button fixed at the end) that fits its parent container.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- items listed above

## Current Behavior
- no disabled state and fixed size

**Comment by neilpfeiffer** [comment]
cc: @Singleton06 @bjankord @mjhenkes

**Comment by Singleton06** [comment]
@neilpfeiffer, I'm going to be working on this today.  For the disabled state when the character count is less than specified, could we move this to a separate enhancement if it is not ready?  I wouldn't want that to block progress on the rest of the features that we will for sure need.

**Comment by Singleton06** [comment]
# Tech Design for Search Field disabled and fits container
## Summary:
The search field needs to be able to be disabled and fit the width of the container.  

## Requirements Added:
* Allow Search Field to be disabled (prop to pass disabled attribute to both input and button).
* Add prop to allow for display to switch from fixed size to a resizable fluid/expanding style input (with button fixed at the end) that fits its parent container.

## Bidirectionality
These changes should make no changes to the existing ltr/rtl functionality.

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| disabled | bool | false    | Indicates whether or not the search control should be disabled. |
| sizing | string | `fixed` | Indicates what sizing style should be used.  Should be `fixed` or `stretch`.  |

## Example:
```jsx
// with new fields
<SearchField
  onSearch={this.handleSearch}
  disabled
  sizing='stretch' 
/>

// with defaults
<SearchField
  onSearch={this.handleSearch}
/>
```

## CSS Classes:
| Selector         | Description |
|------------------|-------------|
| .stretch | This will be applied to the container of the search field to stretch it to it's parent container.  |

## Notes
I was considering whether or not I should add the prop for disabled.  I noticed that the input component does not do this, but the Input component is just a wrapper around the HTML input.  The approach that was taken for that input was to pass all additional props to the html element.  I'm not sure that would be the desired behavior here given that the SearchField wrappers two separate components.  We would have to pass both properties down to the button and input which might be undesired.

I also welcome any naming suggestions for the sizing prop as well.  I used stretch based off of the naming choice that the Arrange component uses, but I am not really sure if that is inconsistent with anything else.

**Comment by Singleton06** [comment]
@mjhenkes @bjankord, I have added the tech design.

**Comment by bjankord** [comment]
+1 on tech design

**Comment by StephenEsser** [comment]
Will there ever be more than one option for `sizing`? Setting sizing to fixed doesn't apply any logic or css. It could be set to any string other than stretch and it would have the same effect.

Are there thoughts on `sizing` being replaced by a boolean that indicates the SearchField will expand to 100%?

**Comment by Singleton06** [comment]
Definitely a good question.  The reason that I chose this is in case there might be some situation in the future that we would want a different sizing option that we wanted to allow.  Having the sizing property would give us freedom to passively add other approaches (which might result in fixed actually adding certain css to style to keep it consistent to how it was in the past).  If we were to just have a boolean then any additional sizing I think could result in a lot of confusion around how the multiple props act together.

**Comment by StephenEsser** [comment]
I agree keeping the sizing prop opens the door to passive future enhancements. I just can't think of any other sizing options. If we think there is a possibility something other than default and stretch will exist keeping sizing door open is a good idea.

**Comment by tm4027** [comment]
JIRA created
