### ISSUE TITLE
Control Components Have Unexpected Padding

### ISSUE THREAD

**Issue by Singleton06** [cerner/terra-core#955]
# Issue Description

When trying to do a UI that has a label and radio buttons on the same line, I am running into spacing issues.  Here in the UI that I am trying to create:
![image](https://user-images.githubusercontent.com/2235110/31890821-269057f4-b7ca-11e7-9829-45e2202958bb.png)

To accomplish this, I am trying to do this using an Arrange where the label is the 'fitStart' prop and the radio buttons (Control component) are surrounded in a div and passed to the 'fill' prop. [Here](https://gist.github.com/Singleton06/09af249e81bca2fd7cefbcebbb3492cb) is the code.

This screenshot shows how the current spacing is working.
![image](https://user-images.githubusercontent.com/2235110/31893720-dda6b01c-b7d1-11e7-9eaf-f6fba1c7d6db.png)

This seems to be an issue caused by the margin on the controls as can be seen here: 
![image](https://user-images.githubusercontent.com/2235110/31893869-4c904204-b7d2-11e7-913e-eb18e3f04c5c.png)

I have found that if I remove the align "center" then it seems to align better, but talking with @emilyrohrbough, she indicated that it still might be something to be concerned about.  The behavior of "center" does seem a bit weird when used with controls that contain margin.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior

The Text component and the Control components would be aligned when using 'center' alignment.

## Current Behavior

The Text component and the Control components are not aligned when using 'center' alignment.  See above for more information.

## Steps to Reproduce

1. See code [here](https://gist.github.com/Singleton06/09af249e81bca2fd7cefbcebbb3492cb)

## Environment

* Component Version:
  * terra-form: 1.11.1
  * terra-arrange: 1.12.1
  * terra-text: 1.11.1
* Browser Name and Version: Chrome Version 62.0.3202.62 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Windows 10

**Comment by yuderekyu** [comment]
`terra-form` will be deprecated, including this control component - this issue should be fixed in the new `terra-form-radio`.

**Comment by bjankord** [comment]
Resolved in #1135
