### ISSUE TITLE
Allow for inputFileSystem to be passed in as param to i18nPlugin

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-core#956]
# Issue Description
Would like to add the ability to pass in an inputFileSystem to be used in place of the compiler's default inputFileSystem.  This is currently being done with the outputFileSystem.  

## Issue Type
- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
An inputFileSystem should be allowed to be passed in through the options the same way as the outputFileSystems.  Then can be used instead of the compilers inputFileSystem.

**Comment by mjhenkes** [comment]
+1

**Comment by bjankord** [comment]
Resolved in #961
