### ISSUE TITLE
Add notificationOff icon

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#958]
# Issue Description
The new icon notificationOff needs to be added to terra-core so others can use it.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Please make the notificationOff icon available from https://github.com/cerner/one-cerner-style-icons

**Comment by mjhenkes** [comment]
@hboege is this an icon in the https://github.com/cerner/one-cerner-style-icons repo?

**Comment by mjhenkes** [comment]
I noticed that the one-cerner-style-icons changelog is at 1.6.0. I've reached out to have a new release cut through github to give us an artifact to reference.

**Comment by mjhenkes** [comment]
New release cut https://github.com/cerner/one-cerner-style-icons/tree/1.6.0
