### ISSUE TITLE
Create new Flexbox container component

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-core#964]
# Issue Description
Create a new container component that is specific to using flexbox to align its content.  

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Should be able to give the container a list of children and to be able to set the flexbox styles such as flex-wrap, order, and align-self as properties along with other css stylings such as margin and padding.

**Comment by kschuste** [comment]
# Tech Design for Flex Container
## Summary:
This is a new component that will allow for the consumer to apply flex-box stylings to the container and drop in any number of elements into it.

## Bidirectionality
These changes should make no changes to the existing ltr/rtl functionality.

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| alignContent | bool |  | Aligns the container's lines within when there is extra space in the cross-axis.  Should be one of `center`, `flex-end`, `flex-start`, `space-around`, `space-between`, or `stretch`. |
| alignItems | string |  | Defines the default behavior for how flex items are laid out along the cross axis on the current line.  Should be  one of `baseline`, `center`, `flex-end`, `flex-start`, or `stretch`.  |
| alignSelf | string |  | Allows the default alignment to be overridden for individual flex items.  Should be  one of `baseline`, `center`, `flex-end`, `flex-start`, or `stretch`.  |
| children | node |  | Child nodes to be displayed in the container.  |
| display | string | `flex` | Enables flex context for all its direct children either inline or block.  Should be `flex` or `inline-flex`.  |
| element | string | `div` | Indicates what type of element the flex container can be.  Should be one of `article`, `aside`, `div`, `figure`, `footer`, `header`, `main`,  `nav`, or `section`.  |
| flex | string |  | Shorthand for flex-grow, flex-shrink and flex-basis combined.  Example `0 1 auto`.  |
| flexBasis | string |  | Defines the default size of an element before the remaining space is distributed.  Can be a length (20%) or a keyword (auto).  |
| flexDirection | string |  | Defines the direction flex items are placed in the container.  Should be one of `column`, `column-reverse`, `row`, or `row-reverse`.  |
| flexGrow | number |  | Defines the ability for a flex item to grow if necessary. It accepts a unitless value that serves as a proportion.  |
| flexShrink | number |  | Defines the ability for a flex item to shrink if necessary.  |
| flexWrap | string |  | Allow the items to wrap as needed.  Should be one of `nowrap`, `wrap`, or `wrap-reverse`.  |
| height | string |  | Defines the height of the container.  |
| justifyContent | string |  | Defines the alignment along the main axis.  Should be  one of `center`, `flex-end`, `flex-start`, `space-around`, or `space-between`.  |
| margin | string |  | Defines the margins for the container.  |
| marginBottom | string |  | Defines the bottom margin for the container.  |
| marginLeft | string |  | Defines the left margin for the container.  |
| marginRight | string |  | Defines the right margin for the container.  |
| marginTop | string |  | Defines the top margin for the container.  |
| maxHeight | string |  | Defines the maximum height for the container.  |
| maxWidth | string |  | Defines the maximum width for the container.  |
| minHeight | string |  | Defines the minimum height for the container.  |
| minWidth | string |  | Defines the minimum width for the container. |
| order | number |  | Controls the order in which items appear in the container.  |
| padding | string |  | Defines the padding for the container.  |
| paddingBottom | string |  | Defines the bottom padding for the container.  |
| paddingLeft | string |  | Defines the left padding for the container.  |
| paddingRight | string |  | Defines the right padding for the container.  |
| paddingTop | string |  | Defines the top padding for the container.  |
| width | string |  | Defines the width for the container.  |

## Example:
```jsx
// with all fields
<FlexContainer 
	alignContent=“true”
	alignItems=“center”
	display=“flex”
	element=“div”
	flexDirection=“column”
	flexWrap=“wrap”
	height=“50%”
	justifyContent=“space-between”
	margin=“10px 10px 10px 10px”
	marginBottom=“10px”
	marginLeft=“10px”
	marginRight=“10px”
	marginTop=“10px”
	maxHeight=“50%”
	maxWidth=“50%”
	minHeight=“10%”
	minWidth=“10%”
	padding=“10px 10px 10px 10px”
	paddingBott0m=“10px”
	paddingLeft=“10px”
	paddingRight=“10px”
	paddingTop=“10px”
	width=“50%”>
    	<FlexContainer alignSelf=“center" order=2 flexGrow=1 flexShrink=1 flexBasis=“50%”>
		<span>Test</span>
	</FlexContainer>
    	<FlexContainer alignSelf=“flex-end” order=3 flex=“1 1 auto”>
		<span>Test</span>
	</FlexContainer>
	<FlexContainer alignSelf=“flex-start" order=1 flex=“1 1 auto”>
		<span>Test</span>
	</FlexContainer>
</FlexContainer>


// with no defaults
<FlexContainer>
    	<span>Test</span>
	<span>Test</span>
	<span>Test</span>
</FlexContainer>
```

## Notes
I was considering creating a FlexContainer.Item similar to how the List has ListItems for the children to contain the specific props.  However, the flex component I am modeling this after has all of these props on just the one component.  Therefore, I have it as is.  I have kept all the height, width, margin, and padding props as well since are included on the flex component modeling this after, which can be found here:  https://github.com/nachoaIvarez/flexbox-react.

**Comment by mjhenkes** [comment]
For the heigh/width/padding/margin props, I think we may want to abstract the values passed in so that we can hook them up to themeing. Alternatively we could leave the component as is and expect components using this component to provide the themed values.

**Comment by bjankord** [comment]
Yeah, I'm concerned about the margin and padding props in regards to theming, I'm less concerned about theming width / height. I'm thinking we should abstract margin / padding into set sizes which can be themed, but until we have a spacing scale, its hard to say how the margin / padding abstraction should be implemented.

How useful do you all think this would be if we implement it without margin / padding props until UX provides a spacing scale?

**Comment by kschuste** [comment]
removed the margin and padding props from the design, I agree that is the best route to go

**Comment by bjankord** [comment]
+1 on tech design

**Comment by StephenEsser** [comment]
Thoughts on naming this `Flexbox`?

```
<Flexbox>
  <span>Happy Name</span>
</Flexbox>
```

**Comment by kschuste** [comment]
I have it as FlexContainer as it is for flexing the items inside of it.  I'm not adverse to FlexBox if we think it's better, but I felt container was a bit more descriptive.

**Comment by JakeLaCombe** [comment]
Flexbox is the official name that's given to it. I would agree with stephen here.

I do have a question on the props though. One power of flexbox is that is you apply margin-left: auto to an element, then it will take as much margin as it possibly can. This comes in great for navigation with links on the right side. @bjankord do you have any thoughts on that? Or do we anticipate having a navigation component that does that for us?

**Comment by mhemesath** [comment]
What is the value proposition to using this component over just using flexbox with CSS/markup? Does it make more sense to create specialized layout components using flexbox for the situations we identify?

**Comment by kschuste** [comment]
We discussed adding this component and agree that we will be holding off on implementing this.  Our new recommendation is to use the third party flexbox component if need to found here: 
 https://github.com/nachoaIvarez/flexbox-react.
