### ISSUE TITLE
Simplify arrange example page

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-core#968]
# Issue Description
The current Arrange page has seven different examples. Several of these allow users to change the alignment of each segment of the arrange component. This is a bit redundant and the content doesn't always flex depending on the selection. For example, the Fit Start image fills the entire fit page, so no matter what alignment value is selected, the example doesn't seem to change.

## Issue Type

- [ ] New Feature
- [x ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- Reduce number of arrange examples
- Provide content that flexes based on user input and exemplifies the intended usage of the component.

**Comment by bjankord** [comment]
On this issue, we'll want to sync up with @mmalaker to see what guidance he has on this.
