### ISSUE TITLE
Pin terra-components to single version to prevent duplicate versions in bundles

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#97]
Based on the spike we did on versioning, we came to the conclusion to pin terra components referenced as dependencies, devDependencies, and/or peerDependencies to singular versions rather than allowing `^` or `~` usage on version numbers which would allow versions to be updated the most recent major or minor version. This is to prevent duplicate versions being compiled in the webpack bundle.

**Comment by Matt-Butler** [comment]
Update on version discussion:
If a package is < 1.0.0
- "^0.x"
If a package is >= 1.0.0
- "^1.0.0"

For more information check out the links below:
https://semver.npmjs.com/
https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by bjankord** [comment]
Closing as this no longer seems to be as important. I do think we should take a look that Jake did a while ago to ensure their are now duplicates of major versions of a component in a bundle, I'll get another issue logged to track that work.
