### ISSUE TITLE
Add ability to differentiate between keyboard and mouse for focus styles.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#972]
# Issue Description
To distinguish between keyboard and mouse, we need to add [whatInput](https://github.com/ten1seven/what-input) to terra-base. Just importing it is enough to get the functionality we need.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Terra core has the ability to differentiate between keyboard and mouse for focus styles.

## Current Behavior
No ability is provided.

**Comment by JakeLaCombe** [comment]
After further investigation, I found that whatInput will not suit our needs well, as it doesn't keep track of the focus input. It keeps track of the current input, which can change between mouse and keyboard while typing in a form. There is the option to track whatintent which lets you keep track of the input device that occurred before the form input was interacted with, but found that mousemove changes that value, something we don't want.

My recommendation is that instead of using whatInput, that we use ally.js (https://github.com/medialize/ally.js/), and rely on the focus-source attribute that is generated from the focusable style of that package.

**Comment by mhemesath** [comment]
We should only add this as a dependency to components that need it.

**Comment by bjankord** [comment]
> After further investigation, I found that whatInput will not suit our needs well

Hearing this, I think we need to pause on incorporating different focus styles based on mouse or keyboard in the textarea PR and move it forward with 1 focus style. I'll leave a comment on the PR, but I don't want to hold that story up as we wait to figure out how we are going to handle mouse vs keyboard focus.

I'm hesitant to add ally.js as it offers a lot more features than what we need. We only really need the code that determines what input created the focus which is this file in the ally.js project: https://github.com/medialize/ally.js/blob/88e1af44df20df3209afe377aa4e9d21ef426ff2/src/style/focus-source.js

My recommendation would be look into the WICG's polyfill for :focus-ring: https://github.com/WICG/focus-ring and see if it works as we intend as it's more focused to our use case. Or we write our own implementation equivalent to the ally.js project's focus-soruce.js file. Here is a jQuery alternative, not saying we use it, but as another example of what features we'd need to write in our own implementation.
