### ISSUE TITLE
Dynamic-Grid grid-[column | row]-gap behavior inconsistency

### ISSUE THREAD

**Issue by dylan-sftwr** [cerner/terra-core#977]
# Issue Description

`terra-dynamic-grid` grid-gap spacing inconsistency.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

The behavior in setting column/row caps on the grid should behave identically, regardless of whether or not specific values were specified with `grid-[column | row]-gap` and `grid-gap`. 

## Current Behavior

In the [`terra-dynamic-grid`](http://engineering.cerner.com/terra-core/#/site/dynamic-grid) component, using the strings `'grid-column-gap': <value>` and `'grid-row-gap': <value>` as part of a grid template doesn't result in a grid with values set with the aforementioned values. However, using the one-liner version of `'grid-gap': <row-gap value> <column-gap value>` does.

## Steps to Reproduce

1. Create an instance of `terra-dynamic-grid`
2. Specify either `grid-column-gap` or `grid-row-gap` with a value as part of the template to pass to the grid instance.
3. Inspect the grid in a browser.

## Environment

* Component Version: 1.6.1
* Browser Name and Version: Chrome (62.0.3202.75) and FirefoxDeveloperEdition(57.0b12)
* Operating System and version (desktop or mobile): macOS 10.12.5

**Comment by mhemesath** [comment]
Only shorthand syntax is supported.  DynamicGrid is built to resemble but not necessarily be a 1-to-1  mirror of the API being it is impossible to support the entire API in legacy IE.  The challenge with supporting long-hand and short-hand properties is that the property declarations on the objects are not ordered so allowing both properties to be passed in is not deterministic.

**Comment by dylan-sftwr** [comment]
That makes sense. In that case however, I beleive the documentation is incorrect as it suggests that using `grid-column-gap` and `grid-row-gap` is possible.
