### ISSUE TITLE
Update examples to reference distributed component files

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#98]
https://github.com/cerner/terra-ui/blob/master/packages/terra-button/examples/ButtonBlock.jsx#L2
```
import Button from '../src/Button';
```

Most of our examples import using the `src` directory. This should be updated to `lib` to ensure our examples work outside this repo.

**Comment by bjankord** [comment]
We should investigate using [feature flags](https://github.com/petehunt/webpack-howto#6-feature-flags) for dev/prod to flex between `src`/`lib`. 

By using `src` we get the value of live reload with the dev server, switching to `lib` means we'd need to compile `lib` after changes to see the changes on the dev server. Though it also means these example components could be used in other applications which is important too.
