### ISSUE TITLE
Theming approach is having issues with directional styles

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#986]
# Issue Description
To implement our theming, we use a combination of the rtl mixin, and the postcss-custom-properties mixin. When both of these are used, the following warning is generated.

     text: 'Custom property ignored: not scoped to the top-level :root element ([dir=ltr]:root { ... --terra-form-field-inline-margin-right: ... })',

This is preventing themeable stylesheets from being used in IE10, 11 and other browsers that do not support css custom variables.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Themeable styles work correctly with dir styles

## Current Behavior
Dir styles are causing issues with the application.

**Comment by bjankord** [comment]
I wonder if we need to flip the order the postcss plugins are run? Maybe have it convert custom properties to static values first, then run RTL plugin on the compiled CSS.

**Comment by JakeLaCombe** [comment]
Unfortunately, I don't think that approach will be feasible either. Lets say we have this style defined.
````
.textarea {
   &:focus {
      box-shadow: var(--terra-form-textarea-focus-mouse-box-shadow, 1px 1px 1px 1px #000000);
    }
}
````

We get this result which ignores the themeable variable.

````
[dir=ltr]:root .textarea:focus {
  box-shadow: 1px 1px 1px 1px #000000; 
}
 
 [dir=rtl]:root .textarea:focus {
  box-shadow: -1px 1px 1px 1px #000000;
 }
```

If we explicitly callout dir=ltr and dir=rtl in the stylesheet, that could potentially fix the issue. I'd have to investigate

**Comment by JakeLaCombe** [comment]
I did the following, and got the following result.

Input
````
.textarea {
   &:focus {
       [dir=ltr]  & {
          box-shadow: var(--terra-form-textarea-focus-mouse-box-shadow, 1px 1px 1px 1px #000000);
        }
    }
}
````

Output
````
[dir=ltr] :root .textarea:focus {
      box-shadow: 1px 1px 1px 1px #000000;
      box-shadow: none;
      box-shadow: var(--terra-form-textarea-focus-mouse-box-shadow, 1px 1px 1px 1px #000000); 
}
````

Since I didn't specify a rtl style, it didn't produce one, meaning we could do themable variables for left and right versions for positioning styles that could be switched between left and right.

**Comment by mhemesath** [comment]
Processing custom properties before RTL plugin should solve the issue because the custom property will be compiled into the CSS before RTL processes. The bigger problem is that approach won't work in modern browsers that support custom properties. @JakeLaCombe does the RTL plugin flip the custom properties defined in root for us?

**Comment by JakeLaCombe** [comment]
Yeah. This is the output of the scss.

````
[dir=ltr]:root {
  --terra-form-textarea-padding-left: 0.429rem;
  --terra-form-textarea-padding-right: 0.429rem;
  --terra-form-textarea-error-focus-animation-background: linear-gradient(to bottom, #ff232a, #ff232a);
  --terra-form-textarea-error-focus-mouse-animation-size: 100% 2px;
  --terra-form-textarea-error-focus-keyboard-animation-size: 100% 2px;
  --terra-form-textarea-focus-animation-background: linear-gradient(to bottom, #396ee5, #396ee5);
  --terra-form-textarea-focus-mouse-animation-size: 100% 2px;
  --terra-form-textarea-focus-keyboard-animation-size: 100% 2px;
 }

[dir=rtl]:root {
  --terra-form-textarea-padding-right: 0.429rem;
  --terra-form-textarea-padding-left: 0.429rem;
  --terra-form-textarea-error-focus-animation-background: linear-gradient(to bottom, #ff232a, #ff232a);
  --terra-form-textarea-error-focus-mouse-animation-size: 100% 2px;
  --terra-form-textarea-error-focus-keyboard-animation-size: 100% 2px;
  --terra-form-textarea-focus-animation-background: linear-gradient(to bottom, #396ee5, #396ee5);
  --terra-form-textarea-focus-mouse-animation-size: 100% 2px;
  --terra-form-textarea-focus-keyboard-animation-size: 100% 2px;
 }
````

**Comment by JakeLaCombe** [comment]
When I run custom properties before rtl, I get the following styles

````
[dir] .Textarea__textarea___UIZ88:focus {
    background-size: 0 0;
    background-size: 100% 2px;
    background-size: var(--terra-form-textarea-focus-mouse-animation-size, 0 0);
    border-color: #dedfe0;
    border-color: #396ee5;
    border-color: var(--terra-form-textarea-focus-mouse-border-color, #dedfe0);
    border-style: solid;
    border-style: solid;
    border-style: var(--terra-form-textarea-focus-mouse-border-style, solid);
    border-width: 1px;
    border-width: 1px;
    border-width: var(--terra-form-textarea-focus-mouse-border-width, 1px);
    box-shadow: none;
    box-shadow: var(--terra-form-textarea-focus-mouse-box-shadow, 1px 1px 1px 1px #000);
 }

  [dir=ltr] .Textarea__textarea___UIZ88:focus {
    box-shadow: 1px 1px 1px 1px #000; 
  }
 
 [dir=rtl] .Textarea__textarea___UIZ88:focus {
     box-shadow: -1px 1px 1px 1px #000; 
  }
````

Because of this result, we lose the themeable variable support for styles that are directional.

**Comment by bjankord** [comment]
Putting the RTL plugin after the Custom Properties plugin solves this partly. There is some nuance here around custom theme override values like `box-shadow: none` which has no directionality and default theme values that do have relation to directionality like `box-shadow: 1px 1px 1px 1px #000;`.

Ideally, the generated CSS would look like the following:

```diff
[dir] .Textarea__textarea___UIZ88:focus {
   background-size: 0 0;
    background-size: 100% 2px;
    background-size: var(--terra-form-textarea-focus-mouse-animation-size, 0 0);
    border-color: #dedfe0;
    border-color: #396ee5;
    border-color: var(--terra-form-textarea-focus-mouse-border-color, #dedfe0);
    border-style: solid;
    border-style: solid;
    border-style: var(--terra-form-textarea-focus-mouse-border-style, solid);
    border-width: 1px;
    border-width: 1px;
    border-width: var(--terra-form-textarea-focus-mouse-border-width, 1px);
    box-shadow: none;
    box-shadow: var(--terra-form-textarea-focus-mouse-box-shadow, 1px 1px 1px 1px #000);
 }

  [dir=ltr] .Textarea__textarea___UIZ88:focus {
    box-shadow: 1px 1px 1px 1px #000; 
+  box-shadow: none; // custom themed style overwrites default
 }
 
 [dir=rtl] .Textarea__textarea___UIZ88:focus {
     box-shadow: -1px 1px 1px 1px #000;
+   box-shadow: none; // custom themed style overwrites default
  }
```
The current output @JakeLaCombe posted above does not move the `box-shadow: none;` theme override into the dir ltr/rtl selectors as none has no directionality related to it, but without moving it into those selectors, the cascade order is different compared to what we would expect for theme overrides that are compiled.

**Comment by bjankord** [comment]
Short term fix would be to manually write out `[dir="ltr"]` and `[dir="rtl"]` selectors around properties we see this issue with. Long term fix is likely creating mixins to do this in places the RTL plugin doesn't output what we would expect.
