### ISSUE TITLE
Dynamic Grid is not generating ms-grid-row correctly

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#989]
# Issue Description
Adding a grid-gap to a dynamic grid does not add the gap spaces to ms-grid-rows. This is needed in order to get vertical gaps on IE10 and IE11.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Grid gap adds gap for column and row

## Current Behavior
Only column gaps are generated

**Comment by mhemesath** [comment]
Please provide reduced example

**Comment by dylan-sftwr** [comment]
After working with Wei, we discovered this actually isn't an issue. The grid displays as it's supposed to, but the documentation around what needs to be done to prevent the issue in the future for others is vague. I'll be creating a PR with an update to the doc in the near future. At that time, I'll come back to this issue and post a link to it.

**Comment by JakeLaCombe** [comment]
Given that, we can close this, and link back when the documentation issue is created.
