### ISSUE TITLE
Collapsible Subheaders (in a list)

### ISSUE THREAD

**Issue by laurunning** [cerner/terra-core#996]
# Issue Description
Collapsible subheaders (within a list in particular)
![image](https://user-images.githubusercontent.com/32143728/32455826-116a44a0-c2e9-11e7-939c-03fbda912e8f.png)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Collapse the section underneath when the caret (pointing down) is clicked and change caret to point to the right, and open the section when the caret (pointing right) is pressed and change the caret to point down again. 

## Current Behavior

N/A

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by bjankord** [comment]
@laurunning Is this a feature request?

**Comment by laurunning** [comment]
Hi @bjankord I wasn't sure if it was an enhancement or feature request. I can change it if you think that is more appropriate.

**Comment by laurunning** [comment]
Hello, I wanted to provide an additional consideration regarding the design. I think we should include a bottom border on each subheader that is expandable/collapsible because when one is next to another in the current design, they blend together. 
<img width="130" alt="current kaiju mockup" src="https://user-images.githubusercontent.com/32143728/33675708-25864d6a-da79-11e7-8f5d-830a494ab4e2.png">
![proposal](https://user-images.githubusercontent.com/32143728/33675709-25942cb4-da79-11e7-9cd9-9465dddd32a7.png)

**Comment by laurunning** [comment]
Hi all, as the expand/collapse header is developed, could we look at the way the font is displaying the parentheses? When centering the caret icon, it is difficult to align it exactly because the parentheses are so low, but I understand that is just part of the font. Will it change with OCS?

**Comment by ChelseaRyanAnderson** [comment]
Hey everyone! PCT will need this functionality for the Diagnosis Assistant so I'll be following along here.

**Comment by neilpfeiffer** [comment]
Closing as duplicate, since will be resolved by upcoming work done for #1320 and #1321
