### ISSUE TITLE
Checkbox component for OCS

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#999]
# Issue Description
Create a checkbox component for OCS. Tech design here: #960

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by tm4027** [comment]
JIRA created

**Comment by tm4027** [comment]
JIRA created

**Comment by yuderekyu** [comment]
Why was this closed? This is in progress.
